<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py platform branch --force`.

declare(strict_types=1);

namespace Academorix\Branch\Events;

use Illuminate\Contracts\Events\ShouldDispatchAfterCommit;

/**
 * The default branch for a (tenant, organization) tuple was reassigned. Fires with both the newly-default row + the previously-default row so downstream caches can drop keys keyed on both.
 *
 * ## Consumers
 *
 * - audit::WriteToAuditLog
 * - activity::WriteToActivityLog
 *
 * @category Branch
 *
 * @since    0.1.0
 */
final readonly class BranchDefaultChanged implements ShouldDispatchAfterCommit
{
    /**
     * @param  string  $tenantId  ULID
     * @param  string  $organizationId  ULID
     * @param  string  $newDefaultBranchId  ULID
     * @param  string  $previousDefaultBranchId  ULID | null
     * @param  string  $changedBy  ULID
     */
    public function __construct(
        public readonly string $tenantId,
        public readonly string $organizationId,
        public readonly string $newDefaultBranchId,
        public readonly string $previousDefaultBranchId,
        public readonly string $changedBy,
    ) {
    }
}
