<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py finance marketplace-fee --force`.

declare(strict_types=1);

namespace Stackra\MarketplaceFee\Enums;

use Stackra\Enum\Enum;

/**
 * Closed-set enum for `status` on `fee-payout`.
 *
 * Enum: pending / settled / failed / cancelled.
 *
 * @category MarketplaceFee
 *
 * @since    0.1.0
 */
enum FeePayoutStatus: string
{
    use Enum;

    case Pending = 'pending';
    case Settled = 'settled';
    case Failed = 'failed';
    case Cancelled = 'cancelled';
}
