<?php

// // AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py workflow approvals --force`.

declare(strict_types=1);

namespace Academorix\Workflow\Approvals\Repositories;

use Academorix\Crud\Attributes\AsRepository;
use Academorix\Crud\Attributes\Cacheable;
use Academorix\Crud\Attributes\Filterable;
use Academorix\Crud\Attributes\UseModel;
use Academorix\Crud\Repositories\Repository;
use Academorix\Workflow\Approvals\Contracts\Data\ApprovalInstanceInterface;
use Academorix\Workflow\Approvals\Contracts\Repositories\ApprovalInstanceRepositoryInterface;
use Academorix\Workflow\Approvals\Models\ApprovalInstance;

/**
 * Attribute-first Eloquent repository for {@see Academorix\Workflow\Approvals\Models\ApprovalInstance}.
 *
 * Bound to the interface via `#[AsRepository]`; the model comes from
 * `#[UseModel(ApprovalInstanceInterface::class)]` which resolves to
 * `ApprovalInstance` through the interface's `#[Bind]`.
 *
 * @extends Repository<\Academorix\Workflow\Approvals\Models\ApprovalInstance>
 *
 * @category Approvals
 *
 * @since    0.1.0
 */
#[AsRepository]
#[UseModel(ApprovalInstanceInterface::class)]
#[Cacheable(ttl: 3600, tags: true)]
#[Filterable('*')]
final class ApprovalInstanceRepository extends Repository implements ApprovalInstanceRepositoryInterface
{
    // Domain methods added here. CRUD comes from Repository.
}
