<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py shared geography --force`.

declare(strict_types=1);

namespace Stackra\Geography\Console;

use Stackra\Console\Attributes\AsCommand;
use Stackra\Console\Commands\BaseCommand;

/**
 * `php artisan geography:describe` — Describe the geography surface.
 *
 * @category Geography
 *
 * @since    0.1.0
 */
#[AsCommand(
    name: 'geography:describe',
    description: 'Describe the geography surface.',
)]
final class DescribeCommand extends BaseCommand
{
    /**
     * Execute the command.
     *
     * TODO(gen): wire the required services + implement the handler body.
     */
    public function handle(): int
    {
        $this->omni->titleBar('Describe the geography surface', 'sky');

        // TODO(gen): wire the required services + implement the handler body.

        $this->omni->success('Describe the geography surface completed.');
        $this->showDuration();

        return self::SUCCESS;
    }
}
