<?php

// // AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py finance invoice --force`.

declare(strict_types=1);

namespace Academorix\Invoice\Data;

use Spatie\LaravelData\Attributes\MapInputName;
use Spatie\LaravelData\Data;
use Spatie\LaravelData\Mappers\SnakeCaseMapper;

/**
 * Server-side output DTO for {@see \Academorix\Invoice\Models\CreditNote}.
 *
 * Consumed by controllers + services on the SERVER side. This is
 * distinct from the wire SDK's DTO (which sits under
 * `Academorix\FinanceInvoiceSdk\Data`) — the wire DTO travels across the HTTP
 * boundary; this one stays in-process.
 *
 * @category Invoice
 *
 * @since    0.1.0
 */
#[MapInputName(SnakeCaseMapper::class)]
final class CreditNoteData extends Data
{
    public function __construct(
        public string $id,
        public string $tenantId,
        public string $creditNoteNumber,
        public string $originalInvoiceId,
        public string $reason,
        public int $amountCents,
        public string $currency,
        public int $taxAmountCents,
        public string $issueDate,
        public string $issuedByUserId,
        public string $status,
        public string $createdAt,
        public string $updatedAt,
        public ?string $reasonNote = null,
        public ?string $appliedToType = null,
        public ?string $appliedToId = null,
        public ?string $pdfUrl = null,
        public ?string $appliedAt = null,
        public ?string $voidedAt = null,
        public ?string $voidReason = null,
        public ?string $createdBy = null,
        public ?string $updatedBy = null,
    ) {
    }
}
