<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py sports event --force`.

declare(strict_types=1);

namespace Academorix\Event\Exceptions;

use Academorix\Exceptions\AcademorixException;

/**
 * Reached the `event_slot` per-calendar-year cap (Small=12/year, Medium=60/year, Enterprise=unlimited).
 *
 * @category Event
 *
 * @since    0.1.0
 */
final class EventQuotaExceededException extends AcademorixException
{
    /**
     * Stable machine-readable error code emitted on the JSON envelope.
     */
    public const CODE = 'EVENT_QUOTA_EXCEEDED';

    /**
     * Translation key for the humanised message.
     */
    public const TRANSLATION_KEY = 'event::errors.EVENT_QUOTA_EXCEEDED';
}
