<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py sports event --force`.

declare(strict_types=1);

namespace Academorix\Event\Exceptions;

use Academorix\Exceptions\AcademorixException;

/**
 * Cannot change entry_fee_cents / late_registration_fee_cents / prize_pool_cents post-registration_open without events.
 *
 * @category Event
 *
 * @since    0.1.0
 */
final class EventPricingLockedPostRegistrationException extends AcademorixException
{
    /**
     * Stable machine-readable error code emitted on the JSON envelope.
     */
    public const CODE = 'EVENT_PRICING_LOCKED_POST_REGISTRATION';

    /**
     * Translation key for the humanised message.
     */
    public const TRANSLATION_KEY = 'event::errors.EVENT_PRICING_LOCKED_POST_REGISTRATION';
}
