<?php

// // AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py sports event --force`.

declare(strict_types=1);

namespace Academorix\Event\Exceptions;

use Academorix\Exceptions\AcademorixException;

/**
 * Athlete registering does not match min_age/max_age/age_group_ids/gender_category.
 *
 * @category Event
 *
 * @since    0.1.0
 */
final class EventEligibilityMismatchException extends AcademorixException
{
    /**
     * Stable machine-readable error code emitted on the JSON envelope.
     */
    public const CODE = 'EVENT_ELIGIBILITY_MISMATCH';

    /**
     * Translation key for the humanised message.
     */
    public const TRANSLATION_KEY = 'event::errors.EVENT_ELIGIBILITY_MISMATCH';
}
