<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py products geofencing --force`.

declare(strict_types=1);

namespace Stackra\Geofencing\Console;

use Stackra\Console\Attributes\AsCommand;
use Stackra\Console\Commands\BaseCommand;

/**
 * `php artisan geofencing:list-fenceable-aliases` — List fenceable aliases — geofencing command.
 *
 * @category Geofencing
 *
 * @since    0.1.0
 */
#[AsCommand(
    name: 'geofencing:list-fenceable-aliases',
    description: 'List fenceable aliases — geofencing command.',
)]
final class ListFenceableAliasesCommand extends BaseCommand
{
    /**
     * Execute the command.
     *
     * TODO(gen): wire the required services + implement the handler body.
     */
    public function handle(): int
    {
        $this->omni->titleBar('List fenceable aliases — geofencing command', 'sky');

        // TODO(gen): wire the required services + implement the handler body.

        $this->omni->success('List fenceable aliases — geofencing command completed.');
        $this->showDuration();

        return self::SUCCESS;
    }
}
