<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py platform webhook --force`.

declare(strict_types=1);

namespace Stackra\Webhook\Enums;

use Stackra\Enum\Enum;

/**
 * Closed-set enum for `http_verb` on `webhook-subscription`.
 *
 * HTTPS destination only.
 *
 * @category Webhook
 *
 * @since    0.1.0
 */
enum WebhookSubscriptionHttpVerb: string
{
    use Enum;

    case Post = 'POST';
    case Put = 'PUT';
    case Patch = 'PATCH';
}
