<?php

// // AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py sports event --force`.

declare(strict_types=1);

namespace Academorix\Event\Events;

use Illuminate\Contracts\Events\ShouldDispatchAfterCommit;

/**
 * Event.status transitioned to any new value. A superset event; the specific-state events below (EventAnnounced, EventRegistrationOpened, ...) fire alongside for the routing case that cares.
 *
 * ## Consumers
 *
 * - audit::WriteToAuditLog
 * - activity::WriteToActivityLog
 *
 * @category Event
 *
 * @since    0.1.0
 */
final readonly class EventStatusChanged implements ShouldDispatchAfterCommit
{
    /**
     * @param  string  $eventId  ULID
     * @param  string  $tenantId  ULID
     * @param  string  $fromStatus  string
     * @param  string  $toStatus  string
     * @param  string  $changedBy  ULID | null
     * @param  string  $trigger  'automated_phase_roll' | 'manual_admin' | 'automated_expire'
     * @param  string  $reason  string | null
     */
    public function __construct(
        public readonly string $eventId,
        public readonly string $tenantId,
        public readonly string $fromStatus,
        public readonly string $toStatus,
        public readonly string $changedBy,
        public readonly string $trigger,
        public readonly string $reason,
    ) {
    }
}
