<?php

// // AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py access rbac --force`.

declare(strict_types=1);

namespace Academorix\Access\Rbac\Policies;

use Academorix\User\Models\User;
use Academorix\Access\Rbac\Models\Permission;

/**
 * Authorization policy for {@see \Academorix\Access\Rbac\Models\Permission}.
 *
 * Wired via `#[UsePolicy]` on the Model.
 *
 * @category Rbac
 *
 * @since    0.1.0
 */
final class PermissionPolicy
{
    /**
     * tenant admins see the full catalogue
     *
     * @return bool
     */
    public function viewAny(User $user, Permission $model): bool
    {
        return $user->can('permissions.viewAny.tenant');
    }
    /**
     * view ability.
     *
     * @return bool
     */
    public function view(User $user, Permission $model): bool
    {
        return $user->can('permissions.view.tenant');
    }
    /**
     * Enterprise-only, requires custom_permissions entitlement
     *
     * @return bool
     */
    public function create(User $user, Permission $model): bool
    {
        return $user->can('permissions.create.tenant');
    }
}
