<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py sports registrations --force`.

declare(strict_types=1);

namespace Academorix\Registrations\Enums;

use Stackra\Enum\Enum;

/**
 * Closed-set enum for `status` on `registration-task`.
 *
 * open / done / cancelled.
 *
 * @category Registrations
 *
 * @since    0.1.0
 */
enum RegistrationTaskStatus: string
{
    use Enum;

    case Open = 'open';
    case Done = 'done';
    case Cancelled = 'cancelled';
}
