<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py platform theme --force`.

declare(strict_types=1);

namespace Academorix\Theme\Database\Factories;

use Illuminate\Database\Eloquent\Factories\Factory;
use Academorix\Theme\Contracts\Data\ThemeTokenOverrideInterface;
use Academorix\Theme\Models\ThemeTokenOverride;

/**
 * Factory for {@see \Academorix\Theme\Models\ThemeTokenOverride}.
 *
 * Auto-generated skeleton — extend with named states as domain
 * cases emerge (e.g. `->published()`, `->overdue()`, `->archived()`).
 *
 * @extends Factory<\Academorix\Theme\Models\ThemeTokenOverride>
 *
 * @category Theme
 *
 * @since    0.1.0
 */
final class ThemeTokenOverrideFactory extends Factory
{
    /**
     * The model this factory builds.
     *
     * @var class-string<ThemeTokenOverride>
     */
    protected $model = ThemeTokenOverride::class;

    /**
     * Return the default model attribute values.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        return [
            ThemeTokenOverrideInterface::ATTR_THEME_ID => fake()->sentence(3),
            ThemeTokenOverrideInterface::ATTR_TOKEN_KEY => fake()->sentence(3),
            ThemeTokenOverrideInterface::ATTR_TOKEN_VALUE => fake()->sentence(3),
            ThemeTokenOverrideInterface::ATTR_TOKEN_TYPE => fake()->randomElement(['color', 'dimension', 'typography', 'radius', 'shadow', 'motion', 'opacity', 'z_index']),
            ThemeTokenOverrideInterface::ATTR_REASON => null,
            ThemeTokenOverrideInterface::ATTR_APPLIED_AT => now(),
        ];
    }
}
