<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py sports athlete-enrollment --force`.

declare(strict_types=1);

namespace Academorix\AthleteEnrollment\Events;

use Academorix\Events\Attributes\AsEvent;
use Illuminate\Contracts\Events\ShouldDispatchAfterCommit;

/**
 * AthleteEnrollmentProvisioner committed. Consumes 1 unit of athlete_enrollment_slot on the tenant's active per-season entitlement.
 *
 * ## Consumers
 *
 * - audit::WriteToAuditLog
 * - activity::WriteToActivityLog
 * - notifications::DispatchEnrollmentSubmittedNotification (to primary guardian + admin + coach)
 * - athlete-enrollment::SnapshotAgeGroupOnEnrollmentSubmitted (in-band snapshot from athlete.current_age_group_id)
 * - cache::InvalidateTeamRosterCache
 *
 * @category AthleteEnrollment
 *
 * @since    0.1.0
 */
#[AsEvent]
final readonly class EnrollmentSubmitted implements ShouldDispatchAfterCommit
{
    /**
     * @param  string  $enrollmentId  ULID (aen_*)
     * @param  string  $tenantId  ULID
     * @param  string  $branchId  ULID
     * @param  string  $teamId  ULID
     * @param  string  $athleteId  ULID
     * @param  string  $seasonId  ULID
     * @param  string  $ageGroupSnapshotId  ULID (age_*) | null
     * @param  string  $enrollmentSource  string
     * @param  string  $enrollmentType  string
     * @param  string  $sourceTrialId  ULID (ttr_*) | null
     * @param  int  $priceAmountCents  integer
     * @param  string  $priceCurrency  string | null
     * @param  string  $createdByUserId  ULID
     */
    public function __construct(
        public readonly string $enrollmentId,
        public readonly string $tenantId,
        public readonly string $branchId,
        public readonly string $teamId,
        public readonly string $athleteId,
        public readonly string $seasonId,
        public readonly string $ageGroupSnapshotId,
        public readonly string $enrollmentSource,
        public readonly string $enrollmentType,
        public readonly string $sourceTrialId,
        public readonly int $priceAmountCents,
        public readonly string $priceCurrency,
        public readonly string $createdByUserId,
    ) {
    }
}
