<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py platform facility --force`.

declare(strict_types=1);

namespace Academorix\Facility\Enums;

use Academorix\Enum\Enum;

/**
 * Closed-set enum for `payment_method` on `day-pass`.
 *
 * Enum category (cash / card / wallet / free / comp).
 *
 * @category Facility
 *
 * @since    0.1.0
 */
enum DayPassPaymentMethod: string
{
    use Enum;

    case Cash = 'cash';
    case Card = 'card';
    case Wallet = 'wallet';
    case Free = 'free';
    case Comp = 'comp';
}
