<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py sports event --force`.

declare(strict_types=1);

namespace Stackra\Event\Events;

use Stackra\Events\Attributes\AsEvent;
use Illuminate\Contracts\Events\ShouldDispatchAfterCommit;

/**
 * Event.visibility transitioned from 'public' to any non-public value. Event no longer appears on public listings.
 *
 * ## Consumers
 *
 * - audit::WriteToAuditLog
 * - activity::WriteToActivityLog
 * - cache::InvalidatePublicEventListings
 *
 * @category Event
 *
 * @since    0.1.0
 */
#[AsEvent]
final readonly class EventUnpublished implements ShouldDispatchAfterCommit
{
    /**
     * @param  string  $eventId  ULID
     * @param  string  $tenantId  ULID
     * @param  string  $unpublishedAt  ISO 8601
     * @param  string  $unpublishedBy  ULID
     * @param  string  $newVisibility  string
     */
    public function __construct(
        public readonly string $eventId,
        public readonly string $tenantId,
        public readonly string $unpublishedAt,
        public readonly string $unpublishedBy,
        public readonly string $newVisibility,
    ) {
    }
}
