<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py identity auth --force`.

declare(strict_types=1);

namespace Stackra\Auth\Models;

use Illuminate\Database\Eloquent\Attributes\Fillable;
use Illuminate\Database\Eloquent\Attributes\Table;
use Illuminate\Database\Eloquent\Attributes\UseFactory;
use Illuminate\Database\Eloquent\Attributes\WithoutIncrementing;
use Illuminate\Database\Eloquent\Model;
use Stackra\Auth\Contracts\Data\AuthRefreshTokenInterface;
use Stackra\Auth\Database\Factories\AuthRefreshTokenFactory;
use Stackra\Foundation\Concerns\Filterable;
use Stackra\Foundation\Concerns\HasMetadata;
use Illuminate\Database\Eloquent\Concerns\HasUlids;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\SoftDeletes;
use Mattiverse\Userstamps\Traits\Userstamps;
use OwenIt\Auditing\Auditable;
use OwenIt\Auditing\Contracts\Auditable as AuditableContract;
use Spatie\Activitylog\Traits\LogsActivity;

/**
 * Eloquent model for a AuthRefreshToken.
 *
 * Refresh token — rotation-with-reuse-detection paired with Sanctum PAT.
 *
 * @category Auth
 *
 * @since    0.1.0
 */
#[Table(name: AuthRefreshTokenInterface::TABLE, key: AuthRefreshTokenInterface::PRIMARY_KEY, keyType: AuthRefreshTokenInterface::KEY_TYPE)]
#[Fillable([
    AuthRefreshTokenInterface::ATTR_TOKENABLE_TYPE,
        AuthRefreshTokenInterface::ATTR_TOKENABLE_ID,
        AuthRefreshTokenInterface::ATTR_TOKEN_HASH,
        AuthRefreshTokenInterface::ATTR_FAMILY_ID,
        AuthRefreshTokenInterface::ATTR_PERSONAL_ACCESS_TOKEN_ID,
        AuthRefreshTokenInterface::ATTR_ISSUED_AT,
        AuthRefreshTokenInterface::ATTR_EXPIRES_AT,
        AuthRefreshTokenInterface::ATTR_CONSUMED_AT,
        AuthRefreshTokenInterface::ATTR_REVOKED_AT,
        AuthRefreshTokenInterface::ATTR_IP_ADDRESS_HASH,
        AuthRefreshTokenInterface::ATTR_USER_AGENT_HASH,
        AuthRefreshTokenInterface::ATTR_METADATA,
])]
#[UseFactory(AuthRefreshTokenFactory::class)]
#[WithoutIncrementing]
final class AuthRefreshToken extends Model implements AuthRefreshTokenInterface, AuditableContract
{
    use HasFactory;
    use HasUlids;
    use HasMetadata;
    use Userstamps;
    use LogsActivity;
    use Filterable;
    use SoftDeletes;
    use Auditable;

    /**
     * Cast map — from the blueprint's `x-eloquent.casts`.
     *
     * @var array<string, string>
     */
    protected $casts = [
        AuthRefreshTokenInterface::ATTR_ISSUED_AT => 'datetime',
        AuthRefreshTokenInterface::ATTR_EXPIRES_AT => 'datetime',
        AuthRefreshTokenInterface::ATTR_CONSUMED_AT => 'datetime',
        AuthRefreshTokenInterface::ATTR_REVOKED_AT => 'datetime',
    ];
}
