<?php

// // AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py compliance compliance --force`.

declare(strict_types=1);

namespace Academorix\Compliance\Compliance\Models;

use Illuminate\Database\Eloquent\Attributes\Fillable;
use Illuminate\Database\Eloquent\Attributes\Table;
use Illuminate\Database\Eloquent\Attributes\UseFactory;
use Illuminate\Database\Eloquent\Model;
use Academorix\Compliance\Compliance\Contracts\Data\RetentionRunInterface;
use Academorix\Compliance\Compliance\Database\Factories\RetentionRunFactory;
use Academorix\Foundation\Concerns\Filterable;
use Academorix\Foundation\Concerns\HasMetadata;
use Academorix\Tenancy\Concerns\BelongsToTenant;
use Illuminate\Database\Eloquent\Concerns\HasUlids;
use Illuminate\Database\Eloquent\Factories\HasFactory;

/**
 * Eloquent model for a RetentionRun.
 *
 * Audit trail of every retention sweep.
 *
 * @category Compliance
 *
 * @since    0.1.0
 */
#[Table(name: RetentionRunInterface::TABLE, keyType: RetentionRunInterface::KEY_TYPE)]
#[Fillable([
    RetentionRunInterface::ATTR_TENANT_ID,
        RetentionRunInterface::ATTR_TRIGGERED_BY,
        RetentionRunInterface::ATTR_TRIGGERED_BY_USER_ID,
        RetentionRunInterface::ATTR_STARTED_AT,
        RetentionRunInterface::ATTR_COMPLETED_AT,
        RetentionRunInterface::ATTR_DURATION_MS,
        RetentionRunInterface::ATTR_SCANNED_COUNT,
        RetentionRunInterface::ATTR_PURGED_COUNT,
        RetentionRunInterface::ATTR_ANONYMIZED_COUNT,
        RetentionRunInterface::ATTR_ARCHIVED_COUNT,
        RetentionRunInterface::ATTR_HELD_COUNT,
        RetentionRunInterface::ATTR_SKIPPED_POLICY_COUNT,
        RetentionRunInterface::ATTR_FAILED_COUNT,
        RetentionRunInterface::ATTR_ERROR_SUMMARY,
        RetentionRunInterface::ATTR_MODULES_PROCESSED,
        RetentionRunInterface::ATTR_SWEEP_CONFIG_HASH,
        RetentionRunInterface::ATTR_METADATA,
])]
#[UseFactory(RetentionRunFactory::class)]
final class RetentionRun extends Model implements RetentionRunInterface
{
    use HasFactory;
    use HasUlids;
    use BelongsToTenant;
    use HasMetadata;
    use Filterable;

    /**
     * The primary key IS a string (prefixed ULID); disable auto-increment.
     *
     * @var bool
     */
    public $incrementing = false;

    /**
     * Cast map — from the blueprint's x-eloquent.casts.
     *
     * @var array<string, string>
     */
    protected $casts = [
        RetentionRunInterface::ATTR_TRIGGERED_BY => 'string',
        RetentionRunInterface::ATTR_STARTED_AT => 'datetime',
        RetentionRunInterface::ATTR_COMPLETED_AT => 'datetime',
        RetentionRunInterface::ATTR_ERROR_SUMMARY => 'array',
        RetentionRunInterface::ATTR_MODULES_PROCESSED => 'array',
        RetentionRunInterface::ATTR_METADATA => 'array',
    ];
}
