<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py workflow approvals --force`.

declare(strict_types=1);

namespace Stackra\Approvals\Actions\Platform;

use Stackra\Routing\Attributes\AsAction;
use Stackra\Routing\Attributes\Middleware;
use Stackra\Routing\Concerns\AsController;
use Stackra\Routing\Attributes\Patch;

/**
 * `PATCH /api/v1/platform/approvals/actions/{action_key}` — update action (platform-admin audience).
 *
 * Single-invoke controller wired via `#[AsAction]` + `#[Patch(...)]`
 * + `#[Middleware(...)]` from `Stackra\Routing`. Discovered by the routing
 * package's boot-time `RouteRegistrar` — no route file needed.
 *
 * @category Approvals
 *
 * @since    0.1.0
 */
#[AsAction(name: 'approvals.actions.update')]
#[Patch('/api/v1/platform/approvals/actions/{action_key}')]
#[Middleware(['api', 'auth:sanctum', 'platform_admin'])]
final class UpdateActionAction
{
    use AsController;

    /**
     * Execute the action.
     *
     * TODO(gen): wire the required services + implement the handler body.
     */
    public function __invoke(): mixed
    {
        // Hand-implement the domain logic here.
        return null;
    }
}
