<?php

/**
 * @file database/migrations/2026_07_15_120007_create_jwks_responses_table.php
 *
 * @description
 * Create the `jwks_responses` table for the `JwksResponse` entity.
 * Owned by the auth module. Emitted from the module blueprint —
 * regenerate via `generate-module.py identity auth --force`.
 */
// // AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py identity auth --force`.

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class() extends Migration {
    /**
     * Run the migration.
     */
    public function up(): void
    {
        Schema::create('jwks_responses', function (Blueprint $table): void {
            $table->string('keys');

        });
    }

    /**
     * Reverse the migration.
     */
    public function down(): void
    {
        Schema::dropIfExists('jwks_responses');
    }
};
