<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py platform branch --force`.

declare(strict_types=1);

namespace Stackra\Branch\Database\Seeders;

use Stackra\Branch\Enums\BranchPermission;
use Stackra\Authorization\Database\Seeders\Concerns\SeedsPermissionEnum;
use Stackra\ServiceProvider\Attributes\AsSeeder;
use Illuminate\Database\Seeder;

/**
 * Seed the {@see BranchPermission} cases into spatie/laravel-permission's
 * `permissions` table.
 *
 * All the boilerplate (spatie model resolution, `updateOrCreate` loop,
 * cache flush) lives in the shared {@see SeedsPermissionEnum} trait.
 *
 * @category Branch
 *
 * @since    0.1.0
 */
#[AsSeeder(priority: 46, environments: [])]
final class BranchPermissionSeeder extends Seeder
{
    use SeedsPermissionEnum;

    /**
     * {@inheritDoc}
     */
    protected function permissionEnums(): array
    {
        return [BranchPermission::class];
    }
}
