<?php

// // AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py sports athlete --force`.

declare(strict_types=1);

namespace Academorix\Athlete\Exceptions;

use Academorix\Exceptions\AcademorixException;

/**
 * The submitted status transition is not allowed.
 *
 * @category Athlete
 *
 * @since    0.1.0
 */
final class AthleteStatusTransitionInvalidException extends AcademorixException
{
    /**
     * Stable machine-readable error code emitted on the JSON envelope.
     */
    public const CODE = 'ATHLETE_STATUS_TRANSITION_INVALID';

    /**
     * Translation key for the humanised message.
     */
    public const TRANSLATION_KEY = 'athlete::errors.ATHLETE_STATUS_TRANSITION_INVALID';
}
