<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py growth analytics --force`.

declare(strict_types=1);

namespace Academorix\Analytics\Events;

use Illuminate\Contracts\Events\ShouldDispatchAfterCommit;

/**
 * identified_user_id transitions null → non-null.
 *
 * ## Consumers
 *
 * - analytics::MergeAliasedEventsListener — rewrites subject_id on prior events from AnalyticsIdentity to User (Enterprise + analytics_identity_merge entitlement only)
 *
 * @category Analytics
 *
 * @since    0.1.0
 */
final readonly class AnalyticsIdentityIdentified implements ShouldDispatchAfterCommit
{
    /**
     * @param  string  $identityId  ULID
     * @param  string  $tenantId  ULID
     * @param  string  $anonymousId  UUID
     * @param  string  $identifiedUserId  ULID (usr_)
     * @param  string  $identifiedAt  ISO 8601
     */
    public function __construct(
        public readonly string $identityId,
        public readonly string $tenantId,
        public readonly string $anonymousId,
        public readonly string $identifiedUserId,
        public readonly string $identifiedAt,
    ) {
    }
}
