<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py sports progress --force`.

declare(strict_types=1);

namespace Stackra\Progress\Actions\Tenant;

use Stackra\Progress\Contracts\Repositories\GradingEventRepositoryInterface;
use Stackra\Progress\Data\GradingEventData;
use Stackra\Routing\Attributes\AsAction;
use Stackra\Routing\Attributes\Middleware;
use Stackra\Routing\Concerns\AsController;
use Stackra\Routing\Attributes\Get;
use Illuminate\Http\Request;
use Illuminate\Pagination\LengthAwarePaginator;
use Spatie\LaravelData\PaginatedDataCollection;

/**
 * `GET /api/v1/grading-events` — list action (tenant audience).
 *
 * Single-invoke controller wired via `#[AsAction]` + `#[Get(...)]`
 * + `#[Middleware(...)]` from `Stackra\Routing`. Discovered by the routing
 * package's boot-time `RouteRegistrar` — no route file needed.
 *
 * @category Progress
 *
 * @since    0.1.0
 */
#[AsAction(name: 'progress.grading_events.list')]
#[Get('/api/v1/grading-events')]
#[Middleware(['api', 'auth:sanctum', 'tenant.resolve'])]
final class ListGradingEventAction
{
    use AsController;

    public function __construct(
        private readonly GradingEventRepositoryInterface $repository,
    ) {
    }

    /**
     * List `grading-events` for the current caller.
     *
     * The `Repository` base picks up `filter[...]` / `sort=...` /
     * `include=...` query parameters via the `#[Filterable]` attribute
     * on the concrete repository — no per-Action wiring needed.
     *
     * @return PaginatedDataCollection<int, GradingEventData>  Paginated wire-visible DTOs.
     */
    public function __invoke(Request $request): PaginatedDataCollection
    {
        /** @var LengthAwarePaginator<int, \Stackra\Progress\Models\GradingEvent> $page */
        $page = $this->repository->paginate(
            perPage: (int) $request->integer('per_page', 15),
        );

        return GradingEventData::collect($page, PaginatedDataCollection::class);
    }
}
