<?php

/**
 * @file database/migrations/2026_07_15_120000_create_cities_table.php
 *
 * @description
 * Create the `cities` table for the `City` entity.
 * Owned by the geography module. Every column + index reference
 * goes through {@see Stackra\Geography\Contracts\Data\CityInterface} per the `models` steering
 * rule §1 — no raw string literals.
 */
// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py shared geography --force`.

declare(strict_types=1);

use Stackra\Geography\Contracts\Data\CityInterface;
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class() extends Migration {
    /**
     * Run the migration.
     */
    public function up(): void
    {
        Schema::create(CityInterface::TABLE, function (Blueprint $table): void {
            $table->string(CityInterface::ATTR_ID);
            $table->string(CityInterface::ATTR_COUNTRY_ID);
            $table->string(CityInterface::ATTR_STATE_ID);
            $table->string(CityInterface::ATTR_NAME);
            $table->string(CityInterface::ATTR_COUNTRY_CODE);
            $table->string(CityInterface::ATTR_STATE_CODE)->nullable();
            $table->string(CityInterface::ATTR_LATITUDE)->nullable();
            $table->string(CityInterface::ATTR_LONGITUDE)->nullable();

        });
    }

    /**
     * Reverse the migration.
     */
    public function down(): void
    {
        Schema::dropIfExists(CityInterface::TABLE);
    }
};
