<?php

// // AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py sports session --force`.

declare(strict_types=1);

namespace Academorix\Sports\Session\Events;

use Illuminate\Contracts\Events\ShouldDispatchAfterCommit;

/**
 * SessionAttendance soft-deleted.
 *
 * ## Consumers
 *
 * - audit::WriteToAuditLog
 * - activity::WriteToActivityLog
 *
 * @category Session
 *
 * @since    0.1.0
 */
final readonly class SessionAthleteRemoved implements ShouldDispatchAfterCommit
{
    /**
     * @param  string  $sessionId  ULID
     * @param  string  $attendanceId  ULID
     * @param  string  $tenantId  ULID
     * @param  string  $athleteId  ULID
     * @param  string  $removedBy  ULID
     * @param  string  $reason  string | null
     */
    public function __construct(
        public readonly string $sessionId,
        public readonly string $attendanceId,
        public readonly string $tenantId,
        public readonly string $athleteId,
        public readonly string $removedBy,
        public readonly string $reason,
    ) {
    }
}
