<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py identity identity --force`.

declare(strict_types=1);

namespace Academorix\Identity\Exceptions;

use Academorix\Exceptions\AcademorixException;

/**
 * Enrolment step: the submitted TOTP code did not match.
 *
 * @category Identity
 *
 * @since    0.1.0
 */
final class MfaTotpConfirmationInvalidException extends AcademorixException
{
    /**
     * Stable machine-readable error code emitted on the JSON envelope.
     */
    public const CODE = 'MFA_TOTP_CONFIRMATION_INVALID';

    /**
     * Translation key for the humanised message.
     */
    public const TRANSLATION_KEY = 'identity::errors.MFA_TOTP_CONFIRMATION_INVALID';
}
