<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py observability audit --force`.

declare(strict_types=1);

namespace Stackra\Audit\Exceptions;

use Stackra\Exceptions\StackraException;

/**
 * byEntity filter references an auditable_type that does not resolve at boot (not a valid audited model class).
 *
 * @category Audit
 *
 * @since    0.1.0
 */
final class NotificationsAuditAuditableTypeUnknownException extends StackraException
{
    /**
     * Stable machine-readable error code emitted on the JSON envelope.
     */
    public const CODE = 'NOTIFICATIONS_AUDIT_AUDITABLE_TYPE_UNKNOWN';

    /**
     * Translation key for the humanised message.
     */
    public const TRANSLATION_KEY = 'audit::errors.NOTIFICATIONS_AUDIT_AUDITABLE_TYPE_UNKNOWN';
}
