<?php

// // AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py workflow approvals --force`.

declare(strict_types=1);

namespace Academorix\Approvals\Database\Factories;

use Illuminate\Database\Eloquent\Factories\Factory;
use Academorix\Approvals\Contracts\Data\ApprovableActionInterface;
use Academorix\Approvals\Models\ApprovableAction;

/**
 * Factory for {@see \Academorix\Approvals\Models\ApprovableAction}.
 *
 * Auto-generated skeleton — extend with named states as domain
 * cases emerge (e.g. `->published()`, `->overdue()`, `->archived()`).
 *
 * @extends Factory<\Academorix\Approvals\Models\ApprovableAction>
 *
 * @category Approvals
 *
 * @since    0.1.0
 */
final class ApprovableActionFactory extends Factory
{
    /**
     * The model this factory builds.
     *
     * @var class-string<ApprovableAction>
     */
    protected $model = ApprovableAction::class;

    /**
     * Return the default model attribute values.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        return [
            ApprovableActionInterface::ATTR_ACTION_KEY => fake()->sentence(3),
            ApprovableActionInterface::ATTR_NAMESPACE => fake()->sentence(3),
            ApprovableActionInterface::ATTR_ACTION_CLASS_FQCN => fake()->sentence(3),
            ApprovableActionInterface::ATTR_LABEL => null,
            ApprovableActionInterface::ATTR_DESCRIPTION => null,
            ApprovableActionInterface::ATTR_PAYLOAD_SCHEMA_JSON => null,
            ApprovableActionInterface::ATTR_CONTEXT_VARIABLES_SCHEMA_JSON => null,
            ApprovableActionInterface::ATTR_IS_ACTIVE => fake()->boolean(),
            ApprovableActionInterface::ATTR_IS_SYSTEM => fake()->boolean(),
            ApprovableActionInterface::ATTR_METADATA => null,
        ];
    }
}
