<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py notifications messaging --force`.

declare(strict_types=1);

namespace Academorix\Messaging\Events;

use Academorix\Events\Attributes\AsEvent;
use Illuminate\Contracts\Events\ShouldDispatchAfterCommit;

/**
 * Message body updated. Edited-timestamp added. Original preserved in audit trail.
 *
 * ## Consumers
 *
 * - audit::WriteToAuditLog (retention 90d)
 * - realtime::BroadcastToConversation
 *
 * @category Messaging
 *
 * @since    0.1.0
 */
#[AsEvent]
final readonly class MessageEdited implements ShouldDispatchAfterCommit
{
    /**
     * @param  string  $messageId  ULID
     * @param  string  $conversationId  ULID
     * @param  string  $editedByUserId  ULID
     * @param  string  $editedAt  ISO 8601
     */
    public function __construct(
        public readonly string $messageId,
        public readonly string $conversationId,
        public readonly string $editedByUserId,
        public readonly string $editedAt,
    ) {
    }
}
