<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py platform credentials --force`.

declare(strict_types=1);

namespace Academorix\Credentials\Enums;

use Academorix\Enum\Enum;

/**
 * Closed-set enum for `holder_type` on `credential`.
 *
 * Polymorphic — athletes / staff.
 *
 * @category Credentials
 *
 * @since    0.1.0
 */
enum CredentialHolderType: string
{
    use Enum;

    case Athletes = 'athletes';
    case Staff = 'staff';
}
