<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py platform application --force`.

declare(strict_types=1);

namespace Stackra\Application\Contracts\Services;

use Stackra\Application\Services\ApplicationResolver;
use Illuminate\Container\Attributes\Bind;

/**
 * Service contract for ApplicationResolver.
 *
 * Bound to the concrete via `#[Bind(ApplicationResolver::class)]`. Consumers
 * type-hint this interface; tests bind a fake through the container.
 *
 * @category Application
 *
 * @since    0.1.0
 */
#[Bind(ApplicationResolver::class)]
interface ApplicationResolverInterface
{
    // TODO(gen): declare the domain methods this service exposes.
}
