<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py identity user --force`.

declare(strict_types=1);

namespace Academorix\User\Events;

use Illuminate\Contracts\Events\ShouldDispatchAfterCommit;

/**
 * TenantMember row created (user joined an additional Tenant within the same Application).
 *
 * ## Consumers
 *
 * - audit::WriteToAuditLog
 * - activity::WriteToActivityLog
 * - notifications::DispatchUserAddedToTenantNotification
 *
 * @category User
 *
 * @since    0.1.0
 */
final readonly class UserLinkedToTenant implements ShouldDispatchAfterCommit
{
    /**
     * @param  string  $userId  ULID
     * @param  string  $tenantId  ULID (the newly-linked tenant)
     * @param  string  $membershipId  ULID (tmb_*)
     * @param  string  $roleId  ULID
     * @param  string  $invitedBy  ULID | null (null = auto-provisioned on tenant creation)
     * @param  bool  $isDefault  boolean
     */
    public function __construct(
        public readonly string $userId,
        public readonly string $tenantId,
        public readonly string $membershipId,
        public readonly string $roleId,
        public readonly string $invitedBy,
        public readonly bool $isDefault,
    ) {
    }
}
