<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py platform forms --force`.

declare(strict_types=1);

namespace Academorix\Forms\Events;

use Academorix\Events\Attributes\AsEvent;
use Illuminate\Contracts\Events\ShouldDispatchAfterCommit;

/**
 * HIGH VOLUME. Medical clearance / signature / photo uploaded through storage module.
 *
 * ## Consumers
 *
 * - storage::MoveToPermanent
 * - activity::WriteToActivityLog (sampled 10%)
 *
 * @category Forms
 *
 * @since    0.1.0
 */
#[AsEvent]
final readonly class FormFileUploaded implements ShouldDispatchAfterCommit
{
    /**
     * @param  string  $submissionId  ULID
     * @param  string  $fileId  ULID
     * @param  string  $fieldKey  string
     * @param  int  $sizeBytes  bigint
     * @param  string  $mimeType  string
     */
    public function __construct(
        public readonly string $submissionId,
        public readonly string $fileId,
        public readonly string $fieldKey,
        public readonly int $sizeBytes,
        public readonly string $mimeType,
    ) {
    }
}
