<?php

// // AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py shared foundation --force`.

declare(strict_types=1);

namespace Academorix\Foundation\Exceptions;

use Academorix\Exceptions\AcademorixException;

/**
 * Resource does not exist OR the caller does not have visibility to it (deliberate — do not distinguish to prevent enumeration).
 *
 * @category Foundation
 *
 * @since    0.1.0
 */
final class FoundationNotFoundException extends AcademorixException
{
    /**
     * Stable machine-readable error code emitted on the JSON envelope.
     */
    public const CODE = 'FOUNDATION_NOT_FOUND';

    /**
     * Translation key for the humanised message.
     */
    public const TRANSLATION_KEY = 'foundation::errors.FOUNDATION_NOT_FOUND';
}
