<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py shared localization --force`.

declare(strict_types=1);

namespace Academorix\Localization\Exceptions;

use Academorix\Exceptions\AcademorixException;

/**
 * Raised when the domain rule `DRIVER_RATE_LIMITED` fires.
 *
 * @category Localization
 *
 * @since    0.1.0
 */
final class DriverRateLimitedException extends AcademorixException
{
    /**
     * Stable machine-readable error code emitted on the JSON envelope.
     */
    public const CODE = 'DRIVER_RATE_LIMITED';

    /**
     * Translation key for the humanised message.
     */
    public const TRANSLATION_KEY = 'localization::errors.DRIVER_RATE_LIMITED';
}
