<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py platform branch --force`.

declare(strict_types=1);

namespace Stackra\Branch\Console;

use Stackra\Console\Attributes\AsCommand;
use Stackra\Console\Commands\BaseCommand;

/**
 * `php artisan branch:audit-address` — Audit address — branch command.
 *
 * @category Branch
 *
 * @since    0.1.0
 */
#[AsCommand(
    name: 'branch:audit-address',
    description: 'Audit address — branch command.',
)]
final class AuditAddressCommand extends BaseCommand
{
    /**
     * Execute the command.
     *
     * TODO(gen): wire the required services + implement the handler body.
     */
    public function handle(): int
    {
        $this->omni->titleBar('Audit address — branch command', 'sky');

        // TODO(gen): wire the required services + implement the handler body.

        $this->omni->success('Audit address — branch command completed.');
        $this->showDuration();

        return self::SUCCESS;
    }
}
