<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py platform branch --force`.

declare(strict_types=1);

namespace Stackra\Branch\Console;

use Stackra\Console\Attributes\AsCommand;
use Stackra\Console\Commands\BaseCommand;

/**
 * `php artisan branch:reopen` — Reopen — branch command.
 *
 * @category Branch
 *
 * @since    0.1.0
 */
#[AsCommand(
    name: 'branch:reopen',
    description: 'Reopen — branch command.',
)]
final class ReopenCommand extends BaseCommand
{
    /**
     * Execute the command.
     *
     * TODO(gen): wire the required services + implement the handler body.
     */
    public function handle(): int
    {
        $this->omni->titleBar('Reopen — branch command', 'sky');

        // TODO(gen): wire the required services + implement the handler body.

        $this->omni->success('Reopen — branch command completed.');
        $this->showDuration();

        return self::SUCCESS;
    }
}
