<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py finance membership --force`.

declare(strict_types=1);

namespace Academorix\Membership\Contracts\Repositories;

use Stackra\Crud\Contracts\RepositoryInterface;

/**
 * Repository contract for {@see Academorix\Membership\Models\MembershipRenewal}.
 *
 * Consumers type-hint the interface; the container binds the concrete
 * via `#[AsRepository]` on `MembershipRenewalRepository`.
 *
 * @extends RepositoryInterface<\Academorix\Membership\Models\MembershipRenewal>
 *
 * @category Membership
 *
 * @since    0.1.0
 */
interface MembershipRenewalRepositoryInterface extends RepositoryInterface
{
    // Domain-specific query methods live here. CRUD comes from the base.
}
