<?php

/**
 * @file database/migrations/2026_07_15_120000_create_transaction_ledger_entries_table.php
 *
 * @description
 * Create the `transaction_ledger_entries` table for the `TransactionLedgerEntry` entity.
 * Owned by the transaction module. Every column + index reference
 * goes through {@see Academorix\Transaction\Contracts\Data\TransactionLedgerEntryInterface} per the `models` steering
 * rule §1 — no raw string literals.
 */
// // AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py finance transaction --force`.

declare(strict_types=1);

use Academorix\Transaction\Contracts\Data\TransactionLedgerEntryInterface;
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class() extends Migration {
    /**
     * Run the migration.
     */
    public function up(): void
    {
        Schema::create(TransactionLedgerEntryInterface::TABLE, function (Blueprint $table): void {
            $table->string(TransactionLedgerEntryInterface::ATTR_ID, 64)->primary();
            $table->string(TransactionLedgerEntryInterface::ATTR_TENANT_ID, 64);
            $table->foreign(TransactionLedgerEntryInterface::ATTR_TENANT_ID)->references('id')->on('tenants')->onDelete('cascade');
            $table->string(TransactionLedgerEntryInterface::ATTR_TRANSACTION_ID, 64);
            $table->foreign(TransactionLedgerEntryInterface::ATTR_TRANSACTION_ID)->references('id')->on('transactions')->onDelete('cascade');
            $table->string(TransactionLedgerEntryInterface::ATTR_ACCOUNT, 32);
            $table->string(TransactionLedgerEntryInterface::ATTR_ACCOUNT_CURRENCY, 3);
            $table->unsignedBigInteger(TransactionLedgerEntryInterface::ATTR_DEBIT_CENTS)->default(0);
            $table->unsignedBigInteger(TransactionLedgerEntryInterface::ATTR_CREDIT_CENTS)->default(0);
            $table->string(TransactionLedgerEntryInterface::ATTR_DESCRIPTION, 256);
            $table->string(TransactionLedgerEntryInterface::ATTR_CREATED_BY_USER_ID, 64)->nullable();
            $table->foreign(TransactionLedgerEntryInterface::ATTR_CREATED_BY_USER_ID)->references('id')->on('users')->onDelete('restrict');
            $table->string(TransactionLedgerEntryInterface::ATTR_UPDATED_BY, 64)->nullable();
            $table->timestampTz(TransactionLedgerEntryInterface::ATTR_CREATED_AT);
            $table->timestampTz(TransactionLedgerEntryInterface::ATTR_UPDATED_AT);
            $table->index([TransactionLedgerEntryInterface::ATTR_TENANT_ID, TransactionLedgerEntryInterface::ATTR_ACCOUNT, TransactionLedgerEntryInterface::ATTR_TRANSACTION_ID], 'ledger_entries_tenant_account_txn_idx');
            $table->index([TransactionLedgerEntryInterface::ATTR_TENANT_ID, TransactionLedgerEntryInterface::ATTR_ACCOUNT, TransactionLedgerEntryInterface::ATTR_CREATED_AT], 'ledger_entries_tenant_account_time_idx');
            $table->index([TransactionLedgerEntryInterface::ATTR_TRANSACTION_ID], 'ledger_entries_transaction_idx');
            $table->index([TransactionLedgerEntryInterface::ATTR_TENANT_ID], 'ledger_entries_debit_xor_credit_check');
        });
    }

    /**
     * Reverse the migration.
     */
    public function down(): void
    {
        Schema::dropIfExists(TransactionLedgerEntryInterface::TABLE);
    }
};
