<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py platform integrations --force`.

declare(strict_types=1);

namespace Academorix\Integrations\Enums;

use Academorix\Enum\Enum;

/**
 * Closed-set enum for `pricing_model` on `app`.
 *
 * free / one_time / recurring / usage_based.
 *
 * @category Integrations
 *
 * @since    0.1.0
 */
enum AppPricingModel: string
{
    use Enum;

    case Free = 'free';
    case OneTime = 'one_time';
    case Recurring = 'recurring';
    case UsageBased = 'usage_based';
}
