<?php

/**
 * @file database/migrations/2026_07_15_120001_create_settings_groups_table.php
 *
 * @description
 * Create the `settings_groups` table for the `SettingsGroup` entity.
 * Owned by the settings module. Emitted from the module blueprint —
 * regenerate via `generate-module.py platform settings --force`.
 */
// // AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py platform settings --force`.

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class() extends Migration {
    /**
     * Run the migration.
     */
    public function up(): void
    {
        Schema::create('settings_groups', function (Blueprint $table): void {
            $table->string('key');
            $table->string('class');
            $table->string('module');
            $table->string('label');
            $table->string('description')->nullable();
            $table->string('icon')->nullable();
            $table->string('scope');
            $table->string('public');
            $table->string('sort_order');
            $table->string('permission')->nullable();
            $table->string('requires_feature')->nullable();
            $table->string('requires_entitlement')->nullable();
            $table->string('sections');

        });
    }

    /**
     * Reverse the migration.
     */
    public function down(): void
    {
        Schema::dropIfExists('settings_groups');
    }
};
