<?php

// // AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py platform reporting --force`.

declare(strict_types=1);

namespace Academorix\Reporting\Contracts\Data;

use Illuminate\Container\Attributes\Bind;
use Academorix\Reporting\Models\Dashboard;

/**
 * Table shape for the `dashboards` table.
 *
 *
 *
 * @category Reporting
 *
 * @since    0.1.0
 */
#[Bind(Dashboard::class)]
interface DashboardInterface
{
    /**
     * Table name.
     */
    public const string TABLE = 'dashboards';

    /**
     * Primary key column.
     */
    public const string PRIMARY_KEY = 'id';

    /**
     * Primary key column type — string (ULID with prefix `dsh_`).
     */
    public const string KEY_TYPE = 'string';

    // ── Columns ───────────────────────────────────────────────

    public const string ATTR_ID               = 'id';
    public const string ATTR_TENANT_ID        = 'tenant_id';
    public const string ATTR_OWNER_USER_ID    = 'owner_user_id';
    public const string ATTR_NAME             = 'name';
    public const string ATTR_DESCRIPTION      = 'description';
    public const string ATTR_LAYOUT           = 'layout';
    public const string ATTR_WIDGETS          = 'widgets';
    public const string ATTR_AUDIENCE_SCOPE   = 'audience_scope';
    public const string ATTR_SHARED_WITH_ROLE = 'shared_with_role';
    public const string ATTR_LAST_SNAPSHOT_AT = 'last_snapshot_at';
    public const string ATTR_METADATA         = 'metadata';
    public const string ATTR_CREATED_AT       = 'created_at';
    public const string ATTR_UPDATED_AT       = 'updated_at';
    public const string ATTR_DELETED_AT       = 'deleted_at';
}
