<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py sports match --force`.

declare(strict_types=1);

namespace Stackra\Match\Repositories;

use Stackra\Crud\Attributes\AsRepository;
use Stackra\Crud\Attributes\Cacheable;
use Stackra\Crud\Attributes\Filterable;
use Stackra\Crud\Attributes\UseModel;
use Stackra\Crud\Repositories\Repository;
use Stackra\Match\Contracts\Data\OpponentLogoInterface;
use Stackra\Match\Contracts\Repositories\OpponentLogoRepositoryInterface;
use Stackra\Match\Models\OpponentLogo;

/**
 * Attribute-first Eloquent repository for {@see Stackra\Match\Models\OpponentLogo}.
 *
 * Bound to the interface via `#[AsRepository]`; the model comes from
 * `#[UseModel(OpponentLogoInterface::class)]` which resolves to
 * `OpponentLogo` through the interface's `#[Bind]`.
 *
 * @extends Repository<\Stackra\Match\Models\OpponentLogo>
 *
 * @category Match
 *
 * @since    0.1.0
 */
#[AsRepository]
#[UseModel(OpponentLogoInterface::class)]
#[Cacheable(ttl: 3600, tags: true)]
#[Filterable('*')]
final class OpponentLogoRepository extends Repository implements OpponentLogoRepositoryInterface
{
    // Domain methods added here. CRUD comes from Repository.
}
