<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py finance marketplace-fee --force`.

declare(strict_types=1);

namespace Academorix\MarketplaceFee\Contracts\Data;

use Illuminate\Container\Attributes\Bind;
use Academorix\MarketplaceFee\Models\FeeApplication;

/**
 * Table shape for the `fee_applications` table.
 *
 * One row per transaction where a fee was applied.
 *
 * @category MarketplaceFee
 *
 * @since    0.1.0
 */
#[Bind(FeeApplication::class)]
interface FeeApplicationInterface
{
    /**
     * Table name.
     */
    public const string TABLE = 'fee_applications';

    /**
     * Primary key column.
     */
    public const string PRIMARY_KEY = 'id';

    /**
     * Primary key column type — string (ULID with prefix `fap_`).
     */
    public const string KEY_TYPE = 'string';

    // ── Columns ───────────────────────────────────────────────

    public const string ATTR_ID                        = 'id';
    public const string ATTR_TENANT_ID                 = 'tenant_id';
    public const string ATTR_FEE_SCHEDULE_ID           = 'fee_schedule_id';
    public const string ATTR_PAYMENT_ID                = 'payment_id';
    public const string ATTR_STATUS                    = 'status';
    public const string ATTR_CURRENCY                  = 'currency';
    public const string ATTR_GROSS_AMOUNT_MINOR        = 'gross_amount_minor';
    public const string ATTR_FEE_RATE_APPLIED          = 'fee_rate_applied';
    public const string ATTR_FEE_AMOUNT_MINOR          = 'fee_amount_minor';
    public const string ATTR_FLAT_FEE_MINOR            = 'flat_fee_minor';
    public const string ATTR_STRIPE_APPLICATION_FEE_ID = 'stripe_application_fee_id';
    public const string ATTR_APPLIED_AT                = 'applied_at';
    public const string ATTR_REVERSED_AT               = 'reversed_at';
    public const string ATTR_REVERSAL_REASON           = 'reversal_reason';
    public const string ATTR_FEE_PAYOUT_ID             = 'fee_payout_id';
    public const string ATTR_SCHEDULE_SNAPSHOT         = 'schedule_snapshot';
    public const string ATTR_METADATA                  = 'metadata';
    public const string ATTR_CREATED_BY                = 'created_by';
    public const string ATTR_UPDATED_BY                = 'updated_by';
    public const string ATTR_CREATED_AT                = 'created_at';
    public const string ATTR_UPDATED_AT                = 'updated_at';
}
