<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py finance payment --force`.

declare(strict_types=1);

namespace Academorix\Payment\Models;

use Illuminate\Database\Eloquent\Attributes\Fillable;
use Illuminate\Database\Eloquent\Attributes\Table;
use Illuminate\Database\Eloquent\Attributes\UseFactory;
use Illuminate\Database\Eloquent\Attributes\WithoutIncrementing;
use Illuminate\Database\Eloquent\Model;
use Academorix\Payment\Contracts\Data\PaymentMethodInterface;
use Academorix\Payment\Database\Factories\PaymentMethodFactory;
use Stackra\Foundation\Concerns\Filterable;
use Stackra\Foundation\Concerns\HasMetadata;
use Academorix\Payment\Enums\PaymentMethodDeactivatedReason;
use Academorix\Payment\Enums\PaymentProvider;
use Academorix\Payment\Policies\PaymentMethodPolicy;
use Stackra\Tenancy\Concerns\BelongsToTenant;
use Illuminate\Database\Eloquent\Attributes\UsePolicy;
use Illuminate\Database\Eloquent\Concerns\HasUlids;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\SoftDeletes;
use Mattiverse\Userstamps\Traits\Userstamps;
use OwenIt\Auditing\Auditable;
use OwenIt\Auditing\Contracts\Auditable as AuditableContract;
use Spatie\Activitylog\Traits\LogsActivity;

/**
 * Eloquent model for a PaymentMethod.
 *
 * Saved payment tokens — NEVER card PAN/CVV/magnetic-stripe.
 *
 * @category Payment
 *
 * @since    0.1.0
 */
#[Table(name: PaymentMethodInterface::TABLE, key: PaymentMethodInterface::PRIMARY_KEY, keyType: PaymentMethodInterface::KEY_TYPE)]
#[Fillable([
    PaymentMethodInterface::ATTR_TENANT_ID,
        PaymentMethodInterface::ATTR_CUSTOMER_TYPE,
        PaymentMethodInterface::ATTR_CUSTOMER_ID,
        PaymentMethodInterface::ATTR_PROVIDER,
        PaymentMethodInterface::ATTR_PROVIDER_REFERENCE_ID,
        PaymentMethodInterface::ATTR_METHOD_TYPE,
        PaymentMethodInterface::ATTR_BRAND,
        PaymentMethodInterface::ATTR_LAST4,
        PaymentMethodInterface::ATTR_EXP_MONTH,
        PaymentMethodInterface::ATTR_EXP_YEAR,
        PaymentMethodInterface::ATTR_FINGERPRINT_HASH,
        PaymentMethodInterface::ATTR_BILLING_ADDRESS,
        PaymentMethodInterface::ATTR_IS_DEFAULT,
        PaymentMethodInterface::ATTR_IS_ACTIVE,
        PaymentMethodInterface::ATTR_LAST_USED_AT,
        PaymentMethodInterface::ATTR_VERIFIED_AT,
        PaymentMethodInterface::ATTR_DEACTIVATED_REASON,
        PaymentMethodInterface::ATTR_METADATA,
])]
#[UseFactory(PaymentMethodFactory::class)]
#[WithoutIncrementing]
#[UsePolicy(PaymentMethodPolicy::class)]
final class PaymentMethod extends Model implements PaymentMethodInterface, AuditableContract
{
    use HasFactory;
    use HasUlids;
    use BelongsToTenant;
    use HasMetadata;
    use Userstamps;
    use Auditable;
    use LogsActivity;
    use Filterable;
    use SoftDeletes;

    /**
     * Cast map — from the blueprint's `x-eloquent.casts`.
     *
     * @var array<string, string>
     */
    protected $casts = [
        PaymentMethodInterface::ATTR_PROVIDER => PaymentProvider::class,
        PaymentMethodInterface::ATTR_PROVIDER_REFERENCE_ID => 'encrypted:string',
        PaymentMethodInterface::ATTR_METHOD_TYPE => PaymentMethodType::class,
        PaymentMethodInterface::ATTR_EXP_MONTH => 'integer',
        PaymentMethodInterface::ATTR_EXP_YEAR => 'integer',
        PaymentMethodInterface::ATTR_BILLING_ADDRESS => 'array',
        PaymentMethodInterface::ATTR_IS_DEFAULT => 'boolean',
        PaymentMethodInterface::ATTR_IS_ACTIVE => 'boolean',
        PaymentMethodInterface::ATTR_LAST_USED_AT => 'datetime',
        PaymentMethodInterface::ATTR_VERIFIED_AT => 'datetime',
        PaymentMethodInterface::ATTR_DEACTIVATED_REASON => PaymentMethodDeactivatedReason::class,
        PaymentMethodInterface::ATTR_METADATA => 'array',
    ];
}
