<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py sports performance --force`.

declare(strict_types=1);

namespace Stackra\Performance\Policies;

use Stackra\User\Models\User;
use Stackra\Performance\Models\TestBattery;

/**
 * Authorization policy for {@see \Stackra\Performance\Models\TestBattery}.
 *
 * Wired via `#[UsePolicy]` on the Model.
 *
 * @category Performance
 *
 * @since    0.1.0
 */
final class TestBatteryPolicy
{
    /**
     * viewAny ability.
     *
     * @return bool
     */
    public function viewAny(User $user, TestBattery $model): bool
    {
        return $user->can('performance.batteries.viewAny');
    }
    /**
     * view ability.
     *
     * @return bool
     */
    public function view(User $user, TestBattery $model): bool
    {
        return $user->can('performance.batteries.view');
    }
    /**
     * coach + branch_manager + admin + owner
     *
     * @return bool
     */
    public function create(User $user, TestBattery $model): bool
    {
        return $user->can('performance.batteries.create');
    }
    /**
     * update ability.
     *
     * @return bool
     */
    public function update(User $user, TestBattery $model): bool
    {
        return $user->can('performance.batteries.update');
    }
    /**
     * admin + owner
     *
     * @return bool
     */
    public function delete(User $user, TestBattery $model): bool
    {
        return $user->can('performance.batteries.delete');
    }
}
