<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py sports registrations --force`.

declare(strict_types=1);

namespace Stackra\Registrations\Events;

use Stackra\Events\Attributes\AsEvent;
use Illuminate\Contracts\Events\ShouldDispatchAfterCommit;

/**
 * Owner initiated contact. stage: lead → contacted.
 *
 * ## Consumers
 *
 * - audit::WriteToAuditLog
 *
 * @category Registrations
 *
 * @since    0.1.0
 */
#[AsEvent]
final readonly class RegistrationContacted implements ShouldDispatchAfterCommit
{
    /**
     * @param  string  $registrationId  ULID
     * @param  string  $contactedByUserId  ULID
     */
    public function __construct(
        public readonly string $registrationId,
        public readonly string $contactedByUserId,
    ) {
    }
}
