<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py workflow approvals --force`.

declare(strict_types=1);

namespace Stackra\Approvals\Exceptions;

use Stackra\Exceptions\StackraException;

/**
 * ApprovalInstanceExecutor dispatched the underlying action but the action threw.
 *
 * @category Approvals
 *
 * @since    0.1.0
 */
final class ApprovalExecutionFailedException extends StackraException
{
    /**
     * Stable machine-readable error code emitted on the JSON envelope.
     */
    public const CODE = 'APPROVAL_EXECUTION_FAILED';

    /**
     * Translation key for the humanised message.
     */
    public const TRANSLATION_KEY = 'approvals::errors.APPROVAL_EXECUTION_FAILED';
}
