<?php

// // AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py sports event --force`.

declare(strict_types=1);

namespace Academorix\Sports\Event\Contracts\Data;

use Illuminate\Container\Attributes\Bind;
use Academorix\Sports\Event\Models\EventReminder;

/**
 * Table shape for the `event_reminders` table.
 *
 * Throttled reminder log — records that a reminder was dispatched for an invitation, prevents double-fire within 24h.
 *
 * @category Event
 *
 * @since    0.1.0
 */
#[Bind(EventReminder::class)]
interface EventReminderInterface
{
    /**
     * Table name.
     */
    public const string TABLE = 'event_reminders';

    /**
     * Primary key column.
     */
    public const string PRIMARY_KEY = 'id';

    /**
     * Primary key column type — string (ULID with prefix `ern_`).
     */
    public const string KEY_TYPE = 'string';

    // ── Columns ───────────────────────────────────────────────

    public const string ATTR_ID                  = 'id';
    public const string ATTR_TENANT_ID           = 'tenant_id';
    public const string ATTR_EVENT_INVITATION_ID = 'event_invitation_id';
    public const string ATTR_KIND                = 'kind';
    public const string ATTR_DISPATCHED_AT       = 'dispatched_at';
    public const string ATTR_DISPATCHED_VIA      = 'dispatched_via';
    public const string ATTR_DELIVERY_ID         = 'delivery_id';
    public const string ATTR_METADATA            = 'metadata';
    public const string ATTR_CREATED_AT          = 'created_at';
    public const string ATTR_UPDATED_AT          = 'updated_at';
}
