<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py sports athlete-guardian --force`.

declare(strict_types=1);

namespace Academorix\AthleteGuardian\Exceptions;

use Stackra\Exceptions\Exception;

/**
 * Only verified guardians can be set as primary.
 *
 * @category AthleteGuardian
 *
 * @since    0.1.0
 */
final class PrimaryGuardianMustBeVerifiedException extends Exception
{
    /**
     * Stable machine-readable error code emitted on the JSON envelope.
     */
    public const CODE = 'PRIMARY_GUARDIAN_MUST_BE_VERIFIED';

    /**
     * Translation key for the humanised message.
     */
    public const TRANSLATION_KEY = 'athlete-guardian::errors.PRIMARY_GUARDIAN_MUST_BE_VERIFIED';
}
