<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py access requests --force`.

declare(strict_types=1);

namespace Stackra\Requests\Services;

use Stackra\Requests\Contracts\Services\AccessRequestSubmitterInterface;
use Illuminate\Container\Attributes\Scoped;
use Stackra\Requests\Contracts\Repositories\AccessRequestProjectionRepositoryInterface;

/**
 * Concrete service — AccessRequestSubmitter.
 *
 * Implements {@see AccessRequestSubmitterInterface}. `#[Scoped]` because most
 * services touch request state (current tenant, current user,
 * correlation id) — see `.kiro/steering/octane-first-di.md`. If
 * the service is provably stateless, promote to `#[Singleton]`.
 *
 * @category Requests
 *
 * @since    0.1.0
 */
#[Scoped]
final class AccessRequestSubmitter implements AccessRequestSubmitterInterface
{
    /**
     * @param  AccessRequestProjectionRepositoryInterface  $accessRequestProjectionRepository  Primary persistence boundary.
     */
    public function __construct(
        private readonly AccessRequestProjectionRepositoryInterface $accessRequestProjectionRepository,
    ) {
    }
}
