<?php

// // AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py sports athlete-enrollment --force`.

declare(strict_types=1);

namespace Academorix\AthleteEnrollment\Exceptions;

use Academorix\Exceptions\AcademorixException;

/**
 * Athlete cannot archive while active enrollments exist.
 *
 * @category AthleteEnrollment
 *
 * @since    0.1.0
 */
final class AthleteHasActiveEnrollmentsException extends AcademorixException
{
    /**
     * Stable machine-readable error code emitted on the JSON envelope.
     */
    public const CODE = 'ATHLETE_HAS_ACTIVE_ENROLLMENTS';

    /**
     * Translation key for the humanised message.
     */
    public const TRANSLATION_KEY = 'athlete-enrollment::errors.ATHLETE_HAS_ACTIVE_ENROLLMENTS';
}
