<?php

// // AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py sports athlete-enrollment --force`.

declare(strict_types=1);

namespace Academorix\AthleteEnrollment\Exceptions;

use Academorix\Exceptions\AcademorixException;

/**
 * Provisional enrollments are Enterprise-only.
 *
 * @category AthleteEnrollment
 *
 * @since    0.1.0
 */
final class EnrollmentProvisionalNotEntitledException extends AcademorixException
{
    /**
     * Stable machine-readable error code emitted on the JSON envelope.
     */
    public const CODE = 'ENROLLMENT_PROVISIONAL_NOT_ENTITLED';

    /**
     * Translation key for the humanised message.
     */
    public const TRANSLATION_KEY = 'athlete-enrollment::errors.ENROLLMENT_PROVISIONAL_NOT_ENTITLED';
}
