<?php

// // AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py finance refund --force`.

declare(strict_types=1);

namespace Academorix\Refund\Events;

use Illuminate\Contracts\Events\ShouldDispatchAfterCommit;

/**
 * Refund.status transitioned awaiting_approval | approved -> cancelled. Cancel path — customer cancelled their own request OR admin cancelled before provider dispatch. Terminal.
 *
 * ## Consumers
 *
 * - audit::WriteToAuditLog (retention: 7 years — financial record)
 * - activity::WriteToActivityLog
 * - notifications::DispatchRefundStatusNotification (customer)
 *
 * @category Refund
 *
 * @since    0.1.0
 */
final readonly class RefundCancelled implements ShouldDispatchAfterCommit
{
    /**
     * @param  string  $refundId  ULID
     * @param  string  $tenantId  ULID
     * @param  string  $cancelledByUserId  ULID (customer or admin)
     * @param  string  $cancelledAt  ISO 8601
     * @param  string  $cancelReason  string | null
     */
    public function __construct(
        public readonly string $refundId,
        public readonly string $tenantId,
        public readonly string $cancelledByUserId,
        public readonly string $cancelledAt,
        public readonly string $cancelReason,
    ) {
    }
}
