<?php

/**
 * @file database/migrations/2026_07_15_120000_create_referral_codes_table.php
 *
 * @description
 * Create the `referral_codes` table for the `ReferralCode` entity.
 * Owned by the referrals module. Every column + index reference
 * goes through {@see Academorix\Referrals\Contracts\Data\ReferralCodeInterface} per the `models` steering
 * rule §1 — no raw string literals.
 */
// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py growth referrals --force`.

declare(strict_types=1);

use Academorix\Referrals\Contracts\Data\ReferralCodeInterface;
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

return new class() extends Migration {
    /**
     * Run the migration.
     */
    public function up(): void
    {
        Schema::create(ReferralCodeInterface::TABLE, function (Blueprint $table): void {
            $table->string(ReferralCodeInterface::ATTR_ID, 64)->primary();
            $table->string(ReferralCodeInterface::ATTR_TENANT_ID, 64);
            $table->foreign(ReferralCodeInterface::ATTR_TENANT_ID)->references('id')->on('tenants')->onDelete('cascade');
            $table->string(ReferralCodeInterface::ATTR_REFERRAL_PROGRAM_ID, 64);
            $table->foreign(ReferralCodeInterface::ATTR_REFERRAL_PROGRAM_ID)->references('id')->on('referral_programs')->onDelete('restrict');
            $table->string(ReferralCodeInterface::ATTR_CODE_TYPE, 16);
            $table->string(ReferralCodeInterface::ATTR_CODE, 64);
            $table->string(ReferralCodeInterface::ATTR_OWNER_TYPE, 16)->nullable();
            $table->string(ReferralCodeInterface::ATTR_OWNER_USER_ID, 64)->nullable();
            $table->foreign(ReferralCodeInterface::ATTR_OWNER_USER_ID)->references('id')->on('users')->onDelete('restrict');
            $table->string(ReferralCodeInterface::ATTR_CAMPAIGN_NAME, 128)->nullable();
            $table->boolean(ReferralCodeInterface::ATTR_IS_ACTIVE)->default(true);
            $table->integer(ReferralCodeInterface::ATTR_USAGE_CAP)->nullable();
            $table->integer(ReferralCodeInterface::ATTR_USAGE_COUNT)->default(0);
            $table->timestampTz(ReferralCodeInterface::ATTR_EXPIRES_AT)->nullable();
            $table->jsonb(ReferralCodeInterface::ATTR_METADATA)->nullable();
            $table->string(ReferralCodeInterface::ATTR_CREATED_BY, 64)->nullable();
            $table->string(ReferralCodeInterface::ATTR_UPDATED_BY, 64)->nullable();
            $table->string(ReferralCodeInterface::ATTR_DELETED_BY, 64)->nullable();
            $table->timestampTz(ReferralCodeInterface::ATTR_DELETED_AT)->nullable();
            $table->timestampTz(ReferralCodeInterface::ATTR_CREATED_AT);
            $table->timestampTz(ReferralCodeInterface::ATTR_UPDATED_AT);
            $table->index([ReferralCodeInterface::ATTR_TENANT_ID, ReferralCodeInterface::ATTR_REFERRAL_PROGRAM_ID, ReferralCodeInterface::ATTR_IS_ACTIVE], 'referral_codes_program_active_idx');
        });

        DB::statement('CREATE UNIQUE INDEX referral_codes_tenant_code_unique ON ' . ReferralCodeInterface::TABLE . ' (' . ReferralCodeInterface::ATTR_TENANT_ID . ', ' . ReferralCodeInterface::ATTR_CODE . ') WHERE deleted_at IS NULL');
        DB::statement('CREATE INDEX referral_codes_owner_user_idx ON ' . ReferralCodeInterface::TABLE . ' (' . ReferralCodeInterface::ATTR_TENANT_ID . ', ' . ReferralCodeInterface::ATTR_OWNER_USER_ID . ') WHERE owner_user_id IS NOT NULL');
        DB::statement('CREATE INDEX referral_codes_campaign_idx ON ' . ReferralCodeInterface::TABLE . ' (' . ReferralCodeInterface::ATTR_TENANT_ID . ', ' . ReferralCodeInterface::ATTR_CAMPAIGN_NAME . ') WHERE campaign_name IS NOT NULL');
    }

    /**
     * Reverse the migration.
     */
    public function down(): void
    {
        Schema::dropIfExists(ReferralCodeInterface::TABLE);
    }
};
