<?php

// // AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py sports competition --force`.

declare(strict_types=1);

namespace Academorix\Sports\Competition\Database\Factories;

use Illuminate\Database\Eloquent\Factories\Factory;
use Academorix\Sports\Competition\Contracts\Data\BracketNodeInterface;
use Academorix\Sports\Competition\Models\BracketNode;

/**
 * Factory for {@see \Academorix\Sports\Competition\Models\BracketNode}.
 *
 * Auto-generated skeleton — extend with named states as domain
 * cases emerge (e.g. `->published()`, `->overdue()`, `->archived()`).
 *
 * @extends Factory<\Academorix\Sports\Competition\Models\BracketNode>
 *
 * @category Competition
 *
 * @since    0.1.0
 */
final class BracketNodeFactory extends Factory
{
    /**
     * The model this factory builds.
     *
     * @var class-string<BracketNode>
     */
    protected $model = BracketNode::class;

    /**
     * Return the default model attribute values.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        return [
            BracketNodeInterface::ATTR_COMPETITION_ID => fake()->sentence(3),
            BracketNodeInterface::ATTR_ROUND => fake()->numberBetween(1, 1000),
            BracketNodeInterface::ATTR_POSITION => fake()->numberBetween(1, 1000),
            BracketNodeInterface::ATTR_TEAM_A_ID => null,
            BracketNodeInterface::ATTR_TEAM_B_ID => null,
            BracketNodeInterface::ATTR_WINNER_TEAM_ID => null,
            BracketNodeInterface::ATTR_ADVANCES_TO_NODE_ID => null,
            BracketNodeInterface::ATTR_FIXTURE_ID => null,
            BracketNodeInterface::ATTR_METADATA => null,
        ];
    }
}
