<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py growth marketing --force`.

declare(strict_types=1);

namespace Academorix\Marketing\Console;

use Stackra\Console\Attributes\AsCommand;
use Stackra\Console\Commands\BaseCommand;

/**
 * `php artisan marketing:list-providers` — List providers — marketing command.
 *
 * @category Marketing
 *
 * @since    0.1.0
 */
#[AsCommand(
    name: 'marketing:list-providers',
    description: 'List providers — marketing command.',
)]
final class ListProvidersCommand extends BaseCommand
{
    /**
     * Execute the command.
     *
     * TODO(gen): wire the required services + implement the handler body.
     */
    public function handle(): int
    {
        $this->omni->titleBar('List providers — marketing command', 'sky');

        // TODO(gen): wire the required services + implement the handler body.

        $this->omni->success('List providers — marketing command completed.');
        $this->showDuration();

        return self::SUCCESS;
    }
}
