<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py observability monitoring --force`.

declare(strict_types=1);

namespace Academorix\Monitoring\Contracts\Services;

use Academorix\Monitoring\Services\CircuitBreakerGate;
use Illuminate\Container\Attributes\Bind;

/**
 * Service contract for CircuitBreakerGate.
 *
 * Bound to the concrete via `#[Bind(CircuitBreakerGate::class)]`. Consumers
 * type-hint this interface; tests bind a fake through the container.
 *
 * @category Monitoring
 *
 * @since    0.1.0
 */
#[Bind(CircuitBreakerGate::class)]
interface CircuitBreakerGateInterface
{
    // TODO(gen): declare the domain methods this service exposes.
}
