<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py sports registry --force`.

declare(strict_types=1);

namespace Academorix\Registry\Exceptions;

use Stackra\Exceptions\Exception;

/**
 * Attempted to deactivate OR hard-delete a Sport that still has downstream references (rows in tables listed in config('sports_registry.
 *
 * @category Registry
 *
 * @since    0.1.0
 */
final class SportReferenceInUseException extends Exception
{
    /**
     * Stable machine-readable error code emitted on the JSON envelope.
     */
    public const CODE = 'SPORT_REFERENCE_IN_USE';

    /**
     * Translation key for the humanised message.
     */
    public const TRANSLATION_KEY = 'registry::errors.SPORT_REFERENCE_IN_USE';
}
