<?php

// // AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py finance tax --force`.

declare(strict_types=1);

namespace Academorix\Finance\Tax\Contracts\Data;

use Illuminate\Container\Attributes\Bind;
use Academorix\Finance\Tax\Models\TaxExemption;

/**
 * Table shape for the `tax_exemptions` table.
 *
 * Per-tenant exemption certificate.
 *
 * @category Tax
 *
 * @since    0.1.0
 */
#[Bind(TaxExemption::class)]
interface TaxExemptionInterface
{
    /**
     * Table name.
     */
    public const string TABLE = 'tax_exemptions';

    /**
     * Primary key column.
     */
    public const string PRIMARY_KEY = 'id';

    /**
     * Primary key column type — string (ULID with prefix `txe_`).
     */
    public const string KEY_TYPE = 'string';

    // ── Columns ───────────────────────────────────────────────

    public const string ATTR_ID                       = 'id';
    public const string ATTR_TENANT_ID                = 'tenant_id';
    public const string ATTR_CUSTOMER_TYPE            = 'customer_type';
    public const string ATTR_CUSTOMER_ID              = 'customer_id';
    public const string ATTR_EXEMPTION_TYPE           = 'exemption_type';
    public const string ATTR_CERTIFICATE_NUMBER       = 'certificate_number';
    public const string ATTR_CERTIFICATE_DOCUMENT_URL = 'certificate_document_url';
    public const string ATTR_ISSUING_JURISDICTION_ID  = 'issuing_jurisdiction_id';
    public const string ATTR_VALID_FROM               = 'valid_from';
    public const string ATTR_VALID_UNTIL              = 'valid_until';
    public const string ATTR_VERIFICATION_STATUS      = 'verification_status';
    public const string ATTR_VERIFIED_BY_USER_ID      = 'verified_by_user_id';
    public const string ATTR_VERIFIED_AT              = 'verified_at';
    public const string ATTR_METADATA                 = 'metadata';
    public const string ATTR_CREATED_BY               = 'created_by';
    public const string ATTR_UPDATED_BY               = 'updated_by';
    public const string ATTR_DELETED_BY               = 'deleted_by';
    public const string ATTR_DELETED_AT               = 'deleted_at';
    public const string ATTR_CREATED_AT               = 'created_at';
    public const string ATTR_UPDATED_AT               = 'updated_at';
}
