<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py observability monitoring --force`.

declare(strict_types=1);

namespace Academorix\Monitoring\Repositories;

use Academorix\Crud\Attributes\AsRepository;
use Academorix\Crud\Attributes\Cacheable;
use Academorix\Crud\Attributes\Filterable;
use Academorix\Crud\Attributes\UseModel;
use Academorix\Crud\Repositories\Repository;
use Academorix\Monitoring\Contracts\Data\HealthCheckInterface;
use Academorix\Monitoring\Contracts\Repositories\HealthCheckRepositoryInterface;
use Academorix\Monitoring\Models\HealthCheck;

/**
 * Attribute-first Eloquent repository for {@see Academorix\Monitoring\Models\HealthCheck}.
 *
 * Bound to the interface via `#[AsRepository]`; the model comes from
 * `#[UseModel(HealthCheckInterface::class)]` which resolves to
 * `HealthCheck` through the interface's `#[Bind]`.
 *
 * @extends Repository<\Academorix\Monitoring\Models\HealthCheck>
 *
 * @category Monitoring
 *
 * @since    0.1.0
 */
#[AsRepository]
#[UseModel(HealthCheckInterface::class)]
#[Cacheable(ttl: 3600, tags: true)]
#[Filterable('*')]
final class HealthCheckRepository extends Repository implements HealthCheckRepositoryInterface
{
    // Domain methods added here. CRUD comes from Repository.
}
