<?php

// // AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py sports awards --force`.

declare(strict_types=1);

namespace Academorix\Awards\Policies;

use Academorix\User\Models\User;
use Academorix\Awards\Models\Award;

/**
 * Authorization policy for {@see \Academorix\Awards\Models\Award}.
 *
 * Wired via `#[UsePolicy]` on the Model.
 *
 * @category Awards
 *
 * @since    0.1.0
 */
final class AwardPolicy
{
    /**
     * viewAny ability.
     *
     * @return bool
     */
    public function viewAny(User $user, Award $model): bool
    {
        return $user->can('awards.viewAny');
    }
    /**
     * own + team + admin
     *
     * @return bool
     */
    public function view(User $user, Award $model): bool
    {
        return $user->can('awards.view');
    }
    /**
     * coach + branch_manager + admin.
     *
     * @return bool
     */
    public function issue(User $user, Award $model): bool
    {
        return $user->can('awards.issue');
    }
    /**
     * admin + owner.
     *
     * @return bool
     */
    public function revoke(User $user, Award $model): bool
    {
        return $user->can('awards.revoke');
    }
}
