<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py sports competition --force`.

declare(strict_types=1);

namespace Stackra\Competition\Console;

use Stackra\Console\Attributes\AsCommand;
use Stackra\Console\Commands\BaseCommand;

/**
 * `php artisan competition:generate-bracket` — Generate bracket — competition command.
 *
 * @category Competition
 *
 * @since    0.1.0
 */
#[AsCommand(
    name: 'competition:generate-bracket',
    description: 'Generate bracket — competition command.',
)]
final class GenerateBracketCommand extends BaseCommand
{
    /**
     * Execute the command.
     *
     * TODO(gen): wire the required services + implement the handler body.
     */
    public function handle(): int
    {
        $this->omni->titleBar('Generate bracket — competition command', 'sky');

        // TODO(gen): wire the required services + implement the handler body.

        $this->omni->success('Generate bracket — competition command completed.');
        $this->showDuration();

        return self::SUCCESS;
    }
}
