<?php

// // AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py access rbac --force`.

declare(strict_types=1);

namespace Academorix\Access\Rbac\Events;

use Illuminate\Contracts\Events\ShouldDispatchAfterCommit;

/**
 * PurgeExpiredRoleAssignmentsJob removed a `model_has_roles` row past its `expires_at`. Fires ONCE per purged row.
 *
 * ## Consumers
 *
 * - activity::WriteToActivityLog
 * - rbac::InvalidatePrincipalPermissionCache
 * - notifications::DispatchRoleRevokedNotification
 *
 * @category Rbac
 *
 * @since    0.1.0
 */
final readonly class RoleAssignmentExpired implements ShouldDispatchAfterCommit
{
    /**
     * @param  string  $roleId  ULID
     * @param  string  $principalType  string
     * @param  string  $principalId  ULID
     * @param  string  $originallyAssignedAt  ISO-8601 timestamp
     * @param  string  $originallyAssignedBy  ULID | null
     * @param  string  $expiresAt  ISO-8601 timestamp
     */
    public function __construct(
        public readonly string $roleId,
        public readonly string $principalType,
        public readonly string $principalId,
        public readonly string $originallyAssignedAt,
        public readonly string $originallyAssignedBy,
        public readonly string $expiresAt,
    ) {
    }
}
