<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py sports event --force`.

declare(strict_types=1);

namespace Academorix\Event\Repositories;

use Stackra\Crud\Attributes\AsRepository;
use Stackra\Crud\Attributes\Cacheable;
use Stackra\Crud\Attributes\Filterable;
use Stackra\Crud\Attributes\UseModel;
use Stackra\Crud\Repositories\Repository;
use Academorix\Event\Contracts\Data\EventInterface;
use Academorix\Event\Contracts\Repositories\EventRepositoryInterface;
use Academorix\Event\Models\Event;

/**
 * Attribute-first Eloquent repository for {@see Academorix\Event\Models\Event}.
 *
 * Bound to the interface via `#[AsRepository]`; the model comes from
 * `#[UseModel(EventInterface::class)]` which resolves to
 * `Event` through the interface's `#[Bind]`.
 *
 * @extends Repository<\Academorix\Event\Models\Event>
 *
 * @category Event
 *
 * @since    0.1.0
 */
#[AsRepository]
#[UseModel(EventInterface::class)]
#[Cacheable(ttl: 3600, tags: true)]
#[Filterable('*')]
final class EventRepository extends Repository implements EventRepositoryInterface
{
    // Domain methods added here. CRUD comes from Repository.
}
