<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py finance expenses --force`.

declare(strict_types=1);

namespace Academorix\Expenses\Actions\Tenant;

use Academorix\Expenses\Contracts\Repositories\PayrollRunRepositoryInterface;
use Academorix\Expenses\Data\PayrollRunData;
use Academorix\Expenses\Data\Requests\CreatePayrollRunRequestData;
use Stackra\Routing\Attributes\AsAction;
use Stackra\Routing\Attributes\Middleware;
use Stackra\Routing\Concerns\AsController;
use Stackra\Routing\Attributes\Post;
use Illuminate\Http\JsonResponse;

/**
 * `POST /api/v1/payroll-runs` — create action (tenant audience).
 *
 * Single-invoke controller wired via `#[AsAction]` + `#[Post(...)]`
 * + `#[Middleware(...)]` from `Stackra\Routing`. Discovered by the routing
 * package's boot-time `RouteRegistrar` — no route file needed.
 *
 * @category Expenses
 *
 * @since    0.1.0
 */
#[AsAction(name: 'expenses.payroll_runs.create')]
#[Post('/api/v1/payroll-runs')]
#[Middleware(['api', 'auth:sanctum', 'tenant.resolve'])]
final class CreatePayrollRunAction
{
    use AsController;

    public function __construct(
        private readonly PayrollRunRepositoryInterface $repository,
    ) {
    }

    /**
     * Create a `payroll-run` from the validated request payload.
     *
     * @param  CreatePayrollRunRequestData  $data  Validated payload (Spatie Data DTO).
     *
     * @return JsonResponse  201 Created with the newly-persisted DTO.
     */
    public function __invoke(CreatePayrollRunRequestData $data): JsonResponse
    {
        $model = $this->repository->create($data->toArray());

        return response()->json(PayrollRunData::from($model), JsonResponse::HTTP_CREATED);
    }
}
