<?php

// // AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py finance chargeback --force`.

declare(strict_types=1);

namespace Academorix\Chargeback\Exceptions;

use Academorix\Exceptions\AcademorixException;

/**
 * The requested state transition is not permitted by the chargeback state machine.
 *
 * @category Chargeback
 *
 * @since    0.1.0
 */
final class ChargebackInvalidStateTransitionException extends AcademorixException
{
    /**
     * Stable machine-readable error code emitted on the JSON envelope.
     */
    public const CODE = 'CHARGEBACK_INVALID_STATE_TRANSITION';

    /**
     * Translation key for the humanised message.
     */
    public const TRANSLATION_KEY = 'chargeback::errors.CHARGEBACK_INVALID_STATE_TRANSITION';
}
