<?php

// // AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py identity user --force`.

declare(strict_types=1);

namespace Academorix\User\Contracts\Services;

use Academorix\User\Services\UserProvisioner;
use Illuminate\Container\Attributes\Bind;

/**
 * Service contract for UserProvisioner.
 *
 * Bound to the concrete via `#[Bind(UserProvisioner::class)]`. Consumers
 * type-hint this interface; tests bind a fake through the container.
 *
 * @category User
 *
 * @since    0.1.0
 */
#[Bind(UserProvisioner::class)]
interface UserProvisionerInterface
{
    // TODO(gen): declare the domain methods this service exposes.
}
