<?php

/**
 * @file database/migrations/2026_07_15_120000_create_reception_visits_table.php
 *
 * @description
 * Create the `reception_visits` table for the `ReceptionVisit` entity.
 * Owned by the reception module. Emitted from the module blueprint —
 * regenerate via `generate-module.py platform reception --force`.
 */
// // AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py platform reception --force`.

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class() extends Migration {
    /**
     * Run the migration.
     */
    public function up(): void
    {
        Schema::create('reception_visits', function (Blueprint $table): void {
            $table->string('id', 30)->primary();
            $table->string('tenant_id', 30);
            $table->foreign('tenant_id')->references('id')->on('tenants')->onDelete('cascade');
            $table->string('branch_id', 30);
            $table->foreign('branch_id')->references('id')->on('branches')->onDelete('cascade');
            $table->string('visitor_name', 200);
            $table->string('visitor_phone', 32)->nullable();
            $table->string('visitor_email', 200)->nullable();
            $table->string('purpose', 200);
            $table->string('host_user_id', 30)->nullable();
            $table->foreign('host_user_id')->references('id')->on('users')->onDelete('set null');
            $table->timestampTz('expected_end_at')->nullable();
            $table->timestampTz('checked_in_at');
            $table->timestampTz('checked_out_at')->nullable();
            $table->string('checked_in_by_user_id', 30);
            $table->foreign('checked_in_by_user_id')->references('id')->on('users')->onDelete('restrict');
            $table->string('checked_out_by_user_id', 30)->nullable();
            $table->foreign('checked_out_by_user_id')->references('id')->on('users')->onDelete('set null');
            $table->string('issued_credential_id', 30)->nullable();
            $table->foreign('issued_credential_id')->references('id')->on('credentials')->onDelete('set null');
            $table->string('day_pass_id', 30)->nullable();
            $table->foreign('day_pass_id')->references('id')->on('day_passes')->onDelete('set null');
            $table->string('status', 16)->default('checked_in');
            $table->text('notes')->nullable();
            $table->jsonb('metadata')->nullable();
            $table->timestampTz('created_at');
            $table->timestampTz('updated_at');
            $table->timestampTz('deleted_at')->nullable();
            $table->index(['tenant_id', 'branch_id', 'checked_in_at'], 'reception_visits_branch_time_idx');
            $table->index(['tenant_id', 'status', 'expected_end_at'], 'reception_visits_stale_idx');
            // Partial-index predicate — hand-add via DB::statement: WHERE status = 'checked_in'
        });
    }

    /**
     * Reverse the migration.
     */
    public function down(): void
    {
        Schema::dropIfExists('reception_visits');
    }
};
