<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py sports match --force`.

declare(strict_types=1);

namespace Academorix\Match\Events;

use Academorix\Events\Attributes\AsEvent;
use Illuminate\Contracts\Events\ShouldDispatchAfterCommit;

/**
 * Match.status transitions LINEUP_SET -> IN_PROGRESS. Typically automatic at kickoff_at or manual from a coach starting the timer.
 *
 * ## Consumers
 *
 * - audit::WriteToAuditLog
 * - match::MaterialiseAttendanceOnMatchStarted (freezes pre-filled attendance rows into the confirmable set)
 * - monitoring::MetricsCollector
 *
 * @category Match
 *
 * @since    0.1.0
 */
#[AsEvent]
final readonly class MatchStarted implements ShouldDispatchAfterCommit
{
    /**
     * @param  string  $matchId  ULID
     * @param  string  $tenantId  ULID
     * @param  string  $kickedOffAt  ISO 8601
     */
    public function __construct(
        public readonly string $matchId,
        public readonly string $tenantId,
        public readonly string $kickedOffAt,
    ) {
    }
}
