<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py growth leads --force`.

declare(strict_types=1);

namespace Academorix\Leads\Events;

use Academorix\Events\Attributes\AsEvent;
use Illuminate\Contracts\Events\ShouldDispatchAfterCommit;

/**
 * Lead.stage transitions NEW -> CONTACTED. LeadObserver.updating fires when the stage_change validator accepts the transition.
 *
 * ## Consumers
 *
 * - audit::WriteToAuditLog
 * - monitoring::MetricsCollector
 *
 * @category Leads
 *
 * @since    0.1.0
 */
#[AsEvent]
final readonly class LeadContacted implements ShouldDispatchAfterCommit
{
    /**
     * @param  string  $leadId  ULID
     * @param  string  $tenantId  ULID
     * @param  string  $fromStage  'NEW'
     * @param  string  $toStage  'CONTACTED'
     * @param  string  $ownerId  ULID (usr_*) | null
     * @param  string  $at  ISO 8601
     */
    public function __construct(
        public readonly string $leadId,
        public readonly string $tenantId,
        public readonly string $fromStage,
        public readonly string $toStage,
        public readonly string $ownerId,
        public readonly string $at,
    ) {
    }
}
