<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py notifications notifications-mail --force`.

declare(strict_types=1);

namespace Academorix\NotificationsMail\Console;

use Academorix\Console\Attributes\AsCommand;
use Academorix\Console\Console\Commands\BaseCommand;

/**
 * `php artisan notifications:mail:test-send` — Mail:test send — notifications command.
 *
 * @category NotificationsMail
 *
 * @since    0.1.0
 */
#[AsCommand(
    name: 'notifications:mail:test-send',
    description: 'Mail:test send — notifications command.',
)]
final class MailTestSendCommand extends BaseCommand
{
    /**
     * Execute the command.
     *
     * TODO(gen): wire the required services + implement the handler body.
     */
    public function handle(): int
    {
        $this->omni->titleBar('Mail:test send — notifications command', 'sky');

        // TODO(gen): wire the required services + implement the handler body.

        $this->omni->success('Mail:test send — notifications command completed.');
        $this->showDuration();

        return self::SUCCESS;
    }
}
