<?php

/**
 * @file database/migrations/2026_07_15_120000_create_audit_retention_policies_table.php
 *
 * @description
 * Create the `audit_retention_policies` table for the `AuditRetentionPolicy` entity.
 * Owned by the audit module. Every column + index reference
 * goes through {@see Academorix\Audit\Contracts\Data\AuditRetentionPolicyInterface} per the `models` steering
 * rule §1 — no raw string literals.
 */
// // AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py observability audit --force`.

declare(strict_types=1);

use Academorix\Audit\Contracts\Data\AuditRetentionPolicyInterface;
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

return new class() extends Migration {
    /**
     * Run the migration.
     */
    public function up(): void
    {
        Schema::create(AuditRetentionPolicyInterface::TABLE, function (Blueprint $table): void {
            $table->string(AuditRetentionPolicyInterface::ATTR_ID, 30)->primary();
            $table->string(AuditRetentionPolicyInterface::ATTR_TENANT_ID, 30);
            $table->foreign(AuditRetentionPolicyInterface::ATTR_TENANT_ID)->references('id')->on('tenants')->onDelete('cascade');
            $table->integer(AuditRetentionPolicyInterface::ATTR_RETENTION_YEARS);
            $table->text(AuditRetentionPolicyInterface::ATTR_OVERRIDE_REASON);
            $table->timestampTz(AuditRetentionPolicyInterface::ATTR_OVERRIDE_STARTS_AT);
            $table->timestampTz(AuditRetentionPolicyInterface::ATTR_OVERRIDE_ENDS_AT)->nullable();
            $table->timestampTz(AuditRetentionPolicyInterface::ATTR_EXPIRING_SOON_NOTIFIED_AT)->nullable();
            $table->text(AuditRetentionPolicyInterface::ATTR_NOTES)->nullable();
            $table->jsonb(AuditRetentionPolicyInterface::ATTR_METADATA)->nullable();
            $table->string(AuditRetentionPolicyInterface::ATTR_CREATED_BY, 30)->nullable();
            $table->string(AuditRetentionPolicyInterface::ATTR_UPDATED_BY, 30)->nullable();
            $table->string(AuditRetentionPolicyInterface::ATTR_DELETED_BY, 30)->nullable();
            $table->timestampTz(AuditRetentionPolicyInterface::ATTR_CREATED_AT);
            $table->timestampTz(AuditRetentionPolicyInterface::ATTR_UPDATED_AT);
            $table->timestampTz(AuditRetentionPolicyInterface::ATTR_DELETED_AT)->nullable();

        });

        DB::statement('CREATE UNIQUE INDEX audit_retention_policies_tenant_active_uniq ON ' . AuditRetentionPolicyInterface::TABLE . ' (' . AuditRetentionPolicyInterface::ATTR_TENANT_ID . ', ' . AuditRetentionPolicyInterface::ATTR_DELETED_AT . ') WHERE deleted_at IS NULL');
        DB::statement('CREATE INDEX audit_retention_policies_expiry_idx ON ' . AuditRetentionPolicyInterface::TABLE . ' (' . AuditRetentionPolicyInterface::ATTR_OVERRIDE_ENDS_AT . ') WHERE deleted_at IS NULL AND override_ends_at IS NOT NULL');
    }

    /**
     * Reverse the migration.
     */
    public function down(): void
    {
        Schema::dropIfExists(AuditRetentionPolicyInterface::TABLE);
    }
};
