<?php

/**
 * @file modules/finance/dunning/src/Providers/DunningServiceProvider.php
 *
 * @description
 * Root service provider for the Dunning domain module —
 * attribute-first end-to-end. Every contribution is attribute-
 * discovered by the shared framework loaders. The provider itself
 * declares just the module identity and which conventional resources
 * auto-load.
 *
 * ## Discoverables (zero code)
 *
 *   - Repositories: `#[AsRepository]` + `#[UseModel]` on the concretes; `#[Bind]` on the interfaces (Laravel-canonical placement per ADR 0006).
 *   - Models: attribute-first — `#[Table]`, `#[Fillable]`, `#[UseFactory]`, `#[UsePolicy]`, `#[ObservedBy]`.
 *   - Actions: `#[AsAction]` + verb attribute (ADR 0016 actions-only).
 *   - Console commands: `#[AsCommand]` — auto-discovered by the base provider's `LoadsResources(commands: true)`.
 *   - Seeder: `#[AsSeeder]` on `DunningPermissionSeeder` — projects `DunningPermission` cases into spatie/laravel-permission.
 *   - Events: `#[AsEvent]` (discovered by `stackra/events`).
 *   - Policies: `#[UsePolicy]` on the models.
 *   - Observers: `#[ObservedBy]` on the models.
 *
 */

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py finance dunning --force`.
declare(strict_types=1);

namespace Academorix\Dunning\Providers;

use Stackra\ServiceProvider\Attributes\AsModule;
use Stackra\ServiceProvider\Attributes\LoadsResources;
use Stackra\ServiceProvider\Providers\ServiceProvider;

/**
 * Dunning module service provider.
 *
 * Priority `30` places dunning in the `finance` tier
 * boot order. Downstream modules load at a higher priority so
 * their attribute-driven wiring resolves after this module's
 * contributions land.
 *
 * @category Dunning
 *
 * @since    0.1.0
 */
#[AsModule(name: 'Dunning', priority: 30)]
#[LoadsResources(
    config: true,
    migrations: true,
    commands: true,
    seeders: true,
    publishables: true,
    translations: true,
)]
final class DunningServiceProvider extends ServiceProvider
{
}
