<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py platform teams --force`.

declare(strict_types=1);

namespace Academorix\Teams\Actions\Tenant;

use Academorix\Teams\Contracts\Repositories\TeamRepositoryInterface;
use Academorix\Teams\Data\TeamData;
use Academorix\Teams\Data\Requests\UpdateTeamRequestData;
use Academorix\Routing\Attributes\AsAction;
use Academorix\Routing\Attributes\Middleware;
use Academorix\Routing\Concerns\AsController;
use Academorix\Routing\Attributes\Patch;

/**
 * `PATCH /api/v1/teams/{team}` — update action (tenant audience).
 *
 * Single-invoke controller wired via `#[AsAction]` + `#[Patch(...)]`
 * + `#[Middleware(...)]` from `Academorix\Routing`. Discovered by the routing
 * package's boot-time `RouteRegistrar` — no route file needed.
 *
 * @category Teams
 *
 * @since    0.1.0
 */
#[AsAction(name: 'teams.update')]
#[Patch('/api/v1/teams/{team}')]
#[Middleware(['api', 'auth:sanctum', 'tenant.resolve'])]
final class UpdateTeamAction
{
    use AsController;

    public function __construct(
        private readonly TeamRepositoryInterface $repository,
    ) {
    }

    /**
     * Update one `team` and return the wire DTO.
     *
     * @param  string  $id  Primary key.
     * @param  UpdateTeamRequestData  $data  Validated payload.
     *
     * @throws \Illuminate\Database\Eloquent\ModelNotFoundException  When the row is absent or hidden by scoping.
     */
    public function __invoke(string $id, UpdateTeamRequestData $data): TeamData
    {
        $model = $this->repository->update($id, $data->toArray());

        return TeamData::from($model);
    }
}
