<?php

/**
 * @file database/migrations/2026_07_15_120001_create_form_versions_table.php
 *
 * @description
 * Create the `form_versions` table for the `FormVersion` entity.
 * Owned by the forms module. Emitted from the module blueprint —
 * regenerate via `generate-module.py platform forms --force`.
 */
// // AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py platform forms --force`.

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class() extends Migration {
    /**
     * Run the migration.
     */
    public function up(): void
    {
        Schema::create('form_versions', function (Blueprint $table): void {
            $table->string('id', 30)->primary();
            $table->string('tenant_id', 30);
            $table->foreign('tenant_id')->references('id')->on('tenants')->onDelete('cascade');
            $table->string('form_id', 30);
            $table->foreign('form_id')->references('id')->on('forms')->onDelete('cascade');
            $table->integer('version_number');
            $table->string('status', 16)->default('draft');
            $table->jsonb('schema');
            $table->jsonb('labels');
            $table->jsonb('validation_rules')->nullable();
            $table->integer('field_count')->default('0');
            $table->integer('submission_count')->default('0');
            $table->timestampTz('published_at')->nullable();
            $table->string('published_by_user_id', 30)->nullable();
            $table->foreign('published_by_user_id')->references('id')->on('users')->onDelete('set null');
            $table->timestampTz('superseded_at')->nullable();
            $table->string('superseded_by_version_id', 30)->nullable();
            $table->foreign('superseded_by_version_id')->references('id')->on('form_versions')->onDelete('set null');
            $table->jsonb('metadata')->nullable();
            $table->string('created_by', 30)->nullable();
            $table->string('updated_by', 30)->nullable();
            $table->timestampTz('created_at');
            $table->timestampTz('updated_at');
            $table->unique(['tenant_id', 'form_id', 'version_number'], 'form_versions_form_number_unique');
            $table->index(['tenant_id', 'form_id', 'status'], 'form_versions_form_status_idx');
        });
    }

    /**
     * Reverse the migration.
     */
    public function down(): void
    {
        Schema::dropIfExists('form_versions');
    }
};
