<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py workflow tasks --force`.

declare(strict_types=1);

namespace Academorix\Tasks\Contracts\Repositories;

use Academorix\Crud\Contracts\RepositoryInterface;

/**
 * Repository contract for {@see Academorix\Tasks\Models\TaskAssignment}.
 *
 * Consumers type-hint the interface; the container binds the concrete
 * via `#[AsRepository]` on `TaskAssignmentRepository`.
 *
 * @extends RepositoryInterface<\Academorix\Tasks\Models\TaskAssignment>
 *
 * @category Tasks
 *
 * @since    0.1.0
 */
interface TaskAssignmentRepositoryInterface extends RepositoryInterface
{
    // Domain-specific query methods live here. CRUD comes from the base.
}
