<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py access rbac --force`.

declare(strict_types=1);

namespace Stackra\Rbac\Actions\Tenant;

use Stackra\Rbac\Contracts\Repositories\RoleRepositoryInterface;
use Stackra\Rbac\Data\RoleData;
use Stackra\Routing\Attributes\AsAction;
use Stackra\Routing\Attributes\Middleware;
use Stackra\Routing\Concerns\AsController;
use Stackra\Routing\Attributes\Get;
use Illuminate\Http\Request;
use Illuminate\Pagination\LengthAwarePaginator;
use Spatie\LaravelData\PaginatedDataCollection;

/**
 * `GET /api/v1/rbac/roles` — list action (tenant audience).
 *
 * Single-invoke controller wired via `#[AsAction]` + `#[Get(...)]`
 * + `#[Middleware(...)]` from `Stackra\Routing`. Discovered by the routing
 * package's boot-time `RouteRegistrar` — no route file needed.
 *
 * @category Rbac
 *
 * @since    0.1.0
 */
#[AsAction(name: 'rbac.roles.list')]
#[Get('/api/v1/rbac/roles')]
#[Middleware(['api', 'auth:sanctum', 'tenant.resolve'])]
final class ListRoleAction
{
    use AsController;

    public function __construct(
        private readonly RoleRepositoryInterface $repository,
    ) {
    }

    /**
     * List `roles` for the current caller.
     *
     * The `Repository` base picks up `filter[...]` / `sort=...` /
     * `include=...` query parameters via the `#[Filterable]` attribute
     * on the concrete repository — no per-Action wiring needed.
     *
     * @return PaginatedDataCollection<int, RoleData>  Paginated wire-visible DTOs.
     */
    public function __invoke(Request $request): PaginatedDataCollection
    {
        /** @var LengthAwarePaginator<int, \Stackra\Rbac\Models\Role> $page */
        $page = $this->repository->paginate(
            perPage: (int) $request->integer('per_page', 15),
        );

        return RoleData::collect($page, PaginatedDataCollection::class);
    }
}
