<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py finance dunning --force`.

declare(strict_types=1);

namespace Stackra\Dunning\Database\Factories;

use Illuminate\Database\Eloquent\Factories\Factory;
use Stackra\Dunning\Contracts\Data\DunningEventInterface;
use Stackra\Dunning\Models\DunningEvent;

/**
 * Factory for {@see \Stackra\Dunning\Models\DunningEvent}.
 *
 * Auto-generated skeleton — extend with named states as domain
 * cases emerge (e.g. `->published()`, `->overdue()`, `->archived()`).
 *
 * @extends Factory<\Stackra\Dunning\Models\DunningEvent>
 *
 * @category Dunning
 *
 * @since    0.1.0
 */
final class DunningEventFactory extends Factory
{
    /**
     * The model this factory builds.
     *
     * @var class-string<DunningEvent>
     */
    protected $model = DunningEvent::class;

    /**
     * Return the default model attribute values.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        return [
            DunningEventInterface::ATTR_DUNNING_RUN_ID => fake()->sentence(3),
            DunningEventInterface::ATTR_KIND => fake()->randomElement(['run_started', 'step_reached', 'retry_attempted', 'retry_succeeded', 'retry_failed', 'notification_sent', 'escalated_step', 'run_paused', 'run_resumed', 'run_cancelled', 'run_exhausted', 'run_resolved']),
            DunningEventInterface::ATTR_STEP_INDEX => null,
            DunningEventInterface::ATTR_MESSAGE => fake()->sentence(3),
            DunningEventInterface::ATTR_PAYLOAD_JSON => null,
            DunningEventInterface::ATTR_METADATA => null,
        ];
    }
}
