<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py finance expenses --force`.

declare(strict_types=1);

namespace Academorix\Expenses\Events;

use Academorix\Events\Attributes\AsEvent;
use Illuminate\Contracts\Events\ShouldDispatchAfterCommit;

/**
 * Payroll batch aggregated N staff payments.
 *
 * ## Consumers
 *
 * - audit::WriteToAuditLog
 * - activity::WriteToActivityLog
 * - notifications::NotifyPayrollBatchReady
 *
 * @category Expenses
 *
 * @since    0.1.0
 */
#[AsEvent]
final readonly class PayrollBatchCreated implements ShouldDispatchAfterCommit
{
    /**
     * @param  string  $batchId  ULID (pyr_*)
     * @param  string  $tenantId  ULID
     * @param  string  $periodStart  date
     * @param  string  $periodEnd  date
     * @param  int  $staffCount  int
     * @param  int  $totalAmountMinor  bigint
     */
    public function __construct(
        public readonly string $batchId,
        public readonly string $tenantId,
        public readonly string $periodStart,
        public readonly string $periodEnd,
        public readonly int $staffCount,
        public readonly int $totalAmountMinor,
    ) {
    }
}
