<?php

// // AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py billing subscription --force`.

declare(strict_types=1);

namespace Academorix\Billing\Subscription\Events;

use Illuminate\Contracts\Events\ShouldDispatchAfterCommit;

/**
 * Grace expired. State → suspended. Tenant loses non-critical features.
 *
 * ## Consumers
 *
 * - notifications::DispatchSubscriptionSuspendedNotification
 * - tenancy::HandleTenantSuspension
 *
 * @category Subscription
 *
 * @since    0.1.0
 */
final readonly class SubscriptionSuspended implements ShouldDispatchAfterCommit
{
    /**
     * @param  string  $subscriptionId  ULID
     * @param  string  $tenantId  ULID
     */
    public function __construct(
        public readonly string $subscriptionId,
        public readonly string $tenantId,
    ) {
    }
}
