<?php

// // AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py platform reporting --force`.

declare(strict_types=1);

namespace Academorix\Reporting\Models;

use Illuminate\Database\Eloquent\Attributes\Fillable;
use Illuminate\Database\Eloquent\Attributes\Table;
use Illuminate\Database\Eloquent\Attributes\UseFactory;
use Illuminate\Database\Eloquent\Attributes\WithoutIncrementing;
use Illuminate\Database\Eloquent\Model;
use Academorix\Reporting\Contracts\Data\ReportRunInterface;
use Academorix\Reporting\Database\Factories\ReportRunFactory;
use Academorix\Foundation\Concerns\Filterable;
use Academorix\Foundation\Concerns\HasMetadata;
use Academorix\Foundation\Concerns\HasPrefixedUlid;
use Academorix\Tenancy\Concerns\BelongsToTenant;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use OwenIt\Auditing\Auditable;
use OwenIt\Auditing\Contracts\Auditable as AuditableContract;

/**
 * Eloquent model for a ReportRun.
 *
 *
 *
 * @category Reporting
 *
 * @since    0.1.0
 */
#[Table(name: ReportRunInterface::TABLE, key: ReportRunInterface::PRIMARY_KEY, keyType: ReportRunInterface::KEY_TYPE)]
#[Fillable([
    ReportRunInterface::ATTR_TENANT_ID,
        ReportRunInterface::ATTR_REPORT_DEFINITION_ID,
        ReportRunInterface::ATTR_SAVED_REPORT_ID,
        ReportRunInterface::ATTR_REQUESTED_BY_USER_ID,
        ReportRunInterface::ATTR_PARAMETERS,
        ReportRunInterface::ATTR_STATUS,
        ReportRunInterface::ATTR_STARTED_AT,
        ReportRunInterface::ATTR_COMPLETED_AT,
        ReportRunInterface::ATTR_ROWS_COUNT,
        ReportRunInterface::ATTR_OUTPUT_DOCUMENT_ID,
        ReportRunInterface::ATTR_ERROR_MESSAGE,
        ReportRunInterface::ATTR_METADATA,
])]
#[UseFactory(ReportRunFactory::class)]
#[WithoutIncrementing]
final class ReportRun extends Model implements ReportRunInterface, AuditableContract
{
    use HasFactory;
    use HasPrefixedUlid;
    use BelongsToTenant;
    use HasMetadata;
    use Auditable;
    use Filterable;
}
