<?php

/**
 * @file database/migrations/2026_07_15_120005_create_payroll_runs_table.php
 *
 * @description
 * Create the `payroll_runs` table for the `PayrollRun` entity.
 * Owned by the expenses module. Emitted from the module blueprint —
 * regenerate via `generate-module.py finance expenses --force`.
 */
// // AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py finance expenses --force`.

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class() extends Migration {
    /**
     * Run the migration.
     */
    public function up(): void
    {
        Schema::create('payroll_runs', function (Blueprint $table): void {
            $table->string('id', 30)->primary();
            $table->string('tenant_id', 30);
            $table->foreign('tenant_id')->references('id')->on('tenants')->onDelete('cascade');
            $table->date('period_start');
            $table->date('period_end');
            $table->string('status', 16)->default('draft');
            $table->unsignedBigInteger('total_amount_minor')->default('0');
            $table->string('currency', 3);
            $table->integer('line_count')->default('0');
            $table->timestampTz('computed_at')->nullable();
            $table->timestampTz('approved_at')->nullable();
            $table->string('approved_by_user_id', 30)->nullable();
            $table->foreign('approved_by_user_id')->references('id')->on('users')->onDelete('set null');
            $table->timestampTz('paid_at')->nullable();
            $table->text('notes')->nullable();
            $table->jsonb('metadata')->nullable();
            $table->timestampTz('created_at');
            $table->timestampTz('updated_at');
            $table->timestampTz('deleted_at')->nullable();
            $table->index(['tenant_id', 'period_start', 'period_end'], 'payroll_runs_period_idx');
        });
    }

    /**
     * Reverse the migration.
     */
    public function down(): void
    {
        Schema::dropIfExists('payroll_runs');
    }
};
