<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py sports registry --force`.

declare(strict_types=1);

namespace Stackra\Registry\Repositories;

use Stackra\Crud\Attributes\AsRepository;
use Stackra\Crud\Attributes\Cacheable;
use Stackra\Crud\Attributes\Filterable;
use Stackra\Crud\Attributes\UseModel;
use Stackra\Crud\Repositories\Repository;
use Stackra\Registry\Contracts\Data\PositionInterface;
use Stackra\Registry\Contracts\Repositories\PositionRepositoryInterface;
use Stackra\Registry\Models\Position;

/**
 * Attribute-first Eloquent repository for {@see Stackra\Registry\Models\Position}.
 *
 * Bound to the interface via `#[AsRepository]`; the model comes from
 * `#[UseModel(PositionInterface::class)]` which resolves to
 * `Position` through the interface's `#[Bind]`.
 *
 * @extends Repository<\Stackra\Registry\Models\Position>
 *
 * @category Registry
 *
 * @since    0.1.0
 */
#[AsRepository]
#[UseModel(PositionInterface::class)]
#[Cacheable(ttl: 3600, tags: true)]
#[Filterable('*')]
final class PositionRepository extends Repository implements PositionRepositoryInterface
{
    // Domain methods added here. CRUD comes from Repository.
}
