<?php

// // AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py growth referrals --force`.

declare(strict_types=1);

namespace Academorix\Referrals\Actions\Platform;

use Academorix\Routing\Attributes\AsController;
use Academorix\Routing\Attributes\Post;

/**
 * `POST /api/v1/platform/referrals/{referral}/force-vest` — custom action (platform-admin audience).
 *
 * Single-invoke controller wired via `#[AsController]` + `#[Post(...)]`
 * attributes from `Academorix\Routing`. Discovered by the routing package's
 * boot-time `RouteRegistrar` — no route file needed.
 *
 * @category Referrals
 *
 * @since    0.1.0
 */
#[AsController]
#[Post('/api/v1/platform/referrals/{referral}/force-vest')]
final class ForceVestForceVestAction
{
    /**
     * Execute the action.
     *
     * TODO(gen): wire the required services + implement the handler body.
     */
    public function __invoke(): mixed
    {
        // Hand-implement the domain logic here.
        return null;
    }
}
