<?php

// // AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py identity platform-user --force`.

declare(strict_types=1);

namespace Academorix\Identity\PlatformUser\Data;

use Spatie\LaravelData\Attributes\MapInputName;
use Spatie\LaravelData\Data;
use Spatie\LaravelData\Mappers\SnakeCaseMapper;

/**
 * Server-side output DTO for {@see \Academorix\Identity\PlatformUser\Models\PlatformProfile}.
 *
 * Consumed by controllers + services on the SERVER side. This is
 * distinct from the wire SDK's DTO (which sits under
 * `Academorix\IdentityPlatformUserSdk\Data`) — the wire DTO travels across the HTTP
 * boundary; this one stays in-process.
 *
 * @category PlatformUser
 *
 * @since    0.1.0
 */
#[MapInputName(SnakeCaseMapper::class)]
final class PlatformProfileData extends Data
{
    public function __construct(
        public string $id,
        public string $firstName,
        public string $lastName,
        public string $phoneE164,
        public string $timezone,
        public string $createdAt,
        public string $updatedAt,
        public ?string $displayName = null,
        public ?string $avatarUrl = null,
        public ?string $slackHandle = null,
        public ?string $githubHandle = null,
        public ?array $metadata = null,
        public ?string $createdBy = null,
        public ?string $updatedBy = null,
        public ?string $deletedBy = null,
        public ?string $deletedAt = null,
    ) {
    }
}
