<?php

// // AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py identity user --force`.

declare(strict_types=1);

namespace Academorix\User\Models;

use Illuminate\Database\Eloquent\Attributes\Fillable;
use Illuminate\Database\Eloquent\Attributes\Table;
use Illuminate\Database\Eloquent\Attributes\UseFactory;
use Illuminate\Database\Eloquent\Model;
use Academorix\User\Contracts\Data\ProfileInterface;
use Academorix\User\Database\Factories\ProfileFactory;
use Academorix\Foundation\Concerns\Filterable;
use Academorix\Foundation\Concerns\HasMetadata;
use Academorix\Tenancy\Concerns\BelongsToTenant;
use Illuminate\Database\Eloquent\Concerns\HasUlids;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\SoftDeletes;
use Mattiverse\Userstamps\Traits\Userstamps;
use OwenIt\Auditing\Auditable;

/**
 * Eloquent model for a Profile.
 *
 * 1:1 PII satellite for User.
 *
 * @category User
 *
 * @since    0.1.0
 */
#[Table(name: ProfileInterface::TABLE, keyType: ProfileInterface::KEY_TYPE)]
#[Fillable([
    ProfileInterface::ATTR_TENANT_ID,
        ProfileInterface::ATTR_FIRST_NAME,
        ProfileInterface::ATTR_LAST_NAME,
        ProfileInterface::ATTR_DISPLAY_NAME,
        ProfileInterface::ATTR_AVATAR_URL,
        ProfileInterface::ATTR_PHONE_E164,
        ProfileInterface::ATTR_LOCALE,
        ProfileInterface::ATTR_TIMEZONE,
        ProfileInterface::ATTR_DOB,
        ProfileInterface::ATTR_METADATA,
])]
#[UseFactory(ProfileFactory::class)]
final class Profile extends Model implements ProfileInterface
{
    use HasFactory;
    use HasUlids;
    use BelongsToTenant;
    use HasMetadata;
    use HasUserstamps;
    use Auditable;
    use Filterable;
    use SoftDeletes;

    /**
     * The primary key IS a string (prefixed ULID); disable auto-increment.
     *
     * @var bool
     */
    public $incrementing = false;

    /**
     * Cast map — from the blueprint's x-eloquent.casts.
     *
     * @var array<string, string>
     */
    protected $casts = [
        ProfileInterface::ATTR_PHONE_E164 => 'E164Phone',
        ProfileInterface::ATTR_LOCALE => 'Bcp47Locale',
        ProfileInterface::ATTR_TIMEZONE => 'IanaTimezone',
        ProfileInterface::ATTR_DOB => 'date',
        ProfileInterface::ATTR_METADATA => 'array',
    ];
}
