<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py compliance compliance --force`.

declare(strict_types=1);

namespace Stackra\Compliance\Data\Requests;

use Spatie\LaravelData\Attributes\MapInputName;
use Spatie\LaravelData\Data;
use Spatie\LaravelData\Mappers\SnakeCaseMapper;
use Spatie\LaravelData\Attributes\Validation\Max;
use Spatie\LaravelData\Attributes\Validation\Min;
use Spatie\LaravelData\Attributes\Validation\Regex;
use Spatie\LaravelData\Attributes\Validation\StringType;

/**
 * Server-side create request DTO for `Subprocessor`.
 *
 * Consumed by the corresponding Action; validated on construction
 * through Spatie Data's property-attribute pipeline (no `rules()`
 * method). See `.kiro/steering/data-first.md`.
 *
 * @category Compliance
 *
 * @since    0.1.0
 */
#[MapInputName(SnakeCaseMapper::class)]
final class CreateSubprocessorRequestData extends Data
{
    public function __construct(
        #[StringType, Regex('/^[a-z][a-z0-9_]{0,62}$/')]
        public string $key,

        #[StringType, Min(1), Max(128)]
        public string $name,

        #[StringType]
        public string $role,

        #[StringType]
        public string $purpose,

        #[StringType]
        public ?string $description = null,

        public array $dataProcessed,

        public array $location,

        #[StringType]
        public string $legalBasis,

        #[StringType]
        public ?string $dpaUrl = null,

        #[StringType]
        public ?string $dpaVersion = null,

        #[StringType]
        public ?string $contactEmail = null,

        public bool $isActive,

        public bool $isSystem,

        public int $version,

        #[StringType, Regex('/^spr_[0-9A-HJKMNP-TV-Z]{26}$/')]
        public ?string $previousVersionId = null,

        #[StringType]
        public string $firstEngagedAt,

        #[StringType]
        public ?string $lastUpdatedBy = null,

        public ?array $metadata = null,
    ) {
    }
}
