<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py access rbac --force`.

declare(strict_types=1);

namespace Stackra\Rbac\Services;

use Stackra\Rbac\Contracts\Services\PermissionResolverInterface;
use Illuminate\Container\Attributes\Scoped;
use Stackra\Rbac\Contracts\Repositories\ModelHasPermissionsRepositoryInterface;

/**
 * Concrete service — PermissionResolver.
 *
 * Implements {@see PermissionResolverInterface}. `#[Scoped]` because most
 * services touch request state (current tenant, current user,
 * correlation id) — see `.kiro/steering/octane-first-di.md`. If
 * the service is provably stateless, promote to `#[Singleton]`.
 *
 * @category Rbac
 *
 * @since    0.1.0
 */
#[Scoped]
final class PermissionResolver implements PermissionResolverInterface
{
    /**
     * @param  ModelHasPermissionsRepositoryInterface  $modelHasPermissionsRepository  Primary persistence boundary.
     */
    public function __construct(
        private readonly ModelHasPermissionsRepositoryInterface $modelHasPermissionsRepository,
    ) {
    }
}
