<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py platform public-site --force`.

declare(strict_types=1);

namespace Academorix\PublicSite\Enums;

use Academorix\Enum\Enum;

/**
 * Closed-set enum for `status` on `public-page`.
 *
 * Backed enum — one case per allowed value.
 *
 * @category PublicSite
 *
 * @since    0.1.0
 */
enum PublicPageStatus: string
{
    use Enum;

    case Draft = 'draft';
    case Published = 'published';
    case Archived = 'archived';
}
