<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py finance coupon --force`.

declare(strict_types=1);

namespace Academorix\Coupon\Repositories;

use Academorix\Crud\Attributes\AsRepository;
use Academorix\Crud\Attributes\Cacheable;
use Academorix\Crud\Attributes\Filterable;
use Academorix\Crud\Attributes\UseModel;
use Academorix\Crud\Repositories\Repository;
use Academorix\Coupon\Contracts\Data\CouponRedemptionInterface;
use Academorix\Coupon\Contracts\Repositories\CouponRedemptionRepositoryInterface;
use Academorix\Coupon\Models\CouponRedemption;

/**
 * Attribute-first Eloquent repository for {@see Academorix\Coupon\Models\CouponRedemption}.
 *
 * Bound to the interface via `#[AsRepository]`; the model comes from
 * `#[UseModel(CouponRedemptionInterface::class)]` which resolves to
 * `CouponRedemption` through the interface's `#[Bind]`.
 *
 * @extends Repository<\Academorix\Coupon\Models\CouponRedemption>
 *
 * @category Coupon
 *
 * @since    0.1.0
 */
#[AsRepository]
#[UseModel(CouponRedemptionInterface::class)]
#[Cacheable(ttl: 3600, tags: true)]
#[Filterable('*')]
final class CouponRedemptionRepository extends Repository implements CouponRedemptionRepositoryInterface
{
    // Domain methods added here. CRUD comes from Repository.
}
