<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py platform teams --force`.

declare(strict_types=1);

namespace Stackra\Teams\Contracts\Repositories;

use Stackra\Crud\Contracts\RepositoryInterface;

/**
 * Repository contract for {@see Stackra\Teams\Models\Team}.
 *
 * Consumers type-hint the interface; the container binds the concrete
 * via `#[AsRepository]` on `TeamRepository`.
 *
 * @extends RepositoryInterface<\Stackra\Teams\Models\Team>
 *
 * @category Teams
 *
 * @since    0.1.0
 */
interface TeamRepositoryInterface extends RepositoryInterface
{
    // Domain-specific query methods live here. CRUD comes from the base.
}
