<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py finance transaction --force`.

declare(strict_types=1);

namespace Academorix\Transaction\Attributes;

use Attribute;

/**
 * PHP attribute — AsTransactionKind.
 *
 * TODO(gen): document the attribute's target + discovery pipeline.
 * Follow the pattern of `#[AsAiTool]` / `#[LoggableActivity]` /
 * `#[AsRepository]` — one attribute per compile-time-declarative
 * concern, scanned at boot via Foundation's `DiscoversAttributes`
 * seam, hydrated into a registry, consumed by a runner.
 *
 * @category Transaction
 *
 * @since    0.1.0
 */
#[Attribute(Attribute::TARGET_CLASS)]
final readonly class AsTransactionKind
{
    // TODO(gen): declare the attribute's constructor parameters, if any.
}
