<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py platform staff --force`.

declare(strict_types=1);

namespace Stackra\Staff\Exceptions;

use Stackra\Exceptions\Exception;

/**
 * The staff still has active team memberships.
 *
 * @category Staff
 *
 * @since    0.1.0
 */
final class StaffHasTeamMembershipsException extends Exception
{
    /**
     * Stable machine-readable error code emitted on the JSON envelope.
     */
    public const CODE = 'STAFF_HAS_TEAM_MEMBERSHIPS';

    /**
     * Translation key for the humanised message.
     */
    public const TRANSLATION_KEY = 'staff::errors.STAFF_HAS_TEAM_MEMBERSHIPS';
}
