<?php

/**
 * @file database/migrations/2026_07_15_120002_create_team_trials_table.php
 *
 * @description
 * Create the `team_trials` table for the `TeamTrial` entity.
 * Owned by the teams module. Emitted from the module blueprint —
 * regenerate via `generate-module.py platform teams --force`.
 */
// // AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py platform teams --force`.

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class() extends Migration {
    /**
     * Run the migration.
     */
    public function up(): void
    {
        Schema::create('team_trials', function (Blueprint $table): void {
            $table->string('id', 64)->primary();
            $table->string('tenant_id', 64);
            $table->foreign('tenant_id')->references('id')->on('tenants')->onDelete('cascade');
            $table->string('team_id', 64);
            $table->foreign('team_id')->references('id')->on('teams')->onDelete('restrict');
            $table->string('trialist_type', 16);
            $table->string('trialist_id', 64)->nullable();
            $table->string('trialist_first_name', 128)->nullable();
            $table->string('trialist_last_name', 128)->nullable();
            $table->string('trialist_phone', 20)->nullable();
            $table->string('trialist_email', 254)->nullable();
            $table->date('trialist_dob')->nullable();
            $table->string('trial_type', 16)->default('individual');
            $table->integer('session_count')->default(1);
            $table->timestampTz('starts_at');
            $table->timestampTz('ends_at');
            $table->string('status', 16)->default('scheduled');
            $table->timestampTz('started_at')->nullable();
            $table->timestampTz('completed_at')->nullable();
            $table->timestampTz('decided_at')->nullable();
            $table->string('evaluated_by_user_id', 64)->nullable();
            $table->foreign('evaluated_by_user_id')->references('id')->on('users')->onDelete('restrict');
            $table->text('evaluation_notes')->nullable();
            $table->text('decision_notes')->nullable();
            $table->integer('price_amount_cents')->default(0);
            $table->string('price_currency', 3)->nullable();
            $table->string('payment_status', 16)->default('none');
            $table->jsonb('metadata')->nullable();
            $table->string('created_by', 64)->nullable();
            $table->string('updated_by', 64)->nullable();
            $table->string('deleted_by', 64)->nullable();
            $table->timestampTz('deleted_at')->nullable();
            $table->timestampTz('created_at');
            $table->timestampTz('updated_at');
            $table->index(['tenant_id', 'team_id', 'starts_at'], 'team_trials_team_starts_idx');
            $table->index(['tenant_id', 'status'], 'team_trials_status_idx');
            $table->index(['tenant_id', 'trialist_type', 'trialist_id'], 'team_trials_trialist_idx');
            // Partial-index predicate — hand-add via DB::statement: WHERE trialist_id IS NOT NULL
            $table->index(['tenant_id', 'team_id', 'status'], 'team_trials_pipeline_idx');
        });
    }

    /**
     * Reverse the migration.
     */
    public function down(): void
    {
        Schema::dropIfExists('team_trials');
    }
};
