<?php

// // AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py sports match --force`.

declare(strict_types=1);

namespace Academorix\Match\Console;

use Academorix\Console\Attributes\AsCommand;
use Academorix\Console\Console\Commands\BaseCommand;

/**
 * `php artisan matches:publish-lineup` — Publish lineup — matches command.
 *
 * @category Match
 *
 * @since    0.1.0
 */
#[AsCommand(
    name: 'matches:publish-lineup',
    description: 'Publish lineup — matches command.',
)]
final class PublishLineupCommand extends BaseCommand
{
    /**
     * Execute the command.
     *
     * TODO(gen): wire the required services + implement the handler body.
     */
    public function handle(): int
    {
        return self::SUCCESS;
    }
}
