<?php

/**
 * @file database/migrations/2026_07_15_120001_create_payment_intents_table.php
 *
 * @description
 * Create the `payment_intents` table for the `PaymentIntent` entity.
 * Owned by the payment module. Every column + index reference
 * goes through {@see Academorix\Payment\Contracts\Data\PaymentIntentInterface} per the `models` steering
 * rule §1 — no raw string literals.
 */
// // AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py finance payment --force`.

declare(strict_types=1);

use Academorix\Payment\Contracts\Data\PaymentIntentInterface;
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

return new class() extends Migration {
    /**
     * Run the migration.
     */
    public function up(): void
    {
        Schema::create(PaymentIntentInterface::TABLE, function (Blueprint $table): void {
            $table->string(PaymentIntentInterface::ATTR_ID, 64)->primary();
            $table->string(PaymentIntentInterface::ATTR_TENANT_ID, 64);
            $table->foreign(PaymentIntentInterface::ATTR_TENANT_ID)->references('id')->on('tenants')->onDelete('cascade');
            $table->string(PaymentIntentInterface::ATTR_INVOICE_ID, 64);
            $table->foreign(PaymentIntentInterface::ATTR_INVOICE_ID)->references('id')->on('invoices')->onDelete('restrict');
            $table->string(PaymentIntentInterface::ATTR_PROVIDER, 32);
            $table->string(PaymentIntentInterface::ATTR_PROVIDER_REFERENCE_ID, 256);
            $table->unsignedBigInteger(PaymentIntentInterface::ATTR_AMOUNT_CENTS);
            $table->string(PaymentIntentInterface::ATTR_CURRENCY, 3);
            $table->string(PaymentIntentInterface::ATTR_STATUS, 32)->default('initialized');
            $table->string(PaymentIntentInterface::ATTR_CAPTURE_METHOD, 16)->default('automatic');
            $table->string(PaymentIntentInterface::ATTR_CONFIRMATION_METHOD, 16)->default('automatic');
            $table->string(PaymentIntentInterface::ATTR_NEXT_ACTION_TYPE, 48)->nullable();
            $table->string(PaymentIntentInterface::ATTR_NEXT_ACTION_URL, 512)->nullable();
            $table->jsonb(PaymentIntentInterface::ATTR_NEXT_ACTION_DATA)->nullable();
            $table->string(PaymentIntentInterface::ATTR_PAYMENT_METHOD_ID, 64)->nullable();
            $table->foreign(PaymentIntentInterface::ATTR_PAYMENT_METHOD_ID)->references('id')->on('payment_methods')->onDelete('restrict');
            $table->string(PaymentIntentInterface::ATTR_CLIENT_SECRET, 512);
            $table->string(PaymentIntentInterface::ATTR_LAST_ERROR_CODE, 128)->nullable();
            $table->string(PaymentIntentInterface::ATTR_LAST_ERROR_MESSAGE, 512)->nullable();
            $table->string(PaymentIntentInterface::ATTR_LAST_ERROR_TYPE, 48)->nullable();
            $table->timestampTz(PaymentIntentInterface::ATTR_SUCCEEDED_AT)->nullable();
            $table->timestampTz(PaymentIntentInterface::ATTR_CANCELLED_AT)->nullable();
            $table->string(PaymentIntentInterface::ATTR_CANCELLATION_REASON, 128)->nullable();
            $table->jsonb(PaymentIntentInterface::ATTR_PROVIDER_METADATA)->nullable();
            $table->string(PaymentIntentInterface::ATTR_CREATED_BY, 64)->nullable();
            $table->string(PaymentIntentInterface::ATTR_UPDATED_BY, 64)->nullable();
            $table->string(PaymentIntentInterface::ATTR_DELETED_BY, 64)->nullable();
            $table->timestampTz(PaymentIntentInterface::ATTR_DELETED_AT)->nullable();
            $table->timestampTz(PaymentIntentInterface::ATTR_CREATED_AT);
            $table->timestampTz(PaymentIntentInterface::ATTR_UPDATED_AT);
            $table->index([PaymentIntentInterface::ATTR_TENANT_ID, PaymentIntentInterface::ATTR_INVOICE_ID], 'payment_intents_tenant_invoice_idx');
            $table->index([PaymentIntentInterface::ATTR_TENANT_ID, PaymentIntentInterface::ATTR_STATUS], 'payment_intents_status_idx');
            $table->index([PaymentIntentInterface::ATTR_PROVIDER_REFERENCE_ID], 'payment_intents_provider_reference_idx');
            $table->index([PaymentIntentInterface::ATTR_TENANT_ID, PaymentIntentInterface::ATTR_CREATED_AT], 'payment_intents_recent_idx');
        });

        DB::statement('CREATE INDEX payment_intents_stale_idx ON ' . PaymentIntentInterface::TABLE . ' (' . PaymentIntentInterface::ATTR_STATUS . ', ' . PaymentIntentInterface::ATTR_CREATED_AT . ') WHERE status IN (\'initialized\', \'requires_action\', \'requires_payment_method\', \'requires_confirmation\', \'processing\')');
    }

    /**
     * Reverse the migration.
     */
    public function down(): void
    {
        Schema::dropIfExists(PaymentIntentInterface::TABLE);
    }
};
