<?php

// // AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py sports competition --force`.

declare(strict_types=1);

namespace Academorix\Competition\Events;

use Illuminate\Contracts\Events\ShouldDispatchAfterCommit;

/**
 * Score entered. status: scheduled → completed. Triggers RecomputeStandingsJob + BracketProgressionJob.
 *
 * ## Consumers
 *
 * - jobs::RecomputeStandingsJob (debounced 5s)
 * - jobs::BracketProgressionJob
 * - audit::WriteToAuditLog
 *
 * @category Competition
 *
 * @since    0.1.0
 */
final readonly class FixtureResultRecorded implements ShouldDispatchAfterCommit
{
    /**
     * @param  string  $fixtureId  ULID
     * @param  int  $homeScore  int
     * @param  int  $awayScore  int
     * @param  string  $recordedByUserId  ULID
     * @param  array  $periodScoresJson  array
     */
    public function __construct(
        public readonly string $fixtureId,
        public readonly int $homeScore,
        public readonly int $awayScore,
        public readonly string $recordedByUserId,
        public readonly array $periodScoresJson,
    ) {
    }
}
