<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py sports registrations --force`.

declare(strict_types=1);

namespace Stackra\Registrations\Repositories;

use Stackra\Crud\Attributes\AsRepository;
use Stackra\Crud\Attributes\Cacheable;
use Stackra\Crud\Attributes\Filterable;
use Stackra\Crud\Attributes\UseModel;
use Stackra\Crud\Repositories\Repository;
use Stackra\Registrations\Contracts\Data\RegistrationActivityInterface;
use Stackra\Registrations\Contracts\Repositories\RegistrationActivityRepositoryInterface;
use Stackra\Registrations\Models\RegistrationActivity;

/**
 * Attribute-first Eloquent repository for {@see Stackra\Registrations\Models\RegistrationActivity}.
 *
 * Bound to the interface via `#[AsRepository]`; the model comes from
 * `#[UseModel(RegistrationActivityInterface::class)]` which resolves to
 * `RegistrationActivity` through the interface's `#[Bind]`.
 *
 * @extends Repository<\Stackra\Registrations\Models\RegistrationActivity>
 *
 * @category Registrations
 *
 * @since    0.1.0
 */
#[AsRepository]
#[UseModel(RegistrationActivityInterface::class)]
#[Cacheable(ttl: 3600, tags: true)]
#[Filterable('*')]
final class RegistrationActivityRepository extends Repository implements RegistrationActivityRepositoryInterface
{
    // Domain methods added here. CRUD comes from Repository.
}
