<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py finance coupon --force`.

declare(strict_types=1);

namespace Stackra\Coupon\Contracts\Repositories;

use Stackra\Crud\Contracts\RepositoryInterface;

/**
 * Repository contract for {@see Stackra\Coupon\Models\Coupon}.
 *
 * Consumers type-hint the interface; the container binds the concrete
 * via `#[AsRepository]` on `CouponRepository`.
 *
 * @extends RepositoryInterface<\Stackra\Coupon\Models\Coupon>
 *
 * @category Coupon
 *
 * @since    0.1.0
 */
interface CouponRepositoryInterface extends RepositoryInterface
{
    // Domain-specific query methods live here. CRUD comes from the base.
}
