<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py finance transaction --force`.

declare(strict_types=1);

namespace Stackra\Transaction\Contracts\Repositories;

use Stackra\Crud\Contracts\RepositoryInterface;

/**
 * Repository contract for {@see Stackra\Transaction\Models\TransactionLedgerEntry}.
 *
 * Consumers type-hint the interface; the container binds the concrete
 * via `#[AsRepository]` on `TransactionLedgerEntryRepository`.
 *
 * @extends RepositoryInterface<\Stackra\Transaction\Models\TransactionLedgerEntry>
 *
 * @category Transaction
 *
 * @since    0.1.0
 */
interface TransactionLedgerEntryRepositoryInterface extends RepositoryInterface
{
    // Domain-specific query methods live here. CRUD comes from the base.
}
