<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py growth attribution --force`.

declare(strict_types=1);

namespace Academorix\Attribution\Events;

use Illuminate\Contracts\Events\ShouldDispatchAfterCommit;

/**
 * attributions.current_session_id changed. Fires when a new browser session begins (session cookie rotated / expired). Distinct from AttributionLastTouchUpdated (session refresh may happen without utm change).
 *
 * ## Consumers
 *
 * - cache::InvalidateAttributionSessionCache
 *
 * @category Attribution
 *
 * @since    0.1.0
 */
final readonly class AttributionSessionRefreshed implements ShouldDispatchAfterCommit
{
    /**
     * @param  string  $attributionId  ULID
     * @param  string  $tenantId  ULID
     * @param  string  $wasSessionId  UUID | null
     * @param  string  $newSessionId  UUID
     * @param  string  $refreshedAt  ISO 8601
     */
    public function __construct(
        public readonly string $attributionId,
        public readonly string $tenantId,
        public readonly string $wasSessionId,
        public readonly string $newSessionId,
        public readonly string $refreshedAt,
    ) {
    }
}
