<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py finance tax --force`.

declare(strict_types=1);

namespace Academorix\Tax\Console;

use Academorix\Console\Attributes\AsCommand;
use Academorix\Console\Commands\BaseCommand;

/**
 * `php artisan tax:list-rates` — List rates — tax command.
 *
 * @category Tax
 *
 * @since    0.1.0
 */
#[AsCommand(
    name: 'tax:list-rates',
    description: 'List rates — tax command.',
)]
final class ListRatesCommand extends BaseCommand
{
    /**
     * Execute the command.
     *
     * TODO(gen): wire the required services + implement the handler body.
     */
    public function handle(): int
    {
        $this->omni->titleBar('List rates — tax command', 'sky');

        // TODO(gen): wire the required services + implement the handler body.

        $this->omni->success('List rates — tax command completed.');
        $this->showDuration();

        return self::SUCCESS;
    }
}
