<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py products geofencing --force`.

declare(strict_types=1);

namespace Stackra\Geofencing\Services;

use Stackra\Geofencing\Contracts\Services\GeofenceCheckServiceInterface;
use Illuminate\Container\Attributes\Scoped;
use Stackra\Geofencing\Contracts\Repositories\GeofenceCheckRepositoryInterface;

/**
 * Concrete service — GeofenceCheckService.
 *
 * Implements {@see GeofenceCheckServiceInterface}. `#[Scoped]` because most
 * services touch request state (current tenant, current user,
 * correlation id) — see `.kiro/steering/octane-first-di.md`. If
 * the service is provably stateless, promote to `#[Singleton]`.
 *
 * @category Geofencing
 *
 * @since    0.1.0
 */
#[Scoped]
final class GeofenceCheckService implements GeofenceCheckServiceInterface
{
    /**
     * @param  GeofenceCheckRepositoryInterface  $geofenceCheckRepository  Primary persistence boundary.
     */
    public function __construct(
        private readonly GeofenceCheckRepositoryInterface $geofenceCheckRepository,
    ) {
    }
}
