#!/usr/bin/env python3
"""generate-module.py — blueprint-driven Laravel module package generator.

Sibling to `generate-sdk.py`. Reads the same module blueprint and emits the
**server-side** Laravel package under `backend-packages/<tier>/<module>/`:

    - composer.json / phpstan.neon / phpunit.xml / README.md
    - src/Providers/<Name>ServiceProvider.php
    - database/migrations/YYYY_MM_DD_HHMMSS_create_<table>_table.php
    - src/Contracts/Data/<Model>Interface.php         (TABLE + ATTR_* constants + #[Bind])
    - src/Models/<Model>.php                          (#[Table] + #[Fillable] + #[UseFactory] + #[UsePolicy])
    - src/Contracts/Repositories/<Model>RepositoryInterface.php
    - src/Repositories/<Model>Repository.php          (#[AsRepository] + #[UseModel])
    - src/Data/<Model>Data.php                        (server-side output DTO)
    - database/factories/<Model>Factory.php
    - database/seeders/<Model>Seeder.php              (dual-source catalogues only)
    - src/Policies/<Model>Policy.php                  (from policies.json)
    - src/Events/*.php                                (from events.json)
    - src/Actions/*.php                               (from module.json routes — one Action per CRUD op)
    - tests/{Feature,Unit}/*Test.php                  (Pest v4 scaffolds)

Wire SDK (Saloon / Spatie Data) is a separate package under `sdk/`.
Both packages share one `composer.json` per side, both consume the same
blueprint through `_blueprint.read_module()`.

Every emitted file carries the AUTO-GENERATED header so regeneration with
`--force` cleanly replaces without clobbering hand-tuned overrides
(same convention as `generate-sdk.py`).

Usage:
    python3 modules/shared/blueprints/foundation/scripts/generate-module.py \\
        <tier> <module> [--force] [--dry-run]

    # Regenerate all in-scope modules:
    bash scripts/gen-all-modules.sh
"""

from __future__ import annotations

import argparse
import json
import os
import re
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

# Shared blueprint reader — same data model as generate-sdk.py.
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from _blueprint import (  # noqa: E402
    REPO_ROOT,
    Column,
    Entity,
    Module,
    Route,
    _first_sentence,
    _php_docblock,
    camel,
    kebab,
    module_dir_path,
    read_module,
    singular,
    snake,
    studly,
)

# Header for auto-generated files — the module drift check keys on this.
AUTOGEN_HEADER = (
    "// AUTO-GENERATED by generate-module.py from the module blueprint. "
    "Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py "
    "{tier} {name} --force`."
)

# ---------------------------------------------------------------------------
# Auxiliary blueprint files.
# ---------------------------------------------------------------------------

def _load_aux(module_dir: Path, filename: str) -> dict[str, Any]:
    """Load one of the auxiliary blueprint files (events.json, policies.json, ...).

    Returns an empty dict when the file is absent — every emitter gracefully
    degrades on missing input, so a module that hasn't yet been fully
    expanded still produces something reasonable.
    """
    path = module_dir / filename
    if not path.is_file():
        return {}
    try:
        return json.loads(path.read_text())
    except json.JSONDecodeError as e:
        print(f"WARN: {path} is not valid JSON ({e}); skipping", file=sys.stderr)
        return {}


# ---------------------------------------------------------------------------
# Package-level emitters (composer.json / phpunit.xml / phpstan.neon / README).
# ---------------------------------------------------------------------------

def emit_composer_json(m: Module) -> str:
    """Emit the module package's composer.json.

    Backslashes flow straight through — json.dumps handles PSR-4 escaping.
    Double-escaping (`ns.replace('\\\\', '\\\\\\\\')`) here caused the JSON
    autoload prefixes to render as `Academorix\\\\Foo\\\\` (double
    backslashes) and PSR-4 to silently fail for every module.
    """
    provider = f"{m.ns_module_root}\\Providers\\{m.studly_name}ServiceProvider"
    payload = {
        "name": m.composer_module_name,
        "type": "library",
        "description": (
            f"Academorix {m.studly_name} module — server-side Laravel package "
            f"emitted from the module blueprint at "
            f"`modules/{m.tier}/blueprints/{m.name}/`. Complements the wire "
            f"SDK at `{m.composer_name}`."
        ),
        "license": "proprietary",
        "keywords": [
            "academorix", "module", "laravel", m.tier, m.name,
        ],
        "require": {
            "php": "^8.3",
            "illuminate/support": "^13.0",
            "illuminate/database": "^13.0",
            "illuminate/container": "^13.0",
            "illuminate/contracts": "^13.0",
            "spatie/laravel-data": "^4.11",
            "academorix/foundation": "@dev",
            "academorix/crud": "@dev",
            "academorix/routing": "@dev",
            "academorix/service-provider": "@dev",
            "academorix/support": "@dev",
            f"{m.composer_name}": "@dev",
        },
        "require-dev": {
            "orchestra/testbench": "^11.0",
            "pestphp/pest": "^4.0",
            "pestphp/pest-plugin-laravel": "^4.0",
            "phpstan/phpstan": "^2.0",
            "mockery/mockery": "^1.6",
        },
        "autoload": {"psr-4": {f"{m.ns_module_root}\\": "src/"}},
        "autoload-dev": {"psr-4": {f"{m.ns_module_root}\\Tests\\": "tests/"}},
        "extra": {
            "laravel": {
                "providers": [provider],
                "aliases": {},
            }
        },
        "scripts": {
            "test": "./vendor/bin/pest",
            "test:coverage": "./vendor/bin/pest --coverage --min=80",
            "lint": "./vendor/bin/pint --test",
            "format": "./vendor/bin/pint",
            "analyse": "./vendor/bin/phpstan analyse --memory-limit=2G",
        },
        "config": {
            "sort-packages": True,
            "allow-plugins": {
                "pestphp/pest-plugin": True,
                "olvlvl/composer-attribute-collector": True,
            },
        },
        "minimum-stability": "stable",
        "prefer-stable": True,
    }
    return json.dumps(payload, indent=2, ensure_ascii=False) + "\n"


def emit_phpstan_neon() -> str:
    return (
        "includes:\n"
        "    - phar://phpstan.phar/conf/bleedingEdge.neon\n"
        "\n"
        "parameters:\n"
        "    level: 9\n"
        "    paths:\n"
        "        - src\n"
        "        - tests\n"
        "    treatPhpDocTypesAsCertain: false\n"
    )


def emit_phpunit_xml() -> str:
    return """<?xml version="1.0" encoding="UTF-8"?>
<phpunit xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="vendor/phpunit/phpunit/phpunit.xsd"
         bootstrap="vendor/autoload.php"
         colors="true"
         processIsolation="false"
         stopOnFailure="false"
         cacheDirectory=".phpunit.cache">
    <testsuites>
        <testsuite name="Feature">
            <directory>tests/Feature</directory>
        </testsuite>
        <testsuite name="Unit">
            <directory>tests/Unit</directory>
        </testsuite>
    </testsuites>
    <source>
        <include>
            <directory suffix=".php">src</directory>
        </include>
    </source>
</phpunit>
"""


def emit_readme(m: Module) -> str:
    entities_list = "\n".join(
        f"- **{e.class_name}** (`{e.key_prefix}...`) — {_first_sentence(e.description, 120)}"
        for e in m.entities
    ) or "- (no entities modelled yet)"
    return f"""# {m.composer_module_name}

Server-side Laravel package for the `{m.name}` module. Auto-generated from
the blueprint at `modules/{m.tier}/blueprints/{m.name}/`.

## Entities

{entities_list}

## Layout

```
src/
├── Providers/                     # <Name>ServiceProvider (module boot)
├── Contracts/
│   ├── Data/*Interface.php        # TABLE + ATTR_* constants (#[Bind]-bound to Model)
│   └── Repositories/*Interface.php
├── Models/*.php                   # Eloquent, attribute-first
├── Repositories/*.php             # #[AsRepository] + #[UseModel]
├── Data/*.php                     # Spatie Data output DTOs
├── Policies/*.php                 # Wired via #[UsePolicy] on the Model
├── Events/*.php                   # Domain events (ShouldDispatchAfterCommit)
└── Actions/*.php                  # Single-invoke controllers (#[AsController])
database/
├── migrations/*.php
├── factories/*.php
└── seeders/*.php                  # (dual-source catalogues only)
tests/
├── Feature/
└── Unit/
```

## Regeneration

```bash
python3 modules/shared/blueprints/foundation/scripts/generate-module.py \\
    {m.tier} {m.name} --force
```

Files carrying the `AUTO-GENERATED` header are safe to regenerate; every
other file is a hand-tuned override that survives regeneration.

## Companion wire SDK

The wire-visible Saloon + Spatie Data package lives at `{m.composer_name}`
under `sdk/{m.tier}-{m.name}-sdk/`. Consumers cross the service boundary
through the SDK; this package is the SERVER-side owner of the domain.
"""


def emit_service_provider(m: Module) -> str:
    """Emit the module's service provider skeleton."""
    ns = f"{m.ns_module_root}\\Providers"
    class_doc = _php_docblock([
        f"Service provider for the `{m.name}` module.",
        "",
        "Registers the module's discovery-driven bindings (attribute-first).",
        "Repository / policy / observer / event wiring is auto-discovered via",
        "the `Academorix\\Foundation\\Contracts\\DiscoversAttributes` seam;",
        "this provider is a thin lifecycle shell.",
        "",
        f"@category {m.studly_name}",
        "",
        "@since    0.1.0",
    ])
    return f"""<?php

declare(strict_types=1);

// {AUTOGEN_HEADER.format(tier=m.tier, name=m.name)}
namespace {ns};

use Illuminate\\Support\\ServiceProvider;

{class_doc}
final class {m.studly_name}ServiceProvider extends ServiceProvider
{{
    /**
     * Register container bindings.
     */
    public function register(): void
    {{
        // Attribute-first: #[Bind] on interfaces + #[AsRepository] /
        // #[AsSeeder] / #[AsAiTool] on concretes are picked up by the
        // Foundation discovery seam. Manual bindings only when a concern
        // cannot be expressed declaratively.
    }}

    /**
     * Bootstrap module services.
     */
    public function boot(): void
    {{
        $this->loadMigrationsFrom(__DIR__ . '/../../database/migrations');
        $this->loadTranslationsFrom(__DIR__ . '/../../lang', '{m.name}');
    }}
}}
"""


# ---------------------------------------------------------------------------
# Migration emitter.
# ---------------------------------------------------------------------------

_SEQ = 0


def _reset_migration_sequence():
    global _SEQ
    _SEQ = 0


def _next_migration_timestamp(base: datetime) -> str:
    """Monotonic timestamp for the migration filename."""
    global _SEQ
    _SEQ += 1
    ts = base + timezone.utc.utcoffset(base) if False else base
    # Advance seconds by _SEQ so filenames sort deterministically.
    seq_ts = ts.replace(microsecond=0)
    seq_str = f"{seq_ts.year:04d}_{seq_ts.month:02d}_{seq_ts.day:02d}_{seq_ts.hour:02d}{seq_ts.minute:02d}{seq_ts.second + _SEQ - 1:02d}"
    return seq_str


def _migration_column_line(col: Column, table_col_spec: dict[str, Any]) -> str:
    """Build one $table->TYPE('name') line from an x-database column spec."""
    name = col.name
    t = (table_col_spec.get("type") or "string").lower()
    length = table_col_spec.get("length")
    nullable = bool(table_col_spec.get("nullable", col.nullable))
    default = table_col_spec.get("default")
    primary = bool(table_col_spec.get("primary", False))
    foreign = table_col_spec.get("foreign") or {}

    # Blueprint kind -> Blueprint::method mapping.
    if t == "string" or t == "citext":
        if length:
            call = f"string('{name}', {length})"
        else:
            call = f"string('{name}')"
    elif t == "text":
        call = f"text('{name}')"
    elif t in ("bigint",):
        call = f"unsignedBigInteger('{name}')"
    elif t in ("integer", "int"):
        call = f"integer('{name}')"
    elif t == "boolean" or t == "bool":
        call = f"boolean('{name}')"
    elif t in ("timestamptz", "timestamp"):
        call = f"timestampTz('{name}')"
    elif t == "date":
        call = f"date('{name}')"
    elif t in ("date-time", "datetime"):
        call = f"dateTimeTz('{name}')"
    elif t in ("jsonb", "json"):
        call = f"jsonb('{name}')"
    elif t in ("uuid",):
        call = f"uuid('{name}')"
    elif t in ("ulid",):
        call = f"string('{name}', 30)"
    elif t in ("number", "float", "decimal"):
        call = f"decimal('{name}', 15, 4)"
    else:
        call = f"string('{name}')"

    line = f"            $table->{call}"

    if nullable and not primary:
        line += "->nullable()"
    if default is not None and not primary:
        # Default is emitted as literal PHP — best effort, wrap strings in quotes.
        if isinstance(default, str):
            # `default` in blueprint may already carry SQL-style quotes.
            if default.startswith("'") and default.endswith("'"):
                literal = default
            else:
                # Escape single quotes.
                escaped = default.replace("'", "\\'")
                literal = f"'{escaped}'"
            line += f"->default({literal})"
        elif isinstance(default, bool):
            line += f"->default({'true' if default else 'false'})"
        else:
            line += f"->default({default})"
    if primary:
        line += "->primary()"

    line += ";"

    # Foreign key reference.
    if foreign:
        f_table = foreign.get("table", "")
        f_col = foreign.get("column", "id")
        on_delete = foreign.get("onDelete", "cascade")
        if f_table:
            line += (
                f"\n            $table->foreign('{name}')->references('{f_col}')"
                f"->on('{f_table}')->onDelete('{on_delete}');"
            )

    return line


def _table_name_from_entity(entity: Entity, x_database: dict[str, Any]) -> str:
    """Return the migrated table name for an entity."""
    # The x-database.table may be on the schema's outer x-eloquent, or the
    # entity's own x-eloquent.table. Best-effort: use the aggregate.
    return entity.aggregate.replace("-", "_")


def emit_migration(m: Module, e: Entity, filename_ts: str) -> tuple[str, str]:
    """Emit one create-table migration file per entity.

    Returns (filename, body).
    """
    # Load the entity's raw schema to reach x-database.columns + indexes.
    module_dir = module_dir_path(m.tier, m.name)
    schema_path = module_dir / "schemas" / f"{e.name}.schema.json"
    schema = json.loads(schema_path.read_text()) if schema_path.is_file() else {}
    x_db = schema.get("x-database", {}) or {}
    columns_spec = x_db.get("columns", {}) or {}
    indexes_spec = x_db.get("indexes", []) or []

    table_name = _table_name_from_entity(e, x_db)
    filename = f"{filename_ts}_create_{table_name}_table.php"

    # Column lines.
    column_lines = []
    for col in e.columns:
        col_spec = columns_spec.get(col.name, {}) or {}
        column_lines.append(_migration_column_line(col, col_spec))
    columns_block = "\n".join(column_lines) if column_lines else "            // No columns declared on the blueprint."

    # Index lines. Skip functional indexes (columns containing SQL expressions
    # like `COALESCE(...)` or `LOWER(...)`) — Blueprint can't express them;
    # emit a hand-implement note instead.
    index_lines = []
    _ident_re = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")
    for idx in indexes_spec:
        cols = idx.get("columns") or []
        name = idx.get("name")
        unique = bool(idx.get("unique", False))
        predicate = idx.get("predicate")
        if not cols:
            continue
        if not all(isinstance(c, str) and _ident_re.match(c) for c in cols):
            # Functional index — hand-implement via DB::statement.
            expr = ", ".join(cols)
            index_lines.append(
                f"            // TODO(gen): hand-implement functional index — "
                f"columns=[{expr}]{' UNIQUE' if unique else ''}"
                f"{' WHERE ' + predicate if predicate else ''}"
            )
            continue
        cols_php = "[" + ", ".join(f"'{c}'" for c in cols) + "]"
        method = "unique" if unique else "index"
        if name:
            index_lines.append(f"            $table->{method}({cols_php}, '{name}');")
        else:
            index_lines.append(f"            $table->{method}({cols_php});")
        if predicate:
            index_lines.append(f"            // Partial-index predicate — hand-add via DB::statement: WHERE {predicate}")
    indexes_block = "\n".join(index_lines) if index_lines else ""

    class_doc = _php_docblock([
        f"@file database/migrations/{filename}",
        "",
        "@description",
        f"Create the `{table_name}` table for the `{e.class_name}` entity.",
        f"Owned by the {m.name} module. Emitted from the module blueprint —",
        f"regenerate via `generate-module.py {m.tier} {m.name} --force`.",
    ])

    return filename, f"""<?php

{class_doc}
// {AUTOGEN_HEADER.format(tier=m.tier, name=m.name)}

declare(strict_types=1);

use Illuminate\\Database\\Migrations\\Migration;
use Illuminate\\Database\\Schema\\Blueprint;
use Illuminate\\Support\\Facades\\Schema;

return new class() extends Migration {{
    /**
     * Run the migration.
     */
    public function up(): void
    {{
        Schema::create('{table_name}', function (Blueprint $table): void {{
{columns_block}
{indexes_block}
        }});
    }}

    /**
     * Reverse the migration.
     */
    public function down(): void
    {{
        Schema::dropIfExists('{table_name}');
    }}
}};
"""


# ---------------------------------------------------------------------------
# Model interface emitter (Contracts/Data/*Interface).
# ---------------------------------------------------------------------------

def emit_model_interface(m: Module, e: Entity) -> str:
    """Emit `src/Contracts/Data/<Model>Interface.php` — table shape."""
    ns = f"{m.ns_module_root}\\Contracts\\Data"
    table = e.aggregate.replace("-", "_")
    attr_lines = []
    max_name_len = max(len(c.name.upper()) for c in e.columns) if e.columns else 4
    for col in e.columns:
        const_name = f"ATTR_{col.name.upper()}"
        padding = " " * (max_name_len - len(col.name.upper()) + 1)
        attr_lines.append(f"    public const string {const_name}{padding}= '{col.name}';")
    columns_block = "\n".join(attr_lines) if attr_lines else "    // No columns declared on the blueprint."

    class_doc = _php_docblock([
        f"Table shape for the `{table}` table.",
        "",
        _first_sentence(e.description, 200),
        "",
        f"@category {m.studly_name}",
        "",
        "@since    0.1.0",
    ])

    return f"""<?php

// {AUTOGEN_HEADER.format(tier=m.tier, name=m.name)}

declare(strict_types=1);

namespace {ns};

use Illuminate\\Container\\Attributes\\Bind;
use {m.ns_module_root}\\Models\\{e.class_name};

{class_doc}
#[Bind({e.class_name}::class)]
interface {e.class_name}Interface
{{
    /**
     * Table name.
     */
    public const string TABLE = '{table}';

    /**
     * Primary key column.
     */
    public const string PRIMARY_KEY = 'id';

    /**
     * Primary key column type — string (ULID with prefix `{e.key_prefix}`).
     */
    public const string KEY_TYPE = 'string';

    // ── Columns ───────────────────────────────────────────────

{columns_block}
}}
"""


# ---------------------------------------------------------------------------
# Model emitter (src/Models/*.php).
# ---------------------------------------------------------------------------

def _extract_traits(schema: dict[str, Any]) -> list[str]:
    """Extract the `x-eloquent.traits` list from a schema."""
    x_el = schema.get("x-eloquent", {}) or {}
    return list(x_el.get("traits", []) or [])


def _trait_import(trait: str) -> str | None:
    """Map a trait short name to its fully-qualified import."""
    trait_map = {
        "HasFactory": "Illuminate\\Database\\Eloquent\\Factories\\HasFactory",
        "HasUlids": "Illuminate\\Database\\Eloquent\\Concerns\\HasUlids",
        "HasPrefixedUlid": "Academorix\\Foundation\\Concerns\\HasPrefixedUlid",
        "HasSlug": "Spatie\\Sluggable\\HasSlug",
        "HasMetadata": "Academorix\\Foundation\\Concerns\\HasMetadata",
        "HasUserstamps": "Mattiverse\\Userstamps\\Traits\\Userstamps",
        "Auditable": "OwenIt\\Auditing\\Auditable",
        "HasActivityLog": "Spatie\\Activitylog\\Traits\\LogsActivity",
        "Filterable": "Academorix\\Foundation\\Concerns\\Filterable",
        "Searchable": "Laravel\\Scout\\Searchable",
        "SoftDeletes": "Illuminate\\Database\\Eloquent\\SoftDeletes",
        "BelongsToTenant": "Academorix\\Tenancy\\Concerns\\BelongsToTenant",
        "BelongsToApplication": "Academorix\\Application\\Concerns\\BelongsToApplication",
        "BelongsToOrganization": "Academorix\\Organization\\Concerns\\BelongsToOrganization",
        "BelongsToBranch": "Academorix\\Branch\\Concerns\\BelongsToBranch",
        "BelongsToRegion": "Academorix\\Region\\Concerns\\BelongsToRegion",
        "BelongsToUser": "Academorix\\User\\Concerns\\BelongsToUser",
        "BelongsToAthlete": "Academorix\\Sports\\Athlete\\Concerns\\BelongsToAthlete",
        "BelongsToStaff": "Academorix\\Staff\\Concerns\\BelongsToStaff",
        "BelongsToSeason": "Academorix\\Sports\\Season\\Concerns\\BelongsToSeason",
        "BelongsToEvent": "Academorix\\Sports\\Event\\Concerns\\BelongsToEvent",
        "HasEventFacilities": "Academorix\\Sports\\Event\\Concerns\\HasEventFacilities",
    }
    return trait_map.get(trait)


def emit_model(m: Module, e: Entity) -> str:
    """Emit `src/Models/<Model>.php` — attribute-first Eloquent model."""
    ns = f"{m.ns_module_root}\\Models"
    module_dir = module_dir_path(m.tier, m.name)
    schema_path = module_dir / "schemas" / f"{e.name}.schema.json"
    schema = json.loads(schema_path.read_text()) if schema_path.is_file() else {}

    traits = _extract_traits(schema)
    trait_imports = []
    trait_use_lines = []
    for trait in traits:
        fqcn = _trait_import(trait)
        if fqcn:
            trait_imports.append(f"use {fqcn};")
            trait_use_lines.append(f"    use {trait};")
        else:
            # Unknown trait — hand-tune post-generation.
            trait_use_lines.append(f"    // TODO(gen): resolve unknown trait `{trait}` — add its import + use line.")

    # Fillable = every non-primary, non-audit column.
    audit_cols = {"id", "created_at", "updated_at", "deleted_at",
                  "created_by", "updated_by", "deleted_by"}
    fillable = [c.name for c in e.columns if c.name not in audit_cols]
    fillable_lines = ",\n        ".join(
        f"{e.class_name}Interface::ATTR_{c.upper()}" for c in fillable
    )

    # Casts from x-eloquent.casts if present.
    x_el = schema.get("x-eloquent", {}) or {}
    casts = x_el.get("casts", {}) or {}
    casts_lines = ",\n        ".join(
        f"{e.class_name}Interface::ATTR_{col.upper()} => '{ctype}'"
        for col, ctype in casts.items()
    ) if casts else ""

    table_name = e.aggregate.replace("-", "_")

    class_doc = _php_docblock([
        f"Eloquent model for a {e.class_name}.",
        "",
        _first_sentence(e.description, 200),
        "",
        f"@category {m.studly_name}",
        "",
        "@since    0.1.0",
    ])

    trait_imports_block = "\n".join(sorted(set(trait_imports)))
    trait_use_block = "\n".join(trait_use_lines) if trait_use_lines else ""

    interface_import = f"use {m.ns_module_root}\\Contracts\\Data\\{e.class_name}Interface;"
    factory_import = f"use {m.ns_module_root}\\Database\\Factories\\{e.class_name}Factory;"

    fillable_block = f"""#[Fillable([
    {fillable_lines},
])]""" if fillable else "#[Unguarded]"

    casts_block = f"""    /**
     * Cast map — from the blueprint's x-eloquent.casts.
     *
     * @var array<string, string>
     */
    protected $casts = [
        {casts_lines},
    ];
""" if casts else ""

    return f"""<?php

// {AUTOGEN_HEADER.format(tier=m.tier, name=m.name)}

declare(strict_types=1);

namespace {ns};

use Illuminate\\Database\\Eloquent\\Attributes\\Fillable;
use Illuminate\\Database\\Eloquent\\Attributes\\Table;
use Illuminate\\Database\\Eloquent\\Attributes\\UseFactory;
use Illuminate\\Database\\Eloquent\\Model;
{interface_import}
{factory_import}
{trait_imports_block}

{class_doc}
#[Table(name: {e.class_name}Interface::TABLE, keyType: {e.class_name}Interface::KEY_TYPE)]
{fillable_block}
#[UseFactory({e.class_name}Factory::class)]
final class {e.class_name} extends Model implements {e.class_name}Interface
{{
{trait_use_block}

    /**
     * The primary key IS a string (prefixed ULID); disable auto-increment.
     *
     * @var bool
     */
    public $incrementing = false;

{casts_block}}}
"""


# ---------------------------------------------------------------------------
# Repository emitter.
# ---------------------------------------------------------------------------

def emit_repository_interface(m: Module, e: Entity) -> str:
    """Emit `src/Contracts/Repositories/<Model>RepositoryInterface.php`."""
    ns = f"{m.ns_module_root}\\Contracts\\Repositories"
    class_doc = _php_docblock([
        f"Repository contract for {{@see {m.ns_module_root}\\Models\\{e.class_name}}}.",
        "",
        "Consumers type-hint the interface; the container binds the concrete",
        f"via `#[AsRepository]` on `{e.class_name}Repository`.",
        "",
        f"@extends RepositoryInterface<\\{m.ns_module_root}\\Models\\{e.class_name}>",
        "",
        f"@category {m.studly_name}",
        "",
        "@since    0.1.0",
    ])
    return f"""<?php

// {AUTOGEN_HEADER.format(tier=m.tier, name=m.name)}

declare(strict_types=1);

namespace {ns};

use Academorix\\Crud\\Contracts\\RepositoryInterface;

{class_doc}
interface {e.class_name}RepositoryInterface extends RepositoryInterface
{{
    // Domain-specific query methods live here. CRUD comes from the base.
}}
"""


def emit_repository(m: Module, e: Entity) -> str:
    """Emit `src/Repositories/<Model>Repository.php` — #[AsRepository]-driven."""
    ns = f"{m.ns_module_root}\\Repositories"
    interface_ns = f"{m.ns_module_root}\\Contracts"
    class_doc = _php_docblock([
        f"Attribute-first Eloquent repository for {{@see {m.ns_module_root}\\Models\\{e.class_name}}}.",
        "",
        "Bound to the interface via `#[AsRepository]`; the model comes from",
        f"`#[UseModel({e.class_name}Interface::class)]` which resolves to",
        f"`{e.class_name}` through the interface's `#[Bind]`.",
        "",
        f"@extends Repository<\\{m.ns_module_root}\\Models\\{e.class_name}>",
        "",
        f"@category {m.studly_name}",
        "",
        "@since    0.1.0",
    ])
    return f"""<?php

// {AUTOGEN_HEADER.format(tier=m.tier, name=m.name)}

declare(strict_types=1);

namespace {ns};

use Academorix\\Crud\\Attributes\\AsRepository;
use Academorix\\Crud\\Attributes\\Cacheable;
use Academorix\\Crud\\Attributes\\Filterable;
use Academorix\\Crud\\Attributes\\UseModel;
use Academorix\\Crud\\Repositories\\Repository;
use {interface_ns}\\Data\\{e.class_name}Interface;
use {interface_ns}\\Repositories\\{e.class_name}RepositoryInterface;
use {m.ns_module_root}\\Models\\{e.class_name};

{class_doc}
#[AsRepository]
#[UseModel({e.class_name}Interface::class)]
#[Cacheable(ttl: 3600, tags: true)]
#[Filterable('*')]
final class {e.class_name}Repository extends Repository implements {e.class_name}RepositoryInterface
{{
    // Domain methods added here. CRUD comes from Repository.
}}
"""


# ---------------------------------------------------------------------------
# Data DTO emitter (server-side output).
# ---------------------------------------------------------------------------

def emit_data_dto(m: Module, e: Entity) -> str:
    """Emit `src/Data/<Model>Data.php` — server-side output DTO."""
    ns = f"{m.ns_module_root}\\Data"

    required_cols = [c for c in e.wire_columns if not c.nullable]
    optional_cols = [c for c in e.wire_columns if c.nullable]

    def prop_line(col: Column) -> str:
        type_hint = ("?" if col.nullable else "") + col.php_type
        default = " = null" if col.nullable else ""
        return f"        public {type_hint} ${camel(col.name)}{default},"

    props_src = "\n".join(prop_line(c) for c in required_cols + optional_cols)

    class_doc = _php_docblock([
        f"Server-side output DTO for {{@see \\{m.ns_module_root}\\Models\\{e.class_name}}}.",
        "",
        "Consumed by controllers + services on the SERVER side. This is",
        "distinct from the wire SDK's DTO (which sits under",
        f"`{m.ns_root}\\Data`) — the wire DTO travels across the HTTP",
        "boundary; this one stays in-process.",
        "",
        f"@category {m.studly_name}",
        "",
        "@since    0.1.0",
    ])

    return f"""<?php

// {AUTOGEN_HEADER.format(tier=m.tier, name=m.name)}

declare(strict_types=1);

namespace {ns};

use Spatie\\LaravelData\\Attributes\\MapInputName;
use Spatie\\LaravelData\\Data;
use Spatie\\LaravelData\\Mappers\\SnakeCaseMapper;

{class_doc}
#[MapInputName(SnakeCaseMapper::class)]
final class {e.class_name}Data extends Data
{{
    public function __construct(
{props_src}
    ) {{
    }}
}}
"""


# ---------------------------------------------------------------------------
# Factory emitter.
# ---------------------------------------------------------------------------

def _faker_call(col: Column) -> str:
    """Return a PHP faker expression for a Column."""
    if col.is_enum and col.enum_values:
        vals = ", ".join(f"'{v}'" for v in col.enum_values if isinstance(v, str))
        return f"fake()->randomElement([{vals}])"
    name_lower = col.name.lower()
    if "email" in name_lower:
        return "fake()->safeEmail()"
    if "phone" in name_lower:
        return "fake()->phoneNumber()"
    if "url" in name_lower:
        return "fake()->url()"
    if name_lower.endswith("_at") or name_lower == "date":
        return "now()"
    if col.php_type == "bool":
        return "fake()->boolean()"
    if col.php_type == "int":
        return "fake()->numberBetween(1, 1000)"
    if col.php_type == "float":
        return "fake()->randomFloat(2, 0, 10000)"
    if col.php_type == "array":
        return "[]"
    if col.max_length and col.max_length <= 32:
        return f"fake()->word()"
    return "fake()->sentence(3)"


def emit_factory(m: Module, e: Entity) -> str:
    """Emit `database/factories/<Model>Factory.php`."""
    ns = f"{m.ns_module_root}\\Database\\Factories"
    # Emit definition() only for columns that don't have safe defaults (audit / tenant / primary).
    audit_cols = {"id", "created_at", "updated_at", "deleted_at",
                  "created_by", "updated_by", "deleted_by"}
    fillable_cols = [c for c in e.columns if c.name not in audit_cols and c.name != "tenant_id"]
    lines = []
    for c in fillable_cols:
        if c.nullable:
            # Optional in factory too.
            lines.append(f"            {e.class_name}Interface::ATTR_{c.name.upper()} => null,")
        else:
            lines.append(f"            {e.class_name}Interface::ATTR_{c.name.upper()} => {_faker_call(c)},")
    body_lines = "\n".join(lines) if lines else "            // No fillable columns."

    class_doc = _php_docblock([
        f"Factory for {{@see \\{m.ns_module_root}\\Models\\{e.class_name}}}.",
        "",
        "Auto-generated skeleton — extend with named states as domain",
        "cases emerge (e.g. `->published()`, `->overdue()`, `->archived()`).",
        "",
        f"@extends Factory<\\{m.ns_module_root}\\Models\\{e.class_name}>",
        "",
        f"@category {m.studly_name}",
        "",
        "@since    0.1.0",
    ])

    return f"""<?php

// {AUTOGEN_HEADER.format(tier=m.tier, name=m.name)}

declare(strict_types=1);

namespace {ns};

use Illuminate\\Database\\Eloquent\\Factories\\Factory;
use {m.ns_module_root}\\Contracts\\Data\\{e.class_name}Interface;
use {m.ns_module_root}\\Models\\{e.class_name};

{class_doc}
final class {e.class_name}Factory extends Factory
{{
    /**
     * The model this factory builds.
     *
     * @var class-string<{e.class_name}>
     */
    protected $model = {e.class_name}::class;

    /**
     * Return the default model attribute values.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {{
        return [
{body_lines}
        ];
    }}
}}
"""


# ---------------------------------------------------------------------------
# Policy emitter.
# ---------------------------------------------------------------------------

def emit_policy(m: Module, e: Entity, policy_spec: dict[str, Any]) -> str:
    """Emit `src/Policies/<Model>Policy.php` from one policies.json entry."""
    ns = f"{m.ns_module_root}\\Policies"
    abilities = policy_spec.get("abilities", []) or []
    method_lines = []
    for ability in abilities:
        action = ability.get("action")
        permission = ability.get("permission")
        scope = ability.get("scope", "")
        if not action:
            continue
        method_name = camel(action)
        doc = _php_docblock([
            _first_sentence(scope or f"{action} ability.", 200) or f"{action} ability.",
            "",
            "@return bool",
        ], indent="    ")
        if permission:
            body = f"        return $user->can('{permission}');"
        else:
            body = "        // TODO(gen): decide policy body — no permission binding declared on the blueprint.\n        return false;"
        method_lines.append(f"""
{doc}
    public function {method_name}(User $user, {e.class_name} $model): bool
    {{
{body}
    }}""")

    class_doc = _php_docblock([
        f"Authorization policy for {{@see \\{m.ns_module_root}\\Models\\{e.class_name}}}.",
        "",
        "Wired via `#[UsePolicy]` on the Model.",
        "",
        f"@category {m.studly_name}",
        "",
        "@since    0.1.0",
    ])

    # Alias the actor `User` import when the policy's model is ALSO named User
    # (e.g. identity/user's UserPolicy), otherwise PHP raises a name collision.
    actor_import_alias = "AuthUser" if e.class_name == "User" else "User"
    actor_type = actor_import_alias
    actor_import_line = (
        f"use Academorix\\User\\Models\\User as {actor_import_alias};"
        if actor_import_alias != "User"
        else "use Academorix\\User\\Models\\User;"
    )

    return f"""<?php

// {AUTOGEN_HEADER.format(tier=m.tier, name=m.name)}

declare(strict_types=1);

namespace {ns};

{actor_import_line}
use {m.ns_module_root}\\Models\\{e.class_name};

{class_doc}
final class {e.class_name}Policy
{{{"".join(method_lines).replace("User $user", f"{actor_type} $user")}
}}
"""


# ---------------------------------------------------------------------------
# Event emitter.
# ---------------------------------------------------------------------------

def emit_event(m: Module, event_spec: dict[str, Any]) -> tuple[str, str]:
    """Emit one event class from an events.json entry. Returns (path, body)."""
    ns = f"{m.ns_module_root}\\Events"
    name = event_spec.get("name") or "UnknownEvent"
    class_name = studly(name)
    trigger = event_spec.get("trigger", "")
    consumers = event_spec.get("consumers", []) or []
    payload = event_spec.get("payload", {}) or {}

    prop_lines = []
    ctor_doc_lines = []
    for key, kind in payload.items():
        prop_name = camel(key)
        php_type = _payload_type_to_php(kind)
        prop_lines.append(f"        public readonly {php_type} ${prop_name},")
        ctor_doc_lines.append(f"@param  {php_type}  ${prop_name}  {kind}")

    doc_lines = [
        f"{trigger}" if trigger else f"Domain event: {class_name}.",
        "",
    ]
    if consumers:
        doc_lines.append("## Consumers")
        doc_lines.append("")
        for c in consumers:
            doc_lines.append(f"- {c}")
        doc_lines.append("")
    doc_lines += [
        f"@category {m.studly_name}",
        "",
        "@since    0.1.0",
    ]

    ctor_doc = _php_docblock(ctor_doc_lines, indent="    ") if ctor_doc_lines else ""
    props_block = "\n".join(prop_lines) if prop_lines else ""

    body = f"""<?php

// {AUTOGEN_HEADER.format(tier=m.tier, name=m.name)}

declare(strict_types=1);

namespace {ns};

use Illuminate\\Contracts\\Events\\ShouldDispatchAfterCommit;

{_php_docblock(doc_lines)}
final readonly class {class_name} implements ShouldDispatchAfterCommit
{{
{ctor_doc}
    public function __construct(
{props_block}
    ) {{
    }}
}}
"""
    return f"src/Events/{class_name}.php", body


def _payload_type_to_php(kind: str) -> str:
    """Map an events.json payload type description to a PHP type hint."""
    k = str(kind).lower()
    if k.startswith("ulid") or k == "string":
        return "string"
    if k.startswith("iso") or "8601" in k:
        return "string"
    if "int" in k:
        return "int"
    if "bool" in k:
        return "bool"
    if "float" in k or "double" in k or "decimal" in k:
        return "float"
    if "array" in k or "object" in k or "jsonb" in k:
        return "array"
    if "|" in k:
        # Union like "'a'|'b'" — string.
        return "string"
    return "string"


# ---------------------------------------------------------------------------
# Action emitter.
# ---------------------------------------------------------------------------

_AUDIENCE_SUBDIR = {
    "platform-admin": "Platform",
    "platform": "Platform",
    "tenant": "Tenant",
    "central": "Central",
    "public": "Public",
}


def emit_action(m: Module, route: Route) -> tuple[str, str]:
    """Emit one Action from a route. Returns (path, body).

    Actions are split by audience: platform-admin → `Actions/Platform/`,
    tenant → `Actions/Tenant/`, central → `Actions/Central/`, ...
    Matches the pattern the real implementations use (see
    `backend-packages/shared/activity/src/Actions/{Platform,Tenant}`).
    """
    subdir = _AUDIENCE_SUBDIR.get(route.audience, studly(route.audience or "Custom"))
    ns = f"{m.ns_module_root}\\Actions\\{subdir}"
    op = route.op
    agg = studly(route.aggregate)
    verb = route.verb
    class_name = f"{studly(op) if op != 'custom' else studly(route.custom_name or 'custom')}{agg[:-1] if agg.endswith('s') else agg}Action"

    doc = _php_docblock([
        f"`{verb} {route.path}` — {op} action ({route.audience or 'unscoped'} audience).",
        "",
        f"Single-invoke controller. Wire via `#[AsController]` +",
        f"the appropriate HTTP-verb attribute from `Academorix\\Routing`.",
        "",
        f"@category {m.studly_name}",
        "",
        "@since    0.1.0",
    ])
    body = f"""<?php

// {AUTOGEN_HEADER.format(tier=m.tier, name=m.name)}

declare(strict_types=1);

namespace {ns};

{doc}
final class {class_name}
{{
    /**
     * Execute the action.
     *
     * TODO(gen): wire the required services + implement the handler body.
     */
    public function __invoke(): mixed
    {{
        // Hand-implement the domain logic here.
        return null;
    }}
}}
"""
    return f"src/Actions/{subdir}/{class_name}.php", body


# ---------------------------------------------------------------------------
# Enum emitter — one class per schema property with an `enum: [...]` closed set.
# ---------------------------------------------------------------------------

# PHP-reserved words that cannot be used as enum case labels. `Class` is
# rejected outright by the parser (reserved for `::class` name fetching);
# the rest are class-constant reserved words (T_HALT_COMPILER, etc.) or
# highly likely to collide with future PHP syntax. When a blueprint uses
# one of these strings as an enum value we prefix the case label to
# disambiguate (e.g. `class` -> `ClassKind`, `default` -> `DefaultKind`).
# The backing wire value stays untouched so external callers are
# unaffected.
_PHP_RESERVED_CASE_NAMES = frozenset({
    "class", "default", "true", "false", "null", "self", "static",
    "parent", "list", "match", "readonly", "iterable",
})


def _safe_case_name(raw: str, field_studly: str) -> str:
    """Return a PHP-legal enum case label.

    Handles the two illegal shapes we've seen in real blueprints:

    - Reserved word: `class` on a `team_type` column would emit
      `case Class` (parser rejects it). We suffix with the field's
      studly form so the label reads meaningfully.
    - Digit-first: numeric values like `1.0.2` studly-normalise to
      `102` which cannot start a PHP identifier. We prefix with `V`
      (version / value) so the label is legal (`V102`).

    The backing wire value stays untouched so external callers are
    unaffected in either case.
    """
    case_name = studly(raw)
    if not case_name:
        # Should never happen for a real enum value; guard anyway.
        return f"Empty{field_studly}"
    if raw.lower() in _PHP_RESERVED_CASE_NAMES:
        return f"{case_name}{field_studly}"
    if case_name[0].isdigit():
        return f"V{case_name}"
    return case_name


def emit_enums(m: Module, e: Entity) -> list[tuple[str, str]]:
    """Emit `src/Enums/<Model><Field>.php` for every closed-set column."""
    ns = f"{m.ns_module_root}\\Enums"
    out: list[tuple[str, str]] = []
    for col in e.columns:
        if not col.is_enum or not col.enum_values:
            continue
        field_studly = studly(col.name)
        class_name = f"{e.class_name}{field_studly}"
        cases = []
        for val in col.enum_values:
            if not isinstance(val, str):
                continue
            case_name = _safe_case_name(val, field_studly)
            cases.append(f"    case {case_name} = '{val}';")
        if not cases:
            continue
        cases_body = "\n".join(cases)
        doc = _php_docblock([
            f"Closed-set enum for `{col.name}` on `{e.name}`.",
            "",
            _first_sentence(col.description, 200) or f"Backed enum — one case per allowed value.",
            "",
            f"@category {m.studly_name}",
            "",
            "@since    0.1.0",
        ])
        body = f"""<?php

// {AUTOGEN_HEADER.format(tier=m.tier, name=m.name)}

declare(strict_types=1);

namespace {ns};

use Academorix\\Enum\\Enum;

{doc}
enum {class_name}: string
{{
    use Enum;

{cases_body}
}}
"""
        out.append((f"src/Enums/{class_name}.php", body))
    return out


# ---------------------------------------------------------------------------
# Exception emitter — from errors.json.
# ---------------------------------------------------------------------------

def emit_exception(m: Module, err_spec: dict[str, Any]) -> tuple[str, str] | None:
    """Emit one exception class per entry in errors.json."""
    code = err_spec.get("code")
    if not code or not isinstance(code, str):
        return None
    ns = f"{m.ns_module_root}\\Exceptions"
    last = code.split(".")[-1]
    class_name = err_spec.get("name") or f"{studly(last)}Exception"
    if not class_name.endswith("Exception"):
        class_name += "Exception"
    description = err_spec.get("description") or f"Raised when the domain rule `{code}` fires."
    translation_key = err_spec.get("translation_key") or f"{m.name}::errors.{last}"
    doc = _php_docblock([
        _first_sentence(description, 200),
        "",
        f"@category {m.studly_name}",
        "",
        "@since    0.1.0",
    ])
    body = f"""<?php

// {AUTOGEN_HEADER.format(tier=m.tier, name=m.name)}

declare(strict_types=1);

namespace {ns};

use Academorix\\Exceptions\\AcademorixException;

{doc}
final class {class_name} extends AcademorixException
{{
    /**
     * Stable machine-readable error code emitted on the JSON envelope.
     */
    public const CODE = '{code}';

    /**
     * Translation key for the humanised message.
     */
    public const TRANSLATION_KEY = '{translation_key}';
}}
"""
    return f"src/Exceptions/{class_name}.php", body


# ---------------------------------------------------------------------------
# Console command emitter — one class per commands[] entry.
# ---------------------------------------------------------------------------

def emit_console_command(m: Module, signature: str) -> tuple[str, str]:
    """Emit `src/Console/<Name>Command.php` for one command entry."""
    ns = f"{m.ns_module_root}\\Console"
    parts = signature.split(":", 1)
    if len(parts) == 2:
        _, verb_part = parts
    else:
        verb_part = parts[0]
    class_name = f"{studly(verb_part)}Command"
    doc = _php_docblock([
        f"`php artisan {signature}` — TODO(gen): describe what this command does.",
        "",
        f"@category {m.studly_name}",
        "",
        "@since    0.1.0",
    ])
    body = f"""<?php

// {AUTOGEN_HEADER.format(tier=m.tier, name=m.name)}

declare(strict_types=1);

namespace {ns};

use Academorix\\Console\\Attributes\\AsCommand;
use Academorix\\Console\\Console\\Commands\\BaseCommand;

{doc}
#[AsCommand(
    name: '{signature}',
    description: 'TODO(gen): one-line description shown by `artisan list`.',
)]
final class {class_name} extends BaseCommand
{{
    /**
     * Execute the command.
     *
     * TODO(gen): wire the required services + implement the handler body.
     */
    public function handle(): int
    {{
        return self::SUCCESS;
    }}
}}
"""
    return f"src/Console/{class_name}.php", body


# ---------------------------------------------------------------------------
# Job emitter — one class per jobs[] entry.
# ---------------------------------------------------------------------------

def emit_job(m: Module, name: str) -> tuple[str, str]:
    """Emit `src/Jobs/<Name>.php` for one queued job entry."""
    ns = f"{m.ns_module_root}\\Jobs"
    class_name = studly(name)
    if not class_name.endswith("Job"):
        class_name += "Job"
    doc = _php_docblock([
        f"Queued job — {class_name}.",
        "",
        f"TODO(gen): describe the job's trigger, payload, and idempotency",
        f"contract. Emitted as a skeleton; hand-implement the `handle()` body.",
        "",
        f"@category {m.studly_name}",
        "",
        "@since    0.1.0",
    ])
    body = f"""<?php

// {AUTOGEN_HEADER.format(tier=m.tier, name=m.name)}

declare(strict_types=1);

namespace {ns};

use Illuminate\\Bus\\Queueable;
use Illuminate\\Contracts\\Queue\\ShouldQueue;
use Illuminate\\Foundation\\Bus\\Dispatchable;
use Illuminate\\Queue\\Attributes\\Queue;
use Illuminate\\Queue\\Attributes\\Timeout;
use Illuminate\\Queue\\Attributes\\Tries;
use Illuminate\\Queue\\InteractsWithQueue;
use Illuminate\\Queue\\SerializesModels;

{doc}
#[Queue('{m.name}')]
#[Timeout(120)]
#[Tries(3)]
final class {class_name} implements ShouldQueue
{{
    use Dispatchable;
    use InteractsWithQueue;
    use Queueable;
    use SerializesModels;

    /**
     * Execute the job.
     *
     * TODO(gen): implement the job body.
     */
    public function handle(): void
    {{
        // Hand-implement.
    }}

    /**
     * Handle a job failure.
     */
    public function failed(\\Throwable $e): void
    {{
        // TODO(gen): compensate or notify. Never `throw` from here.
    }}
}}
"""
    return f"src/Jobs/{class_name}.php", body


# ---------------------------------------------------------------------------
# Service emitter — one interface + one concrete per bindings[] entry.
# ---------------------------------------------------------------------------

def emit_service_interface(m: Module, name: str) -> tuple[str, str]:
    """Emit `src/Contracts/Services/<Name>Interface.php`."""
    ns = f"{m.ns_module_root}\\Contracts\\Services"
    concrete_ns = f"{m.ns_module_root}\\Services"
    class_name = studly(name)
    iface_name = f"{class_name}Interface"
    if class_name.endswith("Interface"):
        iface_name = class_name
        class_name = class_name[: -len("Interface")]
    doc = _php_docblock([
        f"Service contract for {class_name}.",
        "",
        f"Bound to the concrete via `#[Bind({class_name}::class)]`. Consumers",
        f"type-hint this interface; tests bind a fake through the container.",
        "",
        f"@category {m.studly_name}",
        "",
        "@since    0.1.0",
    ])
    body = f"""<?php

// {AUTOGEN_HEADER.format(tier=m.tier, name=m.name)}

declare(strict_types=1);

namespace {ns};

use {concrete_ns}\\{class_name};
use Illuminate\\Container\\Attributes\\Bind;

{doc}
#[Bind({class_name}::class)]
interface {iface_name}
{{
    // TODO(gen): declare the domain methods this service exposes.
}}
"""
    return f"src/Contracts/Services/{iface_name}.php", body


def emit_service_concrete(m: Module, name: str) -> tuple[str, str]:
    """Emit `src/Services/<Name>.php` — concrete service implementation."""
    ns = f"{m.ns_module_root}\\Services"
    iface_ns = f"{m.ns_module_root}\\Contracts\\Services"
    class_name = studly(name)
    iface_name = f"{class_name}Interface"
    if class_name.endswith("Interface"):
        iface_name = class_name
        class_name = class_name[: -len("Interface")]
    doc = _php_docblock([
        f"Concrete service — {class_name}.",
        "",
        f"Implements {{@see {iface_name}}}. `#[Scoped]` because most",
        f"services touch request state (current tenant, current user,",
        f"correlation id) — see `.kiro/steering/octane-first-di.md`. If the",
        f"service is provably stateless, promote to `#[Singleton]`.",
        "",
        f"@category {m.studly_name}",
        "",
        "@since    0.1.0",
    ])
    body = f"""<?php

// {AUTOGEN_HEADER.format(tier=m.tier, name=m.name)}

declare(strict_types=1);

namespace {ns};

use {iface_ns}\\{iface_name};
use Illuminate\\Container\\Attributes\\Scoped;

{doc}
#[Scoped]
final class {class_name} implements {iface_name}
{{
    // TODO(gen): implement the interface methods.
}}
"""
    return f"src/Services/{class_name}.php", body


# ---------------------------------------------------------------------------
# Concerns (trait) emitter — one per traits[] entry.
# ---------------------------------------------------------------------------

def emit_trait(m: Module, name: str) -> tuple[str, str]:
    """Emit `src/Concerns/<Name>.php` — trait skeleton."""
    ns = f"{m.ns_module_root}\\Concerns"
    trait_name = studly(name)
    doc = _php_docblock([
        f"Trait — {trait_name}.",
        "",
        f"TODO(gen): describe the compositional intent. Common patterns:",
        f"BelongsTo<X> (adds an `$x_id` FK + `x()` relation), Has<X>",
        f"(inverse — adds a `has<X>()` scope + a `<x>()` relation),",
        f"Manages<X> (opinionated helpers that operate on <X> children).",
        "",
        f"@category {m.studly_name}",
        "",
        "@since    0.1.0",
    ])
    body = f"""<?php

// {AUTOGEN_HEADER.format(tier=m.tier, name=m.name)}

declare(strict_types=1);

namespace {ns};

{doc}
trait {trait_name}
{{
    // TODO(gen): implement the trait's composition surface.
}}
"""
    return f"src/Concerns/{trait_name}.php", body


# ---------------------------------------------------------------------------
# PHP attribute emitter — one per attributes[] entry.
# ---------------------------------------------------------------------------

def emit_php_attribute(m: Module, name: str) -> tuple[str, str]:
    """Emit `src/Attributes/<Name>.php` — one PHP `#[Attribute]` class."""
    ns = f"{m.ns_module_root}\\Attributes"
    class_name = studly(name)
    doc = _php_docblock([
        f"PHP attribute — {class_name}.",
        "",
        f"TODO(gen): document the attribute's target + discovery pipeline.",
        f"Follow the pattern of `#[AsAiTool]` / `#[LoggableActivity]` /",
        f"`#[AsRepository]` — one attribute per compile-time-declarative",
        f"concern, scanned at boot via Foundation's `DiscoversAttributes`",
        f"seam, hydrated into a registry, consumed by a runner.",
        "",
        f"@category {m.studly_name}",
        "",
        "@since    0.1.0",
    ])
    body = f"""<?php

// {AUTOGEN_HEADER.format(tier=m.tier, name=m.name)}

declare(strict_types=1);

namespace {ns};

use Attribute;

{doc}
#[Attribute(Attribute::TARGET_CLASS)]
final readonly class {class_name}
{{
    // TODO(gen): declare the attribute's constructor parameters, if any.
}}
"""
    return f"src/Attributes/{class_name}.php", body


# ---------------------------------------------------------------------------
# Data/Requests emitter — one write-payload DTO per create/update route.
# ---------------------------------------------------------------------------

def emit_request_data(m: Module, e: Entity, op: str) -> tuple[str, str]:
    """Emit `src/Data/Requests/<Op><Model>RequestData.php`."""
    ns = f"{m.ns_module_root}\\Data\\Requests"
    op_studly = studly(op)
    class_name = f"{op_studly}{e.class_name}RequestData"

    audit_cols = {"id", "created_at", "updated_at", "deleted_at",
                  "created_by", "updated_by", "deleted_by"}
    write_cols = [c for c in e.columns if c.name not in audit_cols and c.name != "tenant_id"]

    is_update = op == "update"

    prop_lines = []
    imports: set[str] = set()

    for col in write_cols:
        prop_name = camel(col.name)
        php_type = ("?" if col.nullable or is_update else "") + col.php_type
        default = " = null" if col.nullable or is_update else ""

        attrs: list[str] = []
        if col.php_type == "string":
            attrs.append("StringType")
            imports.add("Spatie\\LaravelData\\Attributes\\Validation\\StringType")
        if col.min_length is not None:
            attrs.append(f"Min({col.min_length})")
            imports.add("Spatie\\LaravelData\\Attributes\\Validation\\Min")
        if col.max_length is not None:
            attrs.append(f"Max({col.max_length})")
            imports.add("Spatie\\LaravelData\\Attributes\\Validation\\Max")
        if col.pattern:
            escaped = col.pattern.replace("\\", "\\\\").replace("'", "\\'")
            attrs.append(f"Regex('/{escaped}/')")
            imports.add("Spatie\\LaravelData\\Attributes\\Validation\\Regex")
        attrs_block = f"        #[{', '.join(attrs)}]\n" if attrs else ""
        prop_lines.append(f"{attrs_block}        public {php_type} ${prop_name}{default},")

    props_block = "\n\n".join(prop_lines) if prop_lines else ""
    imports_block = "\n".join(f"use {i};" for i in sorted(imports))

    doc = _php_docblock([
        f"Server-side {op} request DTO for `{e.class_name}`.",
        "",
        f"Consumed by the corresponding Action; validated on construction",
        f"through Spatie Data's property-attribute pipeline (no `rules()`",
        f"method). See `.kiro/steering/data-first.md`.",
        "",
        f"@category {m.studly_name}",
        "",
        "@since    0.1.0",
    ])

    return f"src/Data/Requests/{class_name}.php", f"""<?php

// {AUTOGEN_HEADER.format(tier=m.tier, name=m.name)}

declare(strict_types=1);

namespace {ns};

use Spatie\\LaravelData\\Attributes\\MapInputName;
use Spatie\\LaravelData\\Data;
use Spatie\\LaravelData\\Mappers\\SnakeCaseMapper;
{imports_block}

{doc}
#[MapInputName(SnakeCaseMapper::class)]
final class {class_name} extends Data
{{
    public function __construct(
{props_block}
    ) {{
    }}
}}
"""


# ---------------------------------------------------------------------------
# #[AsSetting] emitter — one Spatie Settings subclass per settings.json group.
# ---------------------------------------------------------------------------

# Blueprint controlType string -> PHP ControlType enum case name.
_CONTROL_TYPE_MAP = {
    "text": "Text",
    "textarea": "Textarea",
    "number": "Number",
    "toggle": "Toggle",
    "select": "Select",
    "multiselect": "Multiselect",
    "color": "Color",
    "file": "File",
    "date": "Date",
    "time": "Time",
    "datetime": "Datetime",
    "timezone": "Timezone",
    "locale": "Locale",
    "currency": "Currency",
    "password": "Password",
    "url": "Url",
    "email": "Email",
    "json": "Json",
    "code": "Code",
    "slider": "Slider",
    "icon": "Icon",
    "css-value": "CssValue",
    "font": "Font",
}


def _infer_php_type(default_value: Any, control_type: str, nullable_from_validation: bool) -> tuple[str, str]:
    """Return `(php_type, formatted_default)` for a settings-field property.

    The property default is the source of truth per `settings.md` §2.
    Validation array may include `nullable` — in which case the type
    is prefixed with `?`.
    """
    if isinstance(default_value, bool):
        base = "bool"
        formatted = "true" if default_value else "false"
    elif isinstance(default_value, int):
        base = "int"
        formatted = str(default_value)
    elif isinstance(default_value, float):
        base = "float"
        formatted = repr(default_value)
    elif isinstance(default_value, str):
        base = "string"
        escaped = default_value.replace("\\", "\\\\").replace("'", "\\'")
        formatted = f"'{escaped}'"
    elif default_value is None:
        # Choose a plausible base type from the control widget, then
        # make it explicitly nullable.
        if control_type in ("number", "slider"):
            base = "int"
        elif control_type in ("toggle",):
            base = "bool"
        elif control_type in ("json", "multiselect"):
            base = "array"
        else:
            base = "string"
        return f"?{base}", "null"
    elif isinstance(default_value, list):
        base = "array"
        # Format PHP array literal — only accept scalar list values.
        elems = []
        for v in default_value:
            if isinstance(v, str):
                esc = v.replace("\\", "\\\\").replace("'", "\\'")
                elems.append(f"'{esc}'")
            elif isinstance(v, bool):
                elems.append("true" if v else "false")
            elif isinstance(v, (int, float)):
                elems.append(str(v))
            else:
                # Complex; fall back to json-encoded string literal.
                elems.append("null")
        formatted = "[" + ", ".join(elems) + "]"
    elif isinstance(default_value, dict):
        base = "array"
        formatted = "[]"
    else:
        base = "mixed"
        formatted = "null"

    if nullable_from_validation:
        return f"?{base}", formatted
    return base, formatted


def _format_php_scalar(value: Any) -> str:
    """PHP-literal representation of a JSON scalar. Used for attribute args."""
    if value is None:
        return "null"
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return repr(value) if isinstance(value, float) else str(value)
    if isinstance(value, str):
        escaped = value.replace("\\", "\\\\").replace("'", "\\'")
        return f"'{escaped}'"
    if isinstance(value, list):
        return "[" + ", ".join(_format_php_scalar(v) for v in value) + "]"
    if isinstance(value, dict):
        pairs = []
        for k, v in value.items():
            key_escaped = str(k).replace("\\", "\\\\").replace("'", "\\'")
            pairs.append(f"'{key_escaped}' => {_format_php_scalar(v)}")
        return "[" + ", ".join(pairs) + "]"
    return "null"


def _format_validation_rules(rules: list[Any]) -> str:
    """Format a validation-rules list as a PHP array literal."""
    if not rules:
        return "[]"
    parts = []
    for r in rules:
        if isinstance(r, str):
            escaped = r.replace("\\", "\\\\").replace("'", "\\'")
            parts.append(f"'{escaped}'")
    return "[" + ", ".join(parts) + "]"


def emit_settings_group(m: Module, group: dict[str, Any], ns_override: str | None = None) -> tuple[str, str] | None:
    """Emit `src/Settings/<Name>Settings.php` for one settings.json group.

    Reads:
      - `group.class`         - FQCN (only last segment used as class name)
      - `group.key`           - Spatie group prefix + `#[AsSetting(group: ...)]`
      - `group.label`         - `#[AsSetting(label: ...)]`
      - `group.description`   - `#[AsSetting(description: ...)]`
      - `group.icon`          - `#[AsSetting(icon: ...)]`
      - `group.scope`         - `#[AsSetting(scope: ...)]`
      - `group.permission`    - `#[AsSetting(permission: ...)]`
      - `group.sortOrder`     - `#[AsSetting(sortOrder: ...)]`
      - `group.sections[]`    - list of {label, description, icon, sortOrder, fields}
      - `group.sections[].fields[]` - list of {name, controlType, label,
                                     defaultValue, validation, options?, min?,
                                     max?, sensitive?, sortOrder, helpText?,
                                     placeholder?}

    Returns None when the group is malformed (missing `class`, empty sections).
    """
    class_fqcn = group.get("class")
    key = group.get("key")
    if not class_fqcn or not isinstance(class_fqcn, str) or not key:
        return None

    # Use only the class name from the FQCN; the namespace comes from the
    # module's `ns_module_root` (matches its composer autoload) rather than
    # the blueprint's FQCN prefix (which for ~half the modules encodes a
    # tier-nested convention the generator retired earlier).
    class_name = class_fqcn.rsplit("\\", 1)[-1]
    # The module.json `namespace` field is authoritative — it matches the
    # module's composer.json PSR-4 autoload. Real-impl packages often use
    # tier-prefixed namespaces (`Academorix\Notifications\Mail`) which the
    # generator's `ns_module_root` (`Academorix\NotificationsMail`) does not
    # produce. Callers pass the resolved namespace via `ns_override`.
    module_ns = ns_override or m.ns_module_root
    ns = f"{module_ns}\\Settings"

    sections = group.get("sections") or []
    if not isinstance(sections, list) or not sections:
        return None

    # --- #[AsSetting(...)] on the class ---
    as_setting_args = [
        f"group: '{key}'",
        f"label: '{str(group.get('label', key)).replace(chr(39), chr(92)+chr(39))}'",
    ]
    desc = group.get("description")
    if isinstance(desc, str) and desc.strip():
        as_setting_args.append(
            f"description: '{desc.replace(chr(92), chr(92)+chr(92)).replace(chr(39), chr(92)+chr(39))}'"
        )
    icon = group.get("icon")
    if isinstance(icon, str) and icon.strip():
        as_setting_args.append(f"icon: '{icon}'")
    scope = group.get("scope")
    if isinstance(scope, str) and scope.strip():
        as_setting_args.append(f"scope: '{scope}'")
    perm = group.get("permission")
    if isinstance(perm, str) and perm.strip():
        as_setting_args.append(f"permission: '{perm}'")
    sort_order = group.get("sortOrder")
    if isinstance(sort_order, int):
        as_setting_args.append(f"sortOrder: {sort_order}")
    as_setting_line = "#[AsSetting(\n    " + ",\n    ".join(as_setting_args) + ",\n)]"

    # --- Build property list section-by-section ---
    prop_blocks: list[str] = []
    has_options = False  # Whether any field carries `options` (for use import decisions).

    for section in sections:
        if not isinstance(section, dict):
            continue
        section_label = section.get("label", "")
        section_desc = section.get("description", "")
        section_icon = section.get("icon", "")
        section_sort = section.get("sortOrder", 0)
        section_group = section_label  # Used as `#[SettingField(group: ...)]` value.
        fields = section.get("fields") or []
        if not isinstance(fields, list) or not fields:
            continue

        first_in_section = True
        for field in fields:
            if not isinstance(field, dict):
                continue
            field_name = field.get("name")
            if not field_name or not isinstance(field_name, str):
                continue
            control_type = field.get("controlType", "text")
            control_enum_case = _CONTROL_TYPE_MAP.get(control_type, "Text")
            label = field.get("label", field_name)
            default_value = field.get("defaultValue")
            validation = field.get("validation") or []
            if not isinstance(validation, list):
                validation = []
            nullable = "nullable" in validation
            options = field.get("options")
            if options:
                has_options = True
            min_val = field.get("min")
            max_val = field.get("max")
            sensitive = bool(field.get("sensitive", False))
            field_sort = field.get("sortOrder", 0)
            help_text = field.get("helpText")
            placeholder = field.get("placeholder")

            php_type, php_default = _infer_php_type(default_value, control_type, nullable)

            # --- Build #[SettingField(...)] args ---
            sf_args = [
                f"controlType: ControlType::{control_enum_case}",
                f"label: {_format_php_scalar(label)}",
            ]
            if validation:
                sf_args.append(f"validation: {_format_validation_rules(validation)}")
            if section_group:
                sf_args.append(f"group: {_format_php_scalar(section_group)}")
            if isinstance(field_sort, int):
                sf_args.append(f"sortOrder: {field_sort}")
            if options and isinstance(options, dict):
                sf_args.append(f"options: {_format_php_scalar(options)}")
            if min_val is not None:
                sf_args.append(f"min: {_format_php_scalar(min_val)}")
            if max_val is not None:
                sf_args.append(f"max: {_format_php_scalar(max_val)}")
            if sensitive:
                sf_args.append("sensitive: true")
            if help_text:
                sf_args.append(f"helpText: {_format_php_scalar(help_text)}")
            if placeholder:
                sf_args.append(f"placeholder: {_format_php_scalar(placeholder)}")
            sf_line = "    #[SettingField(" + ", ".join(sf_args) + ")]"

            block_lines: list[str] = []

            # Section header on the first field of each section.
            if first_in_section:
                block_lines.append("")
                block_lines.append(
                    f"    // ── {section_label} ──────────────────────────────────"
                )
                sg_args = [f"label: {_format_php_scalar(section_label)}"]
                if section_desc:
                    sg_args.append(f"description: {_format_php_scalar(section_desc)}")
                if section_icon:
                    sg_args.append(f"icon: {_format_php_scalar(section_icon)}")
                if isinstance(section_sort, int):
                    sg_args.append(f"sortOrder: {section_sort}")
                block_lines.append(
                    "    #[SettingGroup(" + ", ".join(sg_args) + ")]"
                )
                first_in_section = False

            block_lines.append(sf_line)
            block_lines.append(f"    public {php_type} ${field_name} = {php_default};")
            prop_blocks.append("\n".join(block_lines))

    if not prop_blocks:
        return None
    props_body = "\n\n".join(prop_blocks)

    # --- Class docblock ---
    class_doc = _php_docblock([
        f"{class_name} — {group.get('label', key)}.",
        "",
        _first_sentence(group.get("description", ""), 200)
        or f"Attribute-driven settings group for `{key}`.",
        "",
        f"Every field is a public typed property; the property default IS",
        f"the source of truth (§2 of the `settings` steering rule). Storage",
        f"goes through `Scope::write('settings', ...)` — never a bespoke",
        f"`settings_values` table.",
        "",
        f"@category {m.studly_name}",
        "",
        "@since    0.1.0",
    ])

    body = f"""<?php

// {AUTOGEN_HEADER.format(tier=m.tier, name=m.name)}

declare(strict_types=1);

namespace {ns};

use Academorix\\Settings\\Attributes\\AsSetting;
use Academorix\\Settings\\Attributes\\SettingField;
use Academorix\\Settings\\Attributes\\SettingGroup;
use Academorix\\Settings\\Enums\\ControlType;
use Spatie\\LaravelSettings\\Settings;

{class_doc}
{as_setting_line}
class {class_name} extends Settings
{{
{props_body}

    /**
     * Return the Spatie Settings group identifier.
     *
     * @return string The settings group key.
     */
    public static function group(): string
    {{
        return '{key}';
    }}
}}
"""
    return f"src/Settings/{class_name}.php", body


# ---------------------------------------------------------------------------
# Test scaffolds.
# ---------------------------------------------------------------------------

def emit_pest_bootstrap(m: Module) -> str:
    return """<?php

declare(strict_types=1);

use Illuminate\\Foundation\\Testing\\TestCase as BaseTestCase;

uses(BaseTestCase::class)->in('Feature');
uses(BaseTestCase::class)->in('Unit');
"""


def emit_test_case(m: Module) -> str:
    ns = f"{m.ns_module_root}\\Tests"
    return f"""<?php

declare(strict_types=1);

namespace {ns};

use Orchestra\\Testbench\\TestCase as OrchestraTestCase;

/**
 * Base test case for {m.composer_module_name}.
 *
 * @category {m.studly_name}
 *
 * @since    0.1.0
 */
abstract class TestCase extends OrchestraTestCase
{{
    // Add package providers here if the module's tests need Laravel container
    // access beyond Orchestra's defaults.
}}
"""


def emit_unit_test_stub(m: Module, e: Entity) -> str:
    return f"""<?php

declare(strict_types=1);

use {m.ns_module_root}\\Models\\{e.class_name};

it('is a placeholder — replace with actual {e.class_name} unit tests', function (): void {{
    expect({e.class_name}::class)->toBeString();
}});
"""


# ---------------------------------------------------------------------------
# Package writer.
# ---------------------------------------------------------------------------

def write_module(m: Module, out_root: Path, *, force: bool, dry_run: bool) -> tuple[int, int]:
    """Emit the complete server-side module package."""
    pkg_dir = out_root / m.module_pkg_path

    if pkg_dir.exists() and not force and not dry_run:
        raise SystemExit(
            f"{pkg_dir} already exists — use --force to overwrite, or --into to emit elsewhere"
        )

    files: list[tuple[str, str]] = []

    # Static top-level files.
    files.append(("composer.json", emit_composer_json(m)))
    files.append(("phpstan.neon", emit_phpstan_neon()))
    files.append(("phpunit.xml", emit_phpunit_xml()))
    files.append(("README.md", emit_readme(m)))

    # Service provider.
    files.append((
        f"src/Providers/{m.studly_name}ServiceProvider.php",
        emit_service_provider(m),
    ))

    # Migrations — one per entity. Use a shared base timestamp so relative
    # ordering matches entity discovery order.
    _reset_migration_sequence()
    base_ts = datetime(2026, 7, 15, 12, 0, 0)
    for e in m.entities:
        ts_str = _next_migration_timestamp(base_ts)
        filename, body = emit_migration(m, e, ts_str)
        files.append((f"database/migrations/{filename}", body))

    # Per-entity: interface, model, repo interface, repo, data, factory.
    for e in m.entities:
        files.append((f"src/Contracts/Data/{e.class_name}Interface.php", emit_model_interface(m, e)))
        files.append((f"src/Models/{e.class_name}.php", emit_model(m, e)))
        files.append((f"src/Contracts/Repositories/{e.class_name}RepositoryInterface.php", emit_repository_interface(m, e)))
        files.append((f"src/Repositories/{e.class_name}Repository.php", emit_repository(m, e)))
        files.append((f"src/Data/{e.class_name}Data.php", emit_data_dto(m, e)))
        files.append((f"database/factories/{e.class_name}Factory.php", emit_factory(m, e)))

    # Policies from policies.json.
    module_dir = module_dir_path(m.tier, m.name)
    policies = _load_aux(module_dir, "policies.json").get("policies", []) or []
    entities_by_model = {e.class_name: e for e in m.entities}
    for pol in policies:
        model_name = pol.get("model")
        if not model_name:
            continue
        entity = entities_by_model.get(model_name)
        if entity is None:
            continue
        files.append((f"src/Policies/{entity.class_name}Policy.php", emit_policy(m, entity, pol)))

    # Events from events.json.
    events = _load_aux(module_dir, "events.json").get("events", []) or []
    seen_events: set[str] = set()
    for event in events:
        if not isinstance(event, dict):
            continue
        name = event.get("name")
        if not name or name in seen_events:
            continue
        seen_events.add(name)
        path, body = emit_event(m, event)
        files.append((path, body))

    # Actions from routes (audience-split, dedupe by class name).
    seen_actions: set[str] = set()
    for route in m.routes:
        if route.op == "custom" or route.op in ("create", "update", "delete", "list", "show"):
            path, body = emit_action(m, route)
            if path in seen_actions:
                continue
            seen_actions.add(path)
            files.append((path, body))

    # Enums — one per closed-set column across every entity.
    for e in m.entities:
        for enum_path, enum_body in emit_enums(m, e):
            files.append((enum_path, enum_body))

    # Request DTOs — one per create/update route per entity.
    for e in m.entities:
        for op in ("create", "update"):
            has_op = any(
                r.op == op and r.aggregate == e.aggregate for r in m.routes
            )
            if not has_op:
                continue
            path, body = emit_request_data(m, e, op)
            files.append((path, body))

    # Exceptions from errors.json.
    errors_raw = _load_aux(module_dir, "errors.json")
    errors_list = errors_raw.get("errors") or errors_raw.get("classes") or []
    for err in errors_list:
        if not isinstance(err, dict):
            continue
        emitted = emit_exception(m, err)
        if emitted is None:
            continue
        files.append(emitted)

    # Console commands from module.json → contributes.commands.
    module_json_path = module_dir / "module.json"
    module_json = json.loads(module_json_path.read_text())
    contributes = module_json.get("contributes", {}) or {}
    for cmd_signature in contributes.get("commands", []) or []:
        if not isinstance(cmd_signature, str):
            continue
        files.append(emit_console_command(m, cmd_signature))

    # Jobs from module.json → contributes.jobs.
    for job_name in contributes.get("jobs", []) or []:
        if not isinstance(job_name, str):
            continue
        files.append(emit_job(m, job_name))

    # Services + service contracts from module.json → contributes.bindings.
    # Skip anything ending in `Repository` / `RepositoryInterface` — already
    # emitted per entity from schemas.
    for binding_name in contributes.get("bindings", []) or []:
        if not isinstance(binding_name, str):
            continue
        if binding_name.endswith("Repository") or binding_name.endswith("RepositoryInterface"):
            continue
        files.append(emit_service_interface(m, binding_name))
        files.append(emit_service_concrete(m, binding_name))

    # Traits (concerns) from module.json → contributes.traits.
    for trait_name in contributes.get("traits", []) or []:
        if not isinstance(trait_name, str):
            continue
        files.append(emit_trait(m, trait_name))

    # PHP attributes from module.json → contributes.attributes.
    for attr_name in contributes.get("attributes", []) or []:
        if not isinstance(attr_name, str):
            continue
        files.append(emit_php_attribute(m, attr_name))

    # #[AsSetting] classes from settings.json → groups[].
    # The composer.json PSR-4 autoload prefix is the ground truth for the
    # module's namespace root — real-impl packages carry tier-prefixed
    # namespaces the generator's `ns_module_root` does not compute. When the
    # composer.json is emitted by the generator it uses `ns_module_root`;
    # when the composer.json is hand-tuned it may declare a different prefix
    # (like `Academorix\Notifications\Mail\` for notifications-mail).
    # Either way, the settings namespace must match the autoload prefix so
    # PSR-4 resolves the emitted class.
    module_ns_override: str | None = None
    composer_path = pkg_dir / "composer.json"
    if composer_path.is_file():
        try:
            composer_data = json.loads(composer_path.read_text())
            psr4 = composer_data.get("autoload", {}).get("psr-4", {})
            for prefix in psr4:
                trimmed = prefix.rstrip("\\")
                # Prefer the shortest prefix (the root); skip nested keys
                # like `<Ns>\Database\Factories\`.
                if module_ns_override is None or len(trimmed) < len(module_ns_override):
                    if "Database" not in trimmed and "Tests" not in trimmed:
                        module_ns_override = trimmed
        except json.JSONDecodeError:
            pass

    settings_raw = _load_aux(module_dir, "settings.json")
    settings_groups_raw = settings_raw.get("groups") or settings_raw.get("settings") or []
    if isinstance(settings_groups_raw, list):
        for group in settings_groups_raw:
            if not isinstance(group, dict):
                continue
            emitted = emit_settings_group(m, group, ns_override=module_ns_override)
            if emitted is None:
                continue
            files.append(emitted)

    # Test scaffolds.
    files.append(("tests/Pest.php", emit_pest_bootstrap(m)))
    files.append(("tests/TestCase.php", emit_test_case(m)))
    files.append(("tests/Feature/.gitkeep", ""))
    files.append(("tests/Unit/.gitkeep", ""))
    for e in m.entities:
        files.append((f"tests/Unit/{e.class_name}Test.php", emit_unit_test_stub(m, e)))

    written = 0
    skipped = 0
    for rel, body in files:
        target = pkg_dir / rel
        if dry_run:
            print(f"  would write: {target.relative_to(out_root)}")
            written += 1
            continue
        target.parent.mkdir(parents=True, exist_ok=True)
        # Preserve hand-tuned files (no AUTO-GENERATED header) on --force.
        if target.exists() and force and target.name != ".gitkeep":
            existing = target.read_text()
            if "AUTO-GENERATED by generate-module.py" not in existing and existing.strip():
                skipped += 1
                continue
        target.write_text(body)
        written += 1
    return written, skipped


# ---------------------------------------------------------------------------
# Main.
# ---------------------------------------------------------------------------

def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("tier", help="Module tier (e.g. platform, sports, finance).")
    parser.add_argument("name", help="Module name (e.g. forms, registrations, tenants).")
    parser.add_argument("--force", action="store_true", help="Overwrite existing generated files.")
    parser.add_argument("--dry-run", action="store_true", help="Print intended writes; don't touch disk.")
    parser.add_argument(
        "--into",
        default=str(REPO_ROOT),
        help="Alternate output root (for round-trip diff testing).",
    )
    args = parser.parse_args(argv)

    module = read_module(args.tier, args.name)
    print(
        f"Loaded blueprint: tier={args.tier}, name={args.name}, "
        f"entities={len(module.entities)}, routes={len(module.routes)}"
    )

    out_root = Path(args.into)
    written, skipped = write_module(module, out_root, force=args.force, dry_run=args.dry_run)
    print(f"Wrote {written} file(s); skipped {skipped} hand-tuned file(s).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
