<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py finance gateway --force`.

declare(strict_types=1);

namespace Stackra\Gateway\Enums;

use Stackra\Enum\Enum;

/**
 * Closed-set enum for `owner_type` on `payment-method`.
 *
 * Polymorphic: guardian / tenant.
 *
 * @category Gateway
 *
 * @since    0.1.0
 */
enum PaymentMethodOwnerType: string
{
    use Enum;

    case Guardian = 'guardian';
    case Tenant = 'tenant';
}
