<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py growth referrals --force`.

declare(strict_types=1);

namespace Stackra\Referrals\Actions\Platform;

use Stackra\Referrals\Contracts\Repositories\ReferralFraudFlagRepositoryInterface;
use Stackra\Referrals\Data\ReferralFraudFlagData;
use Stackra\Routing\Attributes\AsAction;
use Stackra\Routing\Attributes\Middleware;
use Stackra\Routing\Concerns\AsController;
use Stackra\Routing\Attributes\Get;
use Illuminate\Http\Request;
use Illuminate\Pagination\LengthAwarePaginator;
use Spatie\LaravelData\PaginatedDataCollection;

/**
 * `GET /api/v1/platform/referral-fraud-flags` — list action (platform-admin audience).
 *
 * Single-invoke controller wired via `#[AsAction]` + `#[Get(...)]`
 * + `#[Middleware(...)]` from `Stackra\Routing`. Discovered by the routing
 * package's boot-time `RouteRegistrar` — no route file needed.
 *
 * @category Referrals
 *
 * @since    0.1.0
 */
#[AsAction(name: 'referrals.referral_fraud_flags.list')]
#[Get('/api/v1/platform/referral-fraud-flags')]
#[Middleware(['api', 'auth:sanctum', 'platform_admin'])]
final class ListReferralFraudFlagAction
{
    use AsController;

    public function __construct(
        private readonly ReferralFraudFlagRepositoryInterface $repository,
    ) {
    }

    /**
     * List `referral-fraud-flags` for the current caller.
     *
     * The `Repository` base picks up `filter[...]` / `sort=...` /
     * `include=...` query parameters via the `#[Filterable]` attribute
     * on the concrete repository — no per-Action wiring needed.
     *
     * @return PaginatedDataCollection<int, ReferralFraudFlagData>  Paginated wire-visible DTOs.
     */
    public function __invoke(Request $request): PaginatedDataCollection
    {
        /** @var LengthAwarePaginator<int, \Stackra\Referrals\Models\ReferralFraudFlag> $page */
        $page = $this->repository->paginate(
            perPage: (int) $request->integer('per_page', 15),
        );

        return ReferralFraudFlagData::collect($page, PaginatedDataCollection::class);
    }
}
