<?php

/**
 * @file database/migrations/2026_07_15_120003_create_xfer_shards_table.php
 *
 * @description
 * Create the `xfer_shards` table for the `XferShard` entity.
 * Owned by the transfer module. Emitted from the module blueprint —
 * regenerate via `generate-module.py shared transfer --force`.
 */
// // AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py shared transfer --force`.

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class() extends Migration {
    /**
     * Run the migration.
     */
    public function up(): void
    {
        Schema::create('xfer_shards', function (Blueprint $table): void {
            $table->string('id', 64)->primary();
            $table->string('xfer_job_id', 64);
            $table->foreign('xfer_job_id')->references('id')->on('xfer_jobs')->onDelete('cascade');
            $table->string('tenant_id', 64)->nullable();
            $table->foreign('tenant_id')->references('id')->on('tenants')->onDelete('cascade');
            $table->integer('index');
            $table->string('sheet_name', 128)->nullable();
            $table->integer('offset')->nullable();
            $table->integer('limit')->nullable();
            $table->string('status', 32)->default('queued');
            $table->jsonb('counters')->default('{"total":0,"created":0,"updated":0,"skipped":0,"failed":0,"deleted":0}');
            $table->integer('attempt')->default('1');
            $table->timestampTz('started_at')->nullable();
            $table->timestampTz('finished_at')->nullable();
            $table->text('error_message')->nullable();
            $table->string('error_code', 64)->nullable();
            $table->timestampTz('created_at');
            $table->timestampTz('updated_at');
            $table->unique(['xfer_job_id', 'index'], 'xfer_shards_job_index_uniq_idx');
            $table->index(['xfer_job_id', 'status'], 'xfer_shards_job_status_idx');
            $table->index(['status', 'started_at'], 'xfer_shards_status_time_idx');
        });
    }

    /**
     * Reverse the migration.
     */
    public function down(): void
    {
        Schema::dropIfExists('xfer_shards');
    }
};
