<?php

/**
 * @file database/migrations/2026_07_15_120001_create_xfer_jobs_table.php
 *
 * @description
 * Create the `xfer_jobs` table for the `XferJob` entity.
 * Owned by the transfer module. Emitted from the module blueprint —
 * regenerate via `generate-module.py shared transfer --force`.
 */
// // AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py shared transfer --force`.

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class() extends Migration {
    /**
     * Run the migration.
     */
    public function up(): void
    {
        Schema::create('xfer_jobs', function (Blueprint $table): void {
            $table->string('id', 64)->primary();
            $table->string('tenant_id', 64)->nullable();
            $table->foreign('tenant_id')->references('id')->on('tenants')->onDelete('cascade');
            $table->string('causer_type', 128);
            $table->string('causer_id', 64);
            $table->string('kind', 16);
            $table->string('entity', 128);
            $table->string('mode', 16)->nullable();
            $table->string('format', 16)->nullable();
            $table->string('status', 32)->default('queued');
            $table->jsonb('counters')->default('{"total":0,"created":0,"updated":0,"skipped":0,"failed":0,"deleted":0}');
            $table->jsonb('params')->nullable();
            $table->jsonb('filters')->nullable();
            $table->string('mapping_profile_id', 64)->nullable();
            $table->foreign('mapping_profile_id')->references('id')->on('xfer_mapping_profiles')->onDelete('set null');
            $table->string('source_filename', 255)->nullable();
            $table->unsignedBigInteger('source_file_size_bytes')->nullable();
            $table->string('source_file_hash', 64)->nullable();
            $table->string('source_artifact_id', 64)->nullable();
            $table->foreign('source_artifact_id')->references('id')->on('xfer_artifacts')->onDelete('set null');
            $table->string('result_artifact_id', 64)->nullable();
            $table->foreign('result_artifact_id')->references('id')->on('xfer_artifacts')->onDelete('set null');
            $table->string('errors_artifact_id', 64)->nullable();
            $table->foreign('errors_artifact_id')->references('id')->on('xfer_artifacts')->onDelete('set null');
            $table->jsonb('notify_channels')->default('["database","broadcast"]');
            $table->string('notify_locale', 8)->default('en');
            $table->string('retention_tier', 16)->default('short');
            $table->string('queue_connection', 64)->nullable();
            $table->string('queue_name', 64)->default('transfer');
            $table->uuid('laravel_queue_batch_id')->nullable();
            $table->integer('shards_total')->default('1');
            $table->integer('shards_completed')->default('0');
            $table->integer('progress_percent')->default('0');
            $table->timestampTz('started_at')->nullable();
            $table->timestampTz('finished_at')->nullable();
            $table->timestampTz('last_progress_at')->nullable();
            $table->timestampTz('artifact_purged_at')->nullable();
            $table->text('last_error_message')->nullable();
            $table->string('last_error_code', 64)->nullable();
            $table->string('cancelled_by_type', 128)->nullable();
            $table->string('cancelled_by_id', 64)->nullable();
            $table->string('cancel_reason', 255)->nullable();
            $table->timestampTz('created_at');
            $table->timestampTz('updated_at');
            $table->timestampTz('deleted_at')->nullable();
            $table->index(['tenant_id', 'created_at'], 'xfer_jobs_tenant_time_idx');
            $table->index(['causer_type', 'causer_id', 'created_at'], 'xfer_jobs_causer_time_idx');
            $table->index(['status', 'created_at'], 'xfer_jobs_status_time_idx');
            $table->index(['kind', 'entity', 'created_at'], 'xfer_jobs_kind_entity_time_idx');
            $table->index(['retention_tier', 'created_at'], 'xfer_jobs_retention_scan_idx');
            $table->index(['last_progress_at'], 'xfer_jobs_progress_scan_idx');
            // Partial-index predicate — hand-add via DB::statement: WHERE status = 'running'
            $table->unique(['laravel_queue_batch_id'], 'xfer_jobs_batch_uniq_idx');
            // Partial-index predicate — hand-add via DB::statement: WHERE laravel_queue_batch_id IS NOT NULL
        });
    }

    /**
     * Reverse the migration.
     */
    public function down(): void
    {
        Schema::dropIfExists('xfer_jobs');
    }
};
