<?php

// // AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py shared geography --force`.

declare(strict_types=1);

namespace Academorix\Shared\Geography\Models;

use Illuminate\Database\Eloquent\Attributes\Fillable;
use Illuminate\Database\Eloquent\Attributes\Table;
use Illuminate\Database\Eloquent\Attributes\UseFactory;
use Illuminate\Database\Eloquent\Model;
use Academorix\Shared\Geography\Contracts\Data\StateInterface;
use Academorix\Shared\Geography\Database\Factories\StateFactory;
use Academorix\Foundation\Concerns\Filterable;
use Illuminate\Database\Eloquent\Factories\HasFactory;

/**
 * Eloquent model for a State.
 *
 * ISO-3166-2 state / province / region row.
 *
 * @category Geography
 *
 * @since    0.1.0
 */
#[Table(name: StateInterface::TABLE, keyType: StateInterface::KEY_TYPE)]
#[Fillable([
    StateInterface::ATTR_COUNTRY_ID,
        StateInterface::ATTR_NAME,
        StateInterface::ATTR_COUNTRY_CODE,
        StateInterface::ATTR_STATE_CODE,
        StateInterface::ATTR_TYPE,
        StateInterface::ATTR_LATITUDE,
        StateInterface::ATTR_LONGITUDE,
])]
#[UseFactory(StateFactory::class)]
final class State extends Model implements StateInterface
{
    use HasFactory;
    use Filterable;

    /**
     * The primary key IS a string (prefixed ULID); disable auto-increment.
     *
     * @var bool
     */
    public $incrementing = false;

}
