<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py identity service-accounts --force`.

declare(strict_types=1);

namespace Stackra\ServiceAccounts\Actions\Platform;

use Stackra\Routing\Attributes\AsAction;
use Stackra\Routing\Attributes\Middleware;
use Stackra\Routing\Concerns\AsController;
use Stackra\Routing\Attributes\Get;

/**
 * `GET /api/v1/platform/service-accounts/{serviceAccount}/audit-usage` — custom action (platform-admin audience).
 *
 * Single-invoke controller wired via `#[AsAction]` + `#[Get(...)]`
 * + `#[Middleware(...)]` from `Stackra\Routing`. Discovered by the routing
 * package's boot-time `RouteRegistrar` — no route file needed.
 *
 * @category ServiceAccounts
 *
 * @since    0.1.0
 */
#[AsAction(name: 'service_accounts.audit_usage.audit_usage')]
#[Get('/api/v1/platform/service-accounts/{serviceAccount}/audit-usage')]
#[Middleware(['api', 'auth:sanctum', 'platform_admin'])]
final class AuditUsageAction
{
    use AsController;

    /**
     * Execute the action.
     *
     * TODO(gen): wire the required services + implement the handler body.
     */
    public function __invoke(): mixed
    {
        // Hand-implement the domain logic here.
        return null;
    }
}
