<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py identity service-accounts --force`.

declare(strict_types=1);

namespace Academorix\ServiceAccounts\Actions\Platform;

use Academorix\Routing\Attributes\AsAction;
use Academorix\Routing\Attributes\Middleware;
use Academorix\Routing\Concerns\AsController;
use Academorix\Routing\Attributes\Post;

/**
 * `POST /api/v1/platform/service-accounts/{serviceAccount}/rotate-secret` — custom action (platform-admin audience).
 *
 * Single-invoke controller wired via `#[AsAction]` + `#[Post(...)]`
 * + `#[Middleware(...)]` from `Academorix\Routing`. Discovered by the routing
 * package's boot-time `RouteRegistrar` — no route file needed.
 *
 * @category ServiceAccounts
 *
 * @since    0.1.0
 */
#[AsAction(name: 'service_accounts.rotate_secret.rotate_secret')]
#[Post('/api/v1/platform/service-accounts/{serviceAccount}/rotate-secret')]
#[Middleware(['api', 'auth:sanctum', 'platform_admin'])]
final class RotateSecretAction
{
    use AsController;

    /**
     * Execute the action.
     *
     * TODO(gen): wire the required services + implement the handler body.
     */
    public function __invoke(): mixed
    {
        // Hand-implement the domain logic here.
        return null;
    }
}
