<?php

/**
 * @file database/migrations/2026_07_15_120000_create_analytics_deliveries_table.php
 *
 * @description
 * Create the `analytics_deliveries` table for the `AnalyticsDelivery` entity.
 * Owned by the analytics module. Emitted from the module blueprint —
 * regenerate via `generate-module.py growth analytics --force`.
 */
// // AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py growth analytics --force`.

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class() extends Migration {
    /**
     * Run the migration.
     */
    public function up(): void
    {
        Schema::create('analytics_deliveries', function (Blueprint $table): void {
            $table->string('id', 30)->primary();
            $table->string('tenant_id', 30);
            $table->foreign('tenant_id')->references('id')->on('tenants')->onDelete('cascade');
            $table->string('analytics_event_id', 30);
            $table->foreign('analytics_event_id')->references('id')->on('analytics_events')->onDelete('restrict');
            $table->string('analytics_provider_config_id', 30)->nullable();
            $table->foreign('analytics_provider_config_id')->references('id')->on('analytics_provider_configs')->onDelete('set null');
            $table->string('provider', 32);
            $table->string('status', 32)->default('pending');
            $table->integer('attempt_number')->default(1);
            $table->jsonb('request_payload')->nullable();
            $table->jsonb('response')->nullable();
            $table->integer('response_http_status')->nullable();
            $table->integer('latency_ms')->nullable();
            $table->string('error_code', 64)->nullable();
            $table->text('error_message')->nullable();
            $table->timestampTz('next_retry_at')->nullable();
            $table->timestampTz('sent_at')->nullable();
            $table->string('batch_id', 30)->nullable();
            $table->jsonb('metadata')->nullable();
            $table->timestampTz('created_at');
            $table->timestampTz('updated_at');
            $table->index(['analytics_event_id', 'provider'], 'analytics_deliveries_event_provider_idx');
            $table->index(['tenant_id', 'provider', 'created_at'], 'analytics_deliveries_tenant_provider_time_idx');
            $table->index(['tenant_id', 'status', 'next_retry_at'], 'analytics_deliveries_retry_sweep_idx');
            // Partial-index predicate — hand-add via DB::statement: WHERE status IN ('failed', 'rate_limited') AND next_retry_at IS NOT NULL
            $table->index(['batch_id'], 'analytics_deliveries_batch_idx');
            // Partial-index predicate — hand-add via DB::statement: WHERE batch_id IS NOT NULL
        });
    }

    /**
     * Reverse the migration.
     */
    public function down(): void
    {
        Schema::dropIfExists('analytics_deliveries');
    }
};
