<?php

/**
 * @file database/migrations/2026_07_15_120003_create_analytics_provider_configs_table.php
 *
 * @description
 * Create the `analytics_provider_configs` table for the `AnalyticsProviderConfig` entity.
 * Owned by the analytics module. Every column + index reference
 * goes through {@see Academorix\Analytics\Contracts\Data\AnalyticsProviderConfigInterface} per the `models` steering
 * rule §1 — no raw string literals.
 */
// // AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py growth analytics --force`.

declare(strict_types=1);

use Academorix\Analytics\Contracts\Data\AnalyticsProviderConfigInterface;
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

return new class() extends Migration {
    /**
     * Run the migration.
     */
    public function up(): void
    {
        Schema::create(AnalyticsProviderConfigInterface::TABLE, function (Blueprint $table): void {
            $table->string(AnalyticsProviderConfigInterface::ATTR_ID, 30)->primary();
            $table->string(AnalyticsProviderConfigInterface::ATTR_TENANT_ID, 30);
            $table->foreign(AnalyticsProviderConfigInterface::ATTR_TENANT_ID)->references('id')->on('tenants')->onDelete('cascade');
            $table->string(AnalyticsProviderConfigInterface::ATTR_PROVIDER, 32);
            $table->string(AnalyticsProviderConfigInterface::ATTR_NAME, 128);
            $table->boolean(AnalyticsProviderConfigInterface::ATTR_IS_ACTIVE)->default(true);
            $table->text(AnalyticsProviderConfigInterface::ATTR_CONFIG);
            $table->jsonb(AnalyticsProviderConfigInterface::ATTR_ENABLED_EVENT_TYPES)->default('\'["track:*", "identify", "page", "screen", "alias", "group"]\'::jsonb');
            $table->decimal(AnalyticsProviderConfigInterface::ATTR_SAMPLING_RATE, 15, 4)->default(1.0);
            $table->jsonb(AnalyticsProviderConfigInterface::ATTR_SAMPLING_RULES)->default('\'[]\'::jsonb');
            $table->jsonb(AnalyticsProviderConfigInterface::ATTR_BATCH_CONFIG)->default('\'{"size": 100, "flush_interval_ms": 5000, "max_bytes": 500000}\'::jsonb');
            $table->jsonb(AnalyticsProviderConfigInterface::ATTR_CIRCUIT_BREAKER_CONFIG)->default('\'{"threshold": 5, "failure_rate": 0.2, "window_seconds": 60, "half_open_probe_interval_seconds": 60, "close_after_successes": 3}\'::jsonb');
            $table->jsonb(AnalyticsProviderConfigInterface::ATTR_CIRCUIT_BREAKER_STATE)->default('\'{"state": "closed", "failures": 0, "successes": 0, "opened_at": null, "half_opened_at": null}\'::jsonb');
            $table->jsonb(AnalyticsProviderConfigInterface::ATTR_RETRY_CONFIG)->default('\'{"max_attempts": 5, "backoff_ms": [1000, 5000, 30000, 300000, 3600000], "retry_on_status": [408, 429, 500, 502, 503, 504]}\'::jsonb');
            $table->boolean(AnalyticsProviderConfigInterface::ATTR_TEST_MODE)->default(false);
            $table->text(AnalyticsProviderConfigInterface::ATTR_NOTES)->nullable();
            $table->timestampTz(AnalyticsProviderConfigInterface::ATTR_LAST_SUCCESS_AT)->nullable();
            $table->timestampTz(AnalyticsProviderConfigInterface::ATTR_LAST_FAILURE_AT)->nullable();
            $table->jsonb(AnalyticsProviderConfigInterface::ATTR_METADATA)->nullable();
            $table->uuid(AnalyticsProviderConfigInterface::ATTR_CREATED_BY)->nullable();
            $table->uuid(AnalyticsProviderConfigInterface::ATTR_UPDATED_BY)->nullable();
            $table->uuid(AnalyticsProviderConfigInterface::ATTR_DELETED_BY)->nullable();
            $table->timestampTz(AnalyticsProviderConfigInterface::ATTR_DELETED_AT)->nullable();
            $table->timestampTz(AnalyticsProviderConfigInterface::ATTR_CREATED_AT);
            $table->timestampTz(AnalyticsProviderConfigInterface::ATTR_UPDATED_AT);
            $table->index([AnalyticsProviderConfigInterface::ATTR_TENANT_ID, AnalyticsProviderConfigInterface::ATTR_PROVIDER, AnalyticsProviderConfigInterface::ATTR_IS_ACTIVE], 'analytics_provider_configs_tenant_provider_active_idx');
        });

        DB::statement('CREATE UNIQUE INDEX analytics_provider_configs_tenant_name_uidx ON ' . AnalyticsProviderConfigInterface::TABLE . ' (' . AnalyticsProviderConfigInterface::ATTR_TENANT_ID . ', ' . AnalyticsProviderConfigInterface::ATTR_NAME . ') WHERE deleted_at IS NULL');
    }

    /**
     * Reverse the migration.
     */
    public function down(): void
    {
        Schema::dropIfExists(AnalyticsProviderConfigInterface::TABLE);
    }
};
