<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py platform facility --force`.

declare(strict_types=1);

namespace Academorix\Facility\Console;

use Academorix\Console\Attributes\AsCommand;
use Academorix\Console\Console\Commands\BaseCommand;

/**
 * `php artisan booking:mark-no-show` — Mark no show — booking command.
 *
 * @category Facility
 *
 * @since    0.1.0
 */
#[AsCommand(
    name: 'booking:mark-no-show',
    description: 'Mark no show — booking command.',
)]
final class MarkNoShowCommand extends BaseCommand
{
    /**
     * Execute the command.
     *
     * TODO(gen): wire the required services + implement the handler body.
     */
    public function handle(): int
    {
        $this->omni->titleBar('Mark no show — booking command', 'sky');

        // TODO(gen): wire the required services + implement the handler body.

        $this->omni->success('Mark no show — booking command completed.');
        $this->showDuration();

        return self::SUCCESS;
    }
}
