<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py platform tenancy --force`.

declare(strict_types=1);

namespace Academorix\Tenancy\Console;

use Academorix\Console\Attributes\AsCommand;
use Academorix\Console\Commands\BaseCommand;

/**
 * `php artisan tenancy:hard-delete-archived` — Hard delete archived — tenancy command.
 *
 * @category Tenancy
 *
 * @since    0.1.0
 */
#[AsCommand(
    name: 'tenancy:hard-delete-archived',
    description: 'Hard delete archived — tenancy command.',
)]
final class HardDeleteArchivedCommand extends BaseCommand
{
    /**
     * Execute the command.
     *
     * TODO(gen): wire the required services + implement the handler body.
     */
    public function handle(): int
    {
        $this->omni->titleBar('Hard delete archived — tenancy command', 'sky');

        // TODO(gen): wire the required services + implement the handler body.

        $this->omni->success('Hard delete archived — tenancy command completed.');
        $this->showDuration();

        return self::SUCCESS;
    }
}
