<?php

// // AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py identity people --force`.

declare(strict_types=1);

namespace Academorix\People\Enums;

use Academorix\Enum\Enum;

/**
 * Closed-set enum for `relationship` on `person-guardian-link`.
 *
 * parent / step_parent / legal_guardian / grandparent / other.
 *
 * @category People
 *
 * @since    0.1.0
 */
enum PersonGuardianLinkRelationship: string
{
    use Enum;

    case ParentRelationship = 'parent';
    case StepParent = 'step_parent';
    case LegalGuardian = 'legal_guardian';
    case Grandparent = 'grandparent';
    case Other = 'other';
}
