<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py sports attendance --force`.

declare(strict_types=1);

namespace Academorix\Attendance\Contracts\Services;

use Academorix\Attendance\Services\AttendanceReporter;
use Illuminate\Container\Attributes\Bind;

/**
 * Service contract for AttendanceReporter.
 *
 * Bound to the concrete via `#[Bind(AttendanceReporter::class)]`. Consumers
 * type-hint this interface; tests bind a fake through the container.
 *
 * @category Attendance
 *
 * @since    0.1.0
 */
#[Bind(AttendanceReporter::class)]
interface AttendanceReporterInterface
{
    // TODO(gen): declare the domain methods this service exposes.
}
