<?php

// // AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py sports age-group --force`.

declare(strict_types=1);

namespace Academorix\Sports\AgeGroup\Models;

use Illuminate\Database\Eloquent\Attributes\Fillable;
use Illuminate\Database\Eloquent\Attributes\Table;
use Illuminate\Database\Eloquent\Attributes\UseFactory;
use Illuminate\Database\Eloquent\Model;
use Academorix\Sports\AgeGroup\Contracts\Data\AgeGroupInterface;
use Academorix\Sports\AgeGroup\Database\Factories\AgeGroupFactory;
use Academorix\Foundation\Concerns\Filterable;
use Academorix\Foundation\Concerns\HasMetadata;
use Academorix\Foundation\Concerns\HasPrefixedUlid;
use Academorix\Organization\Concerns\BelongsToOrganization;
use Academorix\Tenancy\Concerns\BelongsToTenant;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\SoftDeletes;
use Laravel\Scout\Searchable;
use Mattiverse\Userstamps\Traits\Userstamps;
use OwenIt\Auditing\Auditable;
use Spatie\Activitylog\Traits\LogsActivity;
use Spatie\Sluggable\HasSlug;

/**
 * Eloquent model for a AgeGroup.
 *
 * Age-bucket classifier for Athletes + Teams.
 *
 * @category AgeGroup
 *
 * @since    0.1.0
 */
#[Table(name: AgeGroupInterface::TABLE, keyType: AgeGroupInterface::KEY_TYPE)]
#[Fillable([
    AgeGroupInterface::ATTR_TENANT_ID,
        AgeGroupInterface::ATTR_ORGANIZATION_ID,
        AgeGroupInterface::ATTR_NAME,
        AgeGroupInterface::ATTR_SLUG,
        AgeGroupInterface::ATTR_SPORT_KEY,
        AgeGroupInterface::ATTR_DESCRIPTION,
        AgeGroupInterface::ATTR_MIN_AGE_INCLUSIVE,
        AgeGroupInterface::ATTR_MAX_AGE_INCLUSIVE,
        AgeGroupInterface::ATTR_CUTOFF_DATE_KIND,
        AgeGroupInterface::ATTR_CUTOFF_MONTH,
        AgeGroupInterface::ATTR_CUTOFF_DAY,
        AgeGroupInterface::ATTR_GENDER_CATEGORY,
        AgeGroupInterface::ATTR_IS_YOUTH,
        AgeGroupInterface::ATTR_IS_DEFAULT,
        AgeGroupInterface::ATTR_IS_SEEDED,
        AgeGroupInterface::ATTR_SORT_ORDER,
        AgeGroupInterface::ATTR_COLOR,
        AgeGroupInterface::ATTR_METADATA,
])]
#[UseFactory(AgeGroupFactory::class)]
final class AgeGroup extends Model implements AgeGroupInterface
{
    use HasFactory;
    use HasPrefixedUlid;
    use BelongsToTenant;
    use BelongsToOrganization;
    use HasSlug;
    use HasMetadata;
    use HasUserstamps;
    use HasActivityLog;
    use Auditable;
    use Filterable;
    use Searchable;
    use SoftDeletes;

    /**
     * The primary key IS a string (prefixed ULID); disable auto-increment.
     *
     * @var bool
     */
    public $incrementing = false;

    /**
     * Cast map — from the blueprint's x-eloquent.casts.
     *
     * @var array<string, string>
     */
    protected $casts = [
        AgeGroupInterface::ATTR_MIN_AGE_INCLUSIVE => 'integer',
        AgeGroupInterface::ATTR_MAX_AGE_INCLUSIVE => 'integer',
        AgeGroupInterface::ATTR_CUTOFF_MONTH => 'integer',
        AgeGroupInterface::ATTR_CUTOFF_DAY => 'integer',
        AgeGroupInterface::ATTR_SORT_ORDER => 'integer',
        AgeGroupInterface::ATTR_IS_YOUTH => 'boolean',
        AgeGroupInterface::ATTR_IS_DEFAULT => 'boolean',
        AgeGroupInterface::ATTR_IS_SEEDED => 'boolean',
        AgeGroupInterface::ATTR_CUTOFF_DATE_KIND => 'Academorix\Sports\AgeGroup\Enums\CutoffDateKind',
        AgeGroupInterface::ATTR_GENDER_CATEGORY => 'Academorix\Sports\AgeGroup\Enums\GenderCategory',
        AgeGroupInterface::ATTR_COLOR => 'Academorix\Sports\AgeGroup\Casts\HexColor',
        AgeGroupInterface::ATTR_METADATA => 'array',
    ];
}
