<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py sports development --force`.

declare(strict_types=1);

namespace Stackra\Development\Contracts\Services;

use Stackra\Development\Services\PromotionEvaluator;
use Illuminate\Container\Attributes\Bind;

/**
 * Service contract for PromotionEvaluator.
 *
 * Bound to the concrete via `#[Bind(PromotionEvaluator::class)]`. Consumers
 * type-hint this interface; tests bind a fake through the container.
 *
 * @category Development
 *
 * @since    0.1.0
 */
#[Bind(PromotionEvaluator::class)]
interface PromotionEvaluatorInterface
{
    // TODO(gen): declare the domain methods this service exposes.
}
