<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py workflow approvals --force`.

declare(strict_types=1);

namespace Academorix\Approvals\Console;

use Academorix\Console\Attributes\AsCommand;
use Academorix\Console\Commands\BaseCommand;

/**
 * `php artisan approvals:list-instances` — List instances — approvals command.
 *
 * @category Approvals
 *
 * @since    0.1.0
 */
#[AsCommand(
    name: 'approvals:list-instances',
    description: 'List instances — approvals command.',
)]
final class ListInstancesCommand extends BaseCommand
{
    /**
     * Execute the command.
     *
     * TODO(gen): wire the required services + implement the handler body.
     */
    public function handle(): int
    {
        $this->omni->titleBar('List instances — approvals command', 'sky');

        // TODO(gen): wire the required services + implement the handler body.

        $this->omni->success('List instances — approvals command completed.');
        $this->showDuration();

        return self::SUCCESS;
    }
}
