<?php

// // AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py sports event --force`.

declare(strict_types=1);

namespace Academorix\Event\Data\Requests;

use Spatie\LaravelData\Attributes\MapInputName;
use Spatie\LaravelData\Data;
use Spatie\LaravelData\Mappers\SnakeCaseMapper;
use Spatie\LaravelData\Attributes\Validation\Max;
use Spatie\LaravelData\Attributes\Validation\Min;
use Spatie\LaravelData\Attributes\Validation\Regex;
use Spatie\LaravelData\Attributes\Validation\StringType;

/**
 * Server-side update request DTO for `Event`.
 *
 * Consumed by the corresponding Action; validated on construction
 * through Spatie Data's property-attribute pipeline (no `rules()`
 * method). See `.kiro/steering/data-first.md`.
 *
 * @category Event
 *
 * @since    0.1.0
 */
#[MapInputName(SnakeCaseMapper::class)]
final class UpdateEventRequestData extends Data
{
    public function __construct(
        #[StringType, Regex('/^org_[0-9A-HJKMNP-TV-Z]{26}$/')]
        public ?string $organizationId = null,

        #[StringType, Regex('/^brn_[0-9A-HJKMNP-TV-Z]{26}$/')]
        public ?string $branchId = null,

        #[StringType, Regex('/^sea_[0-9A-HJKMNP-TV-Z]{26}$/')]
        public ?string $seasonId = null,

        #[StringType, Max(32), Regex('/^[a-z][a-z0-9_]*$/')]
        public ?string $primarySportKey = null,

        #[StringType, Min(2), Max(128)]
        public ?string $name = null,

        #[StringType, Min(2), Max(64), Regex('/^[a-z0-9]+(?:-[a-z0-9]+)*$/')]
        public ?string $slug = null,

        #[StringType]
        public ?string $eventType = null,

        #[StringType]
        public ?string $format = null,

        #[StringType]
        public ?string $description = null,

        #[StringType]
        public ?string $privateNotes = null,

        #[StringType]
        public ?string $visibility = null,

        #[StringType]
        public ?string $status = null,

        #[StringType]
        public ?string $startsAt = null,

        #[StringType]
        public ?string $endsAt = null,

        #[StringType]
        public ?string $timezone = null,

        #[StringType]
        public ?string $registrationOpensAt = null,

        #[StringType]
        public ?string $registrationClosesAt = null,

        public ?int $maxParticipants = null,

        public ?int $maxTeams = null,

        public ?int $minAge = null,

        public ?int $maxAge = null,

        public ?array $ageGroupIds = null,

        #[StringType]
        public ?string $genderCategory = null,

        public ?int $entryFeeCents = null,

        #[StringType, Regex('/^[A-Z]{3}$/')]
        public ?string $entryFeeCurrency = null,

        public ?int $prizePoolCents = null,

        #[StringType, Regex('/^[A-Z]{3}$/')]
        public ?string $prizePoolCurrency = null,

        #[StringType, Max(512)]
        public ?string $livestreamUrl = null,

        #[StringType, Max(128)]
        public ?string $livestreamPassword = null,

        #[StringType, Max(512)]
        public ?string $heroImageUrl = null,

        #[StringType]
        public ?string $registrationFormId = null,

        public ?bool $allowLateRegistration = null,

        public ?int $lateRegistrationFeeCents = null,

        #[StringType]
        public ?string $cancellationReason = null,

        #[StringType]
        public ?string $cancelledAt = null,

        #[StringType, Regex('/^usr_[0-9A-HJKMNP-TV-Z]{26}$/')]
        public ?string $cancelledByUserId = null,

        public ?array $sponsors = null,

        #[StringType, Max(512)]
        public ?string $rulesDocumentUrl = null,

        public ?array $metadata = null,
    ) {
    }
}
