<?php

/**
 * @file database/migrations/2026_07_15_120002_create_apps_table.php
 *
 * @description
 * Create the `apps` table for the `App` entity.
 * Owned by the integrations module. Emitted from the module blueprint —
 * regenerate via `generate-module.py platform integrations --force`.
 */
// // AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py platform integrations --force`.

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class() extends Migration {
    /**
     * Run the migration.
     */
    public function up(): void
    {
        Schema::create('apps', function (Blueprint $table): void {
            $table->string('id', 30)->primary();
            $table->string('slug', 100);
            $table->string('name', 200);
            $table->text('description')->nullable();
            $table->string('developer_name', 200);
            $table->string('developer_email', 200);
            $table->string('developer_website_url', 500)->nullable();
            $table->string('support_url', 500)->nullable();
            $table->string('privacy_policy_url', 500)->nullable();
            $table->string('terms_url', 500)->nullable();
            $table->string('status', 16)->default('draft');
            $table->boolean('is_first_party')->default('false');
            $table->string('oauth_client_id', 30)->nullable();
            $table->jsonb('allowed_scopes')->default('[]');
            $table->boolean('requires_child_data_scopes')->default('false');
            $table->jsonb('webhook_events')->default('[]');
            $table->string('admin_extension_url', 500)->nullable();
            $table->string('logo_url', 500)->nullable();
            $table->jsonb('screenshots')->nullable();
            $table->string('pricing_model', 16)->nullable();
            $table->jsonb('pricing_config')->nullable();
            $table->integer('partner_share_bps')->nullable();
            $table->timestampTz('approved_at')->nullable();
            $table->string('approved_by_platform_user_id', 30)->nullable();
            $table->foreign('approved_by_platform_user_id')->references('id')->on('platform_users')->onDelete('set null');
            $table->timestampTz('suspended_at')->nullable();
            $table->string('suspended_reason', 500)->nullable();
            $table->integer('install_count')->default('0');
            $table->jsonb('metadata')->nullable();
            $table->string('created_by', 30)->nullable();
            $table->string('updated_by', 30)->nullable();
            $table->string('deleted_by', 30)->nullable();
            $table->timestampTz('deleted_at')->nullable();
            $table->timestampTz('created_at');
            $table->timestampTz('updated_at');
            $table->unique(['slug'], 'apps_slug_unique');
            // Partial-index predicate — hand-add via DB::statement: WHERE deleted_at IS NULL
            $table->index(['status', 'is_first_party'], 'apps_status_first_party_idx');
        });
    }

    /**
     * Reverse the migration.
     */
    public function down(): void
    {
        Schema::dropIfExists('apps');
    }
};
