<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py sports attendance --force`.

declare(strict_types=1);

namespace Academorix\Attendance\Console;

use Stackra\Console\Attributes\AsCommand;
use Stackra\Console\Commands\BaseCommand;

/**
 * `php artisan absence:excuse` — Excuse — absence command.
 *
 * @category Attendance
 *
 * @since    0.1.0
 */
#[AsCommand(
    name: 'absence:excuse',
    description: 'Excuse — absence command.',
)]
final class ExcuseCommand extends BaseCommand
{
    /**
     * Execute the command.
     *
     * TODO(gen): wire the required services + implement the handler body.
     */
    public function handle(): int
    {
        $this->omni->titleBar('Excuse — absence command', 'sky');

        // TODO(gen): wire the required services + implement the handler body.

        $this->omni->success('Excuse — absence command completed.');
        $this->showDuration();

        return self::SUCCESS;
    }
}
