<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py sports attendance --force`.

declare(strict_types=1);

namespace Academorix\Attendance\Console;

use Academorix\Console\Attributes\AsCommand;
use Academorix\Console\Commands\BaseCommand;

/**
 * `php artisan absence:report` — Report on the absence data.
 *
 * @category Attendance
 *
 * @since    0.1.0
 */
#[AsCommand(
    name: 'absence:report',
    description: 'Report on the absence data.',
)]
final class ReportCommand extends BaseCommand
{
    /**
     * Execute the command.
     *
     * TODO(gen): wire the required services + implement the handler body.
     */
    public function handle(): int
    {
        $this->omni->titleBar('Report on the absence data', 'sky');

        // TODO(gen): wire the required services + implement the handler body.

        $this->omni->success('Report on the absence data completed.');
        $this->showDuration();

        return self::SUCCESS;
    }
}
