<?php

// // AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py platform forms --force`.

declare(strict_types=1);

namespace Academorix\Forms\Services;

use Academorix\Forms\Contracts\Services\FormValidatorInterface;
use Illuminate\Container\Attributes\Scoped;
use Academorix\Forms\Contracts\Repositories\FormSubmissionRepositoryInterface;

/**
 * Concrete service — FormValidator.
 *
 * Implements {@see FormValidatorInterface}. `#[Scoped]` because most
 * services touch request state (current tenant, current user,
 * correlation id) — see `.kiro/steering/octane-first-di.md`. If
 * the service is provably stateless, promote to `#[Singleton]`.
 *
 * @category Forms
 *
 * @since    0.1.0
 */
#[Scoped]
final class FormValidator implements FormValidatorInterface
{
    /**
     * @param  FormSubmissionRepositoryInterface  $formSubmissionRepository  Primary persistence boundary.
     */
    public function __construct(
        private readonly FormSubmissionRepositoryInterface $formSubmissionRepository,
    ) {
    }
}
