<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py identity user --force`.

declare(strict_types=1);

namespace Stackra\User\Models;

use Illuminate\Database\Eloquent\Attributes\Fillable;
use Illuminate\Database\Eloquent\Attributes\Table;
use Illuminate\Database\Eloquent\Attributes\UseFactory;
use Illuminate\Database\Eloquent\Attributes\WithoutIncrementing;
use Illuminate\Database\Eloquent\Model;
use Stackra\User\Contracts\Data\ProfileInterface;
use Stackra\User\Database\Factories\ProfileFactory;
use Stackra\Foundation\Concerns\Filterable;
use Stackra\Foundation\Concerns\HasMetadata;
use Stackra\Tenancy\Concerns\BelongsToTenant;
use Stackra\User\Policies\ProfilePolicy;
use Illuminate\Database\Eloquent\Attributes\UsePolicy;
use Illuminate\Database\Eloquent\Concerns\HasUlids;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\SoftDeletes;
use Wildside\Userstamps\Traits\Userstamps;
use OwenIt\Auditing\Auditable;
use OwenIt\Auditing\Contracts\Auditable as AuditableContract;

/**
 * Eloquent model for a Profile.
 *
 * 1:1 PII satellite for User.
 *
 * @category User
 *
 * @since    0.1.0
 */
#[Table(name: ProfileInterface::TABLE, key: ProfileInterface::PRIMARY_KEY, keyType: ProfileInterface::KEY_TYPE)]
#[Fillable([
    ProfileInterface::ATTR_TENANT_ID,
        ProfileInterface::ATTR_FIRST_NAME,
        ProfileInterface::ATTR_LAST_NAME,
        ProfileInterface::ATTR_DISPLAY_NAME,
        ProfileInterface::ATTR_AVATAR_URL,
        ProfileInterface::ATTR_PHONE_E164,
        ProfileInterface::ATTR_LOCALE,
        ProfileInterface::ATTR_TIMEZONE,
        ProfileInterface::ATTR_DOB,
        ProfileInterface::ATTR_METADATA,
])]
#[UseFactory(ProfileFactory::class)]
#[WithoutIncrementing]
#[UsePolicy(ProfilePolicy::class)]
final class Profile extends Model implements ProfileInterface, AuditableContract
{
    use HasFactory;
    use HasUlids;
    use BelongsToTenant;
    use HasMetadata;
    use Userstamps;
    use Auditable;
    use Filterable;
    use SoftDeletes;

    /**
     * Cast map — from the blueprint's `x-eloquent.casts`.
     *
     * @var array<string, string>
     */
    protected $casts = [
        ProfileInterface::ATTR_PHONE_E164 => E164Phone::class,
        ProfileInterface::ATTR_LOCALE => Bcp47Locale::class,
        ProfileInterface::ATTR_TIMEZONE => IanaTimezone::class,
        ProfileInterface::ATTR_DOB => 'date',
        ProfileInterface::ATTR_METADATA => 'array',
    ];
}
