<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py sports attendance --force`.

declare(strict_types=1);

namespace Academorix\Attendance\Events;

use Academorix\Events\Attributes\AsEvent;
use Illuminate\Contracts\Events\ShouldDispatchAfterCommit;

/**
 * absence_reason OR explanation mutated on an existing AbsenceRecord. Distinct from AbsenceExcused which flips the STATUS.
 *
 * ## Consumers
 *
 * - audit::WriteToAuditLog
 *
 * @category Attendance
 *
 * @since    0.1.0
 */
#[AsEvent]
final readonly class AbsenceReasonUpdated implements ShouldDispatchAfterCommit
{
    /**
     * @param  string  $absenceRecordId  ULID
     * @param  string  $tenantId  ULID
     * @param  string  $fromReason  string | null
     * @param  string  $toReason  string | null
     * @param  string  $changedByUserId  ULID
     */
    public function __construct(
        public readonly string $absenceRecordId,
        public readonly string $tenantId,
        public readonly string $fromReason,
        public readonly string $toReason,
        public readonly string $changedByUserId,
    ) {
    }
}
