<?php

// // AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py finance payment --force`.

declare(strict_types=1);

namespace Academorix\Finance\Payment\Events;

use Illuminate\Contracts\Events\ShouldDispatchAfterCommit;

/**
 * Provider webhook reported a new dispute. PaymentDisputeObserver.created. Fires CollectDisputeEvidenceJob + P1 notification for high-value disputes (> $500 configurable).
 *
 * ## Consumers
 *
 * - audit::WriteToAuditLog (retention: 7 years)
 * - notifications::DispatchPaymentDisputeOpenedNotification (admin — P1 for high-value; standard for low)
 * - payment::EnqueueCollectDisputeEvidenceJob (auto-collect invoice + membership + notification history)
 * - monitoring::MetricsCollector
 *
 * @category Payment
 *
 * @since    0.1.0
 */
final readonly class PaymentDisputeOpened implements ShouldDispatchAfterCommit
{
    /**
     * @param  string  $paymentDisputeId  ULID (pdi_*)
     * @param  string  $paymentId  ULID
     * @param  string  $tenantId  ULID
     * @param  string  $provider  string
     * @param  string  $reason  string
     * @param  int  $amountCents  integer
     * @param  string  $currency  string
     * @param  string  $evidenceDueBy  ISO 8601 | null
     * @param  string  $openedAt  ISO 8601
     */
    public function __construct(
        public readonly string $paymentDisputeId,
        public readonly string $paymentId,
        public readonly string $tenantId,
        public readonly string $provider,
        public readonly string $reason,
        public readonly int $amountCents,
        public readonly string $currency,
        public readonly string $evidenceDueBy,
        public readonly string $openedAt,
    ) {
    }
}
