<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py growth referrals --force`.

declare(strict_types=1);

namespace Academorix\Referrals\Enums;

use Stackra\Enum\Enum;

/**
 * Closed-set enum for `status` on `referral-reward`.
 *
 * Enum: pending / vesting / vested / materialized / paid / cancelled / clawback.
 *
 * @category Referrals
 *
 * @since    0.1.0
 */
enum ReferralRewardStatus: string
{
    use Enum;

    case Pending = 'pending';
    case Vesting = 'vesting';
    case Vested = 'vested';
    case Materialized = 'materialized';
    case Paid = 'paid';
    case Cancelled = 'cancelled';
    case Clawback = 'clawback';
}
