<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py platform region --force`.

declare(strict_types=1);

namespace Academorix\Region\Repositories;

use Academorix\Crud\Attributes\AsRepository;
use Academorix\Crud\Attributes\Cacheable;
use Academorix\Crud\Attributes\Filterable;
use Academorix\Crud\Attributes\UseModel;
use Academorix\Crud\Repositories\Repository;
use Academorix\Region\Contracts\Data\RegionInterface;
use Academorix\Region\Contracts\Repositories\RegionRepositoryInterface;
use Academorix\Region\Models\Region;

/**
 * Attribute-first Eloquent repository for {@see Academorix\Region\Models\Region}.
 *
 * Bound to the interface via `#[AsRepository]`; the model comes from
 * `#[UseModel(RegionInterface::class)]` which resolves to
 * `Region` through the interface's `#[Bind]`.
 *
 * @extends Repository<\Academorix\Region\Models\Region>
 *
 * @category Region
 *
 * @since    0.1.0
 */
#[AsRepository]
#[UseModel(RegionInterface::class)]
#[Cacheable(ttl: 3600, tags: true)]
#[Filterable('*')]
final class RegionRepository extends Repository implements RegionRepositoryInterface
{
    // Domain methods added here. CRUD comes from Repository.
}
