<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py sports formations --force`.

declare(strict_types=1);

namespace Stackra\Formations\Events;

use Stackra\Events\Attributes\AsEvent;
use Illuminate\Contracts\Events\ShouldDispatchAfterCommit;

/**
 * New Formation row. Tactical layout with player positions.
 *
 * ## Consumers
 *
 * - audit::WriteToAuditLog
 * - activity::WriteToActivityLog
 *
 * @category Formations
 *
 * @since    0.1.0
 */
#[AsEvent]
final readonly class FormationCreated implements ShouldDispatchAfterCommit
{
    /**
     * @param  string  $formationId  ULID (fmt_*)
     * @param  string  $tenantId  ULID
     * @param  string  $sportKey  string
     * @param  string  $teamId  ULID
     * @param  string  $createdByUserId  ULID
     * @param  string  $name  string
     */
    public function __construct(
        public readonly string $formationId,
        public readonly string $tenantId,
        public readonly string $sportKey,
        public readonly string $teamId,
        public readonly string $createdByUserId,
        public readonly string $name,
    ) {
    }
}
