<?php

/**
 * @file database/migrations/2026_07_15_120004_create_auth_mfa_challenges_table.php
 *
 * @description
 * Create the `auth_mfa_challenges` table for the `AuthMfaChallenge` entity.
 * Owned by the auth module. Emitted from the module blueprint —
 * regenerate via `generate-module.py identity auth --force`.
 */
// // AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py identity auth --force`.

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class() extends Migration {
    /**
     * Run the migration.
     */
    public function up(): void
    {
        Schema::create('auth_mfa_challenges', function (Blueprint $table): void {
            $table->string('id', 30)->primary();
            $table->string('identity_id', 30);
            $table->string('challenge_type');
            $table->jsonb('context');
            $table->integer('attempts_count')->default(0);
            $table->timestampTz('expires_at');
            $table->timestampTz('consumed_at')->nullable();
            $table->uuid('created_by')->nullable();
            $table->uuid('updated_by')->nullable();
            $table->timestampTz('created_at');
            $table->timestampTz('updated_at');
            $table->index(['identity_id'], 'auth_mfa_challenges_identity_idx');
            $table->index(['expires_at'], 'auth_mfa_challenges_active_expiry_idx');
            // Partial-index predicate — hand-add via DB::statement: WHERE consumed_at IS NULL
        });
    }

    /**
     * Reverse the migration.
     */
    public function down(): void
    {
        Schema::dropIfExists('auth_mfa_challenges');
    }
};
