<?php

// // AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py platform integrations --force`.

declare(strict_types=1);

namespace Academorix\Integrations\Contracts\Services;

use Academorix\Integrations\Services\AppRegistry;
use Illuminate\Container\Attributes\Bind;

/**
 * Service contract for AppRegistry.
 *
 * Bound to the concrete via `#[Bind(AppRegistry::class)]`. Consumers
 * type-hint this interface; tests bind a fake through the container.
 *
 * @category Integrations
 *
 * @since    0.1.0
 */
#[Bind(AppRegistry::class)]
interface AppRegistryInterface
{
    // TODO(gen): declare the domain methods this service exposes.
}
