<?php

// // AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py notifications notifications --force`.

declare(strict_types=1);

namespace Academorix\Notifications\Notifications\Data;

use Spatie\LaravelData\Attributes\MapInputName;
use Spatie\LaravelData\Data;
use Spatie\LaravelData\Mappers\SnakeCaseMapper;

/**
 * Server-side output DTO for {@see \Academorix\Notifications\Notifications\Models\NotificationPreference}.
 *
 * Consumed by controllers + services on the SERVER side. This is
 * distinct from the wire SDK's DTO (which sits under
 * `Academorix\NotificationsNotificationsSdk\Data`) — the wire DTO travels across the HTTP
 * boundary; this one stays in-process.
 *
 * @category Notifications
 *
 * @since    0.1.0
 */
#[MapInputName(SnakeCaseMapper::class)]
final class NotificationPreferenceData extends Data
{
    public function __construct(
        public string $id,
        public string $tenantId,
        public string $userId,
        public string $categorySlug,
        public string $channel,
        public bool $enabled,
        public string $digestMode,
        public string $createdAt,
        public string $updatedAt,
        public ?string $quietHoursStart = null,
        public ?string $quietHoursEnd = null,
        public ?string $quietHoursTimezone = null,
    ) {
    }
}
