<?php

/**
 * @file database/migrations/2026_07_15_120001_create_membership_renewals_table.php
 *
 * @description
 * Create the `membership_renewals` table for the `MembershipRenewal` entity.
 * Owned by the membership module. Every column + index reference
 * goes through {@see Academorix\Membership\Contracts\Data\MembershipRenewalInterface} per the `models` steering
 * rule §1 — no raw string literals.
 */
// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py finance membership --force`.

declare(strict_types=1);

use Academorix\Membership\Contracts\Data\MembershipRenewalInterface;
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

return new class() extends Migration {
    /**
     * Run the migration.
     */
    public function up(): void
    {
        Schema::create(MembershipRenewalInterface::TABLE, function (Blueprint $table): void {
            $table->string(MembershipRenewalInterface::ATTR_ID, 30)->primary();
            $table->string(MembershipRenewalInterface::ATTR_TENANT_ID, 30);
            $table->foreign(MembershipRenewalInterface::ATTR_TENANT_ID)->references('id')->on('tenants')->onDelete('cascade');
            $table->string(MembershipRenewalInterface::ATTR_MEMBERSHIP_ID, 30);
            $table->foreign(MembershipRenewalInterface::ATTR_MEMBERSHIP_ID)->references('id')->on('memberships')->onDelete('restrict');
            $table->timestampTz(MembershipRenewalInterface::ATTR_PERIOD_STARTS_AT);
            $table->timestampTz(MembershipRenewalInterface::ATTR_PERIOD_ENDS_AT);
            $table->string(MembershipRenewalInterface::ATTR_INVOICE_ID, 30)->nullable();
            $table->foreign(MembershipRenewalInterface::ATTR_INVOICE_ID)->references('id')->on('invoices')->onDelete('restrict');
            $table->unsignedBigInteger(MembershipRenewalInterface::ATTR_AMOUNT_CENTS);
            $table->string(MembershipRenewalInterface::ATTR_CURRENCY, 3);
            $table->string(MembershipRenewalInterface::ATTR_COUPON_ID, 30)->nullable();
            $table->foreign(MembershipRenewalInterface::ATTR_COUPON_ID)->references('id')->on('coupons')->onDelete('restrict');
            $table->jsonb(MembershipRenewalInterface::ATTR_COUPON_SNAPSHOT)->nullable();
            $table->unsignedBigInteger(MembershipRenewalInterface::ATTR_DISCOUNT_AMOUNT_CENTS)->default(0);
            $table->unsignedBigInteger(MembershipRenewalInterface::ATTR_TAX_AMOUNT_CENTS)->default(0);
            $table->unsignedBigInteger(MembershipRenewalInterface::ATTR_TOTAL_AMOUNT_CENTS);
            $table->integer(MembershipRenewalInterface::ATTR_ATTEMPT_NUMBER);
            $table->string(MembershipRenewalInterface::ATTR_STATUS, 32)->default('pending');
            $table->timestampTz(MembershipRenewalInterface::ATTR_ATTEMPTED_AT)->nullable();
            $table->timestampTz(MembershipRenewalInterface::ATTR_SUCCEEDED_AT)->nullable();
            $table->timestampTz(MembershipRenewalInterface::ATTR_FAILED_AT)->nullable();
            $table->string(MembershipRenewalInterface::ATTR_FAILURE_REASON, 256)->nullable();
            $table->timestampTz(MembershipRenewalInterface::ATTR_NEXT_ATTEMPT_AT)->nullable();
            $table->string(MembershipRenewalInterface::ATTR_CREATED_BY, 30)->nullable();
            $table->string(MembershipRenewalInterface::ATTR_UPDATED_BY, 30)->nullable();
            $table->timestampTz(MembershipRenewalInterface::ATTR_CREATED_AT);
            $table->timestampTz(MembershipRenewalInterface::ATTR_UPDATED_AT);
            $table->index([MembershipRenewalInterface::ATTR_TENANT_ID, MembershipRenewalInterface::ATTR_MEMBERSHIP_ID, MembershipRenewalInterface::ATTR_PERIOD_STARTS_AT], 'membership_renewals_by_period_idx');
            $table->index([MembershipRenewalInterface::ATTR_TENANT_ID, MembershipRenewalInterface::ATTR_MEMBERSHIP_ID, MembershipRenewalInterface::ATTR_ATTEMPT_NUMBER], 'membership_renewals_attempt_idx');
        });

        DB::statement('CREATE INDEX membership_renewals_retry_ladder_idx ON ' . MembershipRenewalInterface::TABLE . ' (' . MembershipRenewalInterface::ATTR_TENANT_ID . ', ' . MembershipRenewalInterface::ATTR_STATUS . ', ' . MembershipRenewalInterface::ATTR_NEXT_ATTEMPT_AT . ') WHERE status = \'failed_transient\' AND next_attempt_at IS NOT NULL');
        DB::statement('CREATE INDEX membership_renewals_invoice_idx ON ' . MembershipRenewalInterface::TABLE . ' (' . MembershipRenewalInterface::ATTR_TENANT_ID . ', ' . MembershipRenewalInterface::ATTR_INVOICE_ID . ') WHERE invoice_id IS NOT NULL');
    }

    /**
     * Reverse the migration.
     */
    public function down(): void
    {
        Schema::dropIfExists(MembershipRenewalInterface::TABLE);
    }
};
