<?php

/**
 * @file database/migrations/2026_07_15_120000_create_membership_plans_table.php
 *
 * @description
 * Create the `membership_plans` table for the `MembershipPlan` entity.
 * Owned by the membership module. Every column + index reference
 * goes through {@see Academorix\Membership\Contracts\Data\MembershipPlanInterface} per the `models` steering
 * rule §1 — no raw string literals.
 */
// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py finance membership --force`.

declare(strict_types=1);

use Academorix\Membership\Contracts\Data\MembershipPlanInterface;
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

return new class() extends Migration {
    /**
     * Run the migration.
     */
    public function up(): void
    {
        Schema::create(MembershipPlanInterface::TABLE, function (Blueprint $table): void {
            $table->string(MembershipPlanInterface::ATTR_ID, 30)->primary();
            $table->string(MembershipPlanInterface::ATTR_TENANT_ID, 30);
            $table->foreign(MembershipPlanInterface::ATTR_TENANT_ID)->references('id')->on('tenants')->onDelete('cascade');
            $table->string(MembershipPlanInterface::ATTR_BRANCH_ID, 30);
            $table->foreign(MembershipPlanInterface::ATTR_BRANCH_ID)->references('id')->on('branches')->onDelete('restrict');
            $table->string(MembershipPlanInterface::ATTR_NAME, 128);
            $table->string(MembershipPlanInterface::ATTR_SLUG, 64);
            $table->text(MembershipPlanInterface::ATTR_DESCRIPTION)->nullable();
            $table->unsignedBigInteger(MembershipPlanInterface::ATTR_PRICE_CENTS);
            $table->string(MembershipPlanInterface::ATTR_CURRENCY, 3);
            $table->string(MembershipPlanInterface::ATTR_BILLING_INTERVAL, 16);
            $table->integer(MembershipPlanInterface::ATTR_BILLING_INTERVAL_COUNT)->default(1);
            $table->integer(MembershipPlanInterface::ATTR_TRIAL_DAYS)->default(0);
            $table->integer(MembershipPlanInterface::ATTR_PASSES_PER_PERIOD)->nullable();
            $table->boolean(MembershipPlanInterface::ATTR_PASSES_CARRY_OVER)->default(false);
            $table->string(MembershipPlanInterface::ATTR_AGE_GROUP_ID, 30)->nullable();
            $table->foreign(MembershipPlanInterface::ATTR_AGE_GROUP_ID)->references('id')->on('age_groups')->onDelete('restrict');
            $table->jsonb(MembershipPlanInterface::ATTR_PREREQUISITES)->nullable();
            $table->jsonb(MembershipPlanInterface::ATTR_ADDON_CONFIG)->nullable();
            $table->string(MembershipPlanInterface::ATTR_REFUND_POLICY, 32)->default('no_refund');
            $table->integer(MembershipPlanInterface::ATTR_REFUND_GRACE_DAYS)->default(14);
            $table->boolean(MembershipPlanInterface::ATTR_IS_ACTIVE)->default(true);
            $table->timestampTz(MembershipPlanInterface::ATTR_EFFECTIVE_FROM)->nullable();
            $table->timestampTz(MembershipPlanInterface::ATTR_EFFECTIVE_UNTIL)->nullable();
            $table->integer(MembershipPlanInterface::ATTR_MAX_ACTIVE_MEMBERS)->nullable();
            $table->integer(MembershipPlanInterface::ATTR_CURRENT_ACTIVE_MEMBERS)->default(0);
            $table->jsonb(MembershipPlanInterface::ATTR_METADATA)->nullable();
            $table->string(MembershipPlanInterface::ATTR_CREATED_BY, 30)->nullable();
            $table->string(MembershipPlanInterface::ATTR_UPDATED_BY, 30)->nullable();
            $table->string(MembershipPlanInterface::ATTR_DELETED_BY, 30)->nullable();
            $table->timestampTz(MembershipPlanInterface::ATTR_DELETED_AT)->nullable();
            $table->timestampTz(MembershipPlanInterface::ATTR_CREATED_AT);
            $table->timestampTz(MembershipPlanInterface::ATTR_UPDATED_AT);
            $table->index([MembershipPlanInterface::ATTR_TENANT_ID, MembershipPlanInterface::ATTR_BRANCH_ID, MembershipPlanInterface::ATTR_IS_ACTIVE], 'membership_plans_active_idx');
        });

        DB::statement('CREATE UNIQUE INDEX membership_plans_slug_unique ON ' . MembershipPlanInterface::TABLE . ' (' . MembershipPlanInterface::ATTR_TENANT_ID . ', ' . MembershipPlanInterface::ATTR_BRANCH_ID . ', ' . MembershipPlanInterface::ATTR_SLUG . ') WHERE deleted_at IS NULL');
        DB::statement('CREATE INDEX membership_plans_age_group_idx ON ' . MembershipPlanInterface::TABLE . ' (' . MembershipPlanInterface::ATTR_TENANT_ID . ', ' . MembershipPlanInterface::ATTR_AGE_GROUP_ID . ') WHERE age_group_id IS NOT NULL');
    }

    /**
     * Reverse the migration.
     */
    public function down(): void
    {
        Schema::dropIfExists(MembershipPlanInterface::TABLE);
    }
};
