<?php

// // AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py observability audit --force`.

declare(strict_types=1);

namespace Academorix\Observability\Audit\Models;

use Illuminate\Database\Eloquent\Attributes\Fillable;
use Illuminate\Database\Eloquent\Attributes\Table;
use Illuminate\Database\Eloquent\Attributes\UseFactory;
use Illuminate\Database\Eloquent\Model;
use Academorix\Observability\Audit\Contracts\Data\AuditRetentionPolicyInterface;
use Academorix\Observability\Audit\Database\Factories\AuditRetentionPolicyFactory;
use Academorix\Foundation\Concerns\Filterable;
use Academorix\Foundation\Concerns\HasMetadata;
use Academorix\Tenancy\Concerns\BelongsToTenant;
use Illuminate\Database\Eloquent\Concerns\HasUlids;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\SoftDeletes;
use Mattiverse\Userstamps\Traits\Userstamps;

/**
 * Eloquent model for a AuditRetentionPolicy.
 *
 * Per-tenant retention override.
 *
 * @category Audit
 *
 * @since    0.1.0
 */
#[Table(name: AuditRetentionPolicyInterface::TABLE, keyType: AuditRetentionPolicyInterface::KEY_TYPE)]
#[Fillable([
    AuditRetentionPolicyInterface::ATTR_TENANT_ID,
        AuditRetentionPolicyInterface::ATTR_RETENTION_YEARS,
        AuditRetentionPolicyInterface::ATTR_OVERRIDE_REASON,
        AuditRetentionPolicyInterface::ATTR_OVERRIDE_STARTS_AT,
        AuditRetentionPolicyInterface::ATTR_OVERRIDE_ENDS_AT,
        AuditRetentionPolicyInterface::ATTR_EXPIRING_SOON_NOTIFIED_AT,
        AuditRetentionPolicyInterface::ATTR_NOTES,
        AuditRetentionPolicyInterface::ATTR_METADATA,
])]
#[UseFactory(AuditRetentionPolicyFactory::class)]
final class AuditRetentionPolicy extends Model implements AuditRetentionPolicyInterface
{
    use HasFactory;
    use HasUlids;
    use BelongsToTenant;
    use HasMetadata;
    use HasUserstamps;
    // TODO(gen): resolve unknown trait `HasAuditable` — add its import + use line.
    // TODO(gen): resolve unknown trait `IsRetentionAware` — add its import + use line.
    use Filterable;
    use SoftDeletes;

    /**
     * The primary key IS a string (prefixed ULID); disable auto-increment.
     *
     * @var bool
     */
    public $incrementing = false;

    /**
     * Cast map — from the blueprint's x-eloquent.casts.
     *
     * @var array<string, string>
     */
    protected $casts = [
        AuditRetentionPolicyInterface::ATTR_RETENTION_YEARS => 'int',
        AuditRetentionPolicyInterface::ATTR_OVERRIDE_STARTS_AT => 'datetime',
        AuditRetentionPolicyInterface::ATTR_OVERRIDE_ENDS_AT => 'datetime',
        AuditRetentionPolicyInterface::ATTR_EXPIRING_SOON_NOTIFIED_AT => 'datetime',
    ];
}
