<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py notifications notifications-mail --force`.

declare(strict_types=1);

namespace Stackra\NotificationsMail\Exceptions;

use Stackra\Exceptions\StackraException;

/**
 * Provider rate limit hit.
 *
 * @category NotificationsMail
 *
 * @since    0.1.0
 */
final class NotificationsMailRateLimitedException extends StackraException
{
    /**
     * Stable machine-readable error code emitted on the JSON envelope.
     */
    public const CODE = 'NOTIFICATIONS_MAIL_RATE_LIMITED';

    /**
     * Translation key for the humanised message.
     */
    public const TRANSLATION_KEY = 'notifications-mail::errors.NOTIFICATIONS_MAIL_RATE_LIMITED';
}
