<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py notifications notifications-mail --force`.

declare(strict_types=1);

namespace Academorix\NotificationsMail\Exceptions;

use Academorix\Exceptions\AcademorixException;

/**
 * Provider webhook referenced a provider_message_id we don't have.
 *
 * @category NotificationsMail
 *
 * @since    0.1.0
 */
final class NotificationsMailWebhookDeliveryNotFoundException extends AcademorixException
{
    /**
     * Stable machine-readable error code emitted on the JSON envelope.
     */
    public const CODE = 'NOTIFICATIONS_MAIL_WEBHOOK_DELIVERY_NOT_FOUND';

    /**
     * Translation key for the humanised message.
     */
    public const TRANSLATION_KEY = 'notifications-mail::errors.NOTIFICATIONS_MAIL_WEBHOOK_DELIVERY_NOT_FOUND';
}
