<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py workflow approvals --force`.

declare(strict_types=1);

namespace Stackra\Approvals\Enums;

use Stackra\Enum\Enum;

/**
 * Closed-set enum for `quorum_type` on `approval-template-approver`.
 *
 * Enum: all | any | n_of_m.
 *
 * @category Approvals
 *
 * @since    0.1.0
 */
enum ApprovalTemplateApproverQuorumType: string
{
    use Enum;

    case All = 'all';
    case Any = 'any';
    case NOfM = 'n_of_m';
}
