<?php

// // AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py sports private-sessions --force`.

declare(strict_types=1);

namespace Academorix\PrivateSessions\Events;

use Illuminate\Contracts\Events\ShouldDispatchAfterCommit;

/**
 * Coach approved request. status: requested → approved.
 *
 * ## Consumers
 *
 * - audit::WriteToAuditLog
 * - notifications::NotifyRequesterApproved
 *
 * @category PrivateSessions
 *
 * @since    0.1.0
 */
final readonly class PrivateSessionApproved implements ShouldDispatchAfterCommit
{
    /**
     * @param  string  $requestId  ULID
     * @param  string  $approvedByCoachUserId  ULID
     * @param  string  $proposedSlot  ISO 8601
     */
    public function __construct(
        public readonly string $requestId,
        public readonly string $approvedByCoachUserId,
        public readonly string $proposedSlot,
    ) {
    }
}
