<?php

// // AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py growth leads --force`.

declare(strict_types=1);

namespace Academorix\Leads\Actions\Platform;

use Academorix\Leads\Contracts\Repositories\LeadRepositoryInterface;
use Academorix\Leads\Data\LeadData;
use Academorix\Routing\Attributes\AsController;
use Academorix\Routing\Attributes\Get;

/**
 * `GET /api/v1/platform/leads/{lead}` — show action (platform-admin audience).
 *
 * Single-invoke controller wired via `#[AsController]` + `#[Get(...)]`
 * attributes from `Academorix\Routing`. Discovered by the routing package's
 * boot-time `RouteRegistrar` — no route file needed.
 *
 * @category Leads
 *
 * @since    0.1.0
 */
#[AsController]
#[Get('/api/v1/platform/leads/{lead}')]
final class ShowLeadAction
{
    public function __construct(
        private readonly LeadRepositoryInterface $repository,
    ) {
    }

    /**
     * Fetch one `lead` by id.
     *
     * @param  string  $id  Primary key.
     *
     * @throws \Illuminate\Database\Eloquent\ModelNotFoundException  When the row is absent or hidden by scoping.
     */
    public function __invoke(string $id): LeadData
    {
        return LeadData::from($this->repository->findOrFail($id));
    }
}
