<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py platform ai --force`.

declare(strict_types=1);

namespace Academorix\Ai\Policies;

use Academorix\User\Models\User;
use Academorix\Ai\Models\AiToolCall;

/**
 * Authorization policy for {@see \Academorix\Ai\Models\AiToolCall}.
 *
 * Wired via `#[UsePolicy]` on the Model.
 *
 * @category Ai
 *
 * @since    0.1.0
 */
final class AiToolCallPolicy
{
    /**
     * conversation user + admin
     *
     * @return bool
     */
    public function viewAny(User $user, AiToolCall $model): bool
    {
        return $user->can('ai.tool-calls.viewAny');
    }
    /**
     * conversation user + admin.
     *
     * @return bool
     */
    public function view(User $user, AiToolCall $model): bool
    {
        return $user->can('ai.tool-calls.view');
    }
    /**
     * cross-tenant tool-abuse detection.
     *
     * @return bool
     */
    public function platformAudit(User $user, AiToolCall $model): bool
    {
        return $user->can('platform.ai.tool-calls.audit');
    }
}
