<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py observability monitoring --force`.

declare(strict_types=1);

namespace Academorix\Monitoring\Actions\Tenant;

use Academorix\Monitoring\Contracts\Repositories\HealthCheckRepositoryInterface;
use Academorix\Monitoring\Data\HealthCheckData;
use Academorix\Monitoring\Data\Requests\UpdateHealthCheckRequestData;
use Academorix\Routing\Attributes\AsAction;
use Academorix\Routing\Attributes\Middleware;
use Academorix\Routing\Concerns\AsController;
use Academorix\Routing\Attributes\Patch;

/**
 * `PATCH /api/v1/monitoring/health-checks/{check}` — update action (tenant audience).
 *
 * Single-invoke controller wired via `#[AsAction]` + `#[Patch(...)]`
 * + `#[Middleware(...)]` from `Academorix\Routing`. Discovered by the routing
 * package's boot-time `RouteRegistrar` — no route file needed.
 *
 * @category Monitoring
 *
 * @since    0.1.0
 */
#[AsAction(name: 'monitoring.health_checks.update')]
#[Patch('/api/v1/monitoring/health-checks/{check}')]
#[Middleware(['api', 'auth:sanctum', 'tenant.resolve'])]
final class UpdateHealthCheckAction
{
    use AsController;

    public function __construct(
        private readonly HealthCheckRepositoryInterface $repository,
    ) {
    }

    /**
     * Update one `health-check` and return the wire DTO.
     *
     * @param  string  $id  Primary key.
     * @param  UpdateHealthCheckRequestData  $data  Validated payload.
     *
     * @throws \Illuminate\Database\Eloquent\ModelNotFoundException  When the row is absent or hidden by scoping.
     */
    public function __invoke(string $id, UpdateHealthCheckRequestData $data): HealthCheckData
    {
        $model = $this->repository->update($id, $data->toArray());

        return HealthCheckData::from($model);
    }
}
