<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py shared attributes --force`.

declare(strict_types=1);

namespace Stackra\Attributes\Repositories;

use Stackra\Crud\Attributes\AsRepository;
use Stackra\Crud\Attributes\Cacheable;
use Stackra\Crud\Attributes\Filterable;
use Stackra\Crud\Attributes\UseModel;
use Stackra\Crud\Repositories\Repository;
use Stackra\Attributes\Contracts\Data\AttributeGroupInterface;
use Stackra\Attributes\Contracts\Repositories\AttributeGroupRepositoryInterface;
use Stackra\Attributes\Models\AttributeGroup;

/**
 * Attribute-first Eloquent repository for {@see Stackra\Attributes\Models\AttributeGroup}.
 *
 * Bound to the interface via `#[AsRepository]`; the model comes from
 * `#[UseModel(AttributeGroupInterface::class)]` which resolves to
 * `AttributeGroup` through the interface's `#[Bind]`.
 *
 * @extends Repository<\Stackra\Attributes\Models\AttributeGroup>
 *
 * @category Attributes
 *
 * @since    0.1.0
 */
#[AsRepository]
#[UseModel(AttributeGroupInterface::class)]
#[Cacheable(ttl: 3600, tags: true)]
#[Filterable('*')]
final class AttributeGroupRepository extends Repository implements AttributeGroupRepositoryInterface
{
    // Domain methods added here. CRUD comes from Repository.
}
