<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py access delegation --force`.

declare(strict_types=1);

namespace Stackra\Delegation\Enums;

use Stackra\Enum\Enum;

/**
 * Closed-set enum for `delegation_type` on `role-delegation`.
 *
 * Semantic hint for UX + audit filtering.
 *
 * @category Delegation
 *
 * @since    0.1.0
 */
enum RoleDelegationDelegationType: string
{
    use Enum;

    case Oof = 'oof';
    case Handover = 'handover';
    case Emergency = 'emergency';
}
