<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py identity auth --force`.

declare(strict_types=1);

namespace Stackra\Auth\Actions\Platform;

use Stackra\Routing\Attributes\AsAction;
use Stackra\Routing\Attributes\Middleware;
use Stackra\Routing\Concerns\AsController;
use Stackra\Routing\Attributes\Post;

/**
 * `POST /api/v1/platform/auth/logout` — create action (platform-admin audience).
 *
 * Single-invoke controller wired via `#[AsAction]` + `#[Post(...)]`
 * + `#[Middleware(...)]` from `Stackra\Routing`. Discovered by the routing
 * package's boot-time `RouteRegistrar` — no route file needed.
 *
 * @category Auth
 *
 * @since    0.1.0
 */
#[AsAction(name: 'auth.logout.create')]
#[Post('/api/v1/platform/auth/logout')]
#[Middleware(['api', 'auth:sanctum', 'platform_admin'])]
final class CreateLogoutAction
{
    use AsController;

    /**
     * Execute the action.
     *
     * TODO(gen): wire the required services + implement the handler body.
     */
    public function __invoke(): mixed
    {
        // Hand-implement the domain logic here.
        return null;
    }
}
