<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py finance transaction --force`.

declare(strict_types=1);

namespace Academorix\Transaction\Policies;

use Stackra\User\Models\User;
use Academorix\Transaction\Models\Transaction;

/**
 * Authorization policy for {@see \Academorix\Transaction\Models\Transaction}.
 *
 * Wired via `#[UsePolicy]` on the Model.
 *
 * @category Transaction
 *
 * @since    0.1.0
 */
final class TransactionPolicy
{
    /**
     * admin + finance role only.
     *
     * @return bool
     */
    public function viewAny(User $user, Transaction $model): bool
    {
        return $user->can('transaction.viewAny');
    }
    /**
     * admin + finance role.
     *
     * @return bool
     */
    public function view(User $user, Transaction $model): bool
    {
        return $user->can('transaction.view');
    }
    /**
     * transactions are recorded ONLY via TransactionRecorder from invoice / payment / refund / chargeback modules.
     *
     * @return bool
     */
    public function create(User $user, Transaction $model): bool
    {
        return $user->can('NEVER');
    }
    /**
     * transactions are IMMUTABLE after post.
     *
     * @return bool
     */
    public function update(User $user, Transaction $model): bool
    {
        return $user->can('NEVER');
    }
    /**
     * transactions are append-only.
     *
     * @return bool
     */
    public function delete(User $user, Transaction $model): bool
    {
        return $user->can('NEVER');
    }
    /**
     * admin ONLY (finance role does NOT hold reverse).
     *
     * @return bool
     */
    public function reverse(User $user, Transaction $model): bool
    {
        return $user->can('transaction.reverse');
    }
    /**
     * same audience as view — admin + finance role.
     *
     * @return bool
     */
    public function viewLedgerEntries(User $user, Transaction $model): bool
    {
        return $user->can('transaction.ledger_entries.view');
    }
    /**
     * platform_ops + support — cross-tenant support tooling
     *
     * @return bool
     */
    public function platformViewAny(User $user, Transaction $model): bool
    {
        return $user->can('platform.transaction.viewAny');
    }
    /**
     * platformView ability.
     *
     * @return bool
     */
    public function platformView(User $user, Transaction $model): bool
    {
        return $user->can('platform.transaction.view');
    }
}
