<?php

// // AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py finance membership --force`.

declare(strict_types=1);

namespace Academorix\Finance\Membership\Events;

use Illuminate\Contracts\Events\ShouldDispatchAfterCommit;

/**
 * Admin (or customer via self-serve) migrated the membership to a lower-price plan. Downgrade deferred to period end by default (soft-transition). Passes for next period reflect new plan.
 *
 * ## Consumers
 *
 * - audit::WriteToAuditLog
 * - activity::WriteToActivityLog
 * - notifications::DispatchMembershipPlanChangedNotification
 *
 * @category Membership
 *
 * @since    0.1.0
 */
final readonly class MembershipPlanDowngraded implements ShouldDispatchAfterCommit
{
    /**
     * @param  string  $membershipId  ULID
     * @param  string  $tenantId  ULID
     * @param  string  $fromPlanId  ULID
     * @param  string  $toPlanId  ULID
     * @param  string  $effectiveAt  ISO 8601
     */
    public function __construct(
        public readonly string $membershipId,
        public readonly string $tenantId,
        public readonly string $fromPlanId,
        public readonly string $toPlanId,
        public readonly string $effectiveAt,
    ) {
    }
}
