<?php

// // AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py observability monitoring --force`.

declare(strict_types=1);

namespace Academorix\Monitoring\Enums;

use Academorix\Enum\Enum;

/**
 * Closed-set enum for `status` on `monitoring-alert`.
 *
 * Enum: firing / acknowledged / resolved / suppressed / expired.
 *
 * @category Monitoring
 *
 * @since    0.1.0
 */
enum MonitoringAlertStatus: string
{
    use Enum;

    case Firing = 'firing';
    case Acknowledged = 'acknowledged';
    case Resolved = 'resolved';
    case Suppressed = 'suppressed';
    case Expired = 'expired';
}
