<?php

/**
 * @file database/migrations/2026_07_15_120006_create_approval_templates_table.php
 *
 * @description
 * Create the `approval_templates` table for the `ApprovalTemplate` entity.
 * Owned by the approvals module. Emitted from the module blueprint —
 * regenerate via `generate-module.py workflow approvals --force`.
 */
// // AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py workflow approvals --force`.

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class() extends Migration {
    /**
     * Run the migration.
     */
    public function up(): void
    {
        Schema::create('approval_templates', function (Blueprint $table): void {
            $table->string('id', 64)->primary();
            $table->string('tenant_id', 64);
            $table->foreign('tenant_id')->references('id')->on('tenants')->onDelete('cascade');
            $table->string('application_id', 64);
            $table->foreign('application_id')->references('id')->on('applications')->onDelete('restrict');
            $table->string('action_key', 200);
            $table->foreign('action_key')->references('action_key')->on('approvable_actions')->onDelete('restrict');
            $table->string('name', 200);
            $table->text('description')->nullable();
            $table->text('when_expression')->default('');
            $table->integer('priority')->default(100);
            $table->integer('expires_after_hours')->default(168);
            $table->string('on_timeout', 16)->default('expire');
            $table->jsonb('reminder_config')->default('\'{"intervals_hours":[24,48,72],"max_reminders":3}\'::jsonb');
            $table->boolean('allows_recall')->default(true);
            $table->integer('version')->default(1);
            $table->boolean('is_active')->default(true);
            $table->jsonb('metadata')->nullable();
            $table->uuid('created_by')->nullable();
            $table->uuid('updated_by')->nullable();
            $table->uuid('deleted_by')->nullable();
            $table->timestampTz('deleted_at')->nullable();
            $table->timestampTz('created_at');
            $table->timestampTz('updated_at');
            $table->unique(['tenant_id', 'application_id', 'action_key', 'name', 'version'], 'approval_templates_composite_unique');
            // Partial-index predicate — hand-add via DB::statement: WHERE deleted_at IS NULL
            $table->unique(['tenant_id', 'application_id', 'action_key', 'name'], 'approval_templates_one_active_unique');
            // Partial-index predicate — hand-add via DB::statement: WHERE deleted_at IS NULL AND is_active = true
            $table->index(['tenant_id', 'application_id', 'action_key', 'is_active', 'priority'], 'approval_templates_resolution_idx');
            // Partial-index predicate — hand-add via DB::statement: WHERE deleted_at IS NULL
        });
    }

    /**
     * Reverse the migration.
     */
    public function down(): void
    {
        Schema::dropIfExists('approval_templates');
    }
};
