<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py growth attribution --force`.

declare(strict_types=1);

namespace Academorix\Attribution\Exceptions;

use Academorix\Exceptions\AcademorixException;

/**
 * A reset for this attribution is already in the 90-day audit hold.
 *
 * @category Attribution
 *
 * @since    0.1.0
 */
final class AttributionResetInProgressException extends AcademorixException
{
    /**
     * Stable machine-readable error code emitted on the JSON envelope.
     */
    public const CODE = 'ATTRIBUTION_RESET_IN_PROGRESS';

    /**
     * Translation key for the humanised message.
     */
    public const TRANSLATION_KEY = 'attribution::errors.ATTRIBUTION_RESET_IN_PROGRESS';
}
