<?php

// // AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py identity identity --force`.

declare(strict_types=1);

namespace Academorix\Identity\Console;

use Academorix\Console\Attributes\AsCommand;
use Academorix\Console\Console\Commands\BaseCommand;

/**
 * `php artisan identity:force-password-reset` — Force password reset — identity command.
 *
 * @category Identity
 *
 * @since    0.1.0
 */
#[AsCommand(
    name: 'identity:force-password-reset',
    description: 'Force password reset — identity command.',
)]
final class ForcePasswordResetCommand extends BaseCommand
{
    /**
     * Execute the command.
     *
     * TODO(gen): wire the required services + implement the handler body.
     */
    public function handle(): int
    {
        return self::SUCCESS;
    }
}
