<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py growth referrals --force`.

declare(strict_types=1);

namespace Academorix\Referrals\Policies;

use Stackra\User\Models\User;
use Academorix\Referrals\Models\Referral;

/**
 * Authorization policy for {@see \Academorix\Referrals\Models\Referral}.
 *
 * Wired via `#[UsePolicy]` on the Model.
 *
 * @category Referrals
 *
 * @since    0.1.0
 */
final class ReferralPolicy
{
    /**
     * admin + marketing + support: cross-tenant view of all referrals.
     *
     * @return bool
     */
    public function viewAny(User $user, Referral $model): bool
    {
        return $user->can('referrals.viewAny');
    }
    /**
     * admin + marketing + the referrer + the referred
     *
     * @return bool
     */
    public function view(User $user, Referral $model): bool
    {
        return $user->can('referrals.view');
    }
    /**
     * admin + marketing + owner.
     *
     * @return bool
     */
    public function cancel(User $user, Referral $model): bool
    {
        return $user->can('referrals.cancel');
    }
    /**
     * Enterprise-only via `referrals_manual_override` entitlement + admin/owner.
     *
     * @return bool
     */
    public function forceVest(User $user, Referral $model): bool
    {
        return $user->can('referrals.force-vest');
    }
    /**
     * platformViewAny ability.
     *
     * @return bool
     */
    public function platformViewAny(User $user, Referral $model): bool
    {
        return $user->can('platform.referrals.viewAny');
    }
    /**
     * platformView ability.
     *
     * @return bool
     */
    public function platformView(User $user, Referral $model): bool
    {
        return $user->can('platform.referrals.view');
    }
    /**
     * Platform-plane force-vest for support intervention.
     *
     * @return bool
     */
    public function platformForceVest(User $user, Referral $model): bool
    {
        return $user->can('platform.referrals.force-vest');
    }
}
