<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py platform region --force`.

declare(strict_types=1);

namespace Stackra\Region\Services;

use Stackra\Region\Contracts\Services\CurrencyFormatterInterface;
use Illuminate\Container\Attributes\Scoped;
use Stackra\Region\Contracts\Repositories\RegionRepositoryInterface;

/**
 * Concrete service — CurrencyFormatter.
 *
 * Implements {@see CurrencyFormatterInterface}. `#[Scoped]` because most
 * services touch request state (current tenant, current user,
 * correlation id) — see `.kiro/steering/octane-first-di.md`. If
 * the service is provably stateless, promote to `#[Singleton]`.
 *
 * @category Region
 *
 * @since    0.1.0
 */
#[Scoped]
final class CurrencyFormatter implements CurrencyFormatterInterface
{
    /**
     * @param  RegionRepositoryInterface  $regionRepository  Primary persistence boundary.
     */
    public function __construct(
        private readonly RegionRepositoryInterface $regionRepository,
    ) {
    }
}
