<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py platform forms --force`.

declare(strict_types=1);

namespace Stackra\Forms\Repositories;

use Stackra\Crud\Attributes\AsRepository;
use Stackra\Crud\Attributes\Cacheable;
use Stackra\Crud\Attributes\Filterable;
use Stackra\Crud\Attributes\UseModel;
use Stackra\Crud\Repositories\Repository;
use Stackra\Forms\Contracts\Data\FormSubmissionInterface;
use Stackra\Forms\Contracts\Repositories\FormSubmissionRepositoryInterface;
use Stackra\Forms\Models\FormSubmission;

/**
 * Attribute-first Eloquent repository for {@see Stackra\Forms\Models\FormSubmission}.
 *
 * Bound to the interface via `#[AsRepository]`; the model comes from
 * `#[UseModel(FormSubmissionInterface::class)]` which resolves to
 * `FormSubmission` through the interface's `#[Bind]`.
 *
 * @extends Repository<\Stackra\Forms\Models\FormSubmission>
 *
 * @category Forms
 *
 * @since    0.1.0
 */
#[AsRepository]
#[UseModel(FormSubmissionInterface::class)]
#[Cacheable(ttl: 3600, tags: true)]
#[Filterable('*')]
final class FormSubmissionRepository extends Repository implements FormSubmissionRepositoryInterface
{
    // Domain methods added here. CRUD comes from Repository.
}
