<?php

/**
 * @file database/migrations/2026_07_15_120001_create_referral_fraud_flags_table.php
 *
 * @description
 * Create the `referral_fraud_flags` table for the `ReferralFraudFlag` entity.
 * Owned by the referrals module. Every column + index reference
 * goes through {@see Academorix\Referrals\Contracts\Data\ReferralFraudFlagInterface} per the `models` steering
 * rule §1 — no raw string literals.
 */
// // AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py growth referrals --force`.

declare(strict_types=1);

use Academorix\Referrals\Contracts\Data\ReferralFraudFlagInterface;
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

return new class() extends Migration {
    /**
     * Run the migration.
     */
    public function up(): void
    {
        Schema::create(ReferralFraudFlagInterface::TABLE, function (Blueprint $table): void {
            $table->string(ReferralFraudFlagInterface::ATTR_ID, 64)->primary();
            $table->string(ReferralFraudFlagInterface::ATTR_TENANT_ID, 64);
            $table->foreign(ReferralFraudFlagInterface::ATTR_TENANT_ID)->references('id')->on('tenants')->onDelete('cascade');
            $table->string(ReferralFraudFlagInterface::ATTR_REFERRAL_ID, 64);
            $table->foreign(ReferralFraudFlagInterface::ATTR_REFERRAL_ID)->references('id')->on('referrals')->onDelete('restrict');
            $table->string(ReferralFraudFlagInterface::ATTR_FLAG_TYPE, 48);
            $table->string(ReferralFraudFlagInterface::ATTR_SEVERITY, 16);
            $table->integer(ReferralFraudFlagInterface::ATTR_CONFIDENCE);
            $table->jsonb(ReferralFraudFlagInterface::ATTR_DETAILS)->default('\'{}\'::jsonb');
            $table->timestampTz(ReferralFraudFlagInterface::ATTR_REVIEWED_AT)->nullable();
            $table->string(ReferralFraudFlagInterface::ATTR_REVIEWED_BY_USER_ID, 64)->nullable();
            $table->foreign(ReferralFraudFlagInterface::ATTR_REVIEWED_BY_USER_ID)->references('id')->on('users')->onDelete('restrict');
            $table->string(ReferralFraudFlagInterface::ATTR_DISPOSITION, 32)->nullable();
            $table->jsonb(ReferralFraudFlagInterface::ATTR_METADATA)->nullable();
            $table->string(ReferralFraudFlagInterface::ATTR_CREATED_BY, 64)->nullable();
            $table->string(ReferralFraudFlagInterface::ATTR_UPDATED_BY, 64)->nullable();
            $table->timestampTz(ReferralFraudFlagInterface::ATTR_CREATED_AT);
            $table->timestampTz(ReferralFraudFlagInterface::ATTR_UPDATED_AT);
            $table->index([ReferralFraudFlagInterface::ATTR_TENANT_ID, ReferralFraudFlagInterface::ATTR_REFERRAL_ID, ReferralFraudFlagInterface::ATTR_FLAG_TYPE], 'referral_fraud_flags_referral_type_idx');
            $table->index([ReferralFraudFlagInterface::ATTR_TENANT_ID, ReferralFraudFlagInterface::ATTR_FLAG_TYPE, ReferralFraudFlagInterface::ATTR_CREATED_AT], 'referral_fraud_flags_type_recent_idx');
            $table->index([ReferralFraudFlagInterface::ATTR_TENANT_ID, ReferralFraudFlagInterface::ATTR_REVIEWED_BY_USER_ID], 'referral_fraud_flags_reviewer_idx');
        });

        DB::statement('CREATE INDEX referral_fraud_flags_review_queue_idx ON ' . ReferralFraudFlagInterface::TABLE . ' (' . ReferralFraudFlagInterface::ATTR_TENANT_ID . ', ' . ReferralFraudFlagInterface::ATTR_SEVERITY . ', ' . ReferralFraudFlagInterface::ATTR_DISPOSITION . ') WHERE disposition IS NULL');
    }

    /**
     * Reverse the migration.
     */
    public function down(): void
    {
        Schema::dropIfExists(ReferralFraudFlagInterface::TABLE);
    }
};
