<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py sports athlete --force`.

declare(strict_types=1);

namespace Academorix\Athlete\Events;

use Academorix\Events\Attributes\AsEvent;
use Illuminate\Contracts\Events\ShouldDispatchAfterCommit;

/**
 * RollAthleteAgeGroupSnapshotJob detected the athlete's resolved age-group flipped (birthday drift + AgeGroupBoundsChanged / AgeGroupCutoffChanged cascade). Aggregated event — fires once per job invocation per athlete whose snapshot changed. Athlete.current_age_group_id + current_age_group_snapshot_at are updated on the same transaction.
 *
 * ## Consumers
 *
 * - audit::WriteToAuditLog
 * - activity::WriteToActivityLog
 * - notifications::DispatchAthleteAgeGroupSnapshotChangedNotification (opt-in — to guardians when the child moves to a new age group, e.g. U10 → U12)
 * - athlete-enrollment::MaybeInvalidateEnrollmentEligibility (Wave 3+ — enrollments whose team's age_group_id no longer matches this athlete's snapshot fire a soft-warning flag)
 *
 * @category Athlete
 *
 * @since    0.1.0
 */
#[AsEvent]
final readonly class AthleteAgeGroupSnapshotUpdated implements ShouldDispatchAfterCommit
{
    /**
     * @param  string  $athleteId  ULID
     * @param  string  $tenantId  ULID
     * @param  string  $fromAgeGroupId  ULID (age_*) | null
     * @param  string  $toAgeGroupId  ULID (age_*) | null
     * @param  string  $trigger  'birthday_drift' | 'age_group_bounds_changed' | 'age_group_cutoff_changed' | 'manual_refresh'
     * @param  string  $computedAt  ISO 8601
     */
    public function __construct(
        public readonly string $athleteId,
        public readonly string $tenantId,
        public readonly string $fromAgeGroupId,
        public readonly string $toAgeGroupId,
        public readonly string $trigger,
        public readonly string $computedAt,
    ) {
    }
}
