<?php

// // AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py sports athlete --force`.

declare(strict_types=1);

namespace Academorix\Athlete\Events;

use Illuminate\Contracts\Events\ShouldDispatchAfterCommit;

/**
 * Athlete.user_id transitioned null → non-null. Fires when the minor athlete turns 13-16 + gets a User account, OR when an adult signup's Athlete row is bound to the newly-created User. Never fires for user_id changes (immutable post-first-link).
 *
 * ## Consumers
 *
 * - audit::WriteToAuditLog
 * - activity::WriteToActivityLog
 * - notifications::DispatchAthleteLinkedToUserNotification (to the User's login channel — welcome to your athlete account)
 * - cache::InvalidateAthletesByUserCache
 *
 * @category Athlete
 *
 * @since    0.1.0
 */
final readonly class AthleteLinkedToUser implements ShouldDispatchAfterCommit
{
    /**
     * @param  string  $athleteId  ULID
     * @param  string  $tenantId  ULID
     * @param  string  $userId  ULID
     * @param  string  $linkedByUserId  ULID
     * @param  string  $trigger  'admin_linked' | 'self_serve_signup' | 'minor_turned_adult' | 'guardian_delegated'
     */
    public function __construct(
        public readonly string $athleteId,
        public readonly string $tenantId,
        public readonly string $userId,
        public readonly string $linkedByUserId,
        public readonly string $trigger,
    ) {
    }
}
