<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py growth attribution --force`.

declare(strict_types=1);

namespace Academorix\Attribution\Database\Factories;

use Illuminate\Database\Eloquent\Factories\Factory;
use Academorix\Attribution\Contracts\Data\AttributionInterface;
use Academorix\Attribution\Models\Attribution;

/**
 * Factory for {@see \Academorix\Attribution\Models\Attribution}.
 *
 * Auto-generated skeleton — extend with named states as domain
 * cases emerge (e.g. `->published()`, `->overdue()`, `->archived()`).
 *
 * @extends Factory<\Academorix\Attribution\Models\Attribution>
 *
 * @category Attribution
 *
 * @since    0.1.0
 */
final class AttributionFactory extends Factory
{
    /**
     * The model this factory builds.
     *
     * @var class-string<Attribution>
     */
    protected $model = Attribution::class;

    /**
     * Return the default model attribute values.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        return [
            AttributionInterface::ATTR_SUBJECT_TYPE => fake()->randomElement(['user', 'athlete', 'lead', 'anonymous_session']),
            AttributionInterface::ATTR_SUBJECT_ID => fake()->sentence(3),
            AttributionInterface::ATTR_FIRST_TOUCH_AT => now(),
            AttributionInterface::ATTR_FIRST_TOUCH_SOURCE => fake()->sentence(3),
            AttributionInterface::ATTR_FIRST_TOUCH_MEDIUM => null,
            AttributionInterface::ATTR_FIRST_TOUCH_CAMPAIGN => null,
            AttributionInterface::ATTR_FIRST_TOUCH_CONTENT => null,
            AttributionInterface::ATTR_FIRST_TOUCH_TERM => null,
            AttributionInterface::ATTR_FIRST_TOUCH_LANDING_PAGE => fake()->sentence(3),
            AttributionInterface::ATTR_FIRST_TOUCH_REFERRER => null,
            AttributionInterface::ATTR_FIRST_TOUCH_CLICK_ID => [],
            AttributionInterface::ATTR_FIRST_TOUCH_DEVICE => [],
            AttributionInterface::ATTR_LAST_TOUCH_AT => now(),
            AttributionInterface::ATTR_LAST_TOUCH_SOURCE => fake()->sentence(3),
            AttributionInterface::ATTR_LAST_TOUCH_MEDIUM => null,
            AttributionInterface::ATTR_LAST_TOUCH_CAMPAIGN => null,
            AttributionInterface::ATTR_LAST_TOUCH_CONTENT => null,
            AttributionInterface::ATTR_LAST_TOUCH_TERM => null,
            AttributionInterface::ATTR_LAST_TOUCH_LANDING_PAGE => fake()->sentence(3),
            AttributionInterface::ATTR_LAST_TOUCH_REFERRER => null,
            AttributionInterface::ATTR_LAST_TOUCH_CLICK_ID => fake()->sentence(3),
            AttributionInterface::ATTR_LAST_TOUCH_DEVICE => fake()->sentence(3),
            AttributionInterface::ATTR_CURRENT_SESSION_ID => null,
            AttributionInterface::ATTR_TOUCHPOINT_COUNT => fake()->numberBetween(1, 1000),
            AttributionInterface::ATTR_CONVERSION_TOUCHPOINT_COUNT => fake()->numberBetween(1, 1000),
            AttributionInterface::ATTR_CONSENT_AT_CAPTURE => [],
            AttributionInterface::ATTR_LIFECYCLE_STATE => fake()->randomElement(['anonymous', 'identified', 'converted', 'churned']),
            AttributionInterface::ATTR_LIFECYCLE_CONVERTED_AT => null,
            AttributionInterface::ATTR_METADATA => null,
        ];
    }
}
