<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py platform forms --force`.

declare(strict_types=1);

namespace Academorix\Forms\Contracts\Repositories;

use Academorix\Crud\Contracts\RepositoryInterface;

/**
 * Repository contract for {@see Academorix\Forms\Models\FormSubmission}.
 *
 * Consumers type-hint the interface; the container binds the concrete
 * via `#[AsRepository]` on `FormSubmissionRepository`.
 *
 * @extends RepositoryInterface<\Academorix\Forms\Models\FormSubmission>
 *
 * @category Forms
 *
 * @since    0.1.0
 */
interface FormSubmissionRepositoryInterface extends RepositoryInterface
{
    // Domain-specific query methods live here. CRUD comes from the base.
}
