<?php

/**
 * @file database/migrations/2026_07_15_120001_create_chargebacks_table.php
 *
 * @description
 * Create the `chargebacks` table for the `Chargeback` entity.
 * Owned by the chargeback module. Every column + index reference
 * goes through {@see Academorix\Chargeback\Contracts\Data\ChargebackInterface} per the `models` steering
 * rule §1 — no raw string literals.
 */
// // AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py finance chargeback --force`.

declare(strict_types=1);

use Academorix\Chargeback\Contracts\Data\ChargebackInterface;
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

return new class() extends Migration {
    /**
     * Run the migration.
     */
    public function up(): void
    {
        Schema::create(ChargebackInterface::TABLE, function (Blueprint $table): void {
            $table->string(ChargebackInterface::ATTR_ID, 64)->primary();
            $table->string(ChargebackInterface::ATTR_TENANT_ID, 64);
            $table->foreign(ChargebackInterface::ATTR_TENANT_ID)->references('id')->on('tenants')->onDelete('cascade');
            $table->string(ChargebackInterface::ATTR_CHARGEBACK_NUMBER, 32);
            $table->string(ChargebackInterface::ATTR_PAYMENT_ID, 64);
            $table->foreign(ChargebackInterface::ATTR_PAYMENT_ID)->references('id')->on('payments')->onDelete('restrict');
            $table->string(ChargebackInterface::ATTR_INVOICE_ID, 64);
            $table->foreign(ChargebackInterface::ATTR_INVOICE_ID)->references('id')->on('invoices')->onDelete('restrict');
            $table->string(ChargebackInterface::ATTR_PAYMENT_DISPUTE_ID, 64)->nullable();
            $table->foreign(ChargebackInterface::ATTR_PAYMENT_DISPUTE_ID)->references('id')->on('payment_disputes')->onDelete('restrict');
            $table->string(ChargebackInterface::ATTR_TRANSACTION_ID, 64)->nullable();
            $table->foreign(ChargebackInterface::ATTR_TRANSACTION_ID)->references('id')->on('transactions')->onDelete('restrict');
            $table->string(ChargebackInterface::ATTR_FEE_TRANSACTION_ID, 64)->nullable();
            $table->foreign(ChargebackInterface::ATTR_FEE_TRANSACTION_ID)->references('id')->on('transactions')->onDelete('restrict');
            $table->string(ChargebackInterface::ATTR_REFUND_ID, 64)->nullable();
            $table->foreign(ChargebackInterface::ATTR_REFUND_ID)->references('id')->on('refunds')->onDelete('restrict');
            $table->string(ChargebackInterface::ATTR_NETWORK, 32);
            $table->string(ChargebackInterface::ATTR_REASON_CODE, 16);
            $table->string(ChargebackInterface::ATTR_REASON_DESCRIPTION, 256);
            $table->string(ChargebackInterface::ATTR_REASON_CATEGORY, 32);
            $table->unsignedBigInteger(ChargebackInterface::ATTR_AMOUNT_CENTS);
            $table->string(ChargebackInterface::ATTR_CURRENCY, 3);
            $table->unsignedBigInteger(ChargebackInterface::ATTR_FEE_CENTS);
            $table->string(ChargebackInterface::ATTR_STATUS, 32)->default('pending_evidence');
            $table->timestampTz(ChargebackInterface::ATTR_EVIDENCE_DUE_BY);
            $table->timestampTz(ChargebackInterface::ATTR_EVIDENCE_SUBMITTED_AT)->nullable();
            $table->timestampTz(ChargebackInterface::ATTR_DECISION_AT)->nullable();
            $table->string(ChargebackInterface::ATTR_PROVIDER, 32);
            $table->string(ChargebackInterface::ATTR_PROVIDER_REFERENCE_ID, 128);
            $table->jsonb(ChargebackInterface::ATTR_PROVIDER_METADATA)->nullable();
            $table->boolean(ChargebackInterface::ATTR_RDR_ELIGIBLE)->default(false);
            $table->boolean(ChargebackInterface::ATTR_RDR_AUTO_REFUNDED)->default(false);
            $table->timestampTz(ChargebackInterface::ATTR_RDR_DEADLINE)->nullable();
            $table->boolean(ChargebackInterface::ATTR_CE3_ELIGIBLE)->default(false);
            $table->boolean(ChargebackInterface::ATTR_CUSTOMER_NOTIFIED)->default(false);
            $table->timestampTz(ChargebackInterface::ATTR_FILED_AT);
            $table->string(ChargebackInterface::ATTR_DECISION_REASON, 512)->nullable();
            $table->string(ChargebackInterface::ATTR_OUTCOME_REASON, 256)->nullable();
            $table->jsonb(ChargebackInterface::ATTR_METADATA)->nullable();
            $table->string(ChargebackInterface::ATTR_CREATED_BY, 64)->nullable();
            $table->string(ChargebackInterface::ATTR_UPDATED_BY, 64)->nullable();
            $table->string(ChargebackInterface::ATTR_DELETED_BY, 64)->nullable();
            $table->timestampTz(ChargebackInterface::ATTR_DELETED_AT)->nullable();
            $table->timestampTz(ChargebackInterface::ATTR_CREATED_AT);
            $table->timestampTz(ChargebackInterface::ATTR_UPDATED_AT);
            $table->index([ChargebackInterface::ATTR_TENANT_ID, ChargebackInterface::ATTR_PAYMENT_ID], 'chargebacks_tenant_payment_idx');
            $table->index([ChargebackInterface::ATTR_TENANT_ID, ChargebackInterface::ATTR_INVOICE_ID], 'chargebacks_tenant_invoice_idx');
            $table->index([ChargebackInterface::ATTR_TENANT_ID, ChargebackInterface::ATTR_STATUS, ChargebackInterface::ATTR_EVIDENCE_DUE_BY], 'chargebacks_tenant_status_due_idx');
            $table->index([ChargebackInterface::ATTR_TENANT_ID, ChargebackInterface::ATTR_NETWORK, ChargebackInterface::ATTR_REASON_CODE], 'chargebacks_tenant_network_reason_idx');
            $table->index([ChargebackInterface::ATTR_TENANT_ID, ChargebackInterface::ATTR_FILED_AT], 'chargebacks_tenant_filed_idx');
            $table->unique([ChargebackInterface::ATTR_PROVIDER_REFERENCE_ID], 'chargebacks_provider_reference_unique');
        });

        DB::statement('CREATE UNIQUE INDEX chargebacks_tenant_number_unique ON ' . ChargebackInterface::TABLE . ' (' . ChargebackInterface::ATTR_TENANT_ID . ', ' . ChargebackInterface::ATTR_CHARGEBACK_NUMBER . ') WHERE deleted_at IS NULL');
        DB::statement('CREATE INDEX chargebacks_tenant_rdr_eligible_idx ON ' . ChargebackInterface::TABLE . ' (' . ChargebackInterface::ATTR_TENANT_ID . ', ' . ChargebackInterface::ATTR_RDR_ELIGIBLE . ', ' . ChargebackInterface::ATTR_STATUS . ') WHERE rdr_eligible = true AND status = \'pending_evidence\' AND deleted_at IS NULL');
    }

    /**
     * Reverse the migration.
     */
    public function down(): void
    {
        Schema::dropIfExists(ChargebackInterface::TABLE);
    }
};
