<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py platform facility --force`.

declare(strict_types=1);

namespace Stackra\Facility\Enums;

use Stackra\Enum\Enum;

/**
 * Closed-set enum for `status` on `facility`.
 *
 * Enum: active / maintenance / retired.
 *
 * @category Facility
 *
 * @since    0.1.0
 */
enum FacilityStatus: string
{
    use Enum;

    case Active = 'active';
    case Maintenance = 'maintenance';
    case Retired = 'retired';
}
