<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py finance order --force`.

declare(strict_types=1);

namespace Academorix\Order\Repositories;

use Stackra\Crud\Attributes\AsRepository;
use Stackra\Crud\Attributes\Cacheable;
use Stackra\Crud\Attributes\Filterable;
use Stackra\Crud\Attributes\UseModel;
use Stackra\Crud\Repositories\Repository;
use Academorix\Order\Contracts\Data\OrderInterface;
use Academorix\Order\Contracts\Repositories\OrderRepositoryInterface;
use Academorix\Order\Models\Order;

/**
 * Attribute-first Eloquent repository for {@see Academorix\Order\Models\Order}.
 *
 * Bound to the interface via `#[AsRepository]`; the model comes from
 * `#[UseModel(OrderInterface::class)]` which resolves to
 * `Order` through the interface's `#[Bind]`.
 *
 * @extends Repository<\Academorix\Order\Models\Order>
 *
 * @category Order
 *
 * @since    0.1.0
 */
#[AsRepository]
#[UseModel(OrderInterface::class)]
#[Cacheable(ttl: 3600, tags: true)]
#[Filterable('*')]
final class OrderRepository extends Repository implements OrderRepositoryInterface
{
    // Domain methods added here. CRUD comes from Repository.
}
