<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py observability monitoring --force`.

declare(strict_types=1);

namespace Academorix\Monitoring\Models;

use Illuminate\Database\Eloquent\Attributes\Fillable;
use Illuminate\Database\Eloquent\Attributes\Table;
use Illuminate\Database\Eloquent\Attributes\UseFactory;
use Illuminate\Database\Eloquent\Attributes\WithoutIncrementing;
use Illuminate\Database\Eloquent\Model;
use Academorix\Monitoring\Contracts\Data\MonitoringIncidentInterface;
use Academorix\Monitoring\Database\Factories\MonitoringIncidentFactory;
use Academorix\Foundation\Concerns\Filterable;
use Academorix\Foundation\Concerns\HasMetadata;
use Academorix\Monitoring\Enums\MonitoringIncidentStatus;
use Academorix\Monitoring\Policies\MonitoringIncidentPolicy;
use Academorix\Tenancy\Concerns\BelongsToTenant;
use Illuminate\Database\Eloquent\Attributes\UsePolicy;
use Illuminate\Database\Eloquent\Concerns\HasUlids;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\SoftDeletes;
use Laravel\Scout\Searchable;
use Mattiverse\Userstamps\Traits\Userstamps;
use OwenIt\Auditing\Auditable;
use OwenIt\Auditing\Contracts\Auditable as AuditableContract;
use Spatie\Activitylog\Traits\LogsActivity;

/**
 * Eloquent model for a MonitoringIncident.
 *
 * Grouped alert timeline.
 *
 * @category Monitoring
 *
 * @since    0.1.0
 */
#[Table(name: MonitoringIncidentInterface::TABLE, key: MonitoringIncidentInterface::PRIMARY_KEY, keyType: MonitoringIncidentInterface::KEY_TYPE)]
#[Fillable([
    MonitoringIncidentInterface::ATTR_TENANT_ID,
        MonitoringIncidentInterface::ATTR_TITLE,
        MonitoringIncidentInterface::ATTR_DESCRIPTION,
        MonitoringIncidentInterface::ATTR_SEVERITY,
        MonitoringIncidentInterface::ATTR_STATUS,
        MonitoringIncidentInterface::ATTR_OPENED_AT,
        MonitoringIncidentInterface::ATTR_ACKNOWLEDGED_AT,
        MonitoringIncidentInterface::ATTR_ACKNOWLEDGED_BY_USER_ID,
        MonitoringIncidentInterface::ATTR_RESOLVED_AT,
        MonitoringIncidentInterface::ATTR_RESOLVED_BY,
        MonitoringIncidentInterface::ATTR_RESOLVED_BY_USER_ID,
        MonitoringIncidentInterface::ATTR_POSTMORTEM_URL,
        MonitoringIncidentInterface::ATTR_AFFECTED_SERVICES,
        MonitoringIncidentInterface::ATTR_ALERT_COUNT,
        MonitoringIncidentInterface::ATTR_NOTIFY_PROVIDER_CONFIGS,
        MonitoringIncidentInterface::ATTR_ONCALL_PAGE_CONFIG,
        MonitoringIncidentInterface::ATTR_ESCALATION_COUNT,
        MonitoringIncidentInterface::ATTR_METADATA,
])]
#[UseFactory(MonitoringIncidentFactory::class)]
#[WithoutIncrementing]
#[UsePolicy(MonitoringIncidentPolicy::class)]
final class MonitoringIncident extends Model implements MonitoringIncidentInterface, AuditableContract
{
    use HasFactory;
    use HasUlids;
    use BelongsToTenant;
    // TODO(gen): resolve unknown trait `HasMonitoringAlerts` — add its import + `use` line.
    use HasMetadata;
    use Userstamps;
    use Auditable;
    use LogsActivity;
    use Filterable;
    use Searchable;
    use SoftDeletes;

    /**
     * Cast map — from the blueprint's `x-eloquent.casts`.
     *
     * @var array<string, string>
     */
    protected $casts = [
        MonitoringIncidentInterface::ATTR_SEVERITY => MonitoringSeverity::class,
        MonitoringIncidentInterface::ATTR_STATUS => MonitoringIncidentStatus::class,
        MonitoringIncidentInterface::ATTR_OPENED_AT => 'datetime',
        MonitoringIncidentInterface::ATTR_ACKNOWLEDGED_AT => 'datetime',
        MonitoringIncidentInterface::ATTR_RESOLVED_AT => 'datetime',
        MonitoringIncidentInterface::ATTR_AFFECTED_SERVICES => 'array',
        MonitoringIncidentInterface::ATTR_ALERT_COUNT => 'integer',
        MonitoringIncidentInterface::ATTR_NOTIFY_PROVIDER_CONFIGS => 'array',
        MonitoringIncidentInterface::ATTR_ONCALL_PAGE_CONFIG => 'array',
        MonitoringIncidentInterface::ATTR_METADATA => 'array',
    ];
}
