<?php

// // AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py observability monitoring --force`.

declare(strict_types=1);

namespace Academorix\Monitoring\Models;

use Illuminate\Database\Eloquent\Attributes\Fillable;
use Illuminate\Database\Eloquent\Attributes\Table;
use Illuminate\Database\Eloquent\Attributes\UseFactory;
use Illuminate\Database\Eloquent\Model;
use Academorix\Monitoring\Contracts\Data\MonitoringAlertPolicyInterface;
use Academorix\Monitoring\Database\Factories\MonitoringAlertPolicyFactory;
use Academorix\Foundation\Concerns\Filterable;
use Academorix\Foundation\Concerns\HasMetadata;
use Academorix\Tenancy\Concerns\BelongsToTenant;
use Illuminate\Database\Eloquent\Concerns\HasUlids;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\SoftDeletes;
use Laravel\Scout\Searchable;
use Mattiverse\Userstamps\Traits\Userstamps;
use OwenIt\Auditing\Auditable;
use Spatie\Activitylog\Traits\LogsActivity;

/**
 * Eloquent model for a MonitoringAlertPolicy.
 *
 * Per-tenant threshold configuration.
 *
 * @category Monitoring
 *
 * @since    0.1.0
 */
#[Table(name: MonitoringAlertPolicyInterface::TABLE, keyType: MonitoringAlertPolicyInterface::KEY_TYPE)]
#[Fillable([
    MonitoringAlertPolicyInterface::ATTR_TENANT_ID,
        MonitoringAlertPolicyInterface::ATTR_NAME,
        MonitoringAlertPolicyInterface::ATTR_SIGNAL_TYPE,
        MonitoringAlertPolicyInterface::ATTR_SIGNAL_SOURCE,
        MonitoringAlertPolicyInterface::ATTR_SEVERITY,
        MonitoringAlertPolicyInterface::ATTR_THRESHOLD_OPERATOR,
        MonitoringAlertPolicyInterface::ATTR_THRESHOLD_VALUE,
        MonitoringAlertPolicyInterface::ATTR_THRESHOLD_UNIT,
        MonitoringAlertPolicyInterface::ATTR_WINDOW_SECONDS,
        MonitoringAlertPolicyInterface::ATTR_CONSECUTIVE_BREACHES_REQUIRED,
        MonitoringAlertPolicyInterface::ATTR_IS_ENABLED,
        MonitoringAlertPolicyInterface::ATTR_NOTIFY_PROVIDER_CONFIGS,
        MonitoringAlertPolicyInterface::ATTR_SUPPRESSION_CONFIG,
        MonitoringAlertPolicyInterface::ATTR_METADATA,
])]
#[UseFactory(MonitoringAlertPolicyFactory::class)]
final class MonitoringAlertPolicy extends Model implements MonitoringAlertPolicyInterface
{
    use HasFactory;
    use HasUlids;
    use BelongsToTenant;
    // TODO(gen): resolve unknown trait `HasMonitoringAlerts` — add its import + use line.
    use HasMetadata;
    use HasUserstamps;
    use Auditable;
    use HasActivityLog;
    use Filterable;
    use Searchable;
    use SoftDeletes;

    /**
     * The primary key IS a string (prefixed ULID); disable auto-increment.
     *
     * @var bool
     */
    public $incrementing = false;

    /**
     * Cast map — from the blueprint's x-eloquent.casts.
     *
     * @var array<string, string>
     */
    protected $casts = [
        MonitoringAlertPolicyInterface::ATTR_SIGNAL_TYPE => 'MonitoringSignalType',
        MonitoringAlertPolicyInterface::ATTR_SEVERITY => 'MonitoringSeverity',
        MonitoringAlertPolicyInterface::ATTR_THRESHOLD_OPERATOR => 'MonitoringThresholdOperator',
        MonitoringAlertPolicyInterface::ATTR_THRESHOLD_VALUE => 'float',
        MonitoringAlertPolicyInterface::ATTR_WINDOW_SECONDS => 'integer',
        MonitoringAlertPolicyInterface::ATTR_CONSECUTIVE_BREACHES_REQUIRED => 'integer',
        MonitoringAlertPolicyInterface::ATTR_IS_ENABLED => 'boolean',
        MonitoringAlertPolicyInterface::ATTR_NOTIFY_PROVIDER_CONFIGS => 'array',
        MonitoringAlertPolicyInterface::ATTR_SUPPRESSION_CONFIG => 'array',
        MonitoringAlertPolicyInterface::ATTR_METADATA => 'array',
    ];
}
