<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py sports season --force`.

declare(strict_types=1);

namespace Academorix\Season\Enums;

use Academorix\Enum\Enum;

/**
 * Closed-set enum for `status` on `season`.
 *
 * Enum: planned / registration_open / in_progress / playoffs / completed / archived.
 *
 * @category Season
 *
 * @since    0.1.0
 */
enum SeasonStatus: string
{
    use Enum;

    case Planned = 'planned';
    case RegistrationOpen = 'registration_open';
    case InProgress = 'in_progress';
    case Playoffs = 'playoffs';
    case Completed = 'completed';
    case Archived = 'archived';
}
