<?php

// // AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py growth leads --force`.

declare(strict_types=1);

namespace Academorix\Leads\Actions\Tenant;

use Academorix\Leads\Contracts\Repositories\LeadRepositoryInterface;
use Academorix\Routing\Attributes\AsController;
use Academorix\Routing\Attributes\Delete;
use Illuminate\Http\Response;

/**
 * `DELETE /api/v1/leads/{lead}` — delete action (tenant audience).
 *
 * Single-invoke controller wired via `#[AsController]` + `#[Delete(...)]`
 * attributes from `Academorix\Routing`. Discovered by the routing package's
 * boot-time `RouteRegistrar` — no route file needed.
 *
 * @category Leads
 *
 * @since    0.1.0
 */
#[AsController]
#[Delete('/api/v1/leads/{lead}')]
final class DeleteLeadAction
{
    public function __construct(
        private readonly LeadRepositoryInterface $repository,
    ) {
    }

    /**
     * Soft-delete one `lead` by id.
     *
     * @param  string  $id  Primary key.
     *
     * @throws \Illuminate\Database\Eloquent\ModelNotFoundException  When the row is absent or hidden by scoping.
     */
    public function __invoke(string $id): Response
    {
        $this->repository->delete($id);

        return response()->noContent();
    }
}
