<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py growth leads --force`.

declare(strict_types=1);

namespace Academorix\Leads\Actions\Tenant;

use Academorix\Leads\Contracts\Repositories\LeadActivityRepositoryInterface;
use Academorix\Leads\Data\LeadActivityData;
use Academorix\Routing\Attributes\AsAction;
use Academorix\Routing\Attributes\Middleware;
use Academorix\Routing\Concerns\AsController;
use Academorix\Routing\Attributes\Get;

/**
 * `GET /api/v1/lead-activities/{lead_activity}` — show action (tenant audience).
 *
 * Single-invoke controller wired via `#[AsAction]` + `#[Get(...)]`
 * + `#[Middleware(...)]` from `Academorix\Routing`. Discovered by the routing
 * package's boot-time `RouteRegistrar` — no route file needed.
 *
 * @category Leads
 *
 * @since    0.1.0
 */
#[AsAction(name: 'leads.lead_activities.show')]
#[Get('/api/v1/lead-activities/{lead_activity}')]
#[Middleware(['api', 'auth:sanctum', 'tenant.resolve'])]
final class ShowLeadActivitieAction
{
    use AsController;

    public function __construct(
        private readonly LeadActivityRepositoryInterface $repository,
    ) {
    }

    /**
     * Fetch one `lead-activitie` by id.
     *
     * @param  string  $id  Primary key.
     *
     * @throws \Illuminate\Database\Eloquent\ModelNotFoundException  When the row is absent or hidden by scoping.
     */
    public function __invoke(string $id): LeadActivityData
    {
        return LeadActivityData::from($this->repository->findOrFail($id));
    }
}
