<?php

// // AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py finance coupon --force`.

declare(strict_types=1);

namespace Academorix\Coupon\Contracts\Services;

use Academorix\Coupon\Services\CouponValidator;
use Illuminate\Container\Attributes\Bind;

/**
 * Service contract for CouponValidator.
 *
 * Bound to the concrete via `#[Bind(CouponValidator::class)]`. Consumers
 * type-hint this interface; tests bind a fake through the container.
 *
 * @category Coupon
 *
 * @since    0.1.0
 */
#[Bind(CouponValidator::class)]
interface CouponValidatorInterface
{
    // TODO(gen): declare the domain methods this service exposes.
}
