<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py finance payment --force`.

declare(strict_types=1);

namespace Stackra\Payment\Exceptions;

use Stackra\Exceptions\StackraException;

/**
 * Adyen / Square require Medium+ tier.
 *
 * @category Payment
 *
 * @since    0.1.0
 */
final class PaymentAdvancedProviderNotEntitledException extends StackraException
{
    /**
     * Stable machine-readable error code emitted on the JSON envelope.
     */
    public const CODE = 'PAYMENT_ADVANCED_PROVIDER_NOT_ENTITLED';

    /**
     * Translation key for the humanised message.
     */
    public const TRANSLATION_KEY = 'payment::errors.PAYMENT_ADVANCED_PROVIDER_NOT_ENTITLED';
}
