<?php

// // AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py shared search --force`.

declare(strict_types=1);

namespace Academorix\Search\Policies;

use Academorix\User\Models\User;
use Academorix\Search\Models\SearchAnalyticsEvent;

/**
 * Authorization policy for {@see \Academorix\Search\Models\SearchAnalyticsEvent}.
 *
 * Wired via `#[UsePolicy]` on the Model.
 *
 * @category Search
 *
 * @since    0.1.0
 */
final class SearchAnalyticsEventPolicy
{
    /**
     * Aggregated queries only — raw query text never emitted on the wire (hidden field).
     *
     * @return bool
     */
    public function viewAny(User $user, SearchAnalyticsEvent $model): bool
    {
        return $user->can('search.analytics.view');
    }
    /**
     * Cross-tenant analytics for support triage.
     *
     * @return bool
     */
    public function platformViewAny(User $user, SearchAnalyticsEvent $model): bool
    {
        return $user->can('platform.search.analytics.view');
    }
}
