<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py shared localization --force`.

declare(strict_types=1);

namespace Academorix\Localization\Actions\Tenant;

use Academorix\Localization\Contracts\Repositories\TranslationJobRepositoryInterface;
use Academorix\Localization\Data\TranslationJobData;
use Academorix\Localization\Data\Requests\CreateTranslationJobRequestData;
use Academorix\Routing\Attributes\AsAction;
use Academorix\Routing\Attributes\Middleware;
use Academorix\Routing\Concerns\AsController;
use Academorix\Routing\Attributes\Post;
use Illuminate\Http\JsonResponse;

/**
 * `POST /api/v1/translation-jobs` — create action (tenant audience).
 *
 * Single-invoke controller wired via `#[AsAction]` + `#[Post(...)]`
 * + `#[Middleware(...)]` from `Academorix\Routing`. Discovered by the routing
 * package's boot-time `RouteRegistrar` — no route file needed.
 *
 * @category Localization
 *
 * @since    0.1.0
 */
#[AsAction(name: 'localization.translation_jobs.create')]
#[Post('/api/v1/translation-jobs')]
#[Middleware(['api', 'auth:sanctum', 'tenant.resolve'])]
final class CreateTranslationJobAction
{
    use AsController;

    public function __construct(
        private readonly TranslationJobRepositoryInterface $repository,
    ) {
    }

    /**
     * Create a `translation-job` from the validated request payload.
     *
     * @param  CreateTranslationJobRequestData  $data  Validated payload (Spatie Data DTO).
     *
     * @return JsonResponse  201 Created with the newly-persisted DTO.
     */
    public function __invoke(CreateTranslationJobRequestData $data): JsonResponse
    {
        $model = $this->repository->create($data->toArray());

        return response()->json(TranslationJobData::from($model), JsonResponse::HTTP_CREATED);
    }
}
