<?php

// // AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py access rbac --force`.

declare(strict_types=1);

namespace Academorix\Rbac\Models;

use Illuminate\Database\Eloquent\Attributes\Fillable;
use Illuminate\Database\Eloquent\Attributes\Table;
use Illuminate\Database\Eloquent\Attributes\UseFactory;
use Illuminate\Database\Eloquent\Model;
use Academorix\Rbac\Contracts\Data\RoleDefinitionInterface;
use Academorix\Rbac\Database\Factories\RoleDefinitionFactory;
use Academorix\Foundation\Concerns\Filterable;
use Academorix\Foundation\Concerns\HasMetadata;
use Illuminate\Database\Eloquent\Concerns\HasUlids;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\SoftDeletes;
use Mattiverse\Userstamps\Traits\Userstamps;
use Spatie\Activitylog\Traits\LogsActivity;

/**
 * Eloquent model for a RoleDefinition.
 *
 * Academorix metadata layer FK-linked to system roles.
 *
 * @category Rbac
 *
 * @since    0.1.0
 */
#[Table(name: RoleDefinitionInterface::TABLE, keyType: RoleDefinitionInterface::KEY_TYPE)]
#[Fillable([
    RoleDefinitionInterface::ATTR_ROLE_ID,
        RoleDefinitionInterface::ATTR_BUSINESS_TYPE_SLUGS,
        RoleDefinitionInterface::ATTR_LABEL_I18N,
        RoleDefinitionInterface::ATTR_DESCRIPTION_I18N,
        RoleDefinitionInterface::ATTR_DEFAULT_PERMISSIONS,
        RoleDefinitionInterface::ATTR_MIN_TIER,
        RoleDefinitionInterface::ATTR_IS_CUSTOMISABLE,
        RoleDefinitionInterface::ATTR_MAX_CUSTOM_PERMISSIONS,
        RoleDefinitionInterface::ATTR_IS_ACTIVE,
        RoleDefinitionInterface::ATTR_METADATA,
])]
#[UseFactory(RoleDefinitionFactory::class)]
final class RoleDefinition extends Model implements RoleDefinitionInterface
{
    use HasFactory;
    use HasUlids;
    use HasMetadata;
    use HasUserstamps;
    use HasActivityLog;
    use Filterable;
    use SoftDeletes;

    /**
     * The primary key IS a string (prefixed ULID); disable auto-increment.
     *
     * @var bool
     */
    public $incrementing = false;

    /**
     * Cast map — from the blueprint's x-eloquent.casts.
     *
     * @var array<string, string>
     */
    protected $casts = [
        RoleDefinitionInterface::ATTR_BUSINESS_TYPE_SLUGS => 'array',
        RoleDefinitionInterface::ATTR_LABEL_I18N => 'array',
        RoleDefinitionInterface::ATTR_DESCRIPTION_I18N => 'array',
        RoleDefinitionInterface::ATTR_DEFAULT_PERMISSIONS => 'array',
        RoleDefinitionInterface::ATTR_IS_ACTIVE => 'boolean',
        RoleDefinitionInterface::ATTR_IS_CUSTOMISABLE => 'boolean',
        RoleDefinitionInterface::ATTR_MAX_CUSTOM_PERMISSIONS => 'integer',
        RoleDefinitionInterface::ATTR_METADATA => 'array',
    ];
}
