<?php

// // AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py sports athlete-enrollment --force`.

declare(strict_types=1);

namespace Academorix\Sports\AthleteEnrollment\Events;

use Illuminate\Contracts\Events\ShouldDispatchAfterCommit;

/**
 * jersey_number_assigned mutated. Enforced unique per team via partial unique index.
 *
 * ## Consumers
 *
 * - audit::WriteToAuditLog
 * - activity::WriteToActivityLog
 * - notifications::DispatchJerseyAssignedNotification
 *
 * @category AthleteEnrollment
 *
 * @since    0.1.0
 */
final readonly class EnrollmentJerseyAssigned implements ShouldDispatchAfterCommit
{
    /**
     * @param  string  $enrollmentId  ULID
     * @param  string  $tenantId  ULID
     * @param  int  $fromJersey  integer | null
     * @param  int  $toJersey  integer
     * @param  string  $assignedByUserId  ULID
     */
    public function __construct(
        public readonly string $enrollmentId,
        public readonly string $tenantId,
        public readonly int $fromJersey,
        public readonly int $toJersey,
        public readonly string $assignedByUserId,
    ) {
    }
}
