<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py growth referrals --force`.

declare(strict_types=1);

namespace Academorix\Referrals\Contracts\Data;

use Illuminate\Container\Attributes\Bind;
use Academorix\Referrals\Models\Referral;

/**
 * Table shape for the `referrals` table.
 *
 * The tracked referrer × referred × program × code instance.
 *
 * @category Referrals
 *
 * @since    0.1.0
 */
#[Bind(Referral::class)]
interface ReferralInterface
{
    /**
     * Table name.
     */
    public const string TABLE = 'referrals';

    /**
     * Primary key column.
     */
    public const string PRIMARY_KEY = 'id';

    /**
     * Primary key column type — string (ULID with prefix `ref_`).
     */
    public const string KEY_TYPE = 'string';

    // ── Columns ───────────────────────────────────────────────

    public const string ATTR_ID                   = 'id';
    public const string ATTR_TENANT_ID            = 'tenant_id';
    public const string ATTR_REFERRAL_PROGRAM_ID  = 'referral_program_id';
    public const string ATTR_REFERRAL_CODE_ID     = 'referral_code_id';
    public const string ATTR_REFERRER_TYPE        = 'referrer_type';
    public const string ATTR_REFERRER_ID          = 'referrer_id';
    public const string ATTR_REFERRED_TYPE        = 'referred_type';
    public const string ATTR_REFERRED_ID          = 'referred_id';
    public const string ATTR_REFERRED_EMAIL       = 'referred_email';
    public const string ATTR_ATTRIBUTION_SNAPSHOT = 'attribution_snapshot';
    public const string ATTR_DEVICE_SNAPSHOT      = 'device_snapshot';
    public const string ATTR_STATUS               = 'status';
    public const string ATTR_CLAIMED_AT           = 'claimed_at';
    public const string ATTR_SIGNED_UP_AT         = 'signed_up_at';
    public const string ATTR_TRIGGER_EVENT_AT     = 'trigger_event_at';
    public const string ATTR_VESTED_AT            = 'vested_at';
    public const string ATTR_REWARDED_AT          = 'rewarded_at';
    public const string ATTR_CANCELLED_AT         = 'cancelled_at';
    public const string ATTR_CANCELLATION_REASON  = 'cancellation_reason';
    public const string ATTR_FRAUD_SCORE          = 'fraud_score';
    public const string ATTR_METADATA             = 'metadata';
    public const string ATTR_CREATED_BY           = 'created_by';
    public const string ATTR_UPDATED_BY           = 'updated_by';
    public const string ATTR_DELETED_BY           = 'deleted_by';
    public const string ATTR_DELETED_AT           = 'deleted_at';
    public const string ATTR_CREATED_AT           = 'created_at';
    public const string ATTR_UPDATED_AT           = 'updated_at';
}
