<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py finance dunning --force`.

declare(strict_types=1);

namespace Academorix\Dunning\Enums;

use Stackra\Enum\Enum;

/**
 * Closed-set enum for `kind` on `dunning-event`.
 *
 * Enum: run_started / step_reached / retry_attempted / retry_succeeded / retry_failed / notification_sent / escalated_step / run_paused / run_resumed / run_cancelled / run_exhausted / run_resolved.
 *
 * @category Dunning
 *
 * @since    0.1.0
 */
enum DunningEventKind: string
{
    use Enum;

    case RunStarted = 'run_started';
    case StepReached = 'step_reached';
    case RetryAttempted = 'retry_attempted';
    case RetrySucceeded = 'retry_succeeded';
    case RetryFailed = 'retry_failed';
    case NotificationSent = 'notification_sent';
    case EscalatedStep = 'escalated_step';
    case RunPaused = 'run_paused';
    case RunResumed = 'run_resumed';
    case RunCancelled = 'run_cancelled';
    case RunExhausted = 'run_exhausted';
    case RunResolved = 'run_resolved';
}
