<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py identity user --force`.

declare(strict_types=1);

namespace Academorix\User\Services;

use Academorix\User\Contracts\Services\UserProvisionerInterface;
use Illuminate\Container\Attributes\Scoped;
use Academorix\User\Contracts\Repositories\ProfileRepositoryInterface;

/**
 * Concrete service — UserProvisioner.
 *
 * Implements {@see UserProvisionerInterface}. `#[Scoped]` because most
 * services touch request state (current tenant, current user,
 * correlation id) — see `.kiro/steering/octane-first-di.md`. If
 * the service is provably stateless, promote to `#[Singleton]`.
 *
 * @category User
 *
 * @since    0.1.0
 */
#[Scoped]
final class UserProvisioner implements UserProvisionerInterface
{
    /**
     * @param  ProfileRepositoryInterface  $profileRepository  Primary persistence boundary.
     */
    public function __construct(
        private readonly ProfileRepositoryInterface $profileRepository,
    ) {
    }
}
