<?php

/**
 * @file database/migrations/2026_07_15_120000_create_allergies_table.php
 *
 * @description
 * Create the `allergies` table for the `Allergy` entity.
 * Owned by the medical module. Every column + index reference
 * goes through {@see Academorix\Medical\Contracts\Data\AllergyInterface} per the `models` steering
 * rule §1 — no raw string literals.
 */
// // AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py sports medical --force`.

declare(strict_types=1);

use Academorix\Medical\Contracts\Data\AllergyInterface;
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class() extends Migration {
    /**
     * Run the migration.
     */
    public function up(): void
    {
        Schema::create(AllergyInterface::TABLE, function (Blueprint $table): void {
            $table->string(AllergyInterface::ATTR_ID, 30)->primary();
            $table->string(AllergyInterface::ATTR_TENANT_ID, 30);
            $table->foreign(AllergyInterface::ATTR_TENANT_ID)->references('id')->on('tenants')->onDelete('cascade');
            $table->string(AllergyInterface::ATTR_ATHLETE_ID, 30);
            $table->foreign(AllergyInterface::ATTR_ATHLETE_ID)->references('id')->on('athletes')->onDelete('cascade');
            $table->string(AllergyInterface::ATTR_ALLERGEN, 200);
            $table->string(AllergyInterface::ATTR_SEVERITY, 16);
            $table->text(AllergyInterface::ATTR_NOTES_ENCRYPTED)->nullable();
            $table->string(AllergyInterface::ATTR_REPORTED_BY_USER_ID, 30)->nullable();
            $table->jsonb(AllergyInterface::ATTR_METADATA)->nullable();
            $table->timestampTz(AllergyInterface::ATTR_CREATED_AT);
            $table->timestampTz(AllergyInterface::ATTR_UPDATED_AT);
            $table->timestampTz(AllergyInterface::ATTR_DELETED_AT)->nullable();
            $table->index([AllergyInterface::ATTR_TENANT_ID, AllergyInterface::ATTR_ATHLETE_ID], 'allergies_athlete_idx');
        });
    }

    /**
     * Reverse the migration.
     */
    public function down(): void
    {
        Schema::dropIfExists(AllergyInterface::TABLE);
    }
};
