<?php

// // AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py finance coupon --force`.

declare(strict_types=1);

namespace Academorix\Finance\Coupon\Events;

use Illuminate\Contracts\Events\ShouldDispatchAfterCommit;

/**
 * CouponRedeemer::redeem() successfully committed a CouponRedemption row + incremented Coupon.usage_count inside the enclosing invoice-creation transaction. Fires after commit.
 *
 * ## Consumers
 *
 * - audit::WriteToAuditLog (retention: 7 years — financial record)
 * - activity::WriteToActivityLog
 * - notifications::DispatchCouponRedeemedNotification (opt-in admin real-time redemption stream)
 * - marketing::CaptureCouponRedeemedMarketingEvent (only when issuance_source IN ('referral', 'marketing_campaign'))
 * - finance::ApplyDiscountToInvoiceLine (Wave 4 — the invoice module reads this and adjusts revenue-recognition)
 * - referrals::ProgressReferralOnCouponRedeemed (only when issuance_source='referral' — notifies referrals module the associated referral progressed)
 *
 * @category Coupon
 *
 * @since    0.1.0
 */
final readonly class CouponRedeemed implements ShouldDispatchAfterCommit
{
    /**
     * @param  string  $redemptionId  ULID (crd_*)
     * @param  string  $couponId  ULID (cpn_*)
     * @param  string  $tenantId  ULID
     * @param  string  $code  string
     * @param  string  $customerType  'user' | 'athlete'
     * @param  string  $customerId  ULID
     * @param  string  $redeemedByUserId  ULID
     * @param  string  $appliedToType  'membership' | 'invoice' | 'transaction'
     * @param  string  $appliedToId  ULID
     * @param  int  $sourceAmountCents  integer
     * @param  string  $sourceCurrency  string (ISO 4217)
     * @param  int  $discountAmountCents  integer
     * @param  int  $finalAmountCents  integer
     * @param  array  $discountSnapshot  object (frozen coupon config at redemption time)
     * @param  string  $issuanceSource  string
     * @param  array  $issuanceContext  object | null
     * @param  string  $redeemedAt  ISO 8601
     */
    public function __construct(
        public readonly string $redemptionId,
        public readonly string $couponId,
        public readonly string $tenantId,
        public readonly string $code,
        public readonly string $customerType,
        public readonly string $customerId,
        public readonly string $redeemedByUserId,
        public readonly string $appliedToType,
        public readonly string $appliedToId,
        public readonly int $sourceAmountCents,
        public readonly string $sourceCurrency,
        public readonly int $discountAmountCents,
        public readonly int $finalAmountCents,
        public readonly array $discountSnapshot,
        public readonly string $issuanceSource,
        public readonly array $issuanceContext,
        public readonly string $redeemedAt,
    ) {
    }
}
