<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py platform staff --force`.

declare(strict_types=1);

namespace Academorix\Staff\Console;

use Academorix\Console\Attributes\AsCommand;
use Academorix\Console\Console\Commands\BaseCommand;

/**
 * `php artisan coach:pause` — Pause — coach command.
 *
 * @category Staff
 *
 * @since    0.1.0
 */
#[AsCommand(
    name: 'coach:pause',
    description: 'Pause — coach command.',
)]
final class PauseCommand extends BaseCommand
{
    /**
     * Execute the command.
     *
     * TODO(gen): wire the required services + implement the handler body.
     */
    public function handle(): int
    {
        $this->omni->titleBar('Pause — coach command', 'sky');

        // TODO(gen): wire the required services + implement the handler body.

        $this->omni->success('Pause — coach command completed.');
        $this->showDuration();

        return self::SUCCESS;
    }
}
