<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py sports attendance --force`.

declare(strict_types=1);

namespace Stackra\Attendance\Events;

use Stackra\Events\Attributes\AsEvent;
use Illuminate\Contracts\Events\ShouldDispatchAfterCommit;

/**
 * ReconcileAttendanceJob completed processing a Session. Fires once per session with count metrics — expected / present / absent / late.
 *
 * ## Consumers
 *
 * - audit::WriteToAuditLog
 * - cache::InvalidateSessionRosterCache
 * - growth::analytics::TrackSessionAttendanceAggregate (Wave 8+)
 *
 * @category Attendance
 *
 * @since    0.1.0
 */
#[AsEvent]
final readonly class AttendanceReconciled implements ShouldDispatchAfterCommit
{
    /**
     * @param  string  $sessionId  ULID
     * @param  string  $tenantId  ULID
     * @param  int  $expectedCount  integer
     * @param  int  $presentCount  integer
     * @param  int  $lateCount  integer
     * @param  int  $absentCount  integer
     * @param  int  $excusedCount  integer
     * @param  string  $reconciledAt  ISO 8601
     */
    public function __construct(
        public readonly string $sessionId,
        public readonly string $tenantId,
        public readonly int $expectedCount,
        public readonly int $presentCount,
        public readonly int $lateCount,
        public readonly int $absentCount,
        public readonly int $excusedCount,
        public readonly string $reconciledAt,
    ) {
    }
}
