<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py sports attendance --force`.

declare(strict_types=1);

namespace Academorix\Attendance\Events;

use Stackra\Events\Attributes\AsEvent;
use Illuminate\Contracts\Events\ShouldDispatchAfterCommit;

/**
 * P1. ChargeNoShowFeeJob dispatched an invoice creation via finance::invoice module for a policy-configured no-show fee. Fires per (athlete, session) once.
 *
 * ## Consumers
 *
 * - audit::WriteToAuditLog (retention: 7 years)
 * - activity::WriteToActivityLog
 * - notifications::DispatchNoShowFeeChargedNotification (to guardian — cannot-opt-out, invoice payable)
 * - finance::invoice::CreateNoShowFeeInvoice
 *
 * @category Attendance
 *
 * @since    0.1.0
 */
#[AsEvent]
final readonly class NoShowFeeCharged implements ShouldDispatchAfterCommit
{
    /**
     * @param  string  $absenceRecordId  ULID
     * @param  string  $tenantId  ULID
     * @param  string  $athleteId  ULID
     * @param  string  $membershipId  ULID | null
     * @param  int  $feeAmountCents  integer
     * @param  string  $feeCurrency  string
     * @param  string  $policyId  ULID
     * @param  string  $chargedAt  ISO 8601
     */
    public function __construct(
        public readonly string $absenceRecordId,
        public readonly string $tenantId,
        public readonly string $athleteId,
        public readonly string $membershipId,
        public readonly int $feeAmountCents,
        public readonly string $feeCurrency,
        public readonly string $policyId,
        public readonly string $chargedAt,
    ) {
    }
}
