<?php

// // AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py finance expenses --force`.

declare(strict_types=1);

namespace Academorix\Finance\Expenses\Contracts\Data;

use Illuminate\Container\Attributes\Bind;
use Academorix\Finance\Expenses\Models\PayrollLine;

/**
 * Table shape for the `payroll_lines` table.
 *
 * Per-staff line in a PayrollRun.
 *
 * @category Expenses
 *
 * @since    0.1.0
 */
#[Bind(PayrollLine::class)]
interface PayrollLineInterface
{
    /**
     * Table name.
     */
    public const string TABLE = 'payroll_lines';

    /**
     * Primary key column.
     */
    public const string PRIMARY_KEY = 'id';

    /**
     * Primary key column type — string (ULID with prefix `pll_`).
     */
    public const string KEY_TYPE = 'string';

    // ── Columns ───────────────────────────────────────────────

    public const string ATTR_ID                      = 'id';
    public const string ATTR_TENANT_ID               = 'tenant_id';
    public const string ATTR_PAYROLL_RUN_ID          = 'payroll_run_id';
    public const string ATTR_STAFF_ID                = 'staff_id';
    public const string ATTR_SESSIONS_DELIVERED      = 'sessions_delivered';
    public const string ATTR_HOURS_WORKED            = 'hours_worked';
    public const string ATTR_GROSS_AMOUNT_MINOR      = 'gross_amount_minor';
    public const string ATTR_BONUS_AMOUNT_MINOR      = 'bonus_amount_minor';
    public const string ATTR_DEDUCTIONS_AMOUNT_MINOR = 'deductions_amount_minor';
    public const string ATTR_NET_AMOUNT_MINOR        = 'net_amount_minor';
    public const string ATTR_CURRENCY                = 'currency';
    public const string ATTR_BRANCH_ALLOCATIONS      = 'branch_allocations';
    public const string ATTR_COMPUTED_AT             = 'computed_at';
    public const string ATTR_METADATA                = 'metadata';
    public const string ATTR_CREATED_AT              = 'created_at';
    public const string ATTR_UPDATED_AT              = 'updated_at';
}
