<?php

// // AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py sports awards --force`.

declare(strict_types=1);

namespace Academorix\Awards\Actions\Central;

use Academorix\Awards\Contracts\Repositories\CertificateRepositoryInterface;
use Academorix\Awards\Data\CertificateData;
use Academorix\Routing\Attributes\AsController;
use Academorix\Routing\Attributes\Get;

/**
 * `GET /certificates/{signature}` — show action (central audience).
 *
 * Single-invoke controller wired via `#[AsController]` + `#[Get(...)]`
 * attributes from `Academorix\Routing`. Discovered by the routing package's
 * boot-time `RouteRegistrar` — no route file needed.
 *
 * @category Awards
 *
 * @since    0.1.0
 */
#[AsController]
#[Get('/certificates/{signature}')]
final class ShowCertificateAction
{
    public function __construct(
        private readonly CertificateRepositoryInterface $repository,
    ) {
    }

    /**
     * Fetch one `certificate` by id.
     *
     * @param  string  $id  Primary key.
     *
     * @throws \Illuminate\Database\Eloquent\ModelNotFoundException  When the row is absent or hidden by scoping.
     */
    public function __invoke(string $id): CertificateData
    {
        return CertificateData::from($this->repository->findOrFail($id));
    }
}
