<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py growth attribution --force`.

declare(strict_types=1);

namespace Stackra\Attribution\Actions\Tenant;

use Stackra\Routing\Attributes\AsAction;
use Stackra\Routing\Attributes\Middleware;
use Stackra\Routing\Concerns\AsController;
use Stackra\Routing\Attributes\Get;

/**
 * `GET /api/v1/campaigns/rollup` — list action (tenant audience).
 *
 * Single-invoke controller wired via `#[AsAction]` + `#[Get(...)]`
 * + `#[Middleware(...)]` from `Stackra\Routing`. Discovered by the routing
 * package's boot-time `RouteRegistrar` — no route file needed.
 *
 * @category Attribution
 *
 * @since    0.1.0
 */
#[AsAction(name: 'attribution.rollup.list')]
#[Get('/api/v1/campaigns/rollup')]
#[Middleware(['api', 'auth:sanctum', 'tenant.resolve'])]
final class ListRollupAction
{
    use AsController;

    /**
     * Execute the action.
     *
     * TODO(gen): wire the required services + implement the handler body.
     */
    public function __invoke(): mixed
    {
        // Hand-implement the domain logic here.
        return null;
    }
}
