<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py sports event --force`.

declare(strict_types=1);

namespace Academorix\Event\Enums;

use Stackra\Enum\Enum;

/**
 * Closed-set enum for `status` on `rsvp`.
 *
 * pending / confirmed / declined / cancelled.
 *
 * @category Event
 *
 * @since    0.1.0
 */
enum RsvpStatus: string
{
    use Enum;

    case Pending = 'pending';
    case Confirmed = 'confirmed';
    case Declined = 'declined';
    case Cancelled = 'cancelled';
}
