<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py sports season --force`.

declare(strict_types=1);

namespace Stackra\Season\Console;

use Stackra\Console\Attributes\AsCommand;
use Stackra\Console\Commands\BaseCommand;

/**
 * `php artisan season:describe` — Describe the season surface.
 *
 * @category Season
 *
 * @since    0.1.0
 */
#[AsCommand(
    name: 'season:describe',
    description: 'Describe the season surface.',
)]
final class DescribeCommand extends BaseCommand
{
    /**
     * Execute the command.
     *
     * TODO(gen): wire the required services + implement the handler body.
     */
    public function handle(): int
    {
        $this->omni->titleBar('Describe the season surface', 'sky');

        // TODO(gen): wire the required services + implement the handler body.

        $this->omni->success('Describe the season surface completed.');
        $this->showDuration();

        return self::SUCCESS;
    }
}
