<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py sports drills --force`.

declare(strict_types=1);

namespace Stackra\Drills\Models;

use Illuminate\Database\Eloquent\Attributes\Fillable;
use Illuminate\Database\Eloquent\Attributes\Table;
use Illuminate\Database\Eloquent\Attributes\UseFactory;
use Illuminate\Database\Eloquent\Attributes\WithoutIncrementing;
use Illuminate\Database\Eloquent\Model;
use Stackra\Drills\Contracts\Data\CurriculumInterface;
use Stackra\Drills\Database\Factories\CurriculumFactory;
use Stackra\Foundation\Concerns\Filterable;
use Stackra\Foundation\Concerns\HasMetadata;
use Stackra\Foundation\Concerns\HasPrefixedUlid;
use Stackra\Tenancy\Concerns\BelongsToTenant;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\SoftDeletes;
use Mattiverse\Userstamps\Traits\Userstamps;
use OwenIt\Auditing\Auditable;
use OwenIt\Auditing\Contracts\Auditable as AuditableContract;

/**
 * Eloquent model for a Curriculum.
 *
 *
 *
 * @category Drills
 *
 * @since    0.1.0
 */
#[Table(name: CurriculumInterface::TABLE, key: CurriculumInterface::PRIMARY_KEY, keyType: CurriculumInterface::KEY_TYPE)]
#[Fillable([
    CurriculumInterface::ATTR_TENANT_ID,
        CurriculumInterface::ATTR_SPORT_KEY,
        CurriculumInterface::ATTR_NAME,
        CurriculumInterface::ATTR_AGE_BAND,
        CurriculumInterface::ATTR_TOTAL_WEEKS,
        CurriculumInterface::ATTR_OBJECTIVE,
        CurriculumInterface::ATTR_CLONED_FROM_ID,
        CurriculumInterface::ATTR_IS_ACTIVE,
        CurriculumInterface::ATTR_METADATA,
])]
#[UseFactory(CurriculumFactory::class)]
#[WithoutIncrementing]
final class Curriculum extends Model implements CurriculumInterface, AuditableContract
{
    use HasFactory;
    use HasPrefixedUlid;
    use BelongsToTenant;
    use HasMetadata;
    use Userstamps;
    use Auditable;
    use Filterable;
    use SoftDeletes;
}
