<?php

// // AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py shared transfer --force`.

declare(strict_types=1);

namespace Academorix\Shared\Transfer\Events;

use Illuminate\Contracts\Events\ShouldDispatchAfterCommit;

/**
 * GenerateSampleDataJob completed — fixture records inserted for a #[SampleData]-annotated entity.
 *
 * ## Consumers
 *
 * - activity::HasActivityLog on XferJob (kind=sample)
 * - SendXferJobNotificationJob
 *
 * @category Transfer
 *
 * @since    0.1.0
 */
final readonly class SampleDataGenerated implements ShouldDispatchAfterCommit
{
    /**
     * @param  string  $xferJobId  ULID
     * @param  string  $entity  string
     * @param  int  $recordCount  integer
     * @param  string  $factory  class-string
     */
    public function __construct(
        public readonly string $xferJobId,
        public readonly string $entity,
        public readonly int $recordCount,
        public readonly string $factory,
    ) {
    }
}
