<?php

// // AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py shared transfer --force`.

declare(strict_types=1);

namespace Academorix\Shared\Transfer\Events;

use Illuminate\Contracts\Events\ShouldDispatchAfterCommit;

/**
 * XferJob row inserted (status=queued). Fires from XferJobObserver.created.
 *
 * ## Consumers
 *
 * - activity::HasActivityLog observer on XferJob → activity_log row
 * - audit::HasAudit observer on XferJob → audits row
 *
 * @category Transfer
 *
 * @since    0.1.0
 */
final readonly class XferJobQueued implements ShouldDispatchAfterCommit
{
    /**
     * @param  string  $xferJobId  ULID (xfer_)
     * @param  string  $tenantId  ULID (ten_) | null
     * @param  string  $causerType  string
     * @param  string  $causerId  string
     * @param  string  $kind  'import' | 'export' | 'sample'
     * @param  string  $entity  string
     * @param  string  $mode  ImportMode | null
     * @param  string  $format  string | null
     */
    public function __construct(
        public readonly string $xferJobId,
        public readonly string $tenantId,
        public readonly string $causerType,
        public readonly string $causerId,
        public readonly string $kind,
        public readonly string $entity,
        public readonly string $mode,
        public readonly string $format,
    ) {
    }
}
