<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py sports medical --force`.

declare(strict_types=1);

namespace Stackra\Medical\Database\Factories;

use Illuminate\Database\Eloquent\Factories\Factory;
use Stackra\Medical\Contracts\Data\MedicalRecordInterface;
use Stackra\Medical\Models\MedicalRecord;

/**
 * Factory for {@see \Stackra\Medical\Models\MedicalRecord}.
 *
 * Auto-generated skeleton — extend with named states as domain
 * cases emerge (e.g. `->published()`, `->overdue()`, `->archived()`).
 *
 * @extends Factory<\Stackra\Medical\Models\MedicalRecord>
 *
 * @category Medical
 *
 * @since    0.1.0
 */
final class MedicalRecordFactory extends Factory
{
    /**
     * The model this factory builds.
     *
     * @var class-string<MedicalRecord>
     */
    protected $model = MedicalRecord::class;

    /**
     * Return the default model attribute values.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        return [
            MedicalRecordInterface::ATTR_ATHLETE_ID => fake()->sentence(3),
            MedicalRecordInterface::ATTR_BLOOD_GROUP => null,
            MedicalRecordInterface::ATTR_PRIMARY_PHYSICIAN_ENCRYPTED => null,
            MedicalRecordInterface::ATTR_EMERGENCY_MEDICAL_NOTES_ENCRYPTED => null,
            MedicalRecordInterface::ATTR_METADATA => null,
        ];
    }
}
