<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py growth referrals --force`.

declare(strict_types=1);

namespace Academorix\Referrals\Events;

use Illuminate\Contracts\Events\ShouldDispatchAfterCommit;

/**
 * ReferralProgram.rewards_issued_count >= max_rewards_per_program OR rewards_issued_amount_cents crosses a threshold. New referral claims start refusing with PROGRAM_BUDGET_EXHAUSTED.
 *
 * ## Consumers
 *
 * - audit::WriteToAuditLog
 * - activity::WriteToActivityLog
 * - notifications::DispatchProgramBudgetAlertNotification (to admin)
 *
 * @category Referrals
 *
 * @since    0.1.0
 */
final readonly class ReferralProgramBudgetReached implements ShouldDispatchAfterCommit
{
    /**
     * @param  string  $programId  ULID
     * @param  string  $tenantId  ULID
     * @param  int  $rewardsIssuedCount  integer
     * @param  int  $rewardsIssuedAmountCents  integer
     * @param  int  $budgetCap  integer
     * @param  string  $reachedAt  ISO 8601
     */
    public function __construct(
        public readonly string $programId,
        public readonly string $tenantId,
        public readonly int $rewardsIssuedCount,
        public readonly int $rewardsIssuedAmountCents,
        public readonly int $budgetCap,
        public readonly string $reachedAt,
    ) {
    }
}
