<?php

// // AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py growth referrals --force`.

declare(strict_types=1);

namespace Academorix\Referrals\Events;

use Illuminate\Contracts\Events\ShouldDispatchAfterCommit;

/**
 * Public route GET /api/v1/referrals/claim/{code} was hit. Attribution snapshot + device snapshot captured; a Referral row in status 'pending_claim' may be created (depends on session state).
 *
 * ## Consumers
 *
 * - activity::WriteToActivityLog (staff-visible for viral analytics)
 * - attribution::CaptureReferralClickTouchpoint (adds a touchpoint on the referrer's attribution profile)
 * - observability::MetricsCollector (academorix.referrals.clicks_total)
 *
 * @category Referrals
 *
 * @since    0.1.0
 */
final readonly class ReferralClicked implements ShouldDispatchAfterCommit
{
    /**
     * @param  string  $codeId  ULID | null (nullable when click carries no code — attribution-only)
     * @param  string  $tenantId  ULID
     * @param  string  $code  string | null
     * @param  string  $ipHash  SHA-256 hex string
     * @param  string  $userAgentHash  SHA-256 hex string
     * @param  string  $deviceFingerprintHash  SHA-256 hex string | null
     * @param  string  $clickedAt  ISO 8601
     * @param  string  $referrerUrl  string | null
     */
    public function __construct(
        public readonly string $codeId,
        public readonly string $tenantId,
        public readonly string $code,
        public readonly string $ipHash,
        public readonly string $userAgentHash,
        public readonly string $deviceFingerprintHash,
        public readonly string $clickedAt,
        public readonly string $referrerUrl,
    ) {
    }
}
