<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py platform teams --force`.

declare(strict_types=1);

namespace Academorix\Teams\Console;

use Academorix\Console\Attributes\AsCommand;
use Academorix\Console\Console\Commands\BaseCommand;

/**
 * `php artisan team-member:mark-graduated` — Mark graduated — team member command.
 *
 * @category Teams
 *
 * @since    0.1.0
 */
#[AsCommand(
    name: 'team-member:mark-graduated',
    description: 'Mark graduated — team member command.',
)]
final class MarkGraduatedCommand extends BaseCommand
{
    /**
     * Execute the command.
     *
     * TODO(gen): wire the required services + implement the handler body.
     */
    public function handle(): int
    {
        $this->omni->titleBar('Mark graduated — team member command', 'sky');

        // TODO(gen): wire the required services + implement the handler body.

        $this->omni->success('Mark graduated — team member command completed.');
        $this->showDuration();

        return self::SUCCESS;
    }
}
