<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py identity service-accounts --force`.

declare(strict_types=1);

namespace Academorix\ServiceAccounts\Console;

use Academorix\Console\Attributes\AsCommand;
use Academorix\Console\Console\Commands\BaseCommand;

/**
 * `php artisan service-account:create` — Create a new service account.
 *
 * @category ServiceAccounts
 *
 * @since    0.1.0
 */
#[AsCommand(
    name: 'service-account:create',
    description: 'Create a new service account.',
)]
final class CreateCommand extends BaseCommand
{
    /**
     * Execute the command.
     *
     * TODO(gen): wire the required services + implement the handler body.
     */
    public function handle(): int
    {
        return self::SUCCESS;
    }
}
