<?php

// // AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py shared attributes --force`.

declare(strict_types=1);

namespace Academorix\Attributes\Actions\Tenant;

use Academorix\Routing\Attributes\AsController;
use Academorix\Routing\Attributes\Post;

/**
 * `POST /api/v1/attribute-definitions/{def}/deprecate` — custom action (tenant audience).
 *
 * Single-invoke controller wired via `#[AsController]` + `#[Post(...)]`
 * attributes from `Academorix\Routing`. Discovered by the routing package's
 * boot-time `RouteRegistrar` — no route file needed.
 *
 * @category Attributes
 *
 * @since    0.1.0
 */
#[AsController]
#[Post('/api/v1/attribute-definitions/{def}/deprecate')]
final class DeprecateDeprecateAction
{
    /**
     * Execute the action.
     *
     * TODO(gen): wire the required services + implement the handler body.
     */
    public function __invoke(): mixed
    {
        // Hand-implement the domain logic here.
        return null;
    }
}
