<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py platform teams --force`.

declare(strict_types=1);

namespace Stackra\Teams\Enums;

use Stackra\Enum\Enum;

/**
 * Closed-set enum for `payment_status` on `team-trial`.
 *
 * Enum: none / pending / paid / refunded / waived.
 *
 * @category Teams
 *
 * @since    0.1.0
 */
enum TeamTrialPaymentStatus: string
{
    use Enum;

    case None = 'none';
    case Pending = 'pending';
    case Paid = 'paid';
    case Refunded = 'refunded';
    case Waived = 'waived';
}
