<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py identity auth --force`.

declare(strict_types=1);

namespace Stackra\Auth\Enums;

use Stackra\Enum\Enum;

/**
 * Closed-set enum for `reason` on `auth-jwt-deny-list`.
 *
 * 'password_change' | 'user_suspended' | 'manual_revocation' | 'breach_response'
 *
 * @category Auth
 *
 * @since    0.1.0
 */
enum AuthJwtDenyListReason: string
{
    use Enum;

    case PasswordChange = 'password_change';
    case UserSuspended = 'user_suspended';
    case ManualRevocation = 'manual_revocation';
    case BreachResponse = 'breach_response';
}
