<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py identity mfa --force`.

declare(strict_types=1);

namespace Stackra\Mfa\Actions\Platform;

use Stackra\Routing\Attributes\AsAction;
use Stackra\Routing\Attributes\Middleware;
use Stackra\Routing\Concerns\AsController;
use Stackra\Routing\Attributes\Post;

/**
 * `POST /api/v1/platform/mfa/regenerate-recovery-codes/{user}` — custom action (platform-admin audience).
 *
 * Single-invoke controller wired via `#[AsAction]` + `#[Post(...)]`
 * + `#[Middleware(...)]` from `Stackra\Routing`. Discovered by the routing
 * package's boot-time `RouteRegistrar` — no route file needed.
 *
 * @category Mfa
 *
 * @since    0.1.0
 */
#[AsAction(name: 'mfa.regenerate_recovery_codes.regenerate_recovery_codes')]
#[Post('/api/v1/platform/mfa/regenerate-recovery-codes/{user}')]
#[Middleware(['api', 'auth:sanctum', 'platform_admin'])]
final class RegenerateRecoveryCodesRegenerateRecoveryCodeAction
{
    use AsController;

    /**
     * Execute the action.
     *
     * TODO(gen): wire the required services + implement the handler body.
     */
    public function __invoke(): mixed
    {
        // Hand-implement the domain logic here.
        return null;
    }
}
