<?php

// // AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py sports drills --force`.

declare(strict_types=1);

namespace Academorix\Drills\Actions\Tenant;

use Academorix\Drills\Contracts\Repositories\SessionPlanRepositoryInterface;
use Academorix\Drills\Data\SessionPlanData;
use Academorix\Routing\Attributes\AsController;
use Academorix\Routing\Attributes\Get;

/**
 * `GET /api/v1/session-plans/{plan}` — show action (tenant audience).
 *
 * Single-invoke controller wired via `#[AsController]` + `#[Get(...)]`
 * attributes from `Academorix\Routing`. Discovered by the routing package's
 * boot-time `RouteRegistrar` — no route file needed.
 *
 * @category Drills
 *
 * @since    0.1.0
 */
#[AsController]
#[Get('/api/v1/session-plans/{plan}')]
final class ShowSessionPlanAction
{
    public function __construct(
        private readonly SessionPlanRepositoryInterface $repository,
    ) {
    }

    /**
     * Fetch one `session-plan` by id.
     *
     * @param  string  $id  Primary key.
     *
     * @throws \Illuminate\Database\Eloquent\ModelNotFoundException  When the row is absent or hidden by scoping.
     */
    public function __invoke(string $id): SessionPlanData
    {
        return SessionPlanData::from($this->repository->findOrFail($id));
    }
}
