<?php

// // AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py platform forms --force`.

declare(strict_types=1);

namespace Academorix\Forms\Actions\Tenant;

use Academorix\Forms\Contracts\Repositories\FormRepositoryInterface;
use Academorix\Forms\Data\FormData;
use Academorix\Routing\Attributes\AsController;
use Academorix\Routing\Attributes\Get;
use Illuminate\Http\Request;
use Illuminate\Pagination\LengthAwarePaginator;
use Spatie\LaravelData\PaginatedDataCollection;

/**
 * `GET /api/v1/forms` — list action (tenant audience).
 *
 * Single-invoke controller wired via `#[AsController]` + `#[Get(...)]`
 * attributes from `Academorix\Routing`. Discovered by the routing package's
 * boot-time `RouteRegistrar` — no route file needed.
 *
 * @category Forms
 *
 * @since    0.1.0
 */
#[AsController]
#[Get('/api/v1/forms')]
final class ListFormAction
{
    public function __construct(
        private readonly FormRepositoryInterface $repository,
    ) {
    }

    /**
     * List `forms` for the current caller.
     *
     * The `Repository` base picks up `filter[...]` / `sort=...` /
     * `include=...` query parameters via the `#[Filterable]` attribute
     * on the concrete repository — no per-Action wiring needed.
     *
     * @return PaginatedDataCollection<int, FormData>  Paginated wire-visible DTOs.
     */
    public function __invoke(Request $request): PaginatedDataCollection
    {
        /** @var LengthAwarePaginator<int, \Academorix\Forms\Models\Form> $page */
        $page = $this->repository->paginate(
            perPage: (int) $request->integer('per_page', 15),
        );

        return FormData::collect($page, PaginatedDataCollection::class);
    }
}
