<?php

// // AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py notifications newsletter --force`.

declare(strict_types=1);

namespace Academorix\Newsletter\Enums;

use Academorix\Enum\Enum;

/**
 * Closed-set enum for `state` on `newsletter-issue`.
 *
 * Enum: draft / scheduled / sending / sent / cancelled / archived.
 *
 * @category Newsletter
 *
 * @since    0.1.0
 */
enum NewsletterIssueState: string
{
    use Enum;

    case Draft = 'draft';
    case Scheduled = 'scheduled';
    case Sending = 'sending';
    case Sent = 'sent';
    case Cancelled = 'cancelled';
    case Archived = 'archived';
}
