<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py access invitations --force`.

declare(strict_types=1);

namespace Stackra\Invitations\Exceptions;

use Stackra\Exceptions\StackraException;

/**
 * settings.
 *
 * @category Invitations
 *
 * @since    0.1.0
 */
final class InvitationsResendCapReachedException extends StackraException
{
    /**
     * Stable machine-readable error code emitted on the JSON envelope.
     */
    public const CODE = 'INVITATIONS_RESEND_CAP_REACHED';

    /**
     * Translation key for the humanised message.
     */
    public const TRANSLATION_KEY = 'invitations::errors.INVITATIONS_RESEND_CAP_REACHED';
}
