<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py finance dunning --force`.

declare(strict_types=1);

namespace Stackra\Dunning\Services;

use Stackra\Dunning\Contracts\Services\DunningStepResolverInterface;
use Illuminate\Container\Attributes\Scoped;
use Stackra\Dunning\Contracts\Repositories\DunningEventRepositoryInterface;

/**
 * Concrete service — DunningStepResolver.
 *
 * Implements {@see DunningStepResolverInterface}. `#[Scoped]` because most
 * services touch request state (current tenant, current user,
 * correlation id) — see `.kiro/steering/octane-first-di.md`. If
 * the service is provably stateless, promote to `#[Singleton]`.
 *
 * @category Dunning
 *
 * @since    0.1.0
 */
#[Scoped]
final class DunningStepResolver implements DunningStepResolverInterface
{
    /**
     * @param  DunningEventRepositoryInterface  $dunningEventRepository  Primary persistence boundary.
     */
    public function __construct(
        private readonly DunningEventRepositoryInterface $dunningEventRepository,
    ) {
    }
}
