<?php

// // AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py sports private-sessions --force`.

declare(strict_types=1);

namespace Academorix\PrivateSessions\Actions\Tenant;

use Academorix\PrivateSessions\Contracts\Repositories\PrivateSessionRequestRepositoryInterface;
use Academorix\PrivateSessions\Data\PrivateSessionRequestData;
use Academorix\PrivateSessions\Data\Requests\CreatePrivateSessionRequestRequestData;
use Academorix\Routing\Attributes\AsController;
use Academorix\Routing\Attributes\Post;
use Illuminate\Http\JsonResponse;

/**
 * `POST /api/v1/private-session-requests` — create action (tenant audience).
 *
 * Single-invoke controller wired via `#[AsController]` + `#[Post(...)]`
 * attributes from `Academorix\Routing`. Discovered by the routing package's
 * boot-time `RouteRegistrar` — no route file needed.
 *
 * @category PrivateSessions
 *
 * @since    0.1.0
 */
#[AsController]
#[Post('/api/v1/private-session-requests')]
final class CreatePrivateSessionRequestAction
{
    public function __construct(
        private readonly PrivateSessionRequestRepositoryInterface $repository,
    ) {
    }

    /**
     * Create a `private-session-request` from the validated request payload.
     *
     * @param  CreatePrivateSessionRequestRequestData  $data  Validated payload (Spatie Data DTO).
     *
     * @return JsonResponse  201 Created with the newly-persisted DTO.
     */
    public function __invoke(CreatePrivateSessionRequestRequestData $data): JsonResponse
    {
        $model = $this->repository->create($data->toArray());

        return response()->json(PrivateSessionRequestData::from($model), JsonResponse::HTTP_CREATED);
    }
}
