<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py notifications notifications --force`.

declare(strict_types=1);

namespace Stackra\Notifications\Exceptions;

use Stackra\Exceptions\StackraException;

/**
 * Attempted to set enabled=false on a category with opt_out_allowed=false (transactional_required).
 *
 * @category Notifications
 *
 * @since    0.1.0
 */
final class NotificationsPreferenceUpdateForbiddenException extends StackraException
{
    /**
     * Stable machine-readable error code emitted on the JSON envelope.
     */
    public const CODE = 'NOTIFICATIONS_PREFERENCE_UPDATE_FORBIDDEN';

    /**
     * Translation key for the humanised message.
     */
    public const TRANSLATION_KEY = 'notifications::errors.NOTIFICATIONS_PREFERENCE_UPDATE_FORBIDDEN';
}
