<?php

/**
 * @file modules/shared/telemetry/src/Providers/TelemetryServiceProvider.php
 *
 * @description
 * Root service provider for the Telemetry domain module —
 * attribute-first end-to-end. Every contribution is attribute-
 * discovered by the shared framework loaders. The provider itself
 * declares just the module identity and which conventional resources
 * auto-load.
 *
 * ## Discoverables (zero code)
 *
 *   - Actions: `#[AsAction]` + verb attribute (ADR 0016 actions-only).
 *   - Console commands: `#[AsCommand]` — auto-discovered by the base provider's `LoadsResources(commands: true)`.
 *   - Seeder: `#[AsSeeder]` on `TelemetryPermissionSeeder` — projects `TelemetryPermission` cases into spatie/laravel-permission.
 *   - Events: `#[AsEvent]` (discovered by `academorix/events`).
 *   - Middleware: `#[AsMiddleware]` on each middleware class.
 *
 */

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py shared telemetry --force`.
declare(strict_types=1);

namespace Academorix\Telemetry\Providers;

use Academorix\ServiceProvider\Attributes\AsModule;
use Academorix\ServiceProvider\Attributes\LoadsResources;
use Academorix\ServiceProvider\Providers\ServiceProvider;

/**
 * Telemetry module service provider.
 *
 * Priority `15` places telemetry in the `shared` tier
 * boot order. Downstream modules load at a higher priority so
 * their attribute-driven wiring resolves after this module's
 * contributions land.
 *
 * @category Telemetry
 *
 * @since    0.1.0
 */
#[AsModule(name: 'Telemetry', priority: 15)]
#[LoadsResources(
    config: true,
    migrations: true,
    commands: true,
    seeders: true,
    publishables: true,
    translations: true,
)]
final class TelemetryServiceProvider extends ServiceProvider
{
}
