<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py sports event --force`.

declare(strict_types=1);

namespace Stackra\Event\Exceptions;

use Stackra\Exceptions\StackraException;

/**
 * Attempted to attach a facility from a different tenant.
 *
 * @category Event
 *
 * @since    0.1.0
 */
final class EventFacilityTenantMismatchException extends StackraException
{
    /**
     * Stable machine-readable error code emitted on the JSON envelope.
     */
    public const CODE = 'EVENT_FACILITY_TENANT_MISMATCH';

    /**
     * Translation key for the humanised message.
     */
    public const TRANSLATION_KEY = 'event::errors.EVENT_FACILITY_TENANT_MISMATCH';
}
