<?php

// // AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py growth marketing --force`.

declare(strict_types=1);

namespace Academorix\Marketing\Enums;

use Academorix\Enum\Enum;

/**
 * Closed-set enum for `reason` on `marketing-dead-letter`.
 *
 * Enum: max_attempts_exceeded / provider_permanent_failure / circuit_breaker_max_opens / invalid_payload / auth_failure.
 *
 * @category Marketing
 *
 * @since    0.1.0
 */
enum MarketingDeadLetterReason: string
{
    use Enum;

    case MaxAttemptsExceeded = 'max_attempts_exceeded';
    case ProviderPermanentFailure = 'provider_permanent_failure';
    case CircuitBreakerMaxOpens = 'circuit_breaker_max_opens';
    case InvalidPayload = 'invalid_payload';
    case AuthFailure = 'auth_failure';
}
