<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py growth leads --force`.

declare(strict_types=1);

namespace Stackra\Leads\Enums;

use Stackra\Enum\Enum;

/**
 * Closed-set enum for `lost_reason` on `lead`.
 *
 * Enum: budget / timing / competitor / not_qualified / ghost / other.
 *
 * @category Leads
 *
 * @since    0.1.0
 */
enum LeadLostReason: string
{
    use Enum;

    case Budget = 'budget';
    case Timing = 'timing';
    case Competitor = 'competitor';
    case NotQualified = 'not_qualified';
    case Ghost = 'ghost';
    case Other = 'other';
}
