<?php

// // AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py shared search --force`.

declare(strict_types=1);

namespace Academorix\Shared\Search\Policies;

use Academorix\User\Models\User;
use Academorix\Shared\Search\Models\SearchSyncJob;

/**
 * Authorization policy for {@see \Academorix\Shared\Search\Models\SearchSyncJob}.
 *
 * Wired via `#[UsePolicy]` on the Model.
 *
 * @category Search
 *
 * @since    0.1.0
 */
final class SearchSyncJobPolicy
{
    /**
     * Own jobs via query scope.
     *
     * @return bool
     */
    public function viewAny(User $user, SearchSyncJob $model): bool
    {
        return $user->can('search.sync-jobs.viewAny');
    }
    /**
     * row.
     *
     * @return bool
     */
    public function view(User $user, SearchSyncJob $model): bool
    {
        return $user->can('search.sync-jobs.view');
    }
    /**
     * row.
     *
     * @return bool
     */
    public function cancel(User $user, SearchSyncJob $model): bool
    {
        return $user->can('search.sync-jobs.cancel');
    }
    /**
     * platformViewAny ability.
     *
     * @return bool
     */
    public function platformViewAny(User $user, SearchSyncJob $model): bool
    {
        return $user->can('platform.search.sync-jobs.viewAny');
    }
    /**
     * platformView ability.
     *
     * @return bool
     */
    public function platformView(User $user, SearchSyncJob $model): bool
    {
        return $user->can('platform.search.sync-jobs.view');
    }
    /**
     * Platform admin may cancel any state with --force.
     *
     * @return bool
     */
    public function platformCancel(User $user, SearchSyncJob $model): bool
    {
        return $user->can('platform.search.sync-jobs.cancel');
    }
}
