<?php

/**
 * @file database/migrations/2026_07_15_120001_create_formations_table.php
 *
 * @description
 * Create the `formations` table for the `Formation` entity.
 * Owned by the formations module. Every column + index reference
 * goes through {@see Academorix\Formations\Contracts\Data\FormationInterface} per the `models` steering
 * rule §1 — no raw string literals.
 */
// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py sports formations --force`.

declare(strict_types=1);

use Academorix\Formations\Contracts\Data\FormationInterface;
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

return new class() extends Migration {
    /**
     * Run the migration.
     */
    public function up(): void
    {
        Schema::create(FormationInterface::TABLE, function (Blueprint $table): void {
            $table->string(FormationInterface::ATTR_ID, 30)->primary();
            $table->string(FormationInterface::ATTR_TENANT_ID, 30)->nullable();
            $table->foreign(FormationInterface::ATTR_TENANT_ID)->references('id')->on('tenants')->onDelete('cascade');
            $table->string(FormationInterface::ATTR_SPORT_KEY, 32);
            $table->string(FormationInterface::ATTR_CODE, 64);
            $table->string(FormationInterface::ATTR_NAME, 200);
            $table->integer(FormationInterface::ATTR_EXPECTED_SLOT_COUNT);
            $table->boolean(FormationInterface::ATTR_IS_ACTIVE)->default('true');
            $table->jsonb(FormationInterface::ATTR_METADATA)->nullable();
            $table->timestampTz(FormationInterface::ATTR_CREATED_AT);
            $table->timestampTz(FormationInterface::ATTR_UPDATED_AT);
            $table->timestampTz(FormationInterface::ATTR_DELETED_AT)->nullable();

        });

        DB::statement('CREATE UNIQUE INDEX formations_unique ON ' . FormationInterface::TABLE . ' (' . FormationInterface::ATTR_TENANT_ID . ', ' . FormationInterface::ATTR_SPORT_KEY . ', ' . FormationInterface::ATTR_CODE . ') WHERE deleted_at IS NULL');
    }

    /**
     * Reverse the migration.
     */
    public function down(): void
    {
        Schema::dropIfExists(FormationInterface::TABLE);
    }
};
