<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py platform ai --force`.

declare(strict_types=1);

namespace Academorix\Ai\Actions\Platform;

use Academorix\Routing\Attributes\AsAction;
use Academorix\Routing\Attributes\Middleware;
use Academorix\Routing\Concerns\AsController;
use Academorix\Routing\Attributes\Get;

/**
 * `GET /api/v1/platform/ai/token-usage` — list action (platform-admin audience).
 *
 * Single-invoke controller wired via `#[AsAction]` + `#[Get(...)]`
 * + `#[Middleware(...)]` from `Academorix\Routing`. Discovered by the routing
 * package's boot-time `RouteRegistrar` — no route file needed.
 *
 * @category Ai
 *
 * @since    0.1.0
 */
#[AsAction(name: 'ai.token_usage.list')]
#[Get('/api/v1/platform/ai/token-usage')]
#[Middleware(['api', 'auth:sanctum', 'platform_admin'])]
final class ListTokenUsageAction
{
    use AsController;

    /**
     * Execute the action.
     *
     * TODO(gen): wire the required services + implement the handler body.
     */
    public function __invoke(): mixed
    {
        // Hand-implement the domain logic here.
        return null;
    }
}
