<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py access rbac --force`.

declare(strict_types=1);

namespace Stackra\Rbac\Repositories;

use Stackra\Crud\Attributes\AsRepository;
use Stackra\Crud\Attributes\Cacheable;
use Stackra\Crud\Attributes\Filterable;
use Stackra\Crud\Attributes\UseModel;
use Stackra\Crud\Repositories\Repository;
use Stackra\Rbac\Contracts\Data\PermissionInterface;
use Stackra\Rbac\Contracts\Repositories\PermissionRepositoryInterface;
use Stackra\Rbac\Models\Permission;

/**
 * Attribute-first Eloquent repository for {@see Stackra\Rbac\Models\Permission}.
 *
 * Bound to the interface via `#[AsRepository]`; the model comes from
 * `#[UseModel(PermissionInterface::class)]` which resolves to
 * `Permission` through the interface's `#[Bind]`.
 *
 * @extends Repository<\Stackra\Rbac\Models\Permission>
 *
 * @category Rbac
 *
 * @since    0.1.0
 */
#[AsRepository]
#[UseModel(PermissionInterface::class)]
#[Cacheable(ttl: 3600, tags: true)]
#[Filterable('*')]
final class PermissionRepository extends Repository implements PermissionRepositoryInterface
{
    // Domain methods added here. CRUD comes from Repository.
}
