<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py platform ai --force`.

declare(strict_types=1);

namespace Stackra\Ai\Console;

use Stackra\Console\Attributes\AsCommand;
use Stackra\Console\Commands\BaseCommand;

/**
 * `php artisan ai:list-personas` — List personas — ai command.
 *
 * @category Ai
 *
 * @since    0.1.0
 */
#[AsCommand(
    name: 'ai:list-personas',
    description: 'List personas — ai command.',
)]
final class ListPersonasCommand extends BaseCommand
{
    /**
     * Execute the command.
     *
     * TODO(gen): wire the required services + implement the handler body.
     */
    public function handle(): int
    {
        $this->omni->titleBar('List personas — ai command', 'sky');

        // TODO(gen): wire the required services + implement the handler body.

        $this->omni->success('List personas — ai command completed.');
        $this->showDuration();

        return self::SUCCESS;
    }
}
