<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py platform credentials --force`.

declare(strict_types=1);

namespace Stackra\Credentials\Actions\Tenant;

use Stackra\Credentials\Contracts\Repositories\CredentialRepositoryInterface;
use Stackra\Credentials\Data\CredentialData;
use Stackra\Credentials\Data\Requests\CreateCredentialRequestData;
use Stackra\Routing\Attributes\AsAction;
use Stackra\Routing\Attributes\Middleware;
use Stackra\Routing\Concerns\AsController;
use Stackra\Routing\Attributes\Post;
use Illuminate\Http\JsonResponse;

/**
 * `POST /api/v1/credentials` — create action (tenant audience).
 *
 * Single-invoke controller wired via `#[AsAction]` + `#[Post(...)]`
 * + `#[Middleware(...)]` from `Stackra\Routing`. Discovered by the routing
 * package's boot-time `RouteRegistrar` — no route file needed.
 *
 * @category Credentials
 *
 * @since    0.1.0
 */
#[AsAction(name: 'credentials.create')]
#[Post('/api/v1/credentials')]
#[Middleware(['api', 'auth:sanctum', 'tenant.resolve'])]
final class CreateCredentialAction
{
    use AsController;

    public function __construct(
        private readonly CredentialRepositoryInterface $repository,
    ) {
    }

    /**
     * Create a `credential` from the validated request payload.
     *
     * @param  CreateCredentialRequestData  $data  Validated payload (Spatie Data DTO).
     *
     * @return JsonResponse  201 Created with the newly-persisted DTO.
     */
    public function __invoke(CreateCredentialRequestData $data): JsonResponse
    {
        $model = $this->repository->create($data->toArray());

        return response()->json(CredentialData::from($model), JsonResponse::HTTP_CREATED);
    }
}
