<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py growth leads --force`.

declare(strict_types=1);

namespace Academorix\Leads\Data\Requests;

use Spatie\LaravelData\Attributes\MapInputName;
use Spatie\LaravelData\Data;
use Spatie\LaravelData\Mappers\SnakeCaseMapper;
use Spatie\LaravelData\Attributes\Validation\Max;
use Spatie\LaravelData\Attributes\Validation\Min;
use Spatie\LaravelData\Attributes\Validation\Regex;
use Spatie\LaravelData\Attributes\Validation\StringType;

/**
 * Server-side create request DTO for `LeadTask`.
 *
 * Consumed by the corresponding Action; validated on construction
 * through Spatie Data's property-attribute pipeline (no `rules()`
 * method). See `.kiro/steering/data-first.md`.
 *
 * @category Leads
 *
 * @since    0.1.0
 */
#[MapInputName(SnakeCaseMapper::class)]
final class CreateLeadTaskRequestData extends Data
{
    public function __construct(
        #[StringType, Regex('/^led_[0-9A-HJKMNP-TV-Z]{26}$/')]
        public string $leadId,

        #[StringType, Regex('/^usr_[0-9A-HJKMNP-TV-Z]{26}$/')]
        public ?string $assignedToId = null,

        #[StringType]
        public string $taskType,

        #[StringType, Min(1), Max(255)]
        public string $title,

        #[StringType]
        public ?string $description = null,

        #[StringType]
        public string $priority,

        #[StringType]
        public string $status,

        #[StringType]
        public ?string $dueAt = null,

        #[StringType]
        public ?string $completedAt = null,

        #[StringType, Regex('/^usr_[0-9A-HJKMNP-TV-Z]{26}$/')]
        public ?string $completedBy = null,

        public ?array $metadata = null,
    ) {
    }
}
