<?php

// // AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py growth marketing --force`.

declare(strict_types=1);

namespace Academorix\Marketing\Contracts\Data;

use Illuminate\Container\Attributes\Bind;
use Academorix\Marketing\Models\MarketingDelivery;

/**
 * Table shape for the `marketing_deliveries` table.
 *
 * Per-provider-per-attempt delivery log.
 *
 * @category Marketing
 *
 * @since    0.1.0
 */
#[Bind(MarketingDelivery::class)]
interface MarketingDeliveryInterface
{
    /**
     * Table name.
     */
    public const string TABLE = 'marketing_deliveries';

    /**
     * Primary key column.
     */
    public const string PRIMARY_KEY = 'id';

    /**
     * Primary key column type — string (ULID with prefix `mdv_`).
     */
    public const string KEY_TYPE = 'string';

    // ── Columns ───────────────────────────────────────────────

    public const string ATTR_ID                   = 'id';
    public const string ATTR_TENANT_ID            = 'tenant_id';
    public const string ATTR_MARKETING_EVENT_ID   = 'marketing_event_id';
    public const string ATTR_PROVIDER_CONFIG_ID   = 'provider_config_id';
    public const string ATTR_PROVIDER             = 'provider';
    public const string ATTR_STATUS               = 'status';
    public const string ATTR_ATTEMPT_NUMBER       = 'attempt_number';
    public const string ATTR_REQUEST_PAYLOAD      = 'request_payload';
    public const string ATTR_REQUEST_URL          = 'request_url';
    public const string ATTR_RESPONSE_STATUS_CODE = 'response_status_code';
    public const string ATTR_RESPONSE_HEADERS     = 'response_headers';
    public const string ATTR_RESPONSE_BODY        = 'response_body';
    public const string ATTR_PROVIDER_EVENT_ID    = 'provider_event_id';
    public const string ATTR_ERROR_DETAILS        = 'error_details';
    public const string ATTR_DISPATCHED_AT        = 'dispatched_at';
    public const string ATTR_RESPONDED_AT         = 'responded_at';
    public const string ATTR_LATENCY_MS           = 'latency_ms';
    public const string ATTR_NEXT_RETRY_AT        = 'next_retry_at';
    public const string ATTR_METADATA             = 'metadata';
    public const string ATTR_CREATED_BY           = 'created_by';
    public const string ATTR_UPDATED_BY           = 'updated_by';
    public const string ATTR_CREATED_AT           = 'created_at';
    public const string ATTR_UPDATED_AT           = 'updated_at';
}
