<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py identity people --force`.

declare(strict_types=1);

namespace Stackra\People\Contracts\Services;

use Stackra\People\Services\StackraIdIssuer;
use Illuminate\Container\Attributes\Bind;

/**
 * Service contract for StackraIdIssuer.
 *
 * Bound to the concrete via `#[Bind(StackraIdIssuer::class)]`. Consumers
 * type-hint this interface; tests bind a fake through the container.
 *
 * @category People
 *
 * @since    0.1.0
 */
#[Bind(StackraIdIssuer::class)]
interface StackraIdIssuerInterface
{
    // TODO(gen): declare the domain methods this service exposes.
}
