<?php

// // AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py sports competition --force`.

declare(strict_types=1);

namespace Academorix\Sports\Competition\Policies;

use Academorix\User\Models\User;
use Academorix\Sports\Competition\Models\StandingRow;

/**
 * Authorization policy for {@see \Academorix\Sports\Competition\Models\StandingRow}.
 *
 * Wired via `#[UsePolicy]` on the Model.
 *
 * @category Competition
 *
 * @since    0.1.0
 */
final class StandingRowPolicy
{
    /**
     * Public read via signed URL — competition config decides visibility
     *
     * @return bool
     */
    public function viewAny(User $user, StandingRow $model): bool
    {
        return $user->can('competition-standings.viewAny');
    }
    /**
     * view ability.
     *
     * @return bool
     */
    public function view(User $user, StandingRow $model): bool
    {
        return $user->can('competition-standings.view');
    }
}
