<?php

// // AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py shared transfer --force`.

declare(strict_types=1);

namespace Academorix\Shared\Transfer\Data;

use Spatie\LaravelData\Attributes\MapInputName;
use Spatie\LaravelData\Data;
use Spatie\LaravelData\Mappers\SnakeCaseMapper;

/**
 * Server-side output DTO for {@see \Academorix\Shared\Transfer\Models\XferJob}.
 *
 * Consumed by controllers + services on the SERVER side. This is
 * distinct from the wire SDK's DTO (which sits under
 * `Academorix\SharedTransferSdk\Data`) — the wire DTO travels across the HTTP
 * boundary; this one stays in-process.
 *
 * @category Transfer
 *
 * @since    0.1.0
 */
#[MapInputName(SnakeCaseMapper::class)]
final class XferJobData extends Data
{
    public function __construct(
        public string $id,
        public string $causerType,
        public string $causerId,
        public string $kind,
        public string $entity,
        public string $status,
        public array $counters,
        public array $notifyChannels,
        public string $notifyLocale,
        public string $retentionTier,
        public string $queueName,
        public int $shardsTotal,
        public int $shardsCompleted,
        public int $progressPercent,
        public string $createdAt,
        public string $updatedAt,
        public ?string $tenantId = null,
        public ?string $mode = null,
        public ?string $format = null,
        public ?array $params = null,
        public ?array $filters = null,
        public ?string $mappingProfileId = null,
        public ?string $sourceFilename = null,
        public ?int $sourceFileSizeBytes = null,
        public ?string $sourceArtifactId = null,
        public ?string $resultArtifactId = null,
        public ?string $errorsArtifactId = null,
        public ?string $queueConnection = null,
        public ?string $startedAt = null,
        public ?string $finishedAt = null,
        public ?string $lastProgressAt = null,
        public ?string $artifactPurgedAt = null,
        public ?string $lastErrorMessage = null,
        public ?string $lastErrorCode = null,
        public ?string $cancelledByType = null,
        public ?string $cancelledById = null,
        public ?string $cancelReason = null,
        public ?string $deletedAt = null,
    ) {
    }
}
