<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py platform realtime --force`.

declare(strict_types=1);

namespace Stackra\Realtime\Database\Seeders;

use Stackra\Realtime\Enums\RealtimePermission;
use Stackra\Authorization\Database\Seeders\Concerns\SeedsPermissionEnum;
use Stackra\ServiceProvider\Attributes\AsSeeder;
use Illuminate\Database\Seeder;

/**
 * Seed the {@see RealtimePermission} cases into spatie/laravel-permission's
 * `permissions` table.
 *
 * All the boilerplate (spatie model resolution, `updateOrCreate` loop,
 * cache flush) lives in the shared {@see SeedsPermissionEnum} trait.
 *
 * @category Realtime
 *
 * @since    0.1.0
 */
#[AsSeeder(priority: 46, environments: [])]
final class RealtimePermissionSeeder extends Seeder
{
    use SeedsPermissionEnum;

    /**
     * {@inheritDoc}
     */
    protected function permissionEnums(): array
    {
        return [RealtimePermission::class];
    }
}
