<?php

// // AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py sports registry --force`.

declare(strict_types=1);

namespace Academorix\Sports\Registry\Events;

use Illuminate\Contracts\Events\ShouldDispatchAfterCommit;

/**
 * A tenant created a custom Position.
 *
 * ## Consumers
 *
 * - audit::WriteToAuditLog
 * - activity::WriteToActivityLog
 *
 * @category Registry
 *
 * @since    0.1.0
 */
final readonly class TenantCustomPositionCreated implements ShouldDispatchAfterCommit
{
    /**
     * @param  string  $positionId  ULID
     * @param  string  $disciplineId  ULID
     * @param  bool  $disciplineIsPlatformSeeded  boolean (true when hanging a custom Position off a platform Discipline)
     * @param  string  $tenantId  ULID
     * @param  string  $slug  string
     * @param  string  $createdBy  ULID
     */
    public function __construct(
        public readonly string $positionId,
        public readonly string $disciplineId,
        public readonly bool $disciplineIsPlatformSeeded,
        public readonly string $tenantId,
        public readonly string $slug,
        public readonly string $createdBy,
    ) {
    }
}
