<?php

// // AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py platform organization --force`.

declare(strict_types=1);

namespace Academorix\Organization\Events;

use Illuminate\Contracts\Events\ShouldDispatchAfterCommit;

/**
 * `parent_id` changed on an existing row. Fires on both nulling (child → root) and setting (root → child, or child → new parent).
 *
 * ## Consumers
 *
 * - organization::DispatchRebuildTreePathsJob
 * - activity::WriteToActivityLog
 * - audit::WriteCriticalAuditRow
 * - notifications::DispatchOrganizationReparentedNotification
 * - branch::InvalidateBranchScopeCaches
 *
 * @category Organization
 *
 * @since    0.1.0
 */
final readonly class OrganizationParentChanged implements ShouldDispatchAfterCommit
{
    /**
     * @param  string  $organization  Organization
     * @param  string  $oldParentId  string | null
     * @param  string  $newParentId  string | null
     * @param  string  $oldTreePath  string
     * @param  string  $newTreePath  string
     * @param  int  $oldDepth  integer
     * @param  int  $newDepth  integer
     * @param  int  $descendantCount  integer
     * @param  string  $actorId  string | null
     * @param  string  $reason  string | null
     */
    public function __construct(
        public readonly string $organization,
        public readonly string $oldParentId,
        public readonly string $newParentId,
        public readonly string $oldTreePath,
        public readonly string $newTreePath,
        public readonly int $oldDepth,
        public readonly int $newDepth,
        public readonly int $descendantCount,
        public readonly string $actorId,
        public readonly string $reason,
    ) {
    }
}
