<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py platform organization --force`.

declare(strict_types=1);

namespace Stackra\Organization\Actions\Tenant;

use Stackra\Organization\Contracts\Repositories\OrganizationRepositoryInterface;
use Stackra\Routing\Attributes\AsAction;
use Stackra\Routing\Attributes\Middleware;
use Stackra\Routing\Concerns\AsController;
use Stackra\Routing\Attributes\Delete;
use Illuminate\Http\Response;

/**
 * `DELETE /api/v1/organizations/{organization}` — delete action (tenant audience).
 *
 * Single-invoke controller wired via `#[AsAction]` + `#[Delete(...)]`
 * + `#[Middleware(...)]` from `Stackra\Routing`. Discovered by the routing
 * package's boot-time `RouteRegistrar` — no route file needed.
 *
 * @category Organization
 *
 * @since    0.1.0
 */
#[AsAction(name: 'organization.organizations.delete')]
#[Delete('/api/v1/organizations/{organization}')]
#[Middleware(['api', 'auth:sanctum', 'tenant.resolve'])]
final class DeleteOrganizationAction
{
    use AsController;

    public function __construct(
        private readonly OrganizationRepositoryInterface $repository,
    ) {
    }

    /**
     * Soft-delete one `organization` by id.
     *
     * @param  string  $id  Primary key.
     *
     * @throws \Illuminate\Database\Eloquent\ModelNotFoundException  When the row is absent or hidden by scoping.
     */
    public function __invoke(string $id): Response
    {
        $this->repository->delete($id);

        return response()->noContent();
    }
}
