<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py finance membership --force`.

declare(strict_types=1);

namespace Stackra\Membership\Actions\Tenant;

use Stackra\Membership\Contracts\Repositories\MembershipRepositoryInterface;
use Stackra\Membership\Data\MembershipData;
use Stackra\Routing\Attributes\AsAction;
use Stackra\Routing\Attributes\Middleware;
use Stackra\Routing\Concerns\AsController;
use Stackra\Routing\Attributes\Get;
use Illuminate\Http\Request;
use Illuminate\Pagination\LengthAwarePaginator;
use Spatie\LaravelData\PaginatedDataCollection;

/**
 * `GET /api/v1/memberships` — list action (tenant audience).
 *
 * Single-invoke controller wired via `#[AsAction]` + `#[Get(...)]`
 * + `#[Middleware(...)]` from `Stackra\Routing`. Discovered by the routing
 * package's boot-time `RouteRegistrar` — no route file needed.
 *
 * @category Membership
 *
 * @since    0.1.0
 */
#[AsAction(name: 'membership.memberships.list')]
#[Get('/api/v1/memberships')]
#[Middleware(['api', 'auth:sanctum', 'tenant.resolve'])]
final class ListMembershipAction
{
    use AsController;

    public function __construct(
        private readonly MembershipRepositoryInterface $repository,
    ) {
    }

    /**
     * List `memberships` for the current caller.
     *
     * The `Repository` base picks up `filter[...]` / `sort=...` /
     * `include=...` query parameters via the `#[Filterable]` attribute
     * on the concrete repository — no per-Action wiring needed.
     *
     * @return PaginatedDataCollection<int, MembershipData>  Paginated wire-visible DTOs.
     */
    public function __invoke(Request $request): PaginatedDataCollection
    {
        /** @var LengthAwarePaginator<int, \Stackra\Membership\Models\Membership> $page */
        $page = $this->repository->paginate(
            perPage: (int) $request->integer('per_page', 15),
        );

        return MembershipData::collect($page, PaginatedDataCollection::class);
    }
}
