<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py finance payment --force`.

declare(strict_types=1);

namespace Stackra\Payment\Contracts\Repositories;

use Stackra\Crud\Contracts\RepositoryInterface;

/**
 * Repository contract for {@see Stackra\Payment\Models\PaymentIntent}.
 *
 * Consumers type-hint the interface; the container binds the concrete
 * via `#[AsRepository]` on `PaymentIntentRepository`.
 *
 * @extends RepositoryInterface<\Stackra\Payment\Models\PaymentIntent>
 *
 * @category Payment
 *
 * @since    0.1.0
 */
interface PaymentIntentRepositoryInterface extends RepositoryInterface
{
    // Domain-specific query methods live here. CRUD comes from the base.
}
