<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py sports session --force`.

declare(strict_types=1);

namespace Stackra\Session\Exceptions;

use Stackra\Exceptions\StackraException;

/**
 * Cross-tenant FK smuggling — booking belongs to a different tenant.
 *
 * @category Session
 *
 * @since    0.1.0
 */
final class SessionResourceBookingTenantMismatchException extends StackraException
{
    /**
     * Stable machine-readable error code emitted on the JSON envelope.
     */
    public const CODE = 'SESSION_RESOURCE_BOOKING_TENANT_MISMATCH';

    /**
     * Translation key for the humanised message.
     */
    public const TRANSLATION_KEY = 'session::errors.SESSION_RESOURCE_BOOKING_TENANT_MISMATCH';
}
