<?php

// // AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py identity identity --force`.

declare(strict_types=1);

namespace Academorix\Identity\Identity\Events;

use Illuminate\Contracts\Events\ShouldDispatchAfterCommit;

/**
 * New EmailVerificationToken issued (registration OR email-change flow). Debounced 60s per identity_id.
 *
 * ## Consumers
 *
 * - notifications::DispatchEmailVerificationNotification
 *
 * @category Identity
 *
 * @since    0.1.0
 */
final readonly class IdentityEmailVerificationRequested implements ShouldDispatchAfterCommit
{
    /**
     * @param  string  $identityId  ULID
     * @param  string  $emailFingerprint  string
     * @param  string  $tokenExpiresAt  ISO-8601 timestamp
     * @param  string  $reason  'registration' | 'email_change' | 'resend'
     */
    public function __construct(
        public readonly string $identityId,
        public readonly string $emailFingerprint,
        public readonly string $tokenExpiresAt,
        public readonly string $reason,
    ) {
    }
}
