<?php

// // AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py growth attribution --force`.

declare(strict_types=1);

namespace Academorix\Attribution\Services;

use Academorix\Attribution\Contracts\Services\CampaignRollupAggregatorInterface;
use Illuminate\Container\Attributes\Scoped;
use Academorix\Attribution\Contracts\Repositories\AttributionTouchpointRepositoryInterface;

/**
 * Concrete service — CampaignRollupAggregator.
 *
 * Implements {@see CampaignRollupAggregatorInterface}. `#[Scoped]` because most
 * services touch request state (current tenant, current user,
 * correlation id) — see `.kiro/steering/octane-first-di.md`. If
 * the service is provably stateless, promote to `#[Singleton]`.
 *
 * @category Attribution
 *
 * @since    0.1.0
 */
#[Scoped]
final class CampaignRollupAggregator implements CampaignRollupAggregatorInterface
{
    /**
     * @param  AttributionTouchpointRepositoryInterface  $attributionTouchpointRepository  Primary persistence boundary.
     */
    public function __construct(
        private readonly AttributionTouchpointRepositoryInterface $attributionTouchpointRepository,
    ) {
    }
}
