<?php

// // AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py finance chargeback --force`.

declare(strict_types=1);

namespace Academorix\Chargeback\Events;

use Illuminate\Contracts\Events\ShouldDispatchAfterCommit;

/**
 * FinalizeChargebackJob step 1 completed — the disputed amount recorded as an offsetting Transaction (debit chargebacks_expense, credit cash).
 *
 * ## Consumers
 *
 * - audit::WriteToAuditLog (retention: 7 years — financial record)
 * - activity::WriteToActivityLog
 * - observability::MetricsCollector (academorix.chargeback.losses_total_cents counter — sum of amount_cents)
 *
 * @category Chargeback
 *
 * @since    0.1.0
 */
final readonly class ChargebackTransactionRecorded implements ShouldDispatchAfterCommit
{
    /**
     * @param  string  $chargebackId  ULID
     * @param  string  $tenantId  ULID
     * @param  string  $transactionId  ULID (trx_*)
     * @param  int  $amountCents  integer
     * @param  string  $currency  string
     * @param  string  $recordedAt  ISO 8601
     */
    public function __construct(
        public readonly string $chargebackId,
        public readonly string $tenantId,
        public readonly string $transactionId,
        public readonly int $amountCents,
        public readonly string $currency,
        public readonly string $recordedAt,
    ) {
    }
}
