<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py sports drills --force`.

declare(strict_types=1);

namespace Academorix\Drills\Console;

use Academorix\Console\Attributes\AsCommand;
use Academorix\Console\Console\Commands\BaseCommand;

/**
 * `php artisan drills:reindex-search` — Reindex search — drills command.
 *
 * @category Drills
 *
 * @since    0.1.0
 */
#[AsCommand(
    name: 'drills:reindex-search',
    description: 'Reindex search — drills command.',
)]
final class ReindexSearchCommand extends BaseCommand
{
    /**
     * Execute the command.
     *
     * TODO(gen): wire the required services + implement the handler body.
     */
    public function handle(): int
    {
        $this->omni->titleBar('Reindex search — drills command', 'sky');

        // TODO(gen): wire the required services + implement the handler body.

        $this->omni->success('Reindex search — drills command completed.');
        $this->showDuration();

        return self::SUCCESS;
    }
}
