<?php

// // AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py platform theme --force`.

declare(strict_types=1);

namespace Academorix\Theme\Console;

use Academorix\Console\Attributes\AsCommand;
use Academorix\Console\Console\Commands\BaseCommand;

/**
 * `php artisan theme-preset:create` — TODO(gen): describe what this command does.
 *
 * @category Theme
 *
 * @since    0.1.0
 */
#[AsCommand(
    name: 'theme-preset:create',
    description: 'TODO(gen): one-line description shown by `artisan list`.',
)]
final class CreateCommand extends BaseCommand
{
    /**
     * Execute the command.
     *
     * TODO(gen): wire the required services + implement the handler body.
     */
    public function handle(): int
    {
        return self::SUCCESS;
    }
}
