<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py sports development --force`.

declare(strict_types=1);

namespace Stackra\Development\Actions\Tenant;

use Stackra\Routing\Attributes\AsAction;
use Stackra\Routing\Attributes\Middleware;
use Stackra\Routing\Concerns\AsController;
use Stackra\Routing\Attributes\Post;

/**
 * `POST /api/v1/goals/{goal}/review` — custom action (tenant audience).
 *
 * Single-invoke controller wired via `#[AsAction]` + `#[Post(...)]`
 * + `#[Middleware(...)]` from `Stackra\Routing`. Discovered by the routing
 * package's boot-time `RouteRegistrar` — no route file needed.
 *
 * @category Development
 *
 * @since    0.1.0
 */
#[AsAction(name: 'development.review.review')]
#[Post('/api/v1/goals/{goal}/review')]
#[Middleware(['api', 'auth:sanctum', 'tenant.resolve'])]
final class ReviewAction
{
    use AsController;

    /**
     * Execute the action.
     *
     * TODO(gen): wire the required services + implement the handler body.
     */
    public function __invoke(): mixed
    {
        // Hand-implement the domain logic here.
        return null;
    }
}
