<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py finance payment --force`.

declare(strict_types=1);

namespace Academorix\Payment\Events;

use Stackra\Events\Attributes\AsEvent;
use Illuminate\Contracts\Events\ShouldDispatchAfterCommit;

/**
 * Admin configured a new provider config via POST /payment-providers.
 *
 * ## Consumers
 *
 * - audit::WriteToAuditLog (retention: 7 years — provider connection is a compliance-relevant integration)
 * - notifications::DispatchPaymentConfigurationChangedNotification (audit trail for tenant admins)
 *
 * @category Payment
 *
 * @since    0.1.0
 */
#[AsEvent]
final readonly class PaymentProviderConfigured implements ShouldDispatchAfterCommit
{
    /**
     * @param  string  $providerConfigId  ULID
     * @param  string  $tenantId  ULID
     * @param  string  $provider  string
     * @param  string  $configuredByUserId  ULID
     * @param  string  $configuredAt  ISO 8601
     */
    public function __construct(
        public readonly string $providerConfigId,
        public readonly string $tenantId,
        public readonly string $provider,
        public readonly string $configuredByUserId,
        public readonly string $configuredAt,
    ) {
    }
}
