<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py finance payment --force`.

declare(strict_types=1);

namespace Stackra\Payment\Events;

use Stackra\Events\Attributes\AsEvent;
use Illuminate\Contracts\Events\ShouldDispatchAfterCommit;

/**
 * Status transitioned to 'processing'. Provider accepted the confirmation and is processing async. Terminal within a short window (seconds to minutes).
 *
 * ## Consumers
 *
 * - monitoring::MetricsCollector
 *
 * @category Payment
 *
 * @since    0.1.0
 */
#[AsEvent]
final readonly class PaymentIntentProcessing implements ShouldDispatchAfterCommit
{
    /**
     * @param  string  $paymentIntentId  ULID
     * @param  string  $tenantId  ULID
     * @param  string  $at  ISO 8601
     */
    public function __construct(
        public readonly string $paymentIntentId,
        public readonly string $tenantId,
        public readonly string $at,
    ) {
    }
}
