<?php

// // AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py sports athlete --force`.

declare(strict_types=1);

namespace Academorix\Athlete\Services;

use Academorix\Athlete\Contracts\Services\AthleteConsentGateInterface;
use Illuminate\Container\Attributes\Scoped;

/**
 * Concrete service — AthleteConsentGate.
 *
 * Implements {@see AthleteConsentGateInterface}. `#[Scoped]` because most
 * services touch request state (current tenant, current user,
 * correlation id) — see `.kiro/steering/octane-first-di.md`. If the
 * service is provably stateless, promote to `#[Singleton]`.
 *
 * @category Athlete
 *
 * @since    0.1.0
 */
#[Scoped]
final class AthleteConsentGate implements AthleteConsentGateInterface
{
    // TODO(gen): implement the interface methods.
}
