<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py sports medical --force`.

declare(strict_types=1);

namespace Academorix\Medical\Repositories;

use Stackra\Crud\Attributes\AsRepository;
use Stackra\Crud\Attributes\Cacheable;
use Stackra\Crud\Attributes\Filterable;
use Stackra\Crud\Attributes\UseModel;
use Stackra\Crud\Repositories\Repository;
use Academorix\Medical\Contracts\Data\AllergyInterface;
use Academorix\Medical\Contracts\Repositories\AllergyRepositoryInterface;
use Academorix\Medical\Models\Allergy;

/**
 * Attribute-first Eloquent repository for {@see Academorix\Medical\Models\Allergy}.
 *
 * Bound to the interface via `#[AsRepository]`; the model comes from
 * `#[UseModel(AllergyInterface::class)]` which resolves to
 * `Allergy` through the interface's `#[Bind]`.
 *
 * @extends Repository<\Academorix\Medical\Models\Allergy>
 *
 * @category Medical
 *
 * @since    0.1.0
 */
#[AsRepository]
#[UseModel(AllergyInterface::class)]
#[Cacheable(ttl: 3600, tags: true)]
#[Filterable('*')]
final class AllergyRepository extends Repository implements AllergyRepositoryInterface
{
    // Domain methods added here. CRUD comes from Repository.
}
