<?php

// // AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py platform storage --force`.

declare(strict_types=1);

namespace Academorix\Storage\Repositories;

use Academorix\Crud\Attributes\AsRepository;
use Academorix\Crud\Attributes\Cacheable;
use Academorix\Crud\Attributes\Filterable;
use Academorix\Crud\Attributes\UseModel;
use Academorix\Crud\Repositories\Repository;
use Academorix\Storage\Contracts\Data\FileInterface;
use Academorix\Storage\Contracts\Repositories\FileRepositoryInterface;
use Academorix\Storage\Models\File;

/**
 * Attribute-first Eloquent repository for {@see Academorix\Storage\Models\File}.
 *
 * Bound to the interface via `#[AsRepository]`; the model comes from
 * `#[UseModel(FileInterface::class)]` which resolves to
 * `File` through the interface's `#[Bind]`.
 *
 * @extends Repository<\Academorix\Storage\Models\File>
 *
 * @category Storage
 *
 * @since    0.1.0
 */
#[AsRepository]
#[UseModel(FileInterface::class)]
#[Cacheable(ttl: 3600, tags: true)]
#[Filterable('*')]
final class FileRepository extends Repository implements FileRepositoryInterface
{
    // Domain methods added here. CRUD comes from Repository.
}
