<?php

// // AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py finance invoice --force`.

declare(strict_types=1);

namespace Academorix\Finance\Invoice\Events;

use Illuminate\Contracts\Events\ShouldDispatchAfterCommit;

/**
 * InvoiceLineObserver.updating detected mutation while parent invoice.status='draft'. Refused post-finalize.
 *
 * ## Consumers
 *
 * - audit::WriteToAuditLog
 *
 * @category Invoice
 *
 * @since    0.1.0
 */
final readonly class InvoiceLineUpdated implements ShouldDispatchAfterCommit
{
    /**
     * @param  string  $invoiceLineId  ULID
     * @param  string  $invoiceId  ULID
     * @param  string  $tenantId  ULID
     * @param  string  $changedFields  string[]
     * @param  string  $updatedAt  ISO 8601
     */
    public function __construct(
        public readonly string $invoiceLineId,
        public readonly string $invoiceId,
        public readonly string $tenantId,
        public readonly string $changedFields,
        public readonly string $updatedAt,
    ) {
    }
}
