<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py identity user --force`.

declare(strict_types=1);

namespace Stackra\User\Actions\Platform;

use Stackra\User\Contracts\Repositories\UserRepositoryInterface;
use Stackra\User\Data\UserData;
use Stackra\Routing\Attributes\AsAction;
use Stackra\Routing\Attributes\Middleware;
use Stackra\Routing\Concerns\AsController;
use Stackra\Routing\Attributes\Get;
use Illuminate\Http\Request;
use Illuminate\Pagination\LengthAwarePaginator;
use Spatie\LaravelData\PaginatedDataCollection;

/**
 * `GET /api/v1/platform/users` — list action (platform-admin audience).
 *
 * Single-invoke controller wired via `#[AsAction]` + `#[Get(...)]`
 * + `#[Middleware(...)]` from `Stackra\Routing`. Discovered by the routing
 * package's boot-time `RouteRegistrar` — no route file needed.
 *
 * @category User
 *
 * @since    0.1.0
 */
#[AsAction(name: 'user.users.list')]
#[Get('/api/v1/platform/users')]
#[Middleware(['api', 'auth:sanctum', 'platform_admin'])]
final class ListUserAction
{
    use AsController;

    public function __construct(
        private readonly UserRepositoryInterface $repository,
    ) {
    }

    /**
     * List `users` for the current caller.
     *
     * The `Repository` base picks up `filter[...]` / `sort=...` /
     * `include=...` query parameters via the `#[Filterable]` attribute
     * on the concrete repository — no per-Action wiring needed.
     *
     * @return PaginatedDataCollection<int, UserData>  Paginated wire-visible DTOs.
     */
    public function __invoke(Request $request): PaginatedDataCollection
    {
        /** @var LengthAwarePaginator<int, \Stackra\User\Models\User> $page */
        $page = $this->repository->paginate(
            perPage: (int) $request->integer('per_page', 15),
        );

        return UserData::collect($page, PaginatedDataCollection::class);
    }
}
