<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py shared geography --force`.

declare(strict_types=1);

namespace Academorix\Geography\Events;

use Academorix\Events\Attributes\AsEvent;
use Illuminate\Contracts\Events\ShouldDispatchAfterCommit;

/**
 * Domain event: CountryCreated.
 *
 * ## Consumers
 *
 * - geography::OnCountryCreated (invalidates geography.cache tags)
 *
 * @category Geography
 *
 * @since    0.1.0
 */
#[AsEvent]
final readonly class CountryCreated implements ShouldDispatchAfterCommit
{
    /**
     * @param  int  $countryId  integer
     * @param  string  $iso2  string
     */
    public function __construct(
        public readonly int $countryId,
        public readonly string $iso2,
    ) {
    }
}
