<?php

// // AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py identity mfa --force`.

declare(strict_types=1);

namespace Academorix\Mfa\Services;

use Academorix\Mfa\Contracts\Services\WebauthnAssertionVerifierInterface;
use Illuminate\Container\Attributes\Scoped;

/**
 * Concrete service — WebauthnAssertionVerifier.
 *
 * Implements {@see WebauthnAssertionVerifierInterface}. `#[Scoped]` because most
 * services touch request state (current tenant, current user,
 * correlation id) — see `.kiro/steering/octane-first-di.md`. If the
 * service is provably stateless, promote to `#[Singleton]`.
 *
 * @category Mfa
 *
 * @since    0.1.0
 */
#[Scoped]
final class WebauthnAssertionVerifier implements WebauthnAssertionVerifierInterface
{
    // TODO(gen): implement the interface methods.
}
