<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py compliance compliance --force`.

declare(strict_types=1);

namespace Academorix\Compliance\Console;

use Academorix\Console\Attributes\AsCommand;
use Academorix\Console\Commands\BaseCommand;

/**
 * `php artisan compliance:seed-subprocessors` — Seed subprocessors — compliance command.
 *
 * @category Compliance
 *
 * @since    0.1.0
 */
#[AsCommand(
    name: 'compliance:seed-subprocessors',
    description: 'Seed subprocessors — compliance command.',
)]
final class SeedSubprocessorsCommand extends BaseCommand
{
    /**
     * Execute the command.
     *
     * TODO(gen): wire the required services + implement the handler body.
     */
    public function handle(): int
    {
        $this->omni->titleBar('Seed subprocessors — compliance command', 'sky');

        // TODO(gen): wire the required services + implement the handler body.

        $this->omni->success('Seed subprocessors — compliance command completed.');
        $this->showDuration();

        return self::SUCCESS;
    }
}
