<?php

// // AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py access rbac --force`.

declare(strict_types=1);

namespace Academorix\Rbac\Exceptions;

use Academorix\Exceptions\AcademorixException;

/**
 * Attempted to hard-delete a role that still has active assignments.
 *
 * @category Rbac
 *
 * @since    0.1.0
 */
final class RoleInUseException extends AcademorixException
{
    /**
     * Stable machine-readable error code emitted on the JSON envelope.
     */
    public const CODE = 'ROLE_IN_USE';

    /**
     * Translation key for the humanised message.
     */
    public const TRANSLATION_KEY = 'rbac::errors.ROLE_IN_USE';
}
