<?php

// // AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py sports competition --force`.

declare(strict_types=1);

namespace Academorix\Competition\Services;

use Academorix\Competition\Contracts\Services\StandingsCalculatorInterface;
use Illuminate\Container\Attributes\Scoped;
use Academorix\Competition\Contracts\Repositories\BracketNodeRepositoryInterface;

/**
 * Concrete service — StandingsCalculator.
 *
 * Implements {@see StandingsCalculatorInterface}. `#[Scoped]` because most
 * services touch request state (current tenant, current user,
 * correlation id) — see `.kiro/steering/octane-first-di.md`. If
 * the service is provably stateless, promote to `#[Singleton]`.
 *
 * @category Competition
 *
 * @since    0.1.0
 */
#[Scoped]
final class StandingsCalculator implements StandingsCalculatorInterface
{
    /**
     * @param  BracketNodeRepositoryInterface  $bracketNodeRepository  Primary persistence boundary.
     */
    public function __construct(
        private readonly BracketNodeRepositoryInterface $bracketNodeRepository,
    ) {
    }
}
