<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py sports attendance --force`.

declare(strict_types=1);

namespace Academorix\Attendance\Exceptions;

use Stackra\Exceptions\Exception;

/**
 * Cannot delete an active policy.
 *
 * @category Attendance
 *
 * @since    0.1.0
 */
final class AttendancePolicyActiveCannotDeleteException extends Exception
{
    /**
     * Stable machine-readable error code emitted on the JSON envelope.
     */
    public const CODE = 'ATTENDANCE_POLICY_ACTIVE_CANNOT_DELETE';

    /**
     * Translation key for the humanised message.
     */
    public const TRANSLATION_KEY = 'attendance::errors.ATTENDANCE_POLICY_ACTIVE_CANNOT_DELETE';
}
