/**
 * @file pwa.config.ts
 * @module config/pwa.config
 *
 * @description
 * Single source of truth for **everything that lands in the Web App
 * Manifest** and **everything Workbox emits into the service worker**.
 * `vite.config.ts` consumes this file at build time; nothing else does.
 *
 * ## Why split this out of vite.config.ts
 *
 *  1. The manifest is data, not build logic. Keeping it in `vite.config`
 *     buried it under 200 lines of chunk-splitting minutiae.
 *  2. Arabic (and future) translations need a typed table to pull from —
 *     see {@link buildManifest} which composes the localized values from
 *     `i18n.config.ts` at build time.
 *  3. Desktop (Tauri) and future admin surfaces will want to read the
 *     same manifest values (theme_color, icon paths, shortcuts) without
 *     importing from `vite.config.ts` — which is not a runtime module.
 *  4. Tests can import + snapshot the manifest without spinning up Vite.
 *
 * ## What lives here
 *
 *  - {@link BRAND_COLORS}          — hex values referenced by the manifest,
 *                                    index.html theme-color, and vercel
 *                                    security headers. One place, three
 *                                    consumers.
 *  - {@link MANIFEST_ICONS}        — icon file registry.
 *  - {@link MANIFEST_SHORTCUTS}    — app shortcut registry with stable ids
 *                                    that i18n.config.ts translates.
 *  - {@link buildManifest}         — pure function returning the final
 *                                    manifest object with `translations`
 *                                    injected from PWA_MANIFEST_TRANSLATIONS.
 *  - {@link WORKBOX_OPTIONS}       — runtime caching + navigation fallback
 *                                    rules for the service worker.
 *  - {@link PWA_PLUGIN_OPTIONS}    — the full `VitePWA()` argument.
 *
 * ## What does NOT live here
 *
 *  - Vite build options (chunk splitting, minification, etc.) — those
 *    stay in `vite.config.ts`.
 *  - Icon rasterization — see `pwa-assets.config.ts` at the package
 *    root. Consumed by `@vite-pwa/assets-generator`, invoked manually.
 *  - Service-worker JS handlers (push, click) — those will live in
 *    `src/pwa/sw/` once we migrate from `generateSW` to `injectManifest`
 *    per notifications module § phase 2.
 *
 * ## Design notes
 *
 *  - Zero runtime deps. `import.meta.env` NOT used here — this file must
 *    remain safe for Node import from vite.config.ts.
 *  - Every string that ends up user-visible is either a fixed English
 *    value (matched at the OS install prompt) OR routed through
 *    `PWA_MANIFEST_TRANSLATIONS` in i18n.config.ts.
 */

import { PWA_MANIFEST_TRANSLATIONS } from "./i18n.config";

import type { VitePWAOptions } from "vite-plugin-pwa";

// ---------------------------------------------------------------------------
// Brand tokens
// ---------------------------------------------------------------------------

/**
 * Colour tokens that the manifest, `<meta name="theme-color">`, and
 * pinned-tab SVG mask all read. Kept as a plain constant so every
 * consumer (Vite plugin, index.html generator, Tauri Rust config) sees
 * the same values.
 *
 * Values match HeroUI Pro's default accent (sky-500) so the installed-
 * app chrome matches the primary CTA colour.
 */
export const BRAND_COLORS = {
  /** Primary tint. Used by browser chrome + splash screen top strip. */
  themeLight: "#0EA5E9",
  /** Dark-mode variant of the tint. Used by dark-scheme theme-color. */
  themeDark: "#0369A1",
  /** Splash screen background. White to match the default canvas. */
  background: "#FFFFFF",
  /** Safari pinned-tab mask colour (same as themeLight). */
  maskIcon: "#0EA5E9",
  /** Windows tile background (msapplication-TileColor). */
  msTile: "#0EA5E9",
} as const;

// ---------------------------------------------------------------------------
// Icons
// ---------------------------------------------------------------------------

/**
 * Icon file registry. The physical files are generated by
 * `@vite-pwa/assets-generator` (see `pwa-assets.config.ts`) from the
 * master `public/academorix-icon-tile.png` (brand-provided 1024×1024
 * tile). Any addition here means the generator needs a new preset entry
 * too.
 *
 * Order matters: browsers pick the first matching icon per role, so the
 * legacy 64×64 comes first for the tab-strip favicon, then the standard
 * Android/iOS sizes, then the maskable variant last.
 */
export const MANIFEST_ICONS = [
  { src: "/pwa-64x64.png", sizes: "64x64", type: "image/png", purpose: "any" },
  { src: "/pwa-192x192.png", sizes: "192x192", type: "image/png", purpose: "any" },
  { src: "/pwa-512x512.png", sizes: "512x512", type: "image/png", purpose: "any" },
  { src: "/apple-touch-icon.png", sizes: "180x180", type: "image/png", purpose: "any" },
  {
    src: "/maskable-icon-512x512.png",
    sizes: "512x512",
    type: "image/png",
    purpose: "maskable",
  },
] as const;

// ---------------------------------------------------------------------------
// Shortcuts
// ---------------------------------------------------------------------------

/**
 * Shape of an OS-level app shortcut (right-click / long-press on the app
 * icon). The `id` field is our OWN addition — not part of the manifest
 * spec — used by {@link buildManifest} to look up translations from
 * `i18n.config.ts`. It is stripped before serialization.
 */
export interface ManifestShortcut {
  /** Stable id for i18n translation lookup. Not written to manifest. */
  id: string;
  /** Default (English) name shown on the shortcut. */
  name: string;
  /** Default short name — target ≤ 12 chars per platform HIG. */
  shortName: string;
  /** One-line description shown in some install prompts. */
  description: string;
  /** URL to open when the shortcut is invoked. Must start with `/`. */
  url: string;
  /** Icon references — subset of {@link MANIFEST_ICONS} typically. */
  icons: ReadonlyArray<{ src: string; sizes: string; type: string }>;
}

/**
 * Default shortcut registry. Curated to the four screens most-loaded
 * during a shift. Every URL carries `?source=pwa-shortcut` for analytics.
 */
export const MANIFEST_SHORTCUTS: readonly ManifestShortcut[] = [
  {
    id: "dashboard",
    name: "Dashboard",
    shortName: "Home",
    description: "Overview of today's activity + KPIs",
    url: "/dashboard?source=pwa-shortcut",
    icons: [{ src: "/pwa-192x192.png", sizes: "192x192", type: "image/png" }],
  },
  {
    id: "athletes",
    name: "Athletes",
    shortName: "Athletes",
    description: "Roster + registration + safeguarding",
    url: "/athletes?source=pwa-shortcut",
    icons: [{ src: "/pwa-192x192.png", sizes: "192x192", type: "image/png" }],
  },
  {
    id: "sessions",
    name: "Sessions",
    shortName: "Sessions",
    description: "Training sessions + attendance",
    url: "/sessions?source=pwa-shortcut",
    icons: [{ src: "/pwa-192x192.png", sizes: "192x192", type: "image/png" }],
  },
  {
    id: "command",
    name: "Command Palette",
    shortName: "Search",
    description: "Jump anywhere with ⌘K",
    url: "/?command=open&source=pwa-shortcut",
    icons: [{ src: "/pwa-192x192.png", sizes: "192x192", type: "image/png" }],
  },
] as const;

// ---------------------------------------------------------------------------
// Manifest builder
// ---------------------------------------------------------------------------

/**
 * Shape of the per-locale manifest translation the W3C draft (and
 * Chromium ≥ 100) recognizes. Kept as our own interface because the
 * `vite-plugin-pwa` types don't yet include it.
 */
interface ManifestTranslationEntry {
  name?: string;
  short_name?: string;
  description?: string;
  shortcuts?: Array<{
    url: string;
    name?: string;
    short_name?: string;
    description?: string;
  }>;
}

/**
 * The manifest shape we emit. The vite-plugin-pwa manifest type doesn't
 * know about `translations` yet (W3C draft) so we widen it here.
 */
type BuiltManifest = NonNullable<VitePWAOptions["manifest"]> & {
  translations?: Record<string, ManifestTranslationEntry>;
};

/**
 * Assembles the final Web App Manifest object.
 *
 * - English content lives inline (below) and is the fallback for any
 *   locale not present in `PWA_MANIFEST_TRANSLATIONS`.
 * - Every additional locale from `i18n.config.ts` is added to the
 *   `translations` field (W3C draft; Chromium 100+, Edge 100+, Samsung
 *   Internet 16+, Opera 86+, Android in general). Browsers without
 *   support silently ignore `translations` and use the primary strings.
 * - Shortcut translations are localised per-shortcut using the stable
 *   `id` field defined above; unknown ids fall back to the English name.
 *
 * The return type widens the plugin's manifest schema with our own
 * `translations` shape ({@link ManifestTranslationEntry}) so the
 * unknown-to-the-plugin field passes TypeScript.
 */
export function buildManifest(): BuiltManifest {
  const translations: Record<string, ManifestTranslationEntry> = {};

  for (const [locale, translation] of Object.entries(PWA_MANIFEST_TRANSLATIONS)) {
    if (!translation) continue;

    translations[locale] = {
      name: translation.name,
      short_name: translation.shortName,
      description: translation.description,
      shortcuts: MANIFEST_SHORTCUTS.map((shortcut) => {
        const localized = translation.shortcuts?.[shortcut.id];

        if (!localized) return { url: shortcut.url };

        return {
          url: shortcut.url,
          name: localized.name,
          short_name: localized.shortName,
          description: localized.description,
        };
      }),
    };
  }

  return {
    /** Full product name. Falls back here if `translations` unsupported. */
    name: "Academorix — Academy Operations",

    /** Short home-screen label — ≤ 12 chars is the sweet spot. */
    short_name: "Academorix",

    /** One-line pitch. Shown in some install prompts + store listings. */
    description:
      "Academorix — the operating system for modern academies. Manage athletes, teams, sessions, matches, payments, and safeguarding from one place.",

    /** Primary manifest locale. Everything else comes via `translations`. */
    lang: "en",

    /**
     * Primary manifest direction. Kept `"ltr"` because the plugin's
     * TypeScript type only permits `"rtl" | "ltr"`. Per-locale entries
     * under `translations` don't override direction in the current
     * manifest spec — instead, `lang` is what browsers use to pick
     * text shaping. The SPA still renders RTL at runtime by setting
     * `<html dir="rtl">` on the client based on the active locale.
     */
    dir: "ltr",

    /** No browser chrome — the "app" feel. */
    display: "standalone",

    /** Preferred alternates if `standalone` isn't supported. */
    display_override: ["window-controls-overlay", "standalone", "minimal-ui", "browser"],

    /** Vertical on phones, natural on tablets/desktops. */
    orientation: "any",

    /** Browser chrome tint + splash top strip. */
    theme_color: BRAND_COLORS.themeLight,

    /** Splash screen background. */
    background_color: BRAND_COLORS.background,

    /** SW controls every route under this scope. */
    scope: "/",

    /** Opens the workspace picker. `?source=pwa` gets stripped in-app. */
    start_url: "/?source=pwa",

    /** Store-listing category hints. */
    categories: ["business", "productivity", "sports"],

    /** Icon list — see {@link MANIFEST_ICONS}. Cloned to mutable array. */
    icons: MANIFEST_ICONS.map((icon) => ({ ...icon })),

    /**
     * Shortcut list — we strip our internal `id` field on the way out
     * because the manifest spec doesn't recognize it. The `id` still
     * matters here because translations reference shortcuts by id.
     *
     * We also spread the readonly `icons` tuple into a fresh array
     * because `VitePWAOptions["manifest"]` types `icons` as mutable.
     */
    shortcuts: MANIFEST_SHORTCUTS.map(({ id: _id, icons, ...rest }) => ({
      ...rest,
      icons: icons.map((icon) => ({ ...icon })),
    })),

    /**
     * `translations` — W3C manifest draft. One key per non-primary
     * locale. Each entry contains a subset of the parent manifest with
     * localized `name`, `short_name`, `description`, and per-shortcut
     * localized labels keyed by URL (browsers match on url, not on our
     * internal id).
     *
     * Browsers that don't yet support `translations`:
     *   - Firefox (as of 2026): ignore silently and show English.
     *   - Safari on iOS: ignore silently.
     *
     * We accept the graceful degradation — Arabic-first users on
     * unsupported browsers still get the app; they just see English on
     * the launcher tile until they open it, at which point the SPA's
     * runtime i18n takes over.
     */
    translations,
  };
}

// ---------------------------------------------------------------------------
// Workbox
// ---------------------------------------------------------------------------

/**
 * Runtime caching + navigation fallback for the service worker. The
 * generator (`strategies: "generateSW"`) reads this and emits `sw.js`.
 *
 * Order matters — the first matching entry wins.
 */
export const WORKBOX_OPTIONS: VitePWAOptions["workbox"] = {
  /**
   * Precache glob. Covers every asset Vite emits. We do NOT precache
   * source maps (each can be > 1 MB) and we do NOT precache mock JSON
   * fixtures.
   */
  globPatterns: ["**/*.{js,css,html,ico,png,svg,webp,woff,woff2}"],
  globIgnores: ["**/data/**", "**/*.map"],

  /**
   * Every dynamic navigation falls back to /index.html — the SPA shell.
   * Denylisted paths never fall back so the service worker never
   * masks a real API/asset with the HTML shell.
   */
  navigateFallback: "/index.html",
  navigateFallbackDenylist: [
    /^\/api\//, // Backend API.
    /^\/sw\.js$/, // Service worker itself.
    /^\/workbox-.*\.js$/, // Workbox runtime chunks.
    /^\/manifest\.webmanifest$/, // Manifest — served as-is.
  ],

  runtimeCaching: [
    // -----------------------------------------------------------------
    // Backend API — NetworkFirst
    // -----------------------------------------------------------------
    {
      urlPattern: ({ url, sameOrigin }) => sameOrigin && url.pathname.startsWith("/api/"),
      handler: "NetworkFirst",
      method: "GET",
      options: {
        cacheName: "academorix-api-v1",
        networkTimeoutSeconds: 5,
        expiration: {
          maxEntries: 200,
          maxAgeSeconds: 60 * 60, // 1 hour
          purgeOnQuotaError: true,
        },
        cacheableResponse: { statuses: [0, 200] },
      },
    },
    // -----------------------------------------------------------------
    // Same-origin images — CacheFirst
    // -----------------------------------------------------------------
    {
      urlPattern: ({ request, sameOrigin }) => sameOrigin && request.destination === "image",
      handler: "CacheFirst",
      options: {
        cacheName: "academorix-images-v1",
        expiration: {
          maxEntries: 100,
          maxAgeSeconds: 60 * 60 * 24 * 30, // 30 days
          purgeOnQuotaError: true,
        },
        cacheableResponse: { statuses: [0, 200] },
      },
    },
    // -----------------------------------------------------------------
    // Google Fonts stylesheet — StaleWhileRevalidate
    // -----------------------------------------------------------------
    {
      urlPattern: ({ url }) => url.origin === "https://fonts.googleapis.com",
      handler: "StaleWhileRevalidate",
      options: {
        cacheName: "google-fonts-stylesheets-v1",
        expiration: { maxEntries: 10, maxAgeSeconds: 60 * 60 * 24 * 7 },
      },
    },
    // -----------------------------------------------------------------
    // Google Fonts files — CacheFirst
    // -----------------------------------------------------------------
    {
      urlPattern: ({ url }) => url.origin === "https://fonts.gstatic.com",
      handler: "CacheFirst",
      options: {
        cacheName: "google-fonts-webfonts-v1",
        expiration: { maxEntries: 30, maxAgeSeconds: 60 * 60 * 24 * 365 },
        cacheableResponse: { statuses: [0, 200] },
      },
    },
  ],

  cleanupOutdatedCaches: true,
  clientsClaim: true,
  skipWaiting: false,
  maximumFileSizeToCacheInBytes: 5 * 1024 * 1024,
  sourcemap: false,
};

// ---------------------------------------------------------------------------
// Plugin options
// ---------------------------------------------------------------------------

/**
 * The full argument passed to `VitePWA()` in `vite.config.ts`. This is
 * the shape the plugin expects — see the vite-plugin-pwa docs for the
 * complete surface.
 *
 * `injectRegister: null` is deliberate — we register the service
 * worker from React (`src/pwa/register-sw.ts`) so `useRegisterSW`
 * can surface the update prompt via the HeroUI toast queue.
 */
export const PWA_PLUGIN_OPTIONS = {
  strategies: "generateSW" as const,
  registerType: "prompt" as const,
  injectRegister: null,
  includeAssets: ["favicon.svg", "favicon.ico", "robots.txt", "apple-touch-icon.png"],
  includeManifestIcons: true,
  manifest: buildManifest(),
  workbox: WORKBOX_OPTIONS,
  devOptions: {
    enabled: false,
    type: "module" as const,
    navigateFallback: "index.html",
    suppressWarnings: true,
  },
} satisfies Partial<VitePWAOptions>;

// ---------------------------------------------------------------------------
// Aggregate handle
// ---------------------------------------------------------------------------

/**
 * Bundled PWA config. Prefer named exports at call sites; this shape
 * exists for readability in tests + Playwright snapshots.
 */
export const pwaConfig = {
  brand: BRAND_COLORS,
  icons: MANIFEST_ICONS,
  shortcuts: MANIFEST_SHORTCUTS,
  workbox: WORKBOX_OPTIONS,
  plugin: PWA_PLUGIN_OPTIONS,
} as const;
