<?php

// // AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py notifications notifications-mail --force`.

declare(strict_types=1);

namespace Academorix\NotificationsMail\Models;

use Illuminate\Database\Eloquent\Attributes\Fillable;
use Illuminate\Database\Eloquent\Attributes\Table;
use Illuminate\Database\Eloquent\Attributes\UseFactory;
use Illuminate\Database\Eloquent\Model;
use Academorix\NotificationsMail\Contracts\Data\MailSuppressionInterface;
use Academorix\NotificationsMail\Database\Factories\MailSuppressionFactory;
use Academorix\Foundation\Concerns\Filterable;
use Academorix\Foundation\Concerns\HasMetadata;
use Illuminate\Database\Eloquent\Concerns\HasUlids;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\SoftDeletes;
use Laravel\Scout\Searchable;
use Mattiverse\Userstamps\Traits\Userstamps;

/**
 * Eloquent model for a MailSuppression.
 *
 * Suppressed email addresses.
 *
 * @category NotificationsMail
 *
 * @since    0.1.0
 */
#[Table(name: MailSuppressionInterface::TABLE, keyType: MailSuppressionInterface::KEY_TYPE)]
#[Fillable([
    MailSuppressionInterface::ATTR_TENANT_ID,
        MailSuppressionInterface::ATTR_EMAIL,
        MailSuppressionInterface::ATTR_EMAIL_DOMAIN,
        MailSuppressionInterface::ATTR_REASON,
        MailSuppressionInterface::ATTR_PROVIDER,
        MailSuppressionInterface::ATTR_SOURCE_DELIVERY_ID,
        MailSuppressionInterface::ATTR_BOUNCE_REASON,
        MailSuppressionInterface::ATTR_IS_SYSTEM,
        MailSuppressionInterface::ATTR_EXPIRES_AT,
        MailSuppressionInterface::ATTR_METADATA,
])]
#[UseFactory(MailSuppressionFactory::class)]
final class MailSuppression extends Model implements MailSuppressionInterface
{
    use HasFactory;
    use HasUlids;
    // TODO(gen): resolve unknown trait `HasSystemFlag` — add its import + use line.
    // TODO(gen): resolve unknown trait `BelongsToTenantOptional` — add its import + use line.
    use HasMetadata;
    use HasUserstamps;
    // TODO(gen): resolve unknown trait `HasAuditable` — add its import + use line.
    use Filterable;
    use Searchable;
    use SoftDeletes;

    /**
     * The primary key IS a string (prefixed ULID); disable auto-increment.
     *
     * @var bool
     */
    public $incrementing = false;

    /**
     * Cast map — from the blueprint's x-eloquent.casts.
     *
     * @var array<string, string>
     */
    protected $casts = [
        MailSuppressionInterface::ATTR_REASON => 'MailSuppressionReason',
        MailSuppressionInterface::ATTR_IS_SYSTEM => 'boolean',
        MailSuppressionInterface::ATTR_METADATA => 'array',
        MailSuppressionInterface::ATTR_EXPIRES_AT => 'datetime',
    ];
}
