<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py shared foundation --force`.

declare(strict_types=1);

namespace Stackra\Foundation\Console;

use Stackra\Console\Attributes\AsCommand;
use Stackra\Console\Commands\BaseCommand;

/**
 * `php artisan cache:tags` — Tags — cache command.
 *
 * @category Foundation
 *
 * @since    0.1.0
 */
#[AsCommand(
    name: 'cache:tags',
    description: 'Tags — cache command.',
)]
final class TagsCommand extends BaseCommand
{
    /**
     * Execute the command.
     *
     * TODO(gen): wire the required services + implement the handler body.
     */
    public function handle(): int
    {
        $this->omni->titleBar('Tags — cache command', 'sky');

        // TODO(gen): wire the required services + implement the handler body.

        $this->omni->success('Tags — cache command completed.');
        $this->showDuration();

        return self::SUCCESS;
    }
}
