<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py platform theme --force`.

declare(strict_types=1);

namespace Stackra\Theme\Actions\Platform;

use Stackra\Theme\Contracts\Repositories\ThemePresetRepositoryInterface;
use Stackra\Theme\Data\ThemePresetData;
use Stackra\Routing\Attributes\AsAction;
use Stackra\Routing\Attributes\Middleware;
use Stackra\Routing\Concerns\AsController;
use Stackra\Routing\Attributes\Get;
use Illuminate\Http\Request;
use Illuminate\Pagination\LengthAwarePaginator;
use Spatie\LaravelData\PaginatedDataCollection;

/**
 * `GET /api/v1/platform/theme-presets` — list action (platform-admin audience).
 *
 * Single-invoke controller wired via `#[AsAction]` + `#[Get(...)]`
 * + `#[Middleware(...)]` from `Stackra\Routing`. Discovered by the routing
 * package's boot-time `RouteRegistrar` — no route file needed.
 *
 * @category Theme
 *
 * @since    0.1.0
 */
#[AsAction(name: 'theme.theme_presets.list')]
#[Get('/api/v1/platform/theme-presets')]
#[Middleware(['api', 'auth:sanctum', 'platform_admin'])]
final class ListThemePresetAction
{
    use AsController;

    public function __construct(
        private readonly ThemePresetRepositoryInterface $repository,
    ) {
    }

    /**
     * List `theme-presets` for the current caller.
     *
     * The `Repository` base picks up `filter[...]` / `sort=...` /
     * `include=...` query parameters via the `#[Filterable]` attribute
     * on the concrete repository — no per-Action wiring needed.
     *
     * @return PaginatedDataCollection<int, ThemePresetData>  Paginated wire-visible DTOs.
     */
    public function __invoke(Request $request): PaginatedDataCollection
    {
        /** @var LengthAwarePaginator<int, \Stackra\Theme\Models\ThemePreset> $page */
        $page = $this->repository->paginate(
            perPage: (int) $request->integer('per_page', 15),
        );

        return ThemePresetData::collect($page, PaginatedDataCollection::class);
    }
}
