<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py sports awards --force`.

declare(strict_types=1);

namespace Academorix\Awards\Actions\Tenant;

use Academorix\Awards\Contracts\Repositories\AwardRepositoryInterface;
use Academorix\Awards\Data\AwardData;
use Academorix\Awards\Data\Requests\CreateAwardRequestData;
use Stackra\Routing\Attributes\AsAction;
use Stackra\Routing\Attributes\Middleware;
use Stackra\Routing\Concerns\AsController;
use Stackra\Routing\Attributes\Post;
use Illuminate\Http\JsonResponse;

/**
 * `POST /api/v1/awards` — create action (tenant audience).
 *
 * Single-invoke controller wired via `#[AsAction]` + `#[Post(...)]`
 * + `#[Middleware(...)]` from `Stackra\Routing`. Discovered by the routing
 * package's boot-time `RouteRegistrar` — no route file needed.
 *
 * @category Awards
 *
 * @since    0.1.0
 */
#[AsAction(name: 'awards.create')]
#[Post('/api/v1/awards')]
#[Middleware(['api', 'auth:sanctum', 'tenant.resolve'])]
final class CreateAwardAction
{
    use AsController;

    public function __construct(
        private readonly AwardRepositoryInterface $repository,
    ) {
    }

    /**
     * Create a `award` from the validated request payload.
     *
     * @param  CreateAwardRequestData  $data  Validated payload (Spatie Data DTO).
     *
     * @return JsonResponse  201 Created with the newly-persisted DTO.
     */
    public function __invoke(CreateAwardRequestData $data): JsonResponse
    {
        $model = $this->repository->create($data->toArray());

        return response()->json(AwardData::from($model), JsonResponse::HTTP_CREATED);
    }
}
