<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py finance tax --force`.

declare(strict_types=1);

namespace Academorix\Tax\Events;

use Academorix\Events\Attributes\AsEvent;
use Illuminate\Contracts\Events\ShouldDispatchAfterCommit;

/**
 * CRITICAL. Provider call failed after 3 retry attempts OR jurisdiction unresolvable OR provider mandated but circuit-breaker open. NO tax_calculations row persisted. The invoice line is BLOCKED (fail-safe against under-charging tax).
 *
 * ## Consumers
 *
 * - audit::WriteToAuditLog
 * - notifications::DispatchTaxCalculationBlockedNotification (P1 — pages finance ops)
 * - monitoring::MetricsCollector (increments academorix.tax.calculations.failed_total)
 * - tax::MaybeOpenCircuitBreaker
 *
 * @category Tax
 *
 * @since    0.1.0
 */
#[AsEvent]
final readonly class TaxCalculationFailed implements ShouldDispatchAfterCommit
{
    /**
     * @param  string  $correlationId  ULID
     * @param  string  $tenantId  ULID
     * @param  string  $invoiceLineId  ULID | null
     * @param  string  $provider  string
     * @param  string  $failureReason  string (provider_permanent_failure / provider_timeout / jurisdiction_unresolvable / circuit_breaker_open / auth_failure)
     * @param  string  $errorCode  string | null
     * @param  string  $errorMessage  string
     * @param  int  $attemptCount  integer
     * @param  string  $failedAt  ISO 8601
     */
    public function __construct(
        public readonly string $correlationId,
        public readonly string $tenantId,
        public readonly string $invoiceLineId,
        public readonly string $provider,
        public readonly string $failureReason,
        public readonly string $errorCode,
        public readonly string $errorMessage,
        public readonly int $attemptCount,
        public readonly string $failedAt,
    ) {
    }
}
