<?php

/**
 * @file database/migrations/2026_07_15_120005_create_progress_cards_table.php
 *
 * @description
 * Create the `progress_cards` table for the `ProgressCard` entity.
 * Owned by the progress module. Emitted from the module blueprint —
 * regenerate via `generate-module.py sports progress --force`.
 */
// // AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py sports progress --force`.

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class() extends Migration {
    /**
     * Run the migration.
     */
    public function up(): void
    {
        Schema::create('progress_cards', function (Blueprint $table): void {
            $table->string('id', 30)->primary();
            $table->string('tenant_id', 30);
            $table->foreign('tenant_id')->references('id')->on('tenants')->onDelete('cascade');
            $table->string('progress_assessment_id', 30);
            $table->foreign('progress_assessment_id')->references('id')->on('progress_assessments')->onDelete('cascade');
            $table->string('card_type', 24);
            $table->timestampTz('rendered_at');
            $table->string('rendered_document_id', 30)->nullable();
            $table->foreign('rendered_document_id')->references('id')->on('files')->onDelete('set null');
            $table->string('share_signature', 128)->nullable();
            $table->timestampTz('share_expires_at')->nullable();
            $table->integer('share_views')->default('0');
            $table->jsonb('metadata')->nullable();
            $table->string('created_by', 30)->nullable();
            $table->string('updated_by', 30)->nullable();
            $table->timestampTz('deleted_at')->nullable();
            $table->timestampTz('created_at');
            $table->timestampTz('updated_at');
            $table->index(['tenant_id', 'progress_assessment_id'], 'progress_cards_assessment_idx');
            $table->unique(['share_signature'], 'progress_cards_share_signature_unique');
            // Partial-index predicate — hand-add via DB::statement: WHERE share_signature IS NOT NULL
        });
    }

    /**
     * Reverse the migration.
     */
    public function down(): void
    {
        Schema::dropIfExists('progress_cards');
    }
};
