<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py finance gateway --force`.

declare(strict_types=1);

namespace Academorix\Gateway\Events;

use Academorix\Events\Attributes\AsEvent;
use Illuminate\Contracts\Events\ShouldDispatchAfterCommit;

/**
 * Provider webhook lands + passes HMAC verification + is a new (provider_event_id) entry. Feeds every downstream finance listener chain.
 *
 * ## Consumers
 *
 * - audit::WriteToAuditLog
 * - finance::PaymentEventHandler
 * - finance::RefundEventHandler
 * - finance::ChargebackEventHandler
 * - finance::PayoutEventHandler
 *
 * @category Gateway
 *
 * @since    0.1.0
 */
#[AsEvent]
final readonly class WebhookReceived implements ShouldDispatchAfterCommit
{
    /**
     * @param  string  $webhookEventId  ULID (gwe_*)
     * @param  string  $tenantId  ULID
     * @param  string  $provider  string
     * @param  string  $providerEventId  string
     * @param  string  $eventType  string
     * @param  string  $at  ISO 8601
     */
    public function __construct(
        public readonly string $webhookEventId,
        public readonly string $tenantId,
        public readonly string $provider,
        public readonly string $providerEventId,
        public readonly string $eventType,
        public readonly string $at,
    ) {
    }
}
