<?php

// // AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py platform organization --force`.

declare(strict_types=1);

namespace Academorix\Organization\Contracts\Services;

use Academorix\Organization\Services\OrganizationProvisioner;
use Illuminate\Container\Attributes\Bind;

/**
 * Service contract for OrganizationProvisioner.
 *
 * Bound to the concrete via `#[Bind(OrganizationProvisioner::class)]`. Consumers
 * type-hint this interface; tests bind a fake through the container.
 *
 * @category Organization
 *
 * @since    0.1.0
 */
#[Bind(OrganizationProvisioner::class)]
interface OrganizationProvisionerInterface
{
    // TODO(gen): declare the domain methods this service exposes.
}
