<?php

// // AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py identity mfa --force`.

declare(strict_types=1);

namespace Academorix\Mfa\Actions\Tenant;

use Academorix\Routing\Attributes\AsController;
use Academorix\Routing\Attributes\Patch;

/**
 * `PATCH /api/v1/me/mfa/webauthn/credentials/{id}` — update action (tenant audience).
 *
 * Single-invoke controller wired via `#[AsController]` + `#[Patch(...)]`
 * attributes from `Academorix\Routing`. Discovered by the routing package's
 * boot-time `RouteRegistrar` — no route file needed.
 *
 * @category Mfa
 *
 * @since    0.1.0
 */
#[AsController]
#[Patch('/api/v1/me/mfa/webauthn/credentials/{id}')]
final class UpdateCredentialAction
{
    /**
     * Execute the action.
     *
     * TODO(gen): wire the required services + implement the handler body.
     */
    public function __invoke(): mixed
    {
        // Hand-implement the domain logic here.
        return null;
    }
}
