<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py observability monitoring --force`.

declare(strict_types=1);

namespace Stackra\Monitoring\Database\Factories;

use Illuminate\Database\Eloquent\Factories\Factory;
use Stackra\Monitoring\Contracts\Data\MonitoringAlertPolicyInterface;
use Stackra\Monitoring\Models\MonitoringAlertPolicy;

/**
 * Factory for {@see \Stackra\Monitoring\Models\MonitoringAlertPolicy}.
 *
 * Auto-generated skeleton — extend with named states as domain
 * cases emerge (e.g. `->published()`, `->overdue()`, `->archived()`).
 *
 * @extends Factory<\Stackra\Monitoring\Models\MonitoringAlertPolicy>
 *
 * @category Monitoring
 *
 * @since    0.1.0
 */
final class MonitoringAlertPolicyFactory extends Factory
{
    /**
     * The model this factory builds.
     *
     * @var class-string<MonitoringAlertPolicy>
     */
    protected $model = MonitoringAlertPolicy::class;

    /**
     * Return the default model attribute values.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        return [
            MonitoringAlertPolicyInterface::ATTR_NAME => fake()->sentence(3),
            MonitoringAlertPolicyInterface::ATTR_SIGNAL_TYPE => fake()->randomElement(['health_check_status', 'error_rate', 'latency_p95', 'latency_p99', 'queue_depth', 'worker_health', 'custom_metric']),
            MonitoringAlertPolicyInterface::ATTR_SIGNAL_SOURCE => fake()->sentence(3),
            MonitoringAlertPolicyInterface::ATTR_SEVERITY => fake()->randomElement(['p1', 'p2', 'p3', 'p4']),
            MonitoringAlertPolicyInterface::ATTR_THRESHOLD_OPERATOR => fake()->randomElement(['greater_than', 'less_than', 'equals', 'not_equals']),
            MonitoringAlertPolicyInterface::ATTR_THRESHOLD_VALUE => fake()->randomFloat(2, 0, 10000),
            MonitoringAlertPolicyInterface::ATTR_THRESHOLD_UNIT => fake()->randomElement(['percent', 'ms', 'count', 'bytes']),
            MonitoringAlertPolicyInterface::ATTR_WINDOW_SECONDS => fake()->numberBetween(1, 1000),
            MonitoringAlertPolicyInterface::ATTR_CONSECUTIVE_BREACHES_REQUIRED => fake()->numberBetween(1, 1000),
            MonitoringAlertPolicyInterface::ATTR_IS_ENABLED => fake()->boolean(),
            MonitoringAlertPolicyInterface::ATTR_NOTIFY_PROVIDER_CONFIGS => [],
            MonitoringAlertPolicyInterface::ATTR_SUPPRESSION_CONFIG => [],
            MonitoringAlertPolicyInterface::ATTR_METADATA => null,
        ];
    }
}
