<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py platform region --force`.

declare(strict_types=1);

namespace Academorix\Region\Actions\Platform;

use Academorix\Region\Contracts\Repositories\RegionRepositoryInterface;
use Academorix\Region\Data\RegionData;
use Academorix\Routing\Attributes\AsAction;
use Academorix\Routing\Attributes\Middleware;
use Academorix\Routing\Concerns\AsController;
use Academorix\Routing\Attributes\Get;

/**
 * `GET /api/v1/platform/regions/{region}` — show action (platform-admin audience).
 *
 * Single-invoke controller wired via `#[AsAction]` + `#[Get(...)]`
 * + `#[Middleware(...)]` from `Academorix\Routing`. Discovered by the routing
 * package's boot-time `RouteRegistrar` — no route file needed.
 *
 * @category Region
 *
 * @since    0.1.0
 */
#[AsAction(name: 'region.regions.show')]
#[Get('/api/v1/platform/regions/{region}')]
#[Middleware(['api', 'auth:sanctum', 'platform_admin'])]
final class ShowRegionAction
{
    use AsController;

    public function __construct(
        private readonly RegionRepositoryInterface $repository,
    ) {
    }

    /**
     * Fetch one `region` by id.
     *
     * @param  string  $id  Primary key.
     *
     * @throws \Illuminate\Database\Eloquent\ModelNotFoundException  When the row is absent or hidden by scoping.
     */
    public function __invoke(string $id): RegionData
    {
        return RegionData::from($this->repository->findOrFail($id));
    }
}
