<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py access rbac --force`.

declare(strict_types=1);

namespace Academorix\Rbac\Actions\Tenant;

use Academorix\Rbac\Contracts\Repositories\RoleRepositoryInterface;
use Academorix\Rbac\Data\RoleData;
use Academorix\Rbac\Data\Requests\CreateRoleRequestData;
use Academorix\Routing\Attributes\AsAction;
use Academorix\Routing\Attributes\Middleware;
use Academorix\Routing\Concerns\AsController;
use Academorix\Routing\Attributes\Post;
use Illuminate\Http\JsonResponse;

/**
 * `POST /api/v1/rbac/roles` — create action (tenant audience).
 *
 * Single-invoke controller wired via `#[AsAction]` + `#[Post(...)]`
 * + `#[Middleware(...)]` from `Academorix\Routing`. Discovered by the routing
 * package's boot-time `RouteRegistrar` — no route file needed.
 *
 * @category Rbac
 *
 * @since    0.1.0
 */
#[AsAction(name: 'rbac.roles.create')]
#[Post('/api/v1/rbac/roles')]
#[Middleware(['api', 'auth:sanctum', 'tenant.resolve'])]
final class CreateRoleAction
{
    use AsController;

    public function __construct(
        private readonly RoleRepositoryInterface $repository,
    ) {
    }

    /**
     * Create a `role` from the validated request payload.
     *
     * @param  CreateRoleRequestData  $data  Validated payload (Spatie Data DTO).
     *
     * @return JsonResponse  201 Created with the newly-persisted DTO.
     */
    public function __invoke(CreateRoleRequestData $data): JsonResponse
    {
        $model = $this->repository->create($data->toArray());

        return response()->json(RoleData::from($model), JsonResponse::HTTP_CREATED);
    }
}
