<?php

// // AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py access rbac --force`.

declare(strict_types=1);

namespace Academorix\Rbac\Actions\Tenant;

use Academorix\Rbac\Contracts\Repositories\RoleRepositoryInterface;
use Academorix\Rbac\Data\RoleData;
use Academorix\Rbac\Data\Requests\UpdateRoleRequestData;
use Academorix\Routing\Attributes\AsController;
use Academorix\Routing\Attributes\Patch;

/**
 * `PATCH /api/v1/rbac/roles/{role}` — update action (tenant audience).
 *
 * Single-invoke controller wired via `#[AsController]` + `#[Patch(...)]`
 * attributes from `Academorix\Routing`. Discovered by the routing package's
 * boot-time `RouteRegistrar` — no route file needed.
 *
 * @category Rbac
 *
 * @since    0.1.0
 */
#[AsController]
#[Patch('/api/v1/rbac/roles/{role}')]
final class UpdateRoleAction
{
    public function __construct(
        private readonly RoleRepositoryInterface $repository,
    ) {
    }

    /**
     * Update one `role` and return the wire DTO.
     *
     * @param  string  $id  Primary key.
     * @param  UpdateRoleRequestData  $data  Validated payload.
     *
     * @throws \Illuminate\Database\Eloquent\ModelNotFoundException  When the row is absent or hidden by scoping.
     */
    public function __invoke(string $id, UpdateRoleRequestData $data): RoleData
    {
        $model = $this->repository->update($id, $data->toArray());

        return RoleData::from($model);
    }
}
