<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py growth analytics --force`.

declare(strict_types=1);

namespace Stackra\Analytics\Contracts\Services;

use Stackra\Analytics\Services\IdentityResolver;
use Illuminate\Container\Attributes\Bind;

/**
 * Service contract for IdentityResolver.
 *
 * Bound to the concrete via `#[Bind(IdentityResolver::class)]`. Consumers
 * type-hint this interface; tests bind a fake through the container.
 *
 * @category Analytics
 *
 * @since    0.1.0
 */
#[Bind(IdentityResolver::class)]
interface IdentityResolverInterface
{
    // TODO(gen): declare the domain methods this service exposes.
}
