<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py sports development --force`.

declare(strict_types=1);

namespace Academorix\Development\Database\Seeders;

use Academorix\Development\Enums\DevelopmentPermission;
use Stackra\Authorization\Database\Seeders\Concerns\SeedsPermissionEnum;
use Stackra\ServiceProvider\Attributes\AsSeeder;
use Illuminate\Database\Seeder;

/**
 * Seed the {@see DevelopmentPermission} cases into spatie/laravel-permission's
 * `permissions` table.
 *
 * All the boilerplate (spatie model resolution, `updateOrCreate` loop,
 * cache flush) lives in the shared {@see SeedsPermissionEnum} trait.
 *
 * @category Development
 *
 * @since    0.1.0
 */
#[AsSeeder(priority: 55, environments: [])]
final class DevelopmentPermissionSeeder extends Seeder
{
    use SeedsPermissionEnum;

    /**
     * {@inheritDoc}
     */
    protected function permissionEnums(): array
    {
        return [DevelopmentPermission::class];
    }
}
