<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py platform ai --force`.

declare(strict_types=1);

namespace Academorix\Ai\Contracts\Repositories;

use Academorix\Crud\Contracts\RepositoryInterface;

/**
 * Repository contract for {@see Academorix\Ai\Models\AiDraft}.
 *
 * Consumers type-hint the interface; the container binds the concrete
 * via `#[AsRepository]` on `AiDraftRepository`.
 *
 * @extends RepositoryInterface<\Academorix\Ai\Models\AiDraft>
 *
 * @category Ai
 *
 * @since    0.1.0
 */
interface AiDraftRepositoryInterface extends RepositoryInterface
{
    // Domain-specific query methods live here. CRUD comes from the base.
}
