<?php

// // AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py sports registry --force`.

declare(strict_types=1);

namespace Academorix\Registry\Database\Seeders;

use Academorix\Registry\Enums\RegistryPermission;
use Academorix\Authorization\Database\Seeders\Concerns\SeedsPermissionEnum;
use Academorix\ServiceProvider\Attributes\AsSeeder;
use Illuminate\Database\Seeder;

/**
 * Seed the {@see RegistryPermission} cases into spatie/laravel-permission's
 * `permissions` table.
 *
 * All the boilerplate (spatie model resolution, `updateOrCreate` loop,
 * cache flush) lives in the shared {@see SeedsPermissionEnum} trait.
 *
 * @category Registry
 *
 * @since    0.1.0
 */
#[AsSeeder(priority: 55, environments: [])]
final class RegistryPermissionSeeder extends Seeder
{
    use SeedsPermissionEnum;

    /**
     * {@inheritDoc}
     */
    protected function permissionEnums(): array
    {
        return [RegistryPermission::class];
    }
}
