<?php

/**
 * @file database/migrations/2026_07_15_120002_create_forms_table.php
 *
 * @description
 * Create the `forms` table for the `Form` entity.
 * Owned by the forms module. Every column + index reference
 * goes through {@see Academorix\Forms\Contracts\Data\FormInterface} per the `models` steering
 * rule §1 — no raw string literals.
 */
// // AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py platform forms --force`.

declare(strict_types=1);

use Academorix\Forms\Contracts\Data\FormInterface;
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

return new class() extends Migration {
    /**
     * Run the migration.
     */
    public function up(): void
    {
        Schema::create(FormInterface::TABLE, function (Blueprint $table): void {
            $table->string(FormInterface::ATTR_ID, 30)->primary();
            $table->string(FormInterface::ATTR_TENANT_ID, 30);
            $table->foreign(FormInterface::ATTR_TENANT_ID)->references('id')->on('tenants')->onDelete('cascade');
            $table->string(FormInterface::ATTR_SLUG, 100);
            $table->string(FormInterface::ATTR_TITLE, 200);
            $table->text(FormInterface::ATTR_DESCRIPTION)->nullable();
            $table->string(FormInterface::ATTR_KIND, 32);
            $table->string(FormInterface::ATTR_STATUS, 16)->default('draft');
            $table->string(FormInterface::ATTR_PUBLISHED_VERSION_ID, 30)->nullable();
            $table->foreign(FormInterface::ATTR_PUBLISHED_VERSION_ID)->references('id')->on('form_versions')->onDelete('restrict');
            $table->string(FormInterface::ATTR_HANDOFF_SLUG, 100)->nullable();
            $table->jsonb(FormInterface::ATTR_HANDOFF_CONFIG)->nullable();
            $table->timestampTz(FormInterface::ATTR_OPENS_AT)->nullable();
            $table->timestampTz(FormInterface::ATTR_CLOSES_AT)->nullable();
            $table->boolean(FormInterface::ATTR_REQUIRES_AUTHENTICATION)->default('false');
            $table->string(FormInterface::ATTR_PUBLIC_URL_SIGNATURE, 128)->nullable();
            $table->string(FormInterface::ATTR_LOCALE_DEFAULT, 8)->default('en');
            $table->jsonb(FormInterface::ATTR_LOCALES_AVAILABLE)->default('["en"]');
            $table->jsonb(FormInterface::ATTR_BRANDING_SNAPSHOT)->nullable();
            $table->integer(FormInterface::ATTR_SUBMISSION_COUNT)->default('0');
            $table->jsonb(FormInterface::ATTR_SETTINGS)->nullable();
            $table->jsonb(FormInterface::ATTR_METADATA)->nullable();
            $table->string(FormInterface::ATTR_CREATED_BY, 30)->nullable();
            $table->string(FormInterface::ATTR_UPDATED_BY, 30)->nullable();
            $table->string(FormInterface::ATTR_DELETED_BY, 30)->nullable();
            $table->timestampTz(FormInterface::ATTR_DELETED_AT)->nullable();
            $table->timestampTz(FormInterface::ATTR_CREATED_AT);
            $table->timestampTz(FormInterface::ATTR_UPDATED_AT);
            $table->index([FormInterface::ATTR_TENANT_ID, FormInterface::ATTR_KIND, FormInterface::ATTR_STATUS], 'forms_kind_status_idx');
        });

        DB::statement('CREATE UNIQUE INDEX forms_tenant_slug_unique ON ' . FormInterface::TABLE . ' (' . FormInterface::ATTR_TENANT_ID . ', ' . FormInterface::ATTR_SLUG . ') WHERE deleted_at IS NULL');
        DB::statement('CREATE UNIQUE INDEX forms_public_signature_unique ON ' . FormInterface::TABLE . ' (' . FormInterface::ATTR_PUBLIC_URL_SIGNATURE . ') WHERE public_url_signature IS NOT NULL');
    }

    /**
     * Reverse the migration.
     */
    public function down(): void
    {
        Schema::dropIfExists(FormInterface::TABLE);
    }
};
