<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py identity people --force`.

declare(strict_types=1);

namespace Academorix\People\Events;

use Illuminate\Contracts\Events\ShouldDispatchAfterCommit;

/**
 * PersonIdentity mutated (legal_name / dob / nationality). Notifies all tenants with active links so they can refresh their local prefill.
 *
 * ## Consumers
 *
 * - audit::WriteToAuditLog
 * - notifications::DispatchPersonUpdatedNotification (all tenants with active links)
 *
 * @category People
 *
 * @since    0.1.0
 */
final readonly class PersonUpdated implements ShouldDispatchAfterCommit
{
    /**
     * @param  string  $personIdentityId  ULID
     * @param  string  $changedFields  string[]
     * @param  string  $changedByUserId  ULID
     */
    public function __construct(
        public readonly string $personIdentityId,
        public readonly string $changedFields,
        public readonly string $changedByUserId,
    ) {
    }
}
