<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py workflow approvals --force`.

declare(strict_types=1);

namespace Academorix\Approvals\Repositories;

use Academorix\Crud\Attributes\AsRepository;
use Academorix\Crud\Attributes\Cacheable;
use Academorix\Crud\Attributes\Filterable;
use Academorix\Crud\Attributes\UseModel;
use Academorix\Crud\Repositories\Repository;
use Academorix\Approvals\Contracts\Data\ApprovalTemplateApproverInterface;
use Academorix\Approvals\Contracts\Repositories\ApprovalTemplateApproverRepositoryInterface;
use Academorix\Approvals\Models\ApprovalTemplateApprover;

/**
 * Attribute-first Eloquent repository for {@see Academorix\Approvals\Models\ApprovalTemplateApprover}.
 *
 * Bound to the interface via `#[AsRepository]`; the model comes from
 * `#[UseModel(ApprovalTemplateApproverInterface::class)]` which resolves to
 * `ApprovalTemplateApprover` through the interface's `#[Bind]`.
 *
 * @extends Repository<\Academorix\Approvals\Models\ApprovalTemplateApprover>
 *
 * @category Approvals
 *
 * @since    0.1.0
 */
#[AsRepository]
#[UseModel(ApprovalTemplateApproverInterface::class)]
#[Cacheable(ttl: 3600, tags: true)]
#[Filterable('*')]
final class ApprovalTemplateApproverRepository extends Repository implements ApprovalTemplateApproverRepositoryInterface
{
    // Domain methods added here. CRUD comes from Repository.
}
