<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py finance wallet --force`.

declare(strict_types=1);

namespace Academorix\Wallet\Exceptions;

use Stackra\Exceptions\Exception;

/**
 * Transaction currency does not match wallet currency.
 *
 * @category Wallet
 *
 * @since    0.1.0
 */
final class WalletCurrencyMismatchException extends Exception
{
    /**
     * Stable machine-readable error code emitted on the JSON envelope.
     */
    public const CODE = 'WALLET_CURRENCY_MISMATCH';

    /**
     * Translation key for the humanised message.
     */
    public const TRANSLATION_KEY = 'wallet::errors.WALLET_CURRENCY_MISMATCH';
}
