<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py growth attribution --force`.

declare(strict_types=1);

namespace Academorix\Attribution\Events;

use Academorix\Events\Attributes\AsEvent;
use Illuminate\Contracts\Events\ShouldDispatchAfterCommit;

/**
 * MarkAttributionChurnedJob transitioned lifecycle_state 'anonymous' | 'identified' → 'churned'. Runs nightly. 90-day-inactive threshold.
 *
 * ## Consumers
 *
 * - audit::WriteToAuditLog
 * - activity::WriteToActivityLog
 * - notifications::DispatchAttributionChurnDetectedNotification (opt-in to marketing team — batched daily digest)
 *
 * @category Attribution
 *
 * @since    0.1.0
 */
#[AsEvent]
final readonly class AttributionChurned implements ShouldDispatchAfterCommit
{
    /**
     * @param  string  $attributionId  ULID
     * @param  string  $tenantId  ULID
     * @param  string  $subjectType  string
     * @param  string  $subjectId  ULID | UUID
     * @param  string  $wasLifecycleState  'anonymous' | 'identified'
     * @param  int  $daysInactive  integer
     * @param  string  $lastTouchAt  ISO 8601
     */
    public function __construct(
        public readonly string $attributionId,
        public readonly string $tenantId,
        public readonly string $subjectType,
        public readonly string $subjectId,
        public readonly string $wasLifecycleState,
        public readonly int $daysInactive,
        public readonly string $lastTouchAt,
    ) {
    }
}
