<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py sports age-group --force`.

declare(strict_types=1);

namespace Academorix\AgeGroup\Console;

use Stackra\Console\Attributes\AsCommand;
use Stackra\Console\Commands\BaseCommand;

/**
 * `php artisan age-group:seed-defaults-for-tenant` — Seed defaults for tenant — age group command.
 *
 * @category AgeGroup
 *
 * @since    0.1.0
 */
#[AsCommand(
    name: 'age-group:seed-defaults-for-tenant',
    description: 'Seed defaults for tenant — age group command.',
)]
final class SeedDefaultsForTenantCommand extends BaseCommand
{
    /**
     * Execute the command.
     *
     * TODO(gen): wire the required services + implement the handler body.
     */
    public function handle(): int
    {
        $this->omni->titleBar('Seed defaults for tenant — age group command', 'sky');

        // TODO(gen): wire the required services + implement the handler body.

        $this->omni->success('Seed defaults for tenant — age group command completed.');
        $this->showDuration();

        return self::SUCCESS;
    }
}
