<?php

// // AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py growth referrals --force`.

declare(strict_types=1);

namespace Academorix\Referrals\Enums;

use Academorix\Enum\Enum;

/**
 * Closed-set enum for `referred_type` on `referral`.
 *
 * Polymorphic.
 *
 * @category Referrals
 *
 * @since    0.1.0
 */
enum ReferralReferredType: string
{
    use Enum;

    case User = 'user';
    case Lead = 'lead';
}
