<?php

// // AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py growth marketing --force`.

declare(strict_types=1);

namespace Academorix\Marketing\Database\Factories;

use Illuminate\Database\Eloquent\Factories\Factory;
use Academorix\Marketing\Contracts\Data\MarketingDeadLetterInterface;
use Academorix\Marketing\Models\MarketingDeadLetter;

/**
 * Factory for {@see \Academorix\Marketing\Models\MarketingDeadLetter}.
 *
 * Auto-generated skeleton — extend with named states as domain
 * cases emerge (e.g. `->published()`, `->overdue()`, `->archived()`).
 *
 * @extends Factory<\Academorix\Marketing\Models\MarketingDeadLetter>
 *
 * @category Marketing
 *
 * @since    0.1.0
 */
final class MarketingDeadLetterFactory extends Factory
{
    /**
     * The model this factory builds.
     *
     * @var class-string<MarketingDeadLetter>
     */
    protected $model = MarketingDeadLetter::class;

    /**
     * Return the default model attribute values.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        return [
            MarketingDeadLetterInterface::ATTR_MARKETING_EVENT_ID => fake()->sentence(3),
            MarketingDeadLetterInterface::ATTR_PROVIDER => fake()->randomElement(['meta_capi', 'google_ads', 'google_analytics_4', 'gtm_server', 'tiktok_events', 'linkedin_insight', 'snapchat_capi', 'pinterest_capi', 'custom_webhook']),
            MarketingDeadLetterInterface::ATTR_REASON => fake()->randomElement(['max_attempts_exceeded', 'provider_permanent_failure', 'circuit_breaker_max_opens', 'invalid_payload', 'auth_failure']),
            MarketingDeadLetterInterface::ATTR_FINAL_ERROR_DETAILS => null,
            MarketingDeadLetterInterface::ATTR_REPLAY_ATTEMPTS => fake()->numberBetween(1, 1000),
            MarketingDeadLetterInterface::ATTR_LAST_REPLAY_AT => null,
            MarketingDeadLetterInterface::ATTR_RESOLVED_AT => null,
            MarketingDeadLetterInterface::ATTR_RESOLVED_BY_USER_ID => null,
            MarketingDeadLetterInterface::ATTR_RESOLUTION_NOTE => null,
            MarketingDeadLetterInterface::ATTR_METADATA => null,
        ];
    }
}
