<?php

// // AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py identity platform-user --force`.

declare(strict_types=1);

namespace Academorix\PlatformUser\Contracts\Data;

use Illuminate\Container\Attributes\Bind;
use Academorix\PlatformUser\Models\PlatformUser;

/**
 * Table shape for the `platform_users` table.
 *
 * Academorix-staff principal.
 *
 * @category PlatformUser
 *
 * @since    0.1.0
 */
#[Bind(PlatformUser::class)]
interface PlatformUserInterface
{
    /**
     * Table name.
     */
    public const string TABLE = 'platform_users';

    /**
     * Primary key column.
     */
    public const string PRIMARY_KEY = 'id';

    /**
     * Primary key column type — string (ULID with prefix `plu_`).
     */
    public const string KEY_TYPE = 'string';

    // ── Columns ───────────────────────────────────────────────

    public const string ATTR_ID                   = 'id';
    public const string ATTR_IDENTITY_ID          = 'identity_id';
    public const string ATTR_PROFILE_ID           = 'profile_id';
    public const string ATTR_STATUS               = 'status';
    public const string ATTR_HIRE_DATE            = 'hire_date';
    public const string ATTR_OFFBOARDED_AT        = 'offboarded_at';
    public const string ATTR_OFFBOARDING_REASON   = 'offboarding_reason';
    public const string ATTR_DEPARTMENT           = 'department';
    public const string ATTR_EMPLOYMENT_TYPE      = 'employment_type';
    public const string ATTR_JOB_TITLE            = 'job_title';
    public const string ATTR_MANAGER_ID           = 'manager_id';
    public const string ATTR_ON_CALL_ROTATION_KEY = 'on_call_rotation_key';
    public const string ATTR_METADATA             = 'metadata';
    public const string ATTR_CREATED_BY           = 'created_by';
    public const string ATTR_UPDATED_BY           = 'updated_by';
    public const string ATTR_DELETED_BY           = 'deleted_by';
    public const string ATTR_DELETED_AT           = 'deleted_at';
    public const string ATTR_CREATED_AT           = 'created_at';
    public const string ATTR_UPDATED_AT           = 'updated_at';
}
