<?php

// AUTO-GENERATED by generate-module.py from the module blueprint. Regenerate via `python3 modules/shared/blueprints/foundation/scripts/generate-module.py sports athlete-enrollment --force`.

declare(strict_types=1);

namespace Academorix\AthleteEnrollment\Actions\Platform;

use Academorix\Routing\Attributes\AsAction;
use Academorix\Routing\Attributes\Middleware;
use Academorix\Routing\Concerns\AsController;
use Academorix\Routing\Attributes\Get;

/**
 * `GET /api/v1/platform/enrollments/atomicity-failures` — list action (platform-admin audience).
 *
 * Single-invoke controller wired via `#[AsAction]` + `#[Get(...)]`
 * + `#[Middleware(...)]` from `Academorix\Routing`. Discovered by the routing
 * package's boot-time `RouteRegistrar` — no route file needed.
 *
 * @category AthleteEnrollment
 *
 * @since    0.1.0
 */
#[AsAction(name: 'athlete_enrollment.atomicity_failures.list')]
#[Get('/api/v1/platform/enrollments/atomicity-failures')]
#[Middleware(['api', 'auth:sanctum', 'platform_admin'])]
final class ListAtomicityFailureAction
{
    use AsController;

    /**
     * Execute the action.
     *
     * TODO(gen): wire the required services + implement the handler body.
     */
    public function __invoke(): mixed
    {
        // Hand-implement the domain logic here.
        return null;
    }
}
